src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsTextServices.cs
`int` is not the same as `const TF_HALTCOND *` on x64 arch
=> Fix ZeroForNow parameter

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs
We've already used System.Collections.Generic.HashSet in NameFixupGraph and ObjectWriterFrame, etc
=> Remove the custom HashSet class

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileStream.cpp, src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileStream.h
Fixes #6236
Using a `<Resource>` font in WPF currently causes a lot of allocation, GC pinning, and memory copying. This is entirely avoidable by returning a pointer to the already-loaded font data to DWrite.
Without this fix, customers are forced to hook DWrite APIs and supply their own font-loading implementation; e.g., https://faithlife.codes/blog/2019/06/improving-wpf-text-display-performance/.
Not a regression.
Manual testing using a test app: https://github.com/bgrainger/EmbeddedFontPerformance
Risk is low. This fix has been prototyped in a commercial WPF application that's been shipping for 5 years (see blog post above). Since the font source is an `UnmanagedMemoryStream`, we can rely on its data being present in memory at least as long as we hold a reference to the stream. (And …
=> Eliminate memory copy when reading font data

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusPoint.cs
Benchmark:
|      Method |     Mean |   Error |  StdDev |  Gen 0 |  Gen 1 | Allocated |
|------------ |---------:|--------:|--------:|-------:|-------:|----------:|
|   CopyByFor | 765.7 ns | 3.72 ns | 3.11 ns | 0.6409 | 0.0095 |      4 KB |
| CopyByArray | 260.6 ns | 3.39 ns | 3.17 ns | 0.6413 | 0.0095 |      4 KB |
| CopyByClone | 250.3 ns | 2.04 ns | 1.70 ns | 0.6390 | 0.0095 |      4 KB |
Benchmark code: https://github.com/lindexi/lindexi_gd/tree/5aef1567e56bf2b8a67c21f94b18f9827c18aaf4/CejelfairqereKecelherwelka
Just CI.
Low.
=> Using the `Clone` method to fast clone the array in StylusPoint

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs
The method `VerifyAccess` is not being inlined because of the Exception. Not inlining the throw is enough to inline `VerifyAccess` because the method `CheckAccess` already qualifies to be inlined.
I used the following code to benchmark it :
https://gist.github.com/ThomasGoulet73/3dbc0cf5d24ca06b639ba6888c27fe02
Here are the results :
|               Method | count |      Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |------ |----------:|---------:|---------:|-------:|------:|------:|----------:|
|          CheckAccess |    10 |  95.25 ns | 1.469 ns | 1.374 ns | 0.0764 |     - |     - |     480 B |
|         VerifyAccess |    10 | 143.90 ns | 1.693 ns | 1.501 ns | 0.0763 |     - |     - |     480 B |
|  CheckAccess_Inlined |    10 |  94.92 ns | …
=> Inline VerifyAccess

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Fixes dotnet/wpf#6792
Fixes build of project using source generators coming from NuGet packages. I fixed this by only including analyzers that are coming from a FrameworkReference in the temporary target assembly project. Those analyzers are the ones that are not automatically added in the temporary target assembly project because `ResolveTargetingPackAssets` is never called (We could investigate calling this target in the future but, to me, it seemed riskier than the changes in this PR).
Fixes build.
This is a regression introduced in .Net 6.0.7 by #6534 which was backported by #6680. Those were changes from me, sorry about the regression.
Tested locally by building a project which uses Regex source generator, WinForms source generator and [CommunityToolkit.Mvvm …
=> Fix build when using source generators coming from NuGet packages.

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Fixes dotnet/wpf#6792
Fixes build of project using source generators coming from NuGet packages. Added a new target for de-duplicating the list of analyzers.
[Added a target to de-duplicate the list of analyzers ](https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402)
Fixes build.
This is a regression introduced in .Net 6.0.7 by https://github.com/dotnet/wpf/pull/6534 which was backported by https://github.com/dotnet/wpf/pull/6680. 
Tested locally by building a project which uses Regex source generator, WinForms source generator and [CommunityToolkit.Mvvm 7.1.2](https://www.nuget.org/packages/CommunityToolkit.Mvvm/7.1.2) source generator (This is an example of a source generator that currently fails on .Net 6.0.7 SDK).
Low.
=> Fix build when using source generators coming from NuGet package

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/TextBoxView.cs
=> Fixing TextBoxView memory leak for 2 seconds after unloading host control

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/ButtonBase.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Hyperlink.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonGallery.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonTextBox.cs
Fixes Issue #3452 #4078 (also discussed in #316)
In summary, the issue is that 
```xml
<MenuItem CommandParameter="P" Command="C" />
```
and
```xml
<MenuItem Command="C" CommandParameter="P" />
```
behave differently. In the latter case, `C.CanExecute` is called to determine whether the element should be enabled, but since the parameter has not been parsed yet, `CanExecute` is called with a `null` argument. After the parameter is parsed, the status of the command is not re-evaluated and therefore the element stays disabled when it shouldn't be.
A common workaround is to use the former syntax.
Adds property changed callback to `CommandParameterProperty` wherever applicable (`MenuItem`, `ButtonBase`, `Hyperlink`, `RibbonGallery`, `RibbonTextBox`) to call `UpdateCanExecute`.
This way, …
=> CommandParameter invalidates CanExecute

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherOperation.cs
We don’t need check the `_exception` is null.
No,
Just CI.
Low. I did not change the behavior of the code
=> Merge pattern in DispatcherOperation

src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
- FrugalStructList's `ICollection<T>`-based constructor uses foreach to enumerate the contents of the collection.  If it's an `IList<T>`, we can instead index and avoid allocating the enumerator.
- Avoid multiple interface calls to `ICollection<T>.Count` in FrugalStructList's ctor
- Delete a dead ctor on `ArrayItemList<T>`.  That ctor was the only reason an array field may have been left null, so we can also remove subsequent null checks when accessing that array.
- Use Span/Array in ArrayItemList for Clear, Contains, IndexOf, ToArray, and CopyTo rather than open-coding them
Unnecessary allocation and interface dispatch
No
CI
Minimal
=> Some improvements to FrugalList

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/AlphaFlattener/SegmentTree.cs
Especially for the sorts based on int[], this avoids boxing potentially huge numbers of ints.  Even for classes, it avoids unnecessary casting and expensive Array.Get/SetValue calls, and switching to a delegate avoids a top-level allocation for the comparer inside the current Array.Sort implementation.
Unnecessary allocation, interface dispatch, expensive Array.Get/SetValue calls, etc.
No
CI
Minimal
=> Change most non-generic sorts to be generic

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/PresentationSource.cs
PresentationSource.CriticalCurrentSources is internal and is only ever foreach'd by consumers.  It's strongly-typed to return IEnumerable, but the actual WeakReferenceList it returns has a struct-based enumerator, which means each foreach boxes that enumerator.  By changing CriticalCurrentSources to return `WeakReferenceList` rather than `IEnumerable`, those foreach's can bind directly to the struct, with all the benefits that brings.
No
CI
Minimal
=> Stop boxing WeakReferenceListEnumerator in PresentationSource use

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/CollectionViewGroupInternal.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/ListCollectionView.cs
Pass the required state in as a state object to be passed on to the delegate invocation.
No
CI
Minimal
=> Avoid delegate allocation to call ListCollectionView.PrepareComparer

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/RepeatBehaviorConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Parsers.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Navigation/BaseUriHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/FixedTextSelectionProcessor.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/TextSelectionProcessor.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/TextViewSelectionProcessor.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/FileDialog.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Annotations/Annotation.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ColorConvertedBitmapExtension.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlRecords.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/ContainerUtilities.cs
Uses the single char overload instead of the one using char array.
Note: PresentationBuildTasks targets .Net Framework 4.7.2 and .Net Core 2.1. The method `string.Split(char)` was introduced in .Net Core 2.0 so the changes do not apply to .Net Framework. .Net Framework 4.7.2 will call `string.Split(params char[])` and .Net Core 2.1 will call `string.Split(char)`.
Thoses changes should give a small perf gain and reduce memory usage.
Here is the result for the method `string.Split` on my machine:
|    Method |                 str |     Mean |    Error |   StdDev | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |-------------------- |---------:|---------:|---------:|------:|-------:|------:|------:|----------:|
| CharArray | 123456789,123456789 | 55.03 ns | 0.562 ns | 0.469 ns | …
=> Use params and char overload

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemContainerGenerator.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
Calls to ItemContainerGenerator.DoLinearSearch are capturing locals to use for comparison, resulting in closure/delegate allocations on each call.  We can instead pass the extra state through as a state argument.
Unnecessary allocation/overhead.
No
CI
Minimal.
=> Remove closure/delegate allocation in ItemContainerGenerator

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ToolTipService.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/tooltip.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/KnownBoxes.cs
A boxed boolean doesn't know whether it came from a nullable bool or a bool, so there's no need to maintain separate True/FalseBox objects for bool? vs bool, nor do we need to store a NullBox... that field will just be null.
Nothing measurable.  This is just unnecessary duplication.
No
CI
Minimal
=> Avoid unnecessary duplication of fields in NullableBooleanBoxes

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridColumn.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/GridViewColumnHeader.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs
Fixes #5880
Main PR #6054
Issue related to WPF DataGrid column width can now be changed using the keyboard shortcut "ALT + left arrow key" and "ALT + right arrow key".
Adds a requirement.
NO
Low. Add ability to adjust column width using keyboard for WPF DataGrid.
=> WPF DataGrid/GridView column width can be changed using the keyboard shortcut ALT+left or right arrow key

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/DataBindEngine.cs
The _valueConverterTable is a Hashtable that uses a struct-based key.  It's boxing every time a lookup is performed or an add is performed.
No
CI
Minimal
=> Avoid Hashtable-related allocations in DataBindEngine

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/AccessorTable.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingOperations.cs
Use a strongly-typed Dictionary instead.
- The key is a struct.  Every time an item is added to the table or a lookup into the table is performed, the key is getting boxed. Using Dictionary avoids all this boxing.
- The struct key lacks a strongly-typed Equals.  Every comparison results in a boxing.  Gave the key a strongly-typed Equals.
- Every cleanup operation is allocating an enumerator.  Dictionary has a struct-based enumerator.
- Every cleanup operation is allocating an array to store the items to be removed (even if there aren't any to be removed).  Dictionary supports removal during enumeration, so this can be removed entirely.
Unnecessary allocations
No
CI
Minimal
=> Avoid Hashtable-related allocations in AccessorTable

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapDecoder.cs
Fixes Issue https://github.com/dotnet/wpf/issues/4355
Fix https://github.com/dotnet/wpf/issues/4355
Just CI and my demo: https://github.com/lindexi/lindexi_gd/tree/20b78c5547b2ecacdd244a438ef58518469a91d7/GeafakaijawkeheahemLejeehocear
=> Fix create BitmapDecoder with async file stream.

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PathParser.cs
I replaced the `IndexOf` call on a private static string with a custom method that returns whether or not a char is a special char. I think this method is on a hot path because it is called on almost every char of the path passed to the method `Parse` and one of the usage of this method is in the constructor of `Binding` when you pass a path, which I think is a very common usage.
Check here to follow the usage in `Binding` ctor:
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/Binding.cs#L230
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/PropertyPath.cs#L93
https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Pr …
=> Small performance improvement of PathParser

src/Microsoft.DotNet.Wpf/Directory.Build.Props
Temporarily Disable CA1420 due to https://github.com/dotnet/roslyn-analyzers/issues/6094
=> Supress CA1420 Temporarily to fix build errors

azure-pipelines1.yml, eng/pipeline.yml
=> Move to -Svc pool provider in release branches (7.0 RC1)

eng/common/templates/job/source-build.yml, eng/common/templates/job/source-index-stage1.yml, eng/pipeline.yml
This change is required for builds to continue working in the new org, dev.azure.com/dnceng-public.
=> Update public pool names

azure-pipelines.yml, azure-pipelines1.yml, eng/pipeline.yml
- Remove some unused variables
- Enable in-build signing on release branches
=> [release/7.0] Enable in-build signing and do some clean-up

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ContentFilePart.cs
Fixes Issue #4781 #4987
Main PR 
The Application.ResourceAssembly.CodeBase is the string without escaped.
See:
- https://github.com/dotnet/wpf/issues/4781
- https://github.com/dotnet/wpf/pull/5004
- https://github.com/dotnet/wpf/pull/4799
See https://github.com/dotnet/wpf/issues/4781
Just CI and my demo code.
The test package: https://www.nuget.org/packages/Lindexi.Src.CustomWPF/1.0.6
The test demo: https://github.com/lindexi/lindexi_gd/tree/5f274174e8fd12fe6f4738c0e4605b22a3252901/WhejohafaChalehelair
Low.
=> Fix GetStreamCore in ContentFilePart

src/Microsoft.DotNet.Wpf/src/Themes/Shared/Microsoft/Windows/Themes/DataGridHeaderBorder.cs
Fixes #6713 
CacheFreezable() logic is incorrect in that it checks if the indexed value is NOT null before caching versus if it IS null. This means that values will never actually be cached and any calls to GetCachedFreezable() will always return null causing the Brush to be regenerated rather than reused on every rendering pass.
Unnecessary computation on every rendering pass. Possible memory and brush leak.
Does not appear to be a regression.
Validated fix locally in private implementation of DataGridColumnBorder
This should be minimal. DataGridColumnBorder code was clearly implemented assuming that brushes will be cached but they never actually are. There are various assertions in place already to ensure proper behavior here.
=> DataGridColumnBorder caching of Freezable brushes is not actually caching anything at all

src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Invariant.cs
Fixes #6772
Fix NullReferenceException in Invariant.get_IsDialogOverrideEnabled when .NET Framework Registry key (HKLM\Software\Microsoft\.NETFramework) is not present on the machine
-
-
-
-
=> Fix NullReferenceException in Invariant.get_IsDialogOverrideEnabled

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Classification.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontFace/PhysicalFontFamily.cs
Fixes #6801 
Font fallback does not check combining marks associated with a base character, because the shaping engine might precompose the character with mark into single one which might be present in the font.
However, when the marks are from a different script than the base character, the text does not get to the correct shaping engine, and inappropriate clusters are made (e.g. punctuation with Indic vowels).
The PR compares the script of the base character and the combining marks and only allows to skip font fallback check if they are the same, using the existing character classification tables.
Customers not taking this fix will see incorrectly shaped text and will have difficulty editing affected text, since in non-Latin script cases, cursor cannot be put between the base character …
=> Check script of combining marks during font fallback

src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/ImageSourceTypeConverter.cs
Fixes https://github.com/dotnet/wpf/issues/6842
The ImageSourceTypeConverter will request the stream. And the ImageSourceTypeConverter will close the stream after `CopyImageStream` method. But the stream will not be closed when the `CopyImageStream` throw the exception.
This will make the ZipArchiveEntry throw the `System.IO.IOException: 'Entries cannot be opened multiple times in Update mode.'` when we next time to request the stream.
Maybe this can fix https://github.com/dotnet/wpf/issues/6842
None.
Just CI
Very low?
=> Fix the stream do not be closed in ImageSourceTypeConverter

azure-pipelines1.yml
This should not run except in the official build. It's causing the wrong bits to flow in some cases.
=> Remove post-build from DRT testing

global.json
The 8.0.100-alpha.1.22512.5 SDK was built in a window where System references were versioned `8.0.0.0`, but in a way that broke some things. That was backed out in dotnet/runtime#77899, which means that assemblies built from this repo can't run on the current .NET 8 runtime, which cannot satisfy a dependency on, for example, `System.Runtime, Version=8.0.0.0`.
Move forward to a newer .NET 8 that has those assemblies versioned at `7.0.0.0` again, which should work even when dotnet/runtime#78354 bumps the version again, because the loader will accept higher versions.
Should unblock dotnet/sdk#28897 (once it builds and flows).
=> Update SDK to 8.0.100-alpha.1.22601.6

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorCopyPaste.cs
Fixes #3965
During #969, creating `DataObject`s was effectively changed from `autoConvert = true` to `autoConvert = false`. As a result, dragging selection from a `TextBox` no longer sets `System.String` format on the `DataObject`. I believe this change was unintentional, as the same commit keeps `System.String` elsewhere (e.g. in `GetMappedFormats`).
Not taking this fix would mean existing applications that rely on `System.String` data format would no longer support dropping text from text boxes. A prominent example of such application is a sample in documentation: https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control?view=netframeworkdesktop-4.8
Yes. Introduced in #969, diverting from .NET Framework behaviour.
Compiled on …
=> Revert autoConvert for string DataObjects

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/ErrorCodes.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs
Avoid unnecessary suppression of [CA1823](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1823): Avoid unused private fields
=> Remove suppression of CA1823

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
- Removes the old deny list logic used by RestrictiveXamlXmlReader
- Provides an extensible (via registry) allow list mechanism
Fixes CVE-2022-41089.
This is a port of the fix that was made for .NET Core 3.1, .NET 6, and .NET 7 and that was published as part of the December 13, 2022 Patch Tuesday release. Our servicing team is experiencing a delay in getting the sources for those branches published, but they look identical to the **main** branch fix present here.
=> Change RestrictiveXamlXmlReader to use an allow list

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfGeneratedKnownProperties.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/KnownTypes.cs
Fixes #6977
Adding _IsReadOnly_ as a known property for _TextBox_ and _RichTextBox_
Users were not able to use _IsReadOnly_ property in the _ControlTemplate.Triggers_ while using it in _ResourceDictionary_ in a separate file.
NO
NA
Risk is low as fix does not modify existing code or changes any public api
=> fix(knowntypes): adding IsReadOnly as known property for TextBox and RichTextBox

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs
Fixes #7205
Fixes #7291
Adding static constructor to StyleHelper class to do the required initialization i.e. registering the "alternative Expression storage". Also, adding check to "RegisterAlternateExpressionStorage" function to avoid re-registration being called.
An attempt to call the BindingOperations.GetBindingExpression method in .NET 7.0 leads to Null Reference Exception.
Yes
In progress
NA
=> Adding static constructor to StyleHelper class

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs
Fixes #5231
A calculation to see how much width has been allocated to *-columns produces a result that's less than the available width by a tiny amount, due to floating-point drift. This causes a loop to continue when it shouldn't, leading to infinite loop. In such case adding that tiny remaining width to a column resolved as "min".
VS XAML Designer freezes when resizing the column width.
No
Done
NA
=> Fixing *-defs width calculation

Documentation/developer-guide.md
We need to add PlatformTarget instead of Platform tag
None
NA
NA
NA
=> Rectify documentation - Use PlatformTarget instead of Platform tag

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json
Fixes #7204 
Updates the precedence and identity of WPF Project Templates
Enables localization of template names when using dotnet new --list
No
Installed templates and created sample test apps
Minimal
=> Updated precedence for project templates

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs
Fixes #7322 
adding opt-out switch for column resize and column sorting features by keyboard inputs
Without this changes the features will be enabled by default and any user defined input bindings for Alt + Left/Right arrow keys or F3 function key will not work. Also, user will not have any option to turn of the feature.
Yes
Internal tests (microsuites + DRT)
NA
=> fix(column-resize): adding opt-out switch for column resize and column sorting features by keyboard inputs

azure-pipelines1.yml, eng/wpfautomatedtests.yml
Creating a separate pipeline for automating wpf tests.
=> Separate official and test pipelines

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/UncommonField.cs
This reverts commit 4dfe58650ac63e76b76659cea850df57c0182440.
Fixes #7321 #7315 
Main PR 
The changes in PR https://github.com/dotnet/wpf/pull/4220 are disturbing the HierarchicalVirtualizationConstraints calculation, which is further used in calculation of the sizes of the virtualizing items and availableSize, DesiredSize, Viewport and extendedViewport calculations.
The result of all this is showing just the first item rather than all the items in the group.
The customers will see only the first item in the list of items, as opposed to all the items in the list.
Yes. 
Local WPF Testing. 
Low. Just reverting the change causing the regressions.
=> Revert "avoid boxing (#4220)"

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
Fixes #6861
Main PR 
Let's see the code step by step.
1. The item in a `GroupItem` can be detected by the Automation Software because the GroupItem provides an automation peer named `GroupItemAutomationPeer` and it overrides the `GetChildrenCore` method which returns a list of inner items. Debug the code and we can find that the `itemsControlAP` is null in an ItemsControl GroupItem.
```csharp
// GroupItemAutomationPeer.cs
protected override List<AutomationPeer> GetChildrenCore()
{
GroupItem owner = (GroupItem)Owner;
ItemsControl itemsControl = ItemsControl.ItemsControlFromItemContainer(Owner);
if (itemsControl != null)
{
ItemsControlAutomationPeer itemsControlAP = itemsControl.CreateAutomationPeer() as ItemsControlAutomationPeer;
if (itemsControlAP != null)
{
List<AutomationPeer> children …
```
=> Fix ItemsControl Automation

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
We need not check the popup contains in the empty List
=> Adding the popup to empty List directly in Popup.RegisterPopupWithPlacementTarget

eng/wpfautomatedtests.yml
Currently specific artifacts are being downloaded which require the change in the build version every time the latest build changes. Making the change to download latest artifacts for test.
=> download latest artifacts rather than specific

eng/copy-wpf.ps1
Update .NET version from 7 to 8 for replacing assemblies before test.
=> update .NET version for replacing assemblies.

eng/wpfautomatedtests.yml
dotnet path being picked up in automated test pipeline is shared installation.
Changing to test host installation path.
++ Other cosmetic changes in task display names.
=> set path vars for testhost install

src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsFixedPageReaderWriter.cs
I wrote the test demo code and I found an improvement in performance.
|                                 Method |      Mean |    Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------------------------- |----------:|---------:|----------:|-------:|------:|------:|----------:|
|           LookupContentTypeForImageUri | 114.17 ns | 3.096 ns |  9.130 ns | 0.0153 |     - |     - |      64 B |
| LookupContentTypeForImageUriIgnoreCase |  40.84 ns | 0.975 ns |  2.874 ns |      - |     - |     - |         - |
|           LookupContentTypeForImageUri | 115.00 ns | 3.858 ns | 11.375 ns | 0.0153 |     - |     - |      64 B |
| LookupContentTypeForImageUriIgnoreCase |  55.19 ns | 1.913 ns |  5.642 ns |      - |     - |     - |         - |
| …
=> Improve LookupContentTypeForImageUri performance in XpsFixedPageReaderWriter.cs

Directory.Build.targets
Fixes dotnet/wpf#5224
Removes a workaround, which disables the usage of source generator in this repo, to support VS versions older than VS2022. VS2022 is required to build this repo according to the [README](https://github.com/dotnet/wpf/blob/cfec0cc3f3ded32c4d6dc409e41af516afe64073/README.md?plain=1#L16) and AFAIK the CI also use VS2022.
None. This PR changes only the build of this repo.
No.
Low.
=> Remove Source Generator workaround

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DatePicker.cs
Fixes #4704
This MR adds code similar to `Calendar` to track `FrameworkElement.Language` property.
You need either implement this yourself or change `DatePicker.FirstDayOfWeek` manually.
No. As I can tell, this bug originates from Microsoft .NET Framework.
Manual.
NA.
=> Update DatePicker.FirstDayOfWeek on Language change

.github/ISSUE_TEMPLATE/02_api_proposal.yml, Documentation/project/api-review-process.md
WPF will be using the same public API review process as other dotnet repos and is subscribed in the system for this.
Adding the issue template for public API review and copied the API review process from dotnet/runtime with some minor modifications.
=> API Review Process for WPF

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Selector.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
Fixes Issue #4501
Adding the SelectableProperty in Selector. And we can set the item not to be selected by SelectableProperty.
See:
- https://github.com/dotnet/wpf/issues/5143
- https://github.com/dotnet/wpf/issues/4501
No.
Just CI and my [demo](https://github.com/lindexi/lindexi_gd/tree/ef2c5fe539e051953ad6bae969f4161a1f0b85ee/WPFDemo).
Low.
=> Add the SelectableProperty in Selector.

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs
Fixes # 
#6319 #7002 
Main PR 
When an app opens the tooltip directly, WPF ( independently ) also activates the tooltip ( marks it 'current; , registers handlers for Opened and Closed events , sets some internal properties and opens the tooltip ). Now, when app closes the tooltip directly, the closed event is raised.
Now, when the app re-opens the tooltip, WPF decides to dismiss the 'current' tooltip and while doing so, it uses the internal properties, which were unset by the closed event. Thus resulting in the error
In this fix, 
1. if WPF sees, that the tooltip is already open, we don't register an Opened handler, but do it's work immediately
2. The closed handler ignores events raised from the "current" tooltip.
3. Move unregistering handler in ClearServiceProperties
Apps that do …
=> Tooltip Direct Manipulation Fix

eng/Version.Details.xml, eng/Versions.props
System.Drawing.Common is now live built in winforms and hence the coherent parent dependency shouldn't be needed anymore.
This unblock dependency updates from winforms --> wpf
=> Remove System.Drawing.Common coherent package dependency

eng/pipeline.yml
Regressed with https://github.com/dotnet/wpf/pull/7610.
The CopyFiles, PublishPipelineArtifact and PublishTestResults steps should only be executed when running in the public team project as internal builds don't run tests. This change just mimics the condition that was already on the "Run Tests" powershell step.
=> Fix official build break

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSourceCollection.cs, src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/XmlCompatibilityReader.cs
Follow up to dotnet/wpf#4177
I found more places where we used a Dictionary without using the value just to filter out duplicates.
See dotnet/wpf#4177 for benchmarks.
Better performance.
No.
Low.
=> Replace Dictionary with HashSet

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/KnownTypes.cs
We can use `string.Equals(string1, string2, StringComparison.Ordinal)` to check for equality, see https://learn.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings and https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings
> Use the [String.Compare](https://learn.microsoft.com/en-us/dotnet/api/system.string.compare) and [String.CompareTo](https://learn.microsoft.com/en-us/dotnet/api/system.string.compareto) methods to sort strings, not to check for equality.
Reference https://github.com/dotnet/wpf/issues/6588
Cc @Kuldeep-MS 
Small performance improvements
None.
Just CI.
Low.
=> Replace String.CompareOrdinal to string.Equals in KnownTypes

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerWrapper.cs, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
Fixes dotnet/wpf#7348
Use the project ChecksumAlgorithm to generate `#pragma checksum` in code-behind using the correct algorithm.
Projects setting ChecksumAlgorithm will now generate `#pragma checksum` using the correct algorithm.
No.
I used the repro project in dotnet/wpf#7348 to check the generated code.
Low.
/cc @swenkeratmicrosoft @tmat
=> Use project ChecksumAlgorithm in code-behind.

eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
WriteOnlyWhenDifferent is considered only when Overwrite is set in the WriteLinesToFile task. Therefore, disabling the WriteOnlyWhenDifferent property when Overwrite=false in Wpf.Cpp.targets. See https://github.com/dotnet/msbuild/issues/8363
Developers facing issues with local builds will be unblocked.
--
Local build is working
No.
=> Disable WriteOnlyWhenDifferent if Overwrite=false

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UniqueEventHelper.cs
Use a Dictionary instead of Hashtable in UniqueEventHelper in order to avoid boxing the ref count integer on every add/remove.  And as long as this was being updated, addressed the TODO to combine the identical types into a helper base type that provided most of the functionality shared instead of being duplicated on both the generic and non-generic handler implementation.  Also reduced the allocation in InvokeEvents, just allocating an array for the handlers rather than allocating a complete copy of the dictionary, a keys object, and an enumerator object.  And avoid forcing the delegates dictionary into existence just to remove a delegate.
No
CI
Minimal
=> Avoid boxing in UniqueEventHelper

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphsSerializer.cs
Fixes #7499
Related: #6295
Previous rounding strategy
1. did not calculate the error according to XPS specification
2. updated error with shaping value when font value is used by the client
The PR fixes 1. by keeping track of total advance width (desired and rounded) and 2. by using the font advance width when no value is output to XPS.
Customers not taking this fix will see either gaps or overlapped characters when producing XPS with text. See #7499 for an example.
Yes. Introduced by #6295 trying to fix #6525. This PR addresses both issues.
Tested manually using repro projects for #6525 and #7499.
Same risks as with #6295. This PR changes relative positioning of glyphs in a GlyphRun to match the bounding box, so it should not cause reflow of documents.
=> GlyphSerializer rounding fix

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedFindEngine.cs
Fixes #7567 
Stream is not explicitly disposed when retrieving page contents. This causes stream to stay open even when the usage is over. The next iteration of the same code path then throws the error since it sees that the underlying stream is already open.
Unable to search when using docviewer control
Don't know.
Under testing. 
Low. Since the scope of the stream is anyways local.
=> Disposing page stream eagerly

src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/AnimationException.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/InvalidWMPVersionException.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/DataStreams.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/Pts.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Frame.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PrintDialogException.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/ValueUnavailableException.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlParseException.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/Journal.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/NavigationService.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceKeyNotFoundException.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/XpsViewerException.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Exceptions/XpsException.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintSystemExceptions/PrintSystemException.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/ref/ReachFramework.cs, src/Microsoft.DotNet.Wpf/src/System.Printing/ref/System.Printing.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameParser.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlException.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/ref/System.Xaml.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ElementNotAvailableException.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ElementNotEnabledException.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/NoClickablePointException.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ProxyAssemblyNotLoadedException.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/ref/UIAutomationTypes.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/Exceptions.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/ref/WindowsBase.cs
Disable warnings. 
CS0672 : https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0672
SYSLIB0011 : https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0011
SYSLIB0051 : obsolete: 'This API supports obsolete formatter-based serialization. It should not be called or extended by application code.'
SYSLIB0050: obsolete: 'Formatter-based serialization is obsolete and should not be used.'
=> Disable warnings CS0672, SYSLIB00(11,50,51)

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Validation.cs
=> Fixing validation adorner for not yet visible controls

src/Microsoft.DotNet.Wpf/src/Shared/cpp/dwriteloader.cpp
All supported OS always has `dwrite.dll`.
=> Simplify dwrite.dll loading process

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGrid.cs
I had an issue where I manipulated the `Columns` property of a DataGrid by removing a column. This resulted in a null-reference issue because the `TrackValue` method of the internal class `CellAutomationValueHolder` references to `column.DataGridOwner` which was not set anymore for the DataGridColumn since it was removed.
This is not a default (and maybe not wanted) behavior, but I think WPF should use here an optimistic check.
Adding a optimistic check by ignoring all `TrackValue` calls where the `DataGridOwner` property of the column is not set.
Might throw a null-reference-exception from `System.Windows.Automation.Peers.UIElementAutomationPeer.FromElement(UIElement element)` which is called within the `CellAutomationValueHolder.TrackValue` method.
CI
None
=> optimistic TrackValue check, supporting not anymore connected columns

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/KnownTypes.cs
We can use `string.Equals(string1, string2, StringComparison.Ordinal)` to check for equality, see https://learn.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings and https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings
> Use the [String.Compare](https://learn.microsoft.com/en-us/dotnet/api/system.string.compare) and [String.CompareTo](https://learn.microsoft.com/en-us/dotnet/api/system.string.compareto) methods to sort strings, not to check for equality.
Reference https://github.com/dotnet/wpf/pull/7500
Small performance improvements
None.
Just CI.
Low.
=> Replace String.CompareOrdinal to string.Equals in KnownTypes Part 2

eng/WpfArcadeSdk/tools/SystemResources.props, src/Microsoft.DotNet.Wpf/src/Common/src/System/SR.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System.Windows.Input.Manipulations.csproj, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/UIAutomationTypes.csproj
Closes dotnet/wpf#1
Cleanup following replacing resource constants with properties.
None.
No.
Low.
=> Cleanup following replacing resource constants with properties.

eng/pipeline.yml
Temporarily disabling tasks after RunTests to enable pipeline build
=> Disabled tasks after RunTests

eng/pipeline.yml
Disabling RunDrt tasks temporarily, to enable pipeline build.
=> Disabled tasks after RunTests (#7775)

src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/AnimationException.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/InvalidWMPVersionException.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/DataStreams.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/Pts.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Frame.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PrintDialogException.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/ValueUnavailableException.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlParseException.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/Journal.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/NavigationService.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceKeyNotFoundException.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/XpsViewerException.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Exceptions/XpsException.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintSystemExceptions/PrintSystemException.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/ref/ReachFramework.cs, src/Microsoft.DotNet.Wpf/src/System.Printing/ref/System.Printing.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameParser.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlException.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/ref/System.Xaml.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ElementNotAvailableException.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ElementNotEnabledException.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/NoClickablePointException.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ProxyAssemblyNotLoadedException.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/ref/UIAutomationTypes.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/Exceptions.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/ref/WindowsBase.cs
Disable warnings.
CS0672 : https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0672
SYSLIB0011 : https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0011
SYSLIB0051 : obsolete: 'This API supports obsolete formatter-based serialization. It should not be called or extended by application code.'
SYSLIB0050: obsolete: 'Formatter-based serialization is obsolete and should not be used.'
=> [8.0-preview4] Disable warnings CS0672, SYSLIB00(11,50,51) 

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlTypeInvoker.cs
Example code:
```cs
[Fact]
public void GetAddMethod_NoSuchContentType_ReturnsNull()
{
var invoker = new XamlTypeInvoker(new XamlType(typeof(List<int>), new XamlSchemaContext()));
var type = new XamlType(typeof(string), new XamlSchemaContext());
Assert.Null(invoker.GetAddMethod(type));
};
```
Use `Dictionary.TryAdd` to avoid throwing if there is more than one value. I opted to change this to `TryAdd` rather than removing `addMethods.Add(_xamlType.ItemType, _xamlType.AddMethod);`, as firstly a user can override `LookupContentWrappers` so removing this value could be breaking, and secondly because `ContentWrappers` could contain duplicate types which could throw anyway previously
Expected: we return null
Actual: we throw an ArgumentException for duplicate value in a dictionary
Fixes #210
``` …
```
=> Fix bug in `XamlTypeInvoker.GetAddMethod` if there is no such match

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
Fixes https://github.com/dotnet/wpf/issues/217
The issue here is that `XamlType._namespaces` can actually be null, for example when a `XamlType` is constructed using the `XamlType(string typeName, IList<XamlType> typeArguments, XamlSchemaContext schemaContext` constructor
=>  Fix NullReferenceException in XamlType.Equals/XamlType.GetHashCode

eng/pipeline.yml
Undoes #7775, since we have fixed the pipeline issue, we are re-enabling tests in the pipeline.
DRTs will now run whenever a PR is triggered and users can check the results for feedbacks.
CI Build
=> Re-enabling test on CI

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/Reflector.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs
The method `TryGetXamlType(string typeName, Type[] typeArgs)` is only called from `GetXamlType(string typeName, params Type[] typeArgs()` which has the following code
```cs
public XamlType GetXamlType(string typeName, params XamlType[] typeArgs)
{
if (!IsResolved)
{
return null;
}
string fallbackName = GetTypeExtensionName(typeName);
if (typeArgs == null || typeArgs.Length == 0)
{
return TryGetXamlType(typeName) ?? TryGetXamlType(fallbackName);
}
else
{
Type[] clrTypeArgs = ConvertArrayOfXamlTypesToTypes(typeArgs);
return TryGetXamlType(typeName, clrTypeArgs) ?? TryGetXamlType(fallbackName, clrTypeArgs);
}
}
```
Therefore, the `typeArgs` parameter of `TryGetXamlType(string typeName, Type[] typeArgs)` is never null or empty. Therefore the code in `MangleGenericTypeName` is dead and we can …
=> Remove dead code from XamlNamespace generic parsing

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/TextBoxView.cs
Fixes #7651 
When text box (view) uses any text alignment different from left, `TextBox.GetCharacterIndexFromPoint` does not work: wherever the line bounds do not intersect with what would be a left-aligned line bounds, it returns -1.
The PR fixes the bug by taking into account text alignment when deciding whether a point is on a line or not.
Customers not taking this fix cannot use `TextBox.GetCharacterIndexFromPoint` for text aligned to the right or centered.
No.
Built and tested with the repro in #7651, ensuring the characters do not get returned before the fix but correct characters get returned after the fix (using .NET 8.0.0-preview.3.23174.8).
Low. Existing working behavior is not changed (the `GetContentOffset` returns 0). Slight performance hit for the extra calls and …
=> Use TextAlignment for TextBox.GetCharacterIndexFromPoint

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemCommands.cs
Fixes #7739 
The `SystemCommands.ShowSystemMenu` command shows the system menu in a way that it does not accept right click, although the menu does accept right click when shown by the Windows system.
This PR updates the flag passed to the native API to allow right click to work.
Customers not taking the fix will not be able to use right click in system menu shown explicitly, as is for example the case for `WindowChrome`, introducing inconsistencies between the WPF and Windows system.
No.
Built using .NET 8.0.100-preview.3.23178.7 and tested with the repro in #7739, verified that the _Minimize_ command gets ignored before the fix and works after the fix.
Low. Existing behavior not changed. Allowed right click to not go through the system menu when invoked programmatically.
=> Allow right click in system menu

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FamilyCollection.cs
I improved performance and allocations by using spans and using ordinal ignore case comparison instead of allocating new strings with ToUpper.
Here's the result of my benchmark (I'll post the code soon):
``` ini
BenchmarkDotNet=v0.13.5, OS=Windows 10 (10.0.19045.2846/22H2/2022Update)
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=8.0.100-preview.3.23178.7
[Host]     : .NET 8.0.0 (8.0.23.17408), X64 RyuJIT AVX2
DefaultJob : .NET 8.0.0 (8.0.23.17408), X64 RyuJIT AVX2
```
|          Method | id |   familyName |       fontCollection |         Mean |      Error |     StdDev |       Median | Ratio | RatioSD | Code Size |   Gen0 | Allocated | Alloc Ratio |
|---------------- |--- |------------- |--------------------- …
=> Improve font performance in FamilyCollection.LookupFamily

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/IO/Packaging/PseudoWebRequest.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/ContentDescriptor.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/IO/Packaging/PackagingUtilities.cs
We can use `string.Equals(string1, string2, StringComparison.Ordinal)` to check for equality, see https://learn.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings and https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings
> Use the [String.Compare](https://learn.microsoft.com/en-us/dotnet/api/system.string.compare) and [String.CompareTo](https://learn.microsoft.com/en-us/dotnet/api/system.string.compareto) methods to sort strings, not to check for equality.
Reference: https://github.com/dotnet/wpf/issues/7834
Small performance improvements
None.
Just CI.
Low.
=> Replace String.CompareOrdinal to string.Equals Part 3

src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
Modernize the empty string checking in ContentType.cs
None.
None.
Just CI.
Low.
=> Modernize the empty string checking in ContentType

eng/Versions.props, eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
Fixes #7753 
Main PR 
Visual Studio Intellisense wasn't working for wpf. Fixed the intellisense file sources and bumped up the version.
Customers won't be able to see intellisense for wpf projects in visual studio.
Yes
Local Testing
Low
=> Fix intellisense not working in .NET7

eng/Versions.props, eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
Fixes #7753 
Main PR 
Visual Studio Intellisense wasn't working for wpf. Fixed the intellisense file sources and bumped up the version.
Customers won't be able to see intellisense for wpf projects in visual studio.
Yes
Local Testing
Low
=> Fix Intellisense in Visual Studio for wpf

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs
Fixes #7918
A recent removal of `StringBuilders` had a bug in there causing `Color.ToString()` throw `FormatException`.
This PR fixes the typo.
Customers not taking this fix will continue experiencing exceptions when trying to display the textual representation of colors in scRGB color space.
Yes. #6275 
Built using 8.0.0-preview.3.23174.8 and verified that the ToString() no longer throws for scRGB colors and the output is formatted correctly.
No risk, fixes regression in .NET 7.
=> Fix sc Color.ToString()

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Helper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/ParagraphVisual.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Border.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridColumnCollection.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/FlowDocumentReader.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/FlowDocumentScrollViewer.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/GroupItem.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SinglePageViewer.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Slider.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TreeViewItem.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/DoubleUtil.cs
Benchmark code:
```csharp
public class Program
{
static void Main(string[] args)
{
BenchmarkRunner.Run<Program>();
}
[Benchmark]
[ArgumentsSource(nameof(GetArguments))]
public bool TestGreaterThanZero(double value)
{
return DoubleUtil.GreaterThanZero(value);
}
[Benchmark]
[ArgumentsSource(nameof(GetArguments))]
public bool TestGreaterThanZero2(double value)
{
return DoubleUtil.GreaterThanZero2(value);
}
[Benchmark]
[ArgumentsSource(nameof(GetArguments))]
public bool TestGreaterThan(double value)
{
return DoubleUtil.GreaterThan(value, 0);
}
public IEnumerable<double> GetArguments()
{
const int count = 10;
for (int i = 0; i < count; i++)
{
yield return i;
}
for (double i = 0; i < count; i++)
{
yield return i / count;
}
for (int i = 0; i < count; i++)
{
yield return -i;
}
for (double i = 0; …
```
=> Adding GreaterThanZero to DoubleUtil.cs

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/WindowAutomationPeer.cs
This is an attempt to recover from badly-behaving Windows message hooks that may change the last error during message processing.
Fixes #7344
Fixes #4181
`UnsafeNativeMethods.GetWindowText` may throw if badly-behaving Windows message hooks are installed on the system, or potentially for other reasons. This can crash a WPF application.
Instead of crashing, we now ignore the exception and try to fall back to using `Window.Title`, which should contain the same text.
WPF applications can crash unpredictably. It may be possible for customers to work around it with more P/Invoke code: https://github.com/dotnet/wpf/issues/6026#issuecomment-1051096657
Having a fix in WPF itself would be simpler for most customers.
No.
Will ship in a consumer application and monitor user crash reports.
Legitimate …
=> Fall back to `Window.Title` if `GetWindowText` fails

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs
Fixes #7641
`ListBox` and classes derived from it (notably `ListView`) are expected to _select all_ on <kbd>Ctrl</kbd>+<kbd>/</kbd> and _select item with focus_ on <kbd>Ctrl</kbd>+<kbd>\\</kbd>. However, the implementation only checks the status of the <kbd>Ctrl</kbd> modifier, not the others. As a result, this shortcut hijacks any other combination of keys, most importantly <kbd>Ctrl</kbd>+<kbd>Alt</kbd> which is used for typing on [around 60 keyboard layouts](http://kbdlayout.info/kbdus/shortcut/VK_OEM_2+VK_RMENU) that Windows ships.
This PR fixes the problem by limiting the shortcuts to what has been documented in the code comments as intent, i.e. they will work only when <kbd>Ctrl</kbd> is pressed and nothing else.
Not taking this fix prevents users from typing characters using these …
=> Unblock AltGr+Oem2/5 typing inside ListBox

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
Fixes #7439
Removing call to XamlTyperMapper.Clear() function from finally block in compile function as the static members `HasInternal` is refrenced at the later part of codeflow and it is unsafe to clear the static members at this point of time. That being said, XamlTypeMapper gets clear in the next iteration of call to compile function.
Application having user control with internal constructors will crash.
NA
In-progress
Assessing
=> Removing xamltypemapper clearance from finally in compile function

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputEventArgs.cs
Fixes #7887
`InputEventArgs.Timestamp` field should not be static.
=> Fix InputEventArgs.Timestamp field

src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/CommonItemDialog.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/FileDialog.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/OpenFileDialog.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/OpenFolderDialog.cs
Fixing doc comments for Win32 common dialogs ( OpenFileDialog, SaveFileDialog, OpenFolderDialog ) 
Helps developer avoid confusion and understand the API.
=> Updated doc comments for common dialogs

eng/WpfArcadeSdk/tools/Wpf.Cpp.props
This PR suppresses [Compiler Warning C4956](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-c4956?view=msvc-170) for type safety checks in unmanaged code.
eg.
(__clrcall _Arg0::* )(_Types...)': this type is not verifiable.
Anyone trying to upgrade VS version to 17.7 preview 5 will not be able to build WPF
Local builds are working after this change.
Error log - [err.txt](https://github.com/dotnet/wpf/files/12239118/err.txt)
=> Fix for WPF build error post VS 17.7.0 preview 5.0 update

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/AppContextDefaultValues.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaSystem.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UnsafeNativeMethodsMilCoreApi.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/d3dutils.cpp, src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/display.cpp, src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/renderoptions.cpp, src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/renderoptions.h, src/Microsoft.DotNet.Wpf/src/WpfGfx/core/dll/wpfgfx.def, src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwbitmapcolorsource.cpp, src/Microsoft.DotNet.Wpf/src/WpfGfx/core/meta/desktoprt.cpp
Fixes #3215
Enabling Hardware Acceleration on RDP for exes which can opt-in.
Without this fix, customers won't be able to get the benefits of Hardware Acceleration on RDP.
No
In progress
Risk is Low as the applications which want to have hardware acceleration on RDP need to Opt-in by setting AppContext Switch (`Switch.System.Windows.Media.EnableHardwareAccelerationForRdp`) to true.
=> Enabling Hardware Acceleration on RDP

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/RawStylusInput.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/StickyNote/StickyNoteAnnotations.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/TemplatedAdorner.cs
Fixes #8070 
Main PR 
None
Missing null checks lead to ArgumentNullException when adding transform to collection, in case transform is null.
ArgumentNullException in apps using Validation adorners and similar adorners.
No. The bug can be reproduced in .NET7 as well, with a different repro route.
Local, WPF Test Suite.
Low.
=> Guard with null checks in adorners

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Markup/XmlLanguage.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/XamlFilter.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/XmlGlyphRunInfo.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Image.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReaderHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsCache.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsFixedPageReaderWriter.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsManager.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CaseInsensitiveOrdinalStringComparer.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/CompoundFileStorageReference.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/CompoundFileStreamReference.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/VersionedStreamOwner.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CustomSignedXml.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackUriHelper.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/StorageBasedPackageProperties.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlDigitalSignatureProcessor.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlSignatureManifest.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlSignatureProperties.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Security/RightsManagement/ClientSession.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Security/RightsManagement/IssuanceLicense.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/CompoundFile/FormatVersion.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/CompoundFile/StreamInfo.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/EncryptedPackage.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/PackageDigitalSignatureManager.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/LocalizedNameDescriptionPair.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/UseLicense.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/User.cs
We can use string.Equals(string1, string2, StringComparison.Ordinal) to check for equality, see https://learn.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings and https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings
> Use the [String.Compare](https://learn.microsoft.com/en-us/dotnet/api/system.string.compare) and [String.CompareTo](https://learn.microsoft.com/en-us/dotnet/api/system.string.compareto) methods to sort strings, not to check for equality.
Reference: https://github.com/dotnet/wpf/issues/7834
Small performance improvements
None.
Just CI.
Low.
=> Replace String.CompareOrdinal to string.Equals Final Part

src/Microsoft.DotNet.Wpf/src/Shared/System/IO/FileHelper.cs
Fixes #3138 
When a process does not have rights to delete a temporary file, it crashes, see #3138. The code already contains a catch for the case when the file is in use, so this PR adds another catch for when there are insufficient permissions for the deletion.
Customers not taking this fix may experience crashes if they do not have permission to delete temporary files. An example of codepath that uses temporary files is `Cursor.LoadFromStream` or WinRT spell checker.
This affects Visual Studio as well.
WinRT spell checker codepath has a regression from .NET Framework in that it used to check for file permissions and skip the delete if they were not granted. This PR restores the .NET Framework behavior in this case.
Built using 8.0.0-preview.3.23174.8 and verified that a WPF application …
=> Avoid crashing if temporary file cannot be deleted

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Fixes 
#5711
#5576
When running the `GenerateTemporaryTargetAssmebly` task, a temporary project file gets created from the user defined project and in the process of creation, two instances of `AssemblyName` gets inserted in the file. 
First instance will have evaluated value for assembly name (i.e. all the macros will be resolved) whereas second instance will still have the unresolved macros in the `AssemblyName`.
If `MSBuildProjectName` is being used computation of `AssemblyName`, it will cause MSBuild to pick current project name for naming the assembly and because temporary project file is being used we will have temporary project file name as assembly name and eventually no local references will be found in MarkupCompilation2.
Removing the second instance of `AssemblyName` from …
=> Fixing the AssemblyName in temporary project file for GenerateTemporaryTargetAssembly task

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Fixes dotnet/wpf#4421
Fixes dotnet/wpf#5697
Fixes build when using Razor source generator by adding RootNamespace to the list of property added to the generated project.
Without this PR, the Razor source generator would generate files in the wrong namespace (`WpfBlazorRepro_5s0cnboz_wpftmp ` instead of `WpfBlazorRepro`).
Fixes incremental build where the RootNamespace is changing on each build and therefore is recognized as a fresh build (Not incremental).
Without this PR, customers cannot build a WPF application with the Razor source generator (Maybe others?).
No. To my knowledge, it never worked.
Tested by building the repro project in the issue (https://github.com/Eilon/WPFXamlRazorGeneratorBug). This PR fixed the build.
Tested the repro here: …
=> Fix build when using Razor source generator

eng/pipeline.yml
- As of now, whenever, xUnit tests fail the Publish xUnit test result task is not run, due to the condition `succeeded()` in the task. Fixing this behavior in this PR.
- Updated the name of the xUnit tests run task to differentiate between build and the run test steps
=> Fixed PublishTestResult task and renamed Run xUnit Test task

eng/Versions.props, global.json
This change is to update the code generation using Strawberry Perl to latest version, i.e. 5.38.0.1.
None
None
Successfully build the WPF locally using .NET 8.0.100-preview.5.23303.2 win-x86
Compared the artifacts folders in current build, i.e. Perl's 5.28.1.1-1 Version, to the latest build.
Did not find significant differences in the files and minor changes were along the expected lines.
=> Perl version upgrade

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs
I was tracing an application with dotMemory and noticed a huge amount of temporary `object[]` being allocated by `EventRoute.InvokeHandlersImpl`.
This particular application had attached a listener to `PresentationTraceSources.RoutedEventSource` to trace some diagnostic information. While it's expected that doing so will add some overhead, it shouldn't be this great.
Merging this PR will greatly reduce allocations for customers whose applications add a listener to `PresentationTraceSources.RoutedEventSource.Listeners`. 
No.
Tested with dotMemory after shipping this fix in https://github.com/Faithlife/wpf.
Minimal.
=> Reduce allocations when tracing routed events

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResourceKey.cs
Fixes #679
The issue is that the original code forgets to check `memberInfo`'s declaring type. When there's a property which shares a same member name of `SystemParameters` or `SystemResourceKeyID`, it'll be treated as member of `SystemParameters`.
The following content is a part of compiled baml of issue demo. Generated by dnSpy.
Before:
```
ElementStart [TypeId=0xff02, Flags=0x00]
ContentProperty [AttributeId=0xff2b]
LineNumberAndPosition [LineNumber=0x0000000f, LinePosition=0x0000000a]
ElementStart [TypeId=0xffc9, Flags=0x00]
PropertyWithExtension [AttributeId=0xfff2, Flags=0x025a, ValueId=0xfe52]
LinePosition [LinePosition=0x00000011]
ElementEnd
ElementEnd
```
After:
```
ElementStart [TypeId=0xff02, Flags=0x00]
ContentProperty [AttributeId=0xff2b]
LineNumberAndPosition …
```
=> Fix bug where x:Static argument is treated as member of 'SystemParameters' by mistake

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs
=> Preventing focus steal if parent window/application is not active

src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/CommandEnforcer.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/DocumentManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/DocumentProperties.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/DocumentStream.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/PageTextBox.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/RestrictedTransactionalPackage.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/RightsManagementErrorHandler.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/TransactionalPackage.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/WriteableOnDemandPackagePart.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/WriteableOnDemandStream.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/ZoomComboBox.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/DigitalSignatureProvider.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/DocumentApplicationDocumentViewer.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/DocumentSignatureManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/PeoplePickerWrapper.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RMPublishingDialog.RightsTable.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RequestedSignatureDialog.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementProvider.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementResourceHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/SigningDialog.cs, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero/Microsoft/Windows/Themes/ScrollChrome.cs, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero2/Microsoft/Windows/Themes/ScrollChrome.cs, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.AeroLite/Microsoft/Windows/Themes/ScrollChrome.cs, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Microsoft/Windows/Themes/ScrollChrome.cs, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Royale/Microsoft/Windows/Themes/ScrollChrome.cs
Use ArgumentNullException.ThrowIfNull in `PresentationUI` and `Themes` as in #7181
No
CI
Low: changes are mostly mechanic, using fixer CA1510
Note that many files don't follow indentation conventions, so I had to manually realign what the analyzer changed.
=> Use ArgumentNullException.ThrowIfNull in PresentationUI and Themes

src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Automation/Peers/RibbonComboBoxAutomationPeer.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/KeyTipService.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/Primitives/RibbonGroupsPanel.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/Primitives/RibbonMenuItemsPanel.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonControlLengthConverter.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonControlService.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonHelper.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonQuickAccessToolBar.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonTwoLineText.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/StringCollectionConverter.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/TextSearchInternal.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System/Windows/Input/Manipulations/InertiaProcessor2D.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System/Windows/Input/Manipulations/ManipulationProcessor2D.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System/Windows/Input/Manipulations/Validations.cs
- Use `ArgumentNullException.ThrowIfNull` in System.Windows.Controls.Ribbon, as in #7181
- Remove internal method `Validations.CheckNotNull` and replace with `ArgumentNullException.ThrowIfNull` in System.Windows.Input.Manipulations
No
CI
Low: the changes from the first commit are mostly mechanic, using fixer CA1510. The ones from the second commit are scarce
=> Use ArgumentNullException.ThrowIfNull System.Windows.Controls.Ribbon and System.Windows.Input.Manipulations

src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsCLR.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/Misc.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/AndCondition.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/Automation.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/AutomationElement.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/CacheRequest.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/ClientSettings.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/NotCondition.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/OrCondition.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/PropertyCondition.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/Text/TextRange.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/TextPattern.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/TreeWalker.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/ValuePattern.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsEditBoxRange.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsListViewItem.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsRichEditRange.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/System/Windows/Automation/Provider/AutomationInteropProvider.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/AutomationIdentifier.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/StructureChangedEventArgs.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/WindowClosedEventArgs.cs
There were manual throw helper methods that don't make much sense keeping around anymore now that they exist in the BCL in another form, so I inlined them before using the CA1510 fixer, and then verified that all places that used to call those helpers now call `ArgumentNullException.ThrowIfNull`
- Inline two throw helper methods in UIAutomationClient
- Use `ArgumentNullException.ThrowIfNull` in UIAutomationClient
- Inline a throw helper method in UIAutomationProvider
- Use `ArgumentNullException.ThrowIfNull` in UIAutomationProvider
- Use `ArgumentNullException.ThrowIfNull` in UIAutomationClientSideProviders
- Use `ArgumentNullException.ThrowIfNull` in UIAutomationTypes
No
CI
Low: changes are mostly mechanic, using the IDE to inline methods, and then fixer CA1510
=> Use ArgumentNullException.ThrowIfNull in UIAutomation projects

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/DynamicRenderer.cs
Fixes #7537
The `_applicationDispatcher` may be null with the thread-safe issues, see https://github.com/dotnet/wpf/issues/7537
I use the argument instead of field to solve thread-safe issues.
Fix #7537
None.
CI and the [Demo](https://github.com/dotnet/wpf/files/10762876/PC-Test-develop-2.zip)
But I did not do enough testing.
Low
=> Fix NullReferenceException in DynamicRenderer

src/Microsoft.DotNet.Wpf/src/PresentationCore/ILLinkTrim.xml
Fixes Issue #3903
I added a linker hint for a dependency of DirectWriteForwarder. The linker does not currently C++/CLI assembly (See https://github.com/mono/linker/issues/676). This assembly might have been missed by #1387 because the exception does not occur at startup.
Adds a 23,5 Kb dll when using the linker.
I don't think it ever worked.
I tested using a simple repro that failed with `<TrimMode>link</TrimMode>` and it worked with `<TrimmerRootAssembly Include="System.Runtime.InteropServices" />`.
I don't think there is a risk, it only sets an assembly as never trimmed when a WPF application is trimmed.
=> Added linker hint for DirectWriteForwarder

Directory.Build.props, eng/WpfArcadeSdk/tools/SdkReferences.targets, global.json, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Update TFM from .NET 8 to .NET 9
=> Update TFM from .NET 8 to .NET 9

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/AppModel/CustomCredentialPolicy.cs
Disabled the `SYSLIB0009` warning to by pass the 'AuthenticationManager' is obsolete error
=> Fixing 'AuthenticationManager' is obsolete Build Error

src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/NativeDirectoryServicesQueryAPIs.cs
Adding `SizeConst` attribute in `NativeDirectoryServicesQueryAPIs.cs` to fix the build error.
=> Fixing SizeConst Build Error

eng/pipeline.yml
Fixes #8260 
Uncommenting the unit tests that were disabled.
_None_
_None_
Local build pass. Checked that all 334 unit tests ran and passed.
_None_
=> Enabling UnitTests for .NET 9

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapDecoder.cs
Fixes #2881
Main PR 
None
If an exception is thrown during the creation of BitmapDecoder, the FileStream used internally does not seem to be released.
BitmapStream wasn't closed and due to which the file wasn't being able to be modified or deleted.
The file will be locked for editing/deletion.
None
Local.
Low.
=> Closing the bitmapstream for UnknownBitMapDecoder

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs
Fixes https://github.com/dotnet/wpf/issues/8134
The MILUtilities.MILCopyPixelBuffer may throw ArgumentException. We put Unlock method within the finally block to ensure that the Lock and Unlock methods are called in pairs
See https://github.com/dotnet/wpf/issues/8134
None.
Just CI and my [demo](https://github.com/lindexi/lindexi_gd/tree/20395cade5a79ed40bdd03acf73320994966c691/HawacearkecallLalarnowhallna)
Normal.
=> Put Unlock method within the finally block to ensure that the Lock and Unlock methods are called in pairs

src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/OpenFolderDialog.cs
(I think I'm using Main PR correct, but I'm unsure?)
Main PR #7244 
This PR fixes the event handler invoke by guarding against the possibility that the event can be unsubscribed between the null check and the invocation which raises a null reference exception. The pattern this PR uses was introduced in C# 6. Prior to that, you could only guard against this scenario by making a local variable copy of the event delegate and checking that for null+invoke.
There's a possibility that someone unsubscribes from the event between the check and invoke, which raises a null reference exception when the event is invoked. This guards against it.
No
None
Unsure
=> Fix event call in OpenFolderDialog.cs

src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.cs.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.de.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.es.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.fr.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.it.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ja.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ko.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.pl.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.pt-BR.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ru.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.tr.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.zh-Hans.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.zh-Hant.xlf
Fixes #8292  
Updated the translation state for ScrollBar_ContextMenu_Top resource from __translated__ to __needs-translation__ to kick off the OneLocBuild localization task and get the resources translated.
Context menu for users using ScrollBar will be correctly translated for different languages.
--
--
NA
=> Update translation state for ScrollBar_ContextMenu_Top resource

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs
Fixes 
Exception thrown in GenerateTemporaryTargetAssembly when project name has GB characters in it
Main PR 
None
Bugfix for GB chars, exception thrown when using Load(CurrentProject), when project name has GB characters in it.
Using a filestream instead of using string path to avoid the need to properly compose Uri (which is another way of fixing - but more complicated).
Users will face build error, when building a project which has GB Characters in the project name.
None
Local
Low
=> Fixing exception thrown in GenerateTemporaryTargetAssembly when project name has GB characters in it

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
Adding a Null check for Data in ```SetData``` function of ```DataObject ``` class. 
A null check has been overlooked within one of the ```SetData``` functions. Even when we use the constructor to set the data with the same attributes, it still verifies whether the data is null or not.
None 
Build and local testing passed.
Low
It may cause few applications to crash with Null exception, if we try to drag and drop a null object.
=> Adding a Null check for data in SetData function

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Ink/Stroke2.cs
Just fix the comment typo.
None.
None.
None.
None.
=> Fix comment typo in Stroke2.cs

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/SpellerInteropBase.cs
Simple typo fix.
None.
Not applicable.
Not applicable.
Not applicable.
=> Fix spelling error in `ISpellerSegment`

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ContextMenu.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ContextMenu.xaml.cs
Main PR #8590 
Changed x:Class attribute value for win11 ContextMenu control styles and added ContextMenu.xaml.cs
NA
Build Pass.
NA
=> Changed x:Class attribute value for win11 ContextMenu control styles

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Input/RelayCommand{T}.cs
Main PR #8604 
Added null check in Textbox control on CanExecuteChanged to avoid exception
CanExecuteChanged may throw exception if it is null.
NA
Build Pass. Verified the visual appearance changes of controls in a sample application with this check.
NA
=> Added null check in Textbox control on CanExecuteChanged to avoid exception

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Frame.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Page.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/TabControl.xaml
Adding Win11 Styles to the following controls:
1) TabControl
2) Page
3) Frame
Build Pass.
=> Applying Win11 Styles to TabControl, Frame, Page

eng/SourceBuild.props
While this is currently called SourceBuild.props, we plan to later rename this to distinguish between source build and the dotnet build. Especially for wpf which doesn't participate in source-build.
=> Add VMR build file

src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/AcceptedMarkupExtensionExpressionTypeAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ArrayExtensionTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ConstructorArgumentAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ContentPropertyAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ContentWrapperAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/DateTimeValueSerializerTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/DependsOnAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/DictionaryKeyPropertyAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/MarkupExtensionReturnTypeAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/NameReferenceConverterTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/NameScopePropertyAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ReferenceTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/RootNamespaceAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/RuntimeNamePropertyAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/StaticExtensionTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/StringValueSerializerTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/TypeExtensionTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/UidPropertyAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/XDataTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/XamlSetMarkupExtensionAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/XamlSetTypeConverterAttributeTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/XmlLangPropertyAttributeTests.cs
Disable nullability in System.Xaml unit test to fix build of https://github.com/dotnet/wpf/pull/8695
Will revert these changes when nullability is completed for System.Xaml
=> Disable nullability in System.Xaml unit test to fix build

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/DataGridCellItemAutomationPeer.cs
Fixes #8476 
Lack of null check in `DataGridCellAutomationPeer` causes a `NullReferenceException` referencing to `column.DataGridOwner` property. Adding the null check to avoid the same.
Crashing applications where `DataGridOwner` of a column is not set.
_None_
Local build pass and verified that the sample application no longer throws the said exception.
_Low_
=> GetPattern Null check supporting columns without Datagridowner

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/StreamAsIStream.cs
The native/managed interop layer will allocate a byte array to marshal a native buffer to the `StreamDescriptor.Read` delegate. By using `Span<byte>` and the corresponding overload of `Stream.Read`, we can read directly into the caller's buffer when `CManagedStream::Read` calls this delegate.
Sample improvement by running a benchmark to create a `BitmapImage` with a `MemoryStream` `StreamSource` containing a 79KB PNG:
```
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1706 (21H2)
Intel Core i7-10875H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK=7.0.100-preview.4.22252.9
[Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
Job-FFRIND : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
Runtime=.NET 6.0  Toolchain=net6.0-windows
```
|     Method |     Mean |     Error |    StdDev | …
=> Eliminate allocation in `StreamAsIStream.Read`

src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/PresentationFramework-ref-Net48.baseline.txt, src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/System.Windows.Controls.Ribbon-ref-Net48.baseline.txt, src/Microsoft.DotNet.Wpf/ApiCompat/Baselines/UIAutomationProvider-ref.baseline.txt, src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlAttributeProperties.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
Fixes #1583 
`XmlAttributeProperties.GetXmlNamespaceMaps` and `XmlAttributeProperties.SetXmlNamespaceMaps` were throwing `System.InvalidCastException`, as it was not able to cast object of type `System.Collections.Hashtable` to type `System.String`.
Tests updated : [Test PR](https://github.com/dotnet/wpf-test/pull/264)
Documentation updated : [Documentation PR](https://github.com/dotnet/dotnet-api-docs/pull/9582)
NA
Tests have been modified to work correctly.
Low
=> Fix for GetXmlNamespaceMaps and SetXmlNamespaceMaps exception

eng/DotNetBuild.props
Same as https://github.com/dotnet/winforms/pull/10863
=> Rename SourceBuild.props to DotNetBuild.props for unified-build

.github/ISSUE_TEMPLATE/01_bug_report.yml
Stress the value of attaching projects to bug reports.
=> Bug report template

src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdiprintcontext.cpp
Fixes # 
Build failure in PR: https://github.com/dotnet/wpf/pull/8863
In Dotnet/runtime new TimeSpan.From overloads were added for int values. 
PR: https://github.com/dotnet/runtime/pull/98633
In WPF, we are using FromMinutes function from TimeSpan with value 10. 
On addition of new surface API in runtime, C++/CLI reports it as ambiguous (between int and double)
Fixing it by setting the argument value as double
N/A
=> Use double value as argument in FindMinutes function.

.github/policies/resourceManagement.yml
I noticed that draft PRs were getting "updated" without any changes (See [recently updated PRs](https://github.com/dotnet/wpf/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aopen)). That started recently and I think this was caused by #8767.
I found that for the draft automation, it wasn't checking whether or not the label was already applied before adding it (Or the opposite). There are other places where we already do this check which leads me to believe that it might be the cause for this small bug.
Note: I don't know how to test this so the change might not be correct and/or might not fix this small bug.
/cc ­@jeffhandley (Since you touched this file in #8791)
None.
No.
None.
None.
=> Fix draft PR automation

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/TypeBits.cs
Build failure: https://github.com/dotnet/wpf/pull/8888
[Thread.VolatileRead](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.volatileread?view=net-8.0) and [Thread.VolatileWrite](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.volatilewrite?view=net-8.0) are legacy APIs and have been replaced by [Volatile.Read](https://learn.microsoft.com/en-us/dotnet/api/system.threading.volatile.read?view=net-8.0) and [Volatile.Write](https://learn.microsoft.com/en-us/dotnet/api/system.threading.volatile.write?view=net-8.0).
N/A
=> Use Volatile.Read/Write instead of Thread.VolatileRead/Write

azure-pipelines-pr.yml, azure-pipelines.yml, eng/pipeline-pr.yml
Related: https://github.com/dotnet/wpf/pull/8892
Test: [Results](https://dev.azure.com/dnceng/internal/_build/results?buildId=2416960&view=results)
Steps:
- Ran the migration tool with release/6.0 branch
- changed necessary pools, templates, enable auto baselining
- Clean-up (pending)
=> [release/6.0] Migrate to 1ESPT

azure-pipelines-pr.yml, azure-pipelines.yml, eng/pipeline-pr.yml, eng/pipeline.yml
Related: https://github.com/dotnet/wpf/pull/8892
Test: [Result](https://dev.azure.com/dnceng/internal/_build/results?buildId=2415973&view=results)
Steps:
- Ran the migration tool with release/7.0 branch
- changed necessary pools, templates, enable auto baselining
- Clean-up (pending)
=> [release/7.0] Migrate to 1ESPT

azure-pipelines-pr.yml, azure-pipelines.yml, eng/pipeline-pr.yml
Related: https://github.com/dotnet/wpf/pull/8892
Test: In progress
Steps:
Ran the migration tool with release/8.0 branch
changed necessary pools, templates, enable auto baselining
Clean-up (pending)
=> [release/8.0] Migrate to 1ESPT

NuGet.config, eng/Version.Details.xml, eng/Versions.props, src/Microsoft.DotNet.Wpf/src/PenImc/dll/ComLockableWrapper.hpp, src/Microsoft.DotNet.Wpf/src/PenImc/dll/PimcManager.cpp
=> Merging internal commits for release/7.0

NuGet.config, eng/Version.Details.xml, eng/Versions.props, src/Microsoft.DotNet.Wpf/src/PenImc/dll/ComLockableWrapper.hpp, src/Microsoft.DotNet.Wpf/src/PenImc/dll/PimcManager.cpp
=> Merging internal commits for release/8.0

eng/pipeline-pr.yml
[Internal pipeline ](https://dev.azure.com/dnceng/internal/_build/results?buildId=2416843&view=results)is failing because it is running on _SignType ```real```.
Updating _SignType in pipeline-pr.yml to ```test``` for internal pipeline.
Test: [Results](https://dev.azure.com/dnceng/internal/_build/results?buildId=2421533&view=results)
CC: @lonitra
=> Update _SignType to test for Internal

src/Microsoft.DotNet.Wpf/src/WpfGfx/common/scanop/systembitmap.cpp
Fixes #5125
When acquiring lock for a bitmap rectangle, the stride of the bitmap is casted to signed integer. With sufficient large bitmaps, this will result in integer overflow, miscalculation of pixel data offsets and subsequently access violation exception when trying to access the bogus pointer.
This PR removes the cast from UINT to integer, so that the the data offset to the rectangle's top does not overflow to negative numbers.
Customers not taking this fix will continue experiencing access violation exceptions when manipulating bitmaps where height*stride > int.Max. 
No.
Compiled x64 wpfgfx_cor3.dll using MSVC 14.39.33519 and WinSDK 10.0.22621.0, replaced the existing one in .NET 8 and verified the issue in #5125 reproduces before the fix and works after fix on .NET 8.
Low. The …
=> Treat CSystemMemoryBitmap stride as unsigned

src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System.Windows.Input.Manipulations.csproj, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/UIAutomationTypes.csproj
The latest compiler fails to build WPF with
```
CSC : error CS0656: Missing compiler required member 'System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan' [D:\a\_work\1\vmr\src\wpf\src\Microsoft.DotNet.Wpf\src\System.Windows.Input.Manipulations\System.Windows.Input.Manipulations.csproj]
CSC : error CS0656: Missing compiler required member 'System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan' [D:\a\_work\1\vmr\src\wpf\src\Microsoft.DotNet.Wpf\src\UIAutomation\UIAutomationTypes\UIAutomationTypes.csproj]
```
Adding a reference to System.Memory to avoid this.  I believe this is due to use of collection expressions taking advantage of this API
=> Address CS0656 with latest compiler

src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/UIAutomationProvider.csproj
Follow up to https://github.com/dotnet/wpf/pull/9135 with one additional project.
=> Fix CS0656 in UIAutomationProvider

src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/UIAutomationClient.csproj, src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/WindowsFormsIntegration.csproj
Follow-up on https://github.com/dotnet/wpf/commit/cb1bc77538a0fe02c4af9a364e515d2f77a5be12 & https://github.com/dotnet/wpf/commit/d6b1f4560cb72806a9b55beae86ee5f769ec0960
Found in https://dev.azure.com/dnceng-public/public/_build/results?buildId=682516&view=logs&jobId=9050e078-31bf-5111-d8ec-8b6fa95caf9c&j=9050e078-31bf-5111-d8ec-8b6fa95caf9c&t=523d8a07-ca4d-5c7a-367a-d86c5fc4038b
=> Add missing System.Memory references

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/AppContextDefaultValues.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsSetLastError.cs
Contributes to #109 
Special character ligatures will be included in .NET 9 preview 4. This PR is introducing an AppContext switch to disable the feature.
Without this changes customer won't be able to disable the special character ligature.
NO
DRT + Microsuites + Feature Tests
Low. After upgrading to .NET 9 preview 4, WPF applications which have editing features that use special character ligatures may notice some unforeseen issues. For such cases, an AppContext switch (`Switch.System.Windows.DisableSpecialCharacterLigature`) can be set to `true` which will disable the feature.
=> Adding AppContext Switch for disabling special character ligatures

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml
Fixes #9150
Combobox items and radiobuttons shouldn't have a hand cursor. They don't have a hand cursor in Windows 11 settings as well.
None
I guess so
Irrelevant
None
=> Remove hand cursor in Win11 style

eng/pipeline-pr.yml, eng/pipeline.yml, eng/wpfautomatedtests.yml
The new version of the powershell script will not place the creds in the nuget.config file, instead it will use standard environment variables. Update the YAML file to use NuGetAuthenticate to avoid a build break that may happen if the credential provider is not available.
=> Call NuGetAuthenticate after SetupNuGetSources

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/InkSerializedFormat/DrawingAttributeSerializer.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
Fix build failure: https://github.com/dotnet/wpf/pull/9163
Replacing System.IO.Stream.Read with System.IO.Stream.ReadExactly, to resolve the CA2022 error.
=> Disable CA2022 error

eng/pipeline-pr.yml, eng/pipeline.yml
These use WIF to get dSAS tokens for internal runtimes, as well as using NuGetAuthenticate to authenticate to internal feeds.
=> Use new templates to enable internal sources and runtimes

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml
Due to missing `TargetName` property in various triggers of default button styles in Fluent window, there were visible discrepancies in UI when background property was set. The following changes adds the property and applies the `Background` and `BorderBrush` property specifically to the border enclosing the content presenter.
It fixes the accessibility issues with hover and pressed states of a button, when `Background` or `BorderBrush` property is set at the application level.
Sample Application Testing
_None_
=> Add TargetName to Button's Trigger

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Accent.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC1.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC2.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCBlack.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCWhite.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
To make the colors and brushes more alinged with the WinUI one we have made the following changes:
1. Moved some brushes from accent.xaml file to each theme file.
2. Added some brushes in Light.xaml and dark.xaml
3. Changed the color code of  TextOnAccentFillColorDisabled and ControlAltFillColorTertiary
=> Making resources in parity with WinUI

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
Fixes #9082 
For top-level containers such as app windows, flyouts, cards and dialogs, WinUI uses the resource `OverlayCornerRadius` with a value set to 8 pixel. Similar resource in WPF is set to 4 pixels and this change updates the value the resource to 8 pixels.
_None_
Sample Application Testing
_None_
=> Update Corner Radius Resource

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml
Fix for "Narrator is announcing incorrect information for expand button"
Users who rely on the screen reader users will be confused if Narrator is announcing incorrect information for expand button in the Design Guidance.
None 
Local build passed, tested sample app.
NA
=> Fix for "Narrator is announcing incorrect information for expand button"

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ScrollViewer.xaml
Fix for "keyboard focus is not navigating to next and previous tab items in tab control page."
Motor impaired users will not be able to navigate to the next/previous tab items.
None
Local build passed, tested sample app.
NA
=> Fix keyboard focus is not navigating to next and previous tab items in tab control

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Cursor.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputScopeConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputScopeNameConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemKeyConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementResourceHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/SignatureResourceHelper.cs
Use generic version of Enum.GetName to improve performance and reduce allocations.
The generic version was introduced in .Net 5: https://learn.microsoft.com/en-us/dotnet/api/system.enum.getname?view=net-8.0#system-enum-getname-1(-0)
Benchmark results:
|     Method | knownColor |      Mean |     Error |    StdDev |    Median | Ratio |  Gen 0 | Allocated |
|----------- |----------- |----------:|----------:|----------:|----------:|------:|-------:|----------:|
| NonGeneric |  ScrollAll | 14.631 ns | 0.2646 ns | 0.2346 ns | 14.626 ns |  1.00 | 0.0014 |      24 B |
|    Generic |  ScrollAll |  3.018 ns | 0.0764 ns | 0.1526 ns |  2.959 ns |  0.21 |      - |         - |
I used this benchmark:
<details>
<summary>Code</summary>
```csharp
[MemoryDiagnoser]
public class EnumGetNameBenchmark
{ …
```
=> Use generic version of Enum.GetName

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/CursorConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputScopeNameConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/RequestCachePolicyConverter.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/KeyConverter.cs
Use generic version of Enum.Parse to improve performance and reduce allocations.
The generic version was introduced in .Net Core 2.0: https://learn.microsoft.com/en-us/dotnet/api/system.enum.parse?view=net-8.0#system-enum-parse-1(system-string)
Benchmark results:
|     Method |    value |     Mean |    Error |   StdDev | Ratio |  Gen 0 | Allocated |
|----------- |--------- |---------:|---------:|---------:|------:|-------:|----------:|
| NonGeneric | SizeNESW | 42.99 ns | 0.807 ns | 0.793 ns |  1.00 | 0.0014 |      24 B |
|    Generic | SizeNESW | 16.38 ns | 0.196 ns | 0.174 ns |  0.38 |      - |         - |
I used this benchmark:
<details>
<summary>Code</summary>
```csharp
[MemoryDiagnoser]
public class EnumParseBenchmark
{
[Benchmark(Baseline = true)]
[Arguments("SizeNESW")]
public …
```
=> Use generic version of Enum.Parse

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Knowncolors.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/StickyNote/StickyNoteAnnotations.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Tracing/SpellerCOMActionTraceLogger.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/RightsManagementResourceHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/SignatureResourceHelper.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/PrintSchema.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/DpiAwarenessContext/DpiAwarenessContextHandle.cs
Use generic version of Enum.GetValues to improve performance and reduce allocations.
The generic version was introduced in .Net 5: https://learn.microsoft.com/en-us/dotnet/api/system.enum.getvalues?view=net-8.0#system-enum-getvalues-1
Benchmark results:
|     Method |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 |  Gen 1 | Allocated |
|----------- |---------:|---------:|---------:|------:|--------:|-------:|-------:|----------:|
| NonGeneric | 63.97 ns | 1.292 ns | 2.581 ns |  1.00 |    0.00 | 0.0353 | 0.0001 |     592 B |
|    Generic | 33.34 ns | 0.672 ns | 0.690 ns |  0.50 |    0.02 | 0.0353 | 0.0001 |     592 B |
I used this benchmark:
<details>
<summary>Code</summary>
```csharp
[MemoryDiagnoser]
public class EnumGetValuesBenchmark
{
[Benchmark(Baseline = true)]
public …
```
=> Use generic version of Enum.GetValues

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/Utilities.cs
Now, the Version of PresentationFramework will never less than 4. It reduces unnecessary initialization.
Minor Performance Optimization
None.
Just CI.
Very Low.
=> Performance Optimization by Reduce reflection assemblies in Utilities.cs

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TabItem.cs
Fixes #8293
When a `TabItem` is selected in `TabControl`, it sets focus to its content (unless the `TabItem` itself is focused). If the content gets succesfully focused, then the `TabItem` supresses receiving focus to not steal it from the content back.
When the content is a `Button` in its own focus scope (such as in a `ToolBar`), the `Button` will try to switch back to the main focus scope after pressed (on losing mouse capture).
Finally, when a `TabItem` is focused, the `TabControl` will switch to that tab.
As a result, if a `TabItem` contains `ToolBar` with a `Button`, that `Button` will try to re-focus the previously focused element. However, if the `TabItem` suppressed receiving focus,  then the previously selected tab will still be remembered as the last focused element, and …
=> Keep track of selected TabItem for focus

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/MouseActionConverter.cs
Fixes Xaml Unsupported MouseAction.None value #8842
=> Supported MouseAction.None in xaml #8842 

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
Fixes Issue #4468 
The currently used implementation to keep track of DynamicResource usages is suboptimal as the list can grow quite large and scanning gets very expensive.
That's caused by two issues:
- Every call to FetchResource adds a new entry to the list
- The list implementation is slow as it does not use keys
The improved implementation only adds items with the same key once by checking for existing items before adding new ones. As the new implementation uses keys, retrieval of items is very fast. 
Slow performance.
Tested the app from #4468
=> Improve performance of DynamicResource usages

src/Microsoft.DotNet.Wpf/src/PenImc/dll/ComLockableWrapper.hpp, src/Microsoft.DotNet.Wpf/src/PenImc/dll/PimcManager.cpp
Adds a check in ComLockableWrapper to verify the availability of the m_serverobject before calling Release on the object.
Mitigates [CVE-2024-21409](https://www.cve.org/CVERecord?id=CVE-2024-21409)
=> Avoid unlocking ComLockableWrapper when server object is already null

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
Fixed names of base methods referred to in XML documentation remarks. This was clearly caused by the documentation being copied from the `OnClosed` method.
Slight confusion because the documentation is telling the user to call the base method of a different method.
No
None, as only XML documentation was fixed.
None, as only XML documentation was fixed.
=> Fixed method names in Window XML doc remarks

eng/Version.Details.xml, eng/Versions.props, eng/common/templates-official/job/source-build.yml, eng/common/templates-official/job/source-index-stage1.yml, eng/common/templates-official/jobs/source-build.yml, eng/common/templates-official/post-build/common-variables.yml, eng/common/templates-official/steps/enable-internal-runtimes.yml, eng/common/templates-official/steps/get-delegation-sas.yml, eng/common/templates-official/steps/get-federated-access-token.yml, eng/common/templates/job/source-build.yml, eng/common/templates/job/source-index-stage1.yml, eng/common/templates/jobs/source-build.yml, eng/common/templates/post-build/common-variables.yml, eng/common/templates/steps/enable-internal-runtimes.yml, eng/common/templates/steps/get-delegation-sas.yml, eng/common/templates/steps/get-federated-access-token.yml, eng/pipeline-pr.yml, eng/pipeline.yml, global.json
=> [release/6.0] Switch to dSAS for internal runtimes

eng/pipeline-pr.yml
Updated the .NET Runtime being downloaded for running WPF's automated tests.
NA
Build pipeline success will verify the changes.
NA
=> Updated .NET Runtime used for running WPF automated tests ( DRTs )

src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Certificate.cs
Fix Build failure: https://github.com/dotnet/wpf/pull/9366
Use ```X509Certificate2``` constructor to create certificate is marked as obsolete. 
Update it with new ```X509CertificateLoader.LoadCertificate``` added in runtime.
Reference:
https://github.com/dotnet/runtime/pull/104165
=> Replace X509Certificate2 ctor with X509CertificateLoader.LoadCertificate

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
The current implementation of `Fluent` themes does not work in Windows 10. The following changes makes the control styles and theme effects affective for windows 10 as well. 
Customers will be able to use Fluent themes in Windows 10 by including the Fluent resource dictionary as they could have in windows 11.
_None_
Sample Application Testing
=> Enabling Fluent theme in Windows 10

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
To make the colors and brushes more alinged with the WinUI one we have made the following changes:
1. Added some brushes in Light.xaml and dark.xaml
2. Changed the color code of TextOnAccentFillColorDisabled and ControlAltFillColorTertiary in Light.xaml and dark.xaml
3. Removed some brushes from Light.xaml, HC.xaml and dark.xaml
None
Local build passed, tested sample app.
NA
=> Making common resource in parity with WinUI

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Window.xaml
Until now, we had two different styles for Window, one for Highcontrast and when backdrop is disabled and other one that is used in the normal scenario. 
We don't need to handle two different styles for Window in Fluent theme.
N/A
Local testing with WPF Gallery application.
N/A
=> Combining backdrop disabled and default window styles

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Speller.cs
Replaces `CaseInsensitiveComparer` with `IComparer<string>` interface (`StringComparer`). Also replaces `ArrayList` with generic `List<string>` for minor perf benefit and increased code quality.
- The `IComparer<string>` is now stored as a `readonly` variable in `Speller`, removing constant comparer allocs on segment checks. 
- Also removes unnecessary `char[]` allocation/copy and its immediate conversion to `string`, skipping one whole alloc round.
- Keeps the initial capacity of 1 for the list, the subsequent sorted insertions are not a bottleneck for this use-case.
I've created a very rough typical use-case benchmark that's not gonna be 100% time-accurate but the time itself isn't important, allocs are (should mimic the previous/new code).
| Method   | Mean [ns]    | Error [ns] | …
=> Replace CaseInsensitiveComparer with generics in Speller, remove allocations

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeRenderer.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/MouseGestureConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/FontFamilyConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/PresentationSource.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/Journaling.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextAdaptor.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/RtfToXamlReader.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextSelection.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfKnownMemberInvoker.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfMemberInvoker.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/JournalEntry.cs
Hi 🙂
This pull request removes unnecessary semicolons from the `PresentationCore` and `PresentationFramework` projects in the .NET WPF repository.
There is no risk to functionality from these changes.
=> Remove Redundant Semicolons

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceExpression.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/DependencyObject.cs
This PR fixes the issues introduced by my other PR #5610.
=> Fixing issues with DynamicResource usage

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontCollectionLoader.h, src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileEnumerator.h, src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileLoader.h, src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileStream.h, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/inc/GDIExporter/gdirt.h, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/FontInfo.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdibitmap.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdidevice.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdipath.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdipen.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdirt.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gditextrt.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/utils.cpp
Main PR  #9433 
Addressed error C2668: 'System::Diagnostics::Debug::Assert': ambiguous call to overloaded function.
NA
Local build pass.
None
=> Addressed build failure : ambiguous call to overloaded function

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontCollectionLoader.h, src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileEnumerator.h, src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileLoader.h, src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/FontFileStream.h, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdibitmap.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdibrush.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdipath.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdipen.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gdirt.cpp, src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/GDIExporter/gditextrt.cpp
https://github.com/dotnet/sdk/pull/42262#issuecomment-2243885156
=> Debug::Assert(false to Debug::Fail

Microsoft.Dotnet.Wpf.sln, eng/Versions.props, src/Microsoft.DotNet.Wpf/src/PresentationCore/OtherAssemblyAttrs.cs, src/Microsoft.DotNet.Wpf/tests/Directory.Build.props, src/Microsoft.DotNet.Wpf/tests/UnitTests/Directory.Build.targets, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System.Xaml.Tests.csproj
Enables PresentationCore tests.
@adamsitnik noted here https://github.com/dotnet/wpf/pull/9465#discussion_r1691382762 that PresentationCore.Tests was not included so the tests were not running. By reading the commit messages in dotnet/wpf#8532 it seems like they were disabled temporarily but I don't know why. I took it upon myself on enabling them and fixing the build and runtime errors (I don't know if they were the cause on why they were disabled).
It also fixes the build errors and some runtime errors in dotnet/wpf#8215 but WindowsBase.Tests would need some changes to completely fix it and I plan on working on it once this PR is merged.
I hope I didn't step on anyone's toes if they were working on it.
WPF would be more tested.
No.
Local build + tests passing locally.
None, shouldn't …
=> Enable PresentationCore tests

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/net5.0/Themes/Generic.xaml, packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/net6.0/Themes/Generic.xaml
Fixes #8773 
Added Themes folder with Generic.xaml under net5.0 and net6.0 folders so that when a user creates a WPF Custom Control Library project (NOT the .NET Framework version) it will include a Themes folder that in turn will contain Generic.xaml.
I created a new WPF Custom Control Library project (NOT the .NET Framework version) and it has a Themes folder that in turn contains Generic.xaml.
=> Added Themes folder with Generic.xaml under net5.0 and net6.0 folders.

eng/WpfArcadeSdk/tools/TestProjects.targets, global.json, src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj, src/Microsoft.DotNet.Wpf/src/PresentationCore/ref/PresentationCore-ref.csproj, src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj, src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework-ref.csproj, src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj, src/Microsoft.DotNet.Wpf/src/System.Xaml/ref/System.Xaml-ref.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
Fixes # https://github.com/dotnet/wpf/issues/9309
WPF was depending on the package version of System.Runtime.Serialization.Formatters but never shipping it. Instead WPF should depend on the built-in assembly version.  To do that we need to update the SDK version since WPF's vcxprojs don't
enable the nuget package targeting pack https://github.com/dotnet/wpf/issues/9490
Customers see a `FileNotFoundException` instead of the expected `PlatformNotSupportedException` when using API that depends on `BinaryFormatter`.
Yes, regressed in Preview6.
I've run the unit tests with the fix.  I made sure the test assemblies reference the compatibility package.  WPF should add more tests to validate that without the package they'll throw PNSE - https://github.com/dotnet/wpf/issues/9491
Low.  If it builds …
=> Ensure WPF builds against framework SRSF version

src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1
Update ThemeGenerator.Fluent.ps1 script
None
NA
=> Update ThemeGenerator.Fluent.ps1 script

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #9059
Renamed accent button style name to AccentButtonStyle to match WinUI
=> Renamed accent button style name to AccentButtonStyle

src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/RCW/IXpsOMFontResource.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/RCW/IXpsOMPartUriCollection.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/XpsOMPackagingPolicy.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/XpsOMSerializationManager.cs
Fixes #6296
Printing a large size of document ends up consuming a lot of memory. The change in the PR targets to address this issue.
This change releases the font resources after every four pages. We see huge memory consumption difference as the number of pages grow.
Also, with the change we make sure that all resources gests released once printing is completed.
Don't know.
Made sure existing functionality remains same. Validated this by comparing the file sizes and the content of it.
Low.
=> Release font resources to fix memory leak

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Making accent color brushes of Light.xaml and Dark.xaml in parity with WinUI
None
NA
=> Bringing accent color brushes of light.xaml and dark.xaml in parity with WinUI

eng/Versions.props
reverting branding to release/9.0-rc2 changes
=> Reverting : Branding to release/9.0-rc2 changes

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Fonts.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/MenuItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ScrollBar.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolBar.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TreeViewItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
The following changes enables icon support for various controls when styled using Fluent theme on Windows 10. Also, it updates the resource value used by the `SegoeFluentIcons`.
Developers can use icon support controls in windows 10 with Fluent theme.
Developers also need to update the fluent key value to `SymbolThemeFontFamily` in their application if used earlier.
_None_
Sample Application Testing on Windows 10 and Windows 11
Low
=> Icon Support for Windows 10

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/FrameworkAppContextSwitches.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceExpression.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
Implements the opt-out switch for DynamicResource optimization implemented in ( #5610, #9393 )
See here https://github.com/dotnet/wpf/pull/5610#issuecomment-2262959543
N/A
Local Testing with sample apps
cc @miloush @batzen @h3xds1nz
=> Opt-out switch for DynamicResource optimization

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourcesChangeInfo.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
Fixes : #9486 
This is another variation of the fix for above issue. 
Currently, when we get an Application Resource invalidation request, we check if there is a need to update the ThemeMode property due to the change in the Application.Resources . In the case, when ThemeMode property needs to be updated we returned true after sync, and when we get true, we did not do further invalidation of the resources for the original request.
Ignoring the original request results in incoherent UI, as the values changed are not getting properly reflected in the visual tree.
So, the core fix here is that I have removed the `return` statement and let all the invalidation's take place. Apart from this, I have also renamed the flags and methods to make it a bit easier to understand. Moreover, as an …
=> [Fix] Don't ignore application resource invalidations

eng/WpfArcadeSdk/Sdk/Sdk.props
Increate LangVersion to support c# 12 version features for rtm build
=> Set default LangVersion to 12

eng/WpfArcadeSdk/Sdk/Sdk.props
Change the default LangVersion for 9.0.0 rtm build to version 12
=> [release/9.0] Default LangVersion update to to 12

eng/wpf-debug.targets
Setting `RuntimeIdentifier` to win-x64 incase `PlatformTarget` is not explicitly mentioned
Developer needs to add `PlatformTarget` explicitly when trying to link local build
NA
NA
Low
=> Setting RuntimeIdentifier to win-x64 incase PlatformTarget is not available

global.json, src/Microsoft.DotNet.Wpf/redist/D3DCompiler/D3DCompiler.vcxproj
Works around https://github.com/dotnet/wpf/issues/9670. An updated redist came in from a recent update. The old redist has been uploaded to netcorenativeassets, and we use that rather than the Windows SDK path to resolve the file paths.
=> Work around d3d redist incompat.

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/DataObjectTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
Fixes # https://github.com/dotnet/wpf/issues/9491
Adding 12 new unit tests, which ensure that the unsupported data types will use BinaryFormatter and in the absence of System.Runtime.Serialization.Formatters package the Clipboard will throw an exception which is expected.
Outer exception:
DataObject stored in clipboard is invalid.
Inner exception is 
PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
=> Add unit test to ensure the unsupported data types will use BinaryFormatter

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
Replaces boxing `ArrayList` with `List<IntPtr>` to hold window handles for the current thread (`_threadWindowHandles`).
Sample benchmark showing difference between `ArrayList` and `List<IntPtr>` (box/unbox cost).
| Original | 108.51 ns |   2.088 ns |    1.953 ns | 0.0339 |       1,179 B |         568 B |
| PR__EDIT |  58.36 ns |   0.880 ns |    0.780 ns | 0.0196 |         305 B |         328 B |
```c#
[Benchmark]
public void Original()
{
ArrayList? _threadWindowHandles = null;
for (int i = 0; i < 10; i++)
BenchV1(ref _threadWindowHandles);
for (int i = 0; i < …
```
=> Replace boxing ArrayList in Window with List<IntPtr> (ThreadWindowHandles)

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/ValueChangedEventManager.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Interop/ComponentDispatcherThread.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/PropertyMetadata.cs
Use `Delegate.EnumerateInvocationList` instead of `Delegate.GetInvocationList`. `Delegate.GetInvocationList` allocates an array on every call while `Delegate.EnumerateInvocationList` doesn't allocate which makes the code faster and use less memory.
I also used `Delegate.HasSingleTarget` for places where we only wanted to check if there was only one entry in `Delegate.GetInvocationList`, which makes it even faster.
`Delegate.EnumerateInvocationList` and `Delegate.HasSingleTarget` were added in .Net 9.0 Preview 4 with dotnet/runtime#97683.
Benchmark results for `Delegate.EnumerateInvocationList`:
| Method                  | count | eventHandler         | Mean      | Error     | StdDev    | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|------------------------ |------ …
=> Use Delegate.EnumerateInvocationList instead of Delegate.GetInvocationList

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
Replaces two `Array.CreateInstance` calls with the `new[]` keyword. There is no reason to use the former call in this case.
Improved array allocation performance.
None.
Verifying basic method functionality.
None.
=> Replace Array.CreateInstance(...) calls in DataObject with the new[] operator

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GridViewItemAutomationPeer.cs
Fixes #9181 
I was running some tests with ListView (using GridView) and when I loaded `1 000 000` items (yes, an obscure use case but that's why we got virtualization, no?), the scrolling performance would degrade and keyboard scrolling felt almost unusable.
During a quick rundown, I've discovered the culprit is in override of `GetChildrenCore` of `GridViewItemAutomationPeer`, which performs IndexOf (linear) search in the `Items` collection of the underlying `ItemsSource` to find the respective item's Row. 
The easiest step to reproduce is to add a ListView with GridView plus a ComboBox, after opening the ComboBox's dropdown (clicking it), `Accessibility.dll` gets loaded and the party gets started. You can find a demo repository on [Github - …
=> Fix ListView/GridView scroll performance when automation peers are created

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/TextBoxBase.cs
Fixes # none
Main PR  N/A
As noted in the title, the `TextBoxBase.OnPreviewKeyDown` override incorrectly calls virtual base method `UIElement.OnKeyDown` instead of `UIElement.OnPreviewKeyDown`.
This type of bug could have been catastrophic (and thus would have been found years ago), but in this case it happens to be benign, since both of those base methods (`UIElement.OnKeyDown` and `UIElement.OnPreviewKeyDown`) are vacuous.
Fixing this typo would mitigate a future problem in the (unlikely) case that code ended up getting added to one or both of the affected virtual base methods.
A more practical concern is that the error could cause false positive errors, diagnoses, and/or reports to occur with static analysis and automated code manipulation tools.
Code readability and principled …
=> [TextBoxBase.cs] OnPreviewKeyDown override calls wrong virtual base method

src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
Change Substring for AsSpan for a method that already accepts a span. It looks like it was missed in dotnet/wpf#6268 when ParseParameterAndValue was changed to accept a span.
Better perf
No
Local build + CI
Low
=> Use span in ContentType

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/EffectiveValueEntry.cs
In this PR, I have updated the initialization of `IsCoercedWithCurrentValue` in `FullValueSource` to use a 4-digit representation. This change does not alter any code behavior and is purely for the sake of code consistency. 
Previously, all other member definitions in `FullValueSource` were using a 4-digit representation, with `IsCoercedWithCurrentValue` being the only exception with a 3-digit representation. I have made this change to unify the digit representation across all members in `FullValueSource` to 4 digits.
None.
None.
None.
None. I do not change any of the code behavior.
=> chore: Standardize digit representation in FullValueSource by updating IsCoercedWithCurrentValue initialization

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #9197 
Fixes visibility of ScrollViewer in TextBox in the new Fluent styles introduced in .NET 9. 
In the previous styles ( Aero2 ) when we set the ScrollViewer.HorizontalScrollBarVisibility or ScrollViewer.VerticalScrollBarVisibility on TextBox, scrollbars appear in the TextBox area, however in the new Fluent styles, the properties did not work. This PR fixes the above issue
Technically no, but any developer who will try to port their application to use the new styles will face this issue and the property won't work for them.
Local build pass. Tested with sample application.
NA
=> Fixing scrollviewer visibility in textbox

src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj, src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
With dotnet/runtime#107905, we are marking `System.Formats.Nrbf` as `[Experimental]`, using diagnostic ID `SYSLIB5005`. This suppresses the diagnostics produced by that annotation.
We plan to backport this change to `release/9.0` and `release/9.0-rc2`.
=> Suppress SYSLIB5005 for System.Formats.Nrbf as experimental

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ContextMenu.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListBoxItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListView.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListViewItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Menu.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/MenuItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Page.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ScrollBar.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolTip.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #9564 
In many of the Fluent styles template bindings are not set correctly. In this PR, I have tried to fix most of the template binding issues by comparing the styles to both Aero2 and WinUI styles.
Developers using the new Fluent styles won't have to create custom styles for setting properties like BorderBrush, Background, BorderThickness and alignment properties.
Technically no, but any developer who will try to port their application to use the new styles will face this issue and the properties won't work for them.
Local testing with sample apps and WPF Gallery application.
Minimal. Apps are not using this feature ( except those who are working with .NET 9 preview releases )
=> Add missing Bindings in Fluent ControlTemplates

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemColors.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeMode.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeModeConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
Adds the API reference docs for ThemeMode and ThemeModeConverter APIs introduced in .NET 9. This will be used to generate the .NET 9 reference API docs.
Developers using ThemeMode and ThemeModeConverter in their applications can refer to the docs to understand how to use the given APIs
N/A
N/A
N/A
=> Added ThemeMode and ThemeModeConverter reference docs

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/AttachableMemberIdentifier.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterFrame.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlNodes.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/NamespacePrefixLookup.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/NodeStreamSorter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlAttribute.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlPropertyName.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlQualifiedName.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/ClrObjectRuntime.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/DynamicMethodRuntime.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ClrNamespaceUriParser.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/Reflector.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlDirective.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlValueConverter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMarkupExtensionWriter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMember.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlXmlWriter.cs
See #8519
We replace as many manual string concatenations and string.Format with interpolated strings. This saves allocations in many instances, and makes for a more readable code.
Less allocations
No
CI
Low. Most changes are automated using the IDE
=> Prefer use of interpolated strings in System.Xaml

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/DpiUtil/DpiUtil+ProcessDpiAwarenessHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/SafeNativeMethodsCLR.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/Accessible.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/SafeProcessHandle.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Win32/UnsafeNativeMethods.cs
Use Environment.ProcessId instead of calling a Win32 function. Environment.ProcessId uses the same [Win32 function](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocessid) that we were currently using but the difference is that Environment.ProcessId caches the process id instead of doing a PInvoke every time it is accessed (The Win32 function is documented as not changing during the lifetime of the process, see [here](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocessid#remarks)). 
Here's the current implementation of Environment.ProcessId on Windows: https://github.com/dotnet/runtime/blob/60edbf9371ff00349e9224fb0920c8bca51f1a4f/src/libraries/System.Private.CoreLib/src/System/ …
=> Use Environment.ProcessId instead of calling a Win32 function

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Parsers.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/ColorTypeConverter.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/ReachSerializationCacheItems.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlSignatureProperties.cs
Replaces `Array.GetLength(0)` on single-dimensional arrays with the `Length` property for performance benefit, clarity and general code quality. I didn't replace a few in `Color` and `ColorTransform` as that's part of my other PR and I don't want to create conflicts.
Improved performance.
No.
Build, the changes are minimal hence no further testing.
Low.
=> Replace Array.GetLength on single-dimensional arrays with Length property

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlReader.cs
Replaces boxing `Stack` with `Stack<bool>`, increasing overall performance and decreasing allocations/code-size.
Also replaces non-generic `Stack` with `Stack<BamlNodeInfo>` and makes it `readonly`.
For ilustration, here are some benchmarks:
| Method       | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|------------- |----------:|-----------:|------------:|-------:|--------------:|--------------:|
| BoxingStack  |  67.83 ns |   1.107 ns |    0.981 ns | 0.0238 |         869 B |         400 B |
| GenericStack |  22.23 ns |   0.213 ns |    0.189 ns | 0.0038 |         210 B |          64 B |
```c#
[Benchmark]
public void BoxingStack()
{
Stack stack = new Stack();
stack.Push(true);
int i = 0;
while (i < 10)
{
if …
```
=> Replace boxing Stacks in BamlReader, decrease allocs, improve performance

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Thickness.cs
Fixes https://github.com/dotnet/wpf/issues/8789
I change the GetHashCode implementation of the Thickness struct. I use the HashCode to calculate the hash code of Thickness.
I'm not sure I'm doing the right thing.
The GetHashCode  of Thickness will be change
Just CI.
Normal. It's hard to evaluate. Because some logic that depends on the original behavior can break down.
=> Try fix GetHashCode implementation of the Thickness struct is broken for uniform length

src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/HwndWrapper.cs
I have optimized the performance by reducing the number of times `AppDomain.CurrentDomain.FriendlyName` property is accessed. Accessing the FriendlyName property is not cheap and results in some additional performance overhead. By assigning it to a local variable first, I have managed to reduce multiple property accesses, thereby slightly improving performance without altering the existing logic.
```
public sealed partial class AppDomain : MarshalByRefObject
{
public string FriendlyName
{
get
{
Assembly? assembly = Assembly.GetEntryAssembly();
return assembly != null ? assembly.GetName().Name! : "DefaultDomain";
}
}
}
```
See https://github.com/dotnet/runtime/blob/222d4c5df0b63edb4dbb75771c6e0f8c1315746e/src/libraries/System.Private.CoreLib/src/System/AppDomain.cs#L65-L72
Minor …
=> Minor Performance Optimization by Reducing Calls to `AppDomain.CurrentDomain.FriendlyName`

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Control.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridTextColumn.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextElement.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkElement.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemFonts.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RepeatButton.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToggleButton.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TreeViewItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #9192  
Fluent styles use 14 as the default size and so in order to handle this we check if the Fluent theme is enabled at the Application level and in that case we used to return the size 14 without scaling it. Hence, even though Text Scaling is set to something other than original size, we did not adjust the font size to match the scaling.
In this PR, I have replaced the DefaultFluentFontSize with DefaultFluentFontSizeFactor and use this to modify the system font size that we get from SystemParameters
Developers and users that use scaling other than 100% will see the text in scaled size ( whenever the size is not explicitly set on the control )
Technically no, as Fluent style is a new feature.
Local Ad-Hoc testing with sample applications
Minimal. No one is using this currently ( …
=> Fixed Font Scaling issue when FontSize is not set explicitly

NuGet.config, eng/Versions.props
We want to enable NuGet audit on all the repos that make up the .NET product. https://github.com/dotnet/arcade/issues/15019
The only problems I encountered were due to transitive dependencies brought in by Moq.  I fixed those by upgrading to the same version used in other dotnet repos.
=> Enable NuGet Audit

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/RBTree.cs
Resolving policheck bugs by replacing country with country/region
NA
NA
=> Resolving Policheck bugs

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputLanguageManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputLanguageSource.cs
Replaces `ArrayList` with a `CultureInfo[]` of 1 item downcasted to `IEnumerable` to improve performance of retrieval and decrease allocations caused by allocating an `ArrayList` and adding an item into it.
| Method       |  Mean [ns] | Error [ns] | StdDev [ns] | Code Size [B] | Gen0   | Allocated |
|------------- |----------:|-----------:|------------:|--------------:|-------:|----------:|
| ArrayList | 13.167 ns |  0.2586 ns |   0.3362 ns |         488 B | 0.0053 |          88 B |
| GenericList|   8.222 ns |  0.1907 ns |   0.1690 ns |       1,261 B | 0.0038 |          64 B |
| PR__EDIT|  4.229 ns |  0.1225 ns |   0.2864 ns |          54 B | 0.0019 |          32 B |
Improved performance, less allocations.
No.
Local build, CI.
As outlined in the discussion with @miloush, this is a change …
=> Replace ArrayList in InputLanguageSource with fixed-size array, reduce allocations

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/CursorConverter.cs
Optimizes `GetStandardValues` function from TypeConverter by replacing `ArrayList` with preallocated array as we know the size beforehand, removes unnecessary allocations caused by copying the list and re-allocating the internal array.
Removes the private helper function `GetProperties` that's only used in 1 place, inlining it instead.
| Method                    | Mean     | Error    | StdDev   | Median   | Gen0   | Allocated |
|-------------------------- |---------:|---------:|---------:|---------:|-------:|----------:|
| GetStandardValues         | 560.4 ns | 11.12 ns | 15.21 ns | 555.2 ns | 0.0677 |    1136 B |
| GetStandardValues_PR      | 455.9 ns |  9.11 ns | 16.88 ns | 447.2 ns | 0.0315 |     528 B |
Improved performance, reduced allocations.
No.
Method functionality test, build. …
=> Replace ArrayList in CursorConverter with preallocated array and reduce allocations

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/DependencyProperty.cs
Optimizes name lookup of `DependencyProperty`, this way all name-lookups are allocation free as the key is now `struct` and is created on stack everytime. Since name is looked up when registering property as well, this optimizes that case too.
- `Hashtable` is replaced with `Dictionary<FromNameKey, DependencyProperty>`, offering perf benefits.
- Thread-safety concerns do not apply, all operations on the dictionary are under the same lock.
- `FromNameKey` is now `struct` instead of `class`, which removes any heap/gen0 allocations on lookups.
- The `Synchronized` field for locking is now `System.Threading.Lock` instead of `object` (slight perf improvement).
- Since key is a `struct` now, the memory footprint of the whole collection will be lower.
| Method   | name       | ownerType  | Mean …
=> Optimize DependencyProperty lookup/registration performance, remove allocs

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Component/AdornerPresentationContext.cs
Replaces two boxing `Hashtable` collections with generic `Dictionary<K, V>`, improving performance and decreasing allocations.
- There are no locks but I do not believe there are any thread-safety concerns as the collections are only set once per my code inspection and testing it with few sample apps, plus if it was a concern, even `Hashtable` would need lock for proper functionality in this scenario.
- Worst case, we could swap it to `ConcurrentDictionary<K, V>` which would still work out very well over boxing `Hashtable` in read-only context.
- ZRange is now a `readonly struct`, further decreasing memory footprint of the underlying collection.
- As `AdornerPresentationContext` is a derived class, I've sealed it.
| Method   | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] …
=> Replace boxing Hashtable in AdornerPresentationContext, reduce allocations

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Speller.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/SpellerError.cs
Decreases allocations while enumerating suggestions in `Speller`. Further improves performance, anywhere from `1.5` to `2.5`.
- Replace `ArrayList` with `List<string>`.
- Replace custom iteration with the base implementation.
- Raises base allocation of items from 1 to 4 as in most cases the number of suggestions more than 1.
- The return type could be an `IList<string>` or `IEnumerable<string>` but since it is internal I didn't bother.
| Original |  21.56 ns |   0.345 ns |    0.288 ns | 0.0072 |       1,415 B |         120 B |
| PR__EDIT |  14.20 ns |   0.292 ns |    0.300 ns | 0.0076 |       1,531 B | …
=> Reduce allocations while enumerating Speller suggestions and improve performance

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/MouseActionConverter.cs
Parsing optimization for `MouseAction` and its conversion from/to `string`. Allocation-free.
- Removes trimming on string, now trims on the span, resulting in no allocations.
- Removes conversion `ToUpperInvariant` and uses `StringComparison.OrdinalIgnoreCase` instead.
- This will allow for string interning between `Convert`/`ConvertFrom` and other literals, saving static memory.
- The JITTed codegen takes up less memory as we removed few things.
- Adds/completes code documentation for the whole class.
| Method   | source            | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size | Allocated |
|--------- |------------------ |----------:|-----------:|------------:|-------:|----------:|----------:|
| Original | MiddleDoubleClick | 19.632 ns |  0.2160 ns |   0.2020 ns | 0.0033 | …
=> Optimize conversion of MouseAction enum from/to string, remove allocations

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/GestureRecognizer/NativeRecognizer.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputProcessorProfiles.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/PixelFormat.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppSecurityManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Printing/PrintDlgExMarshaler.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/Marshalers.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/ImmComposition.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/InputScopeAttribute.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/PeoplePickerWrapper.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/PrintConfig/FallbackPTProvider.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Ink/Native.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/Condition.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/CommonXSendMessage.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/ContainerUtilities.cs
Replaces `Marshal.SizeOf` calls for primitive types with `sizeof` operator, saving some unnecessary overhead as the codegen results in a constant number generated in compile time.
I've also replaced the calls for `Marshal.SizeOf(typeof(Guid))` with `Unsafe.SizeOf<Guid>()` as the source counts on 16 bytes in all instances I could find anyways.
Finally, I've replaced some instances of weird ways to retrieve IntPtr size, using its property instead, which also results in a constant in runtime.
| Method   | Mean [ns]   | Error [ns] | StdDev [ns] | Code Size [B] | Allocated [B] |
|--------- |------------:|-----------:|------------:|--------------:|--------------:|
| Original | 117.3583 ns |  0.3339 ns |   0.2960 ns |         689 B |             - |
| PR__EDIT |   0.2285 ns |  0.0056 ns | …
=> Replace Marshal.SizeOf(...) calls for primitive types with sizeof(...)

src/Microsoft.DotNet.Wpf/src/Common/src/System/AppContextDefaultValues.cs
All WPF apps will spend now spend considerable time on startup evaluating whether they're running on NetFX or not by initializing `AppContextDefaultValues` in each assembly (`PresentationCore`/`PresentationFramework`/`WindowsBase`), querying `TargetFrameworkName` property via reflection on AppDomain/AppContext (depends which runtime, one forwards the other).
The only place where the check makes sense is in `PresentationBuildTasks` on net472, which can be easily opted-in by using a preprocessor macro, rest of the assemblies do not need it and can confidently init as `.NETCoreApp`, version doesn't matter.
- We can keep the current code for `PBT` on `net472` via preprocessor condition and omit it from core builds
- We do not need to retrieve `TargetFrameworkName` via reflection on any target …
=> Improve start-up time by not figuring out NetFX version for AppContext switches

src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
Replaces two uses of `string.Compare` in `ContentType` which is used for equality check with `string.Equals`.
| Method  | Mean [ns] | Error [ns] | StdDev [ns] | Code Size [B] | Allocated [B] |
|--------- |----------:|-----------:|------------:|--------------:|--------------:|
| Original | 36.525 ns |  0.7577 ns |   0.7781 ns |         446 B |             - |
| PR_EDIT  |  4.873 ns |  0.0175 ns |   0.0155 ns |         467 B |             - |
| Method   |  Mean [ns] | Error [ns] | StdDev [ns] | Code Size [B] | Allocated [B] |
|--------- |----------:|-----------:|------------:|--------------:|--------------:|
| Original |   4.627 ns |  0.0493 ns |   0.0437 ns |         446 B |             - |
| PR_EDIT  |  2.668 ns |  0.0138 ns |   0.0129 ns |         467 B |             - |
```csharp …
```
=> Use string.Equals over string.Compare in ContentType for improved performance

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/LengthConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThicknessConverter.cs
Simplifies code in `CanConvertTo`/`ConvertFrom`/`ConvertTo`, removes additional type casts by using `is` checks/pattern match. Commits should be easy to review.
Uses `DefaultInterpolatedStringHandler` instead of `StringBuilder` to handle conversion in `ToString` with a pre-allocated on-stack buffer (not using interpolated strings directly due to the `NaN`->`Auto` conversion which would box as Roslyn won't handle that one.
Also stackallocs 4 doubles instead of allocating an array in `FromString`, this uses unsafe quotation due to how the current code-gen with Span<double> looks like; additional perf improvement. I didn't include benchmark/tests in this one, they're together in the other PR for `LengthConverter` #9364.
```c#
ToString(new Thickness(3.33371, 2.25888, 6.6666, 8.444), …
```
=> Reduce ThicknessConverter allocs to minimum and improve conversion performance

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #  #9755 
Main PR  #9757 
Removes the invalid Fluent DataGridColumn styles, which can cause the application to crash when they are accessed explicitly.
Developers trying to iterate through the Fluent theme ResourceDictionary will not face crash in their applications. Will allow easier migration to use the Fluent styles.
Not really, as this is part of the new Fluent styles being introduced in .NET 9. However, anyone who tries to use the new styles may face the following issues.
Local build, reproduction app and WPF Gallery application.
Minimal, no one is using the above styles currently ( except for .NET 9 preview and rc releases )
=> [release/9.0] Removing invalid Fluent DataGridColumn styles

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/AppModel/SiteOfOriginPart.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Navigation/BaseUriHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppModelKnownContentFactory.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/AddressUtility.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SecurityHelper.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/BindUriHelper.cs
One of the few leftover remnants from CAS times is the `SecurityHelper.AreStringTypesEqual` that just calls case-insensitive `string.Equals`. There is no reason for this method as it has even lost the original comment throughout the removals and just makes newcomers wonder why is it there.
Few bytes less in size of all libraries.
No.
Local build.
None.
=> Replace SecurityHelper.AreStringTypesEqual with string.Equals for code quality

start-vs.cmd
Following along with WinForms existing helper for this purpose.
=> Add batch file for easier launching of VS

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/Utilities.cs
Since those code blocks are never entered (in #8681 @lindexi made `IsPresentationFrameworkVersionLessThan4` strictly `false` as it was always the result from reflection call anyways), we're just wasting memory by having the code around (and a tiny bit of perf).
Decreased framework memory usage, decreased file size; cleaner codebase for developers.
No.
Local build but the diff is super easy to review.
There isn't any.
=> Remove IsPresentationFrameworkVersionLessThan4 property and associated dead code

eng/restore-toolset.ps1
When building the repo for the first time, installing the WPF Git pre-commit hook will fail because it tries to Copy-Item the script into a directory that does not exist.
This change adds a check for the directory and if it does not exist, will create it.
They'll continue to not have the pre-commit hook installed.
Doesn't appear to be.
Just build off a fresh repo and notice the prehook gets installed.
None that I know of.
=> Make sure Git pre-commit hook directory exists before copying script

src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #9755
Removes invalid Fluent DataGridColumn styles
Would be good to fix this before .NET 9 releases so that existing codebases can have a smoother transition to new Windows 11 themes
No
- Used reproduction from #9755 to reference all resource dictionaries like in [Fluent.xaml](https://github.com/dotnet/wpf/blob/94751f56a45603960704642bdbc245a78e725644/src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml)
```xaml
<Application.Resources>
<ResourceDictionary>
<ResourceDictionary.MergedDictionaries>
...
<ResourceDictionary Source="pack://application:,,,/PresentationFramework.Fluent;component/Styles/ComboBox.xaml" />
<ResourceDictionary Source="pack://application:,,,/PresentationFramework.Fluent;component/Styles/ContextMenu.xaml" />
<ResourceDictionary …
```
=> Remove invalid Fluent DataGridColumn styles

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs
.NET 9 previews added new string.Trim/TrimStart/TrimEnd methods accepting (params) `ReadOnlySpan<char>`.  Those methods are being removed from .NET 9 GA (and .NET 10/main), so they should no longer be called by WPF.
WPF won't build.
No
It compiles.
Extremely low, mechanical change.
=> Avoid calling soon-to-be-removed string.Trim(ReadOnlySpan<char>) methods

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #  #9939 
In RC2, we modified some TemplateBinding's in Fluent styles, to allow developers to modify properties for default Fluent styles. While modifying ListView styles, the changes were made to make it similar to Aero2 style, but that caused a regression when using the ListView inside another container. Reverting that change to mitigate the issue.
Developers will get the correct ListView styles
Technically no, but it is a regression in .NET 9 RC2
Tested with sample repro application
Minimal. The new styles are not in use. Reverts a change made in RC2
=> Fixed ListView content alignment regression

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/Line.cs
Replaces `ArrayList` with `List<GlyphRun>` to function as a temporary array. Improves code quality by swapping to generic collection. Also makes `AddGlyphRunRecursive` function static as it does not use any instance members.
Sample benchmark showing difference between `ArrayList` and `List<T>` with reference type can be found f.e. in #9432.
Improved performance, getting rid of `ArrayList`.
No.
Local build.
None, changes are minimal.
=> Replace ArrayList with List<GlyphRun> in PtsHost for performance/code quality

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/ColorTransform.cs
Improves slightly performance and subsequent allocations when subtracting/multiplying or just generally working with `Color` using a custom profile / `ColorContext` by removing `Marshal` code/allocs and simply using `stackalloc` for the buffer, replacing some dead code (It is obvious `Translate` method has been rewritten previously) and removing the `try`/`finally` block used for unmanaged memory deallocation.
Redundant array inits to `0` have been removed in `ICM2Color` and also some heap-allocated arrays have been replaced with stack-allocated spans in the call chain.
Last two commits are not included in benchmarks but are pretty straightforward improvements.
| Method     | Mean     | Error     | StdDev    | Gen0   | Allocated |
|----------- …
=> Remove Marshalling code during Color Translation, reduce allocations

eng/Tools.props, eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
Unblocks https://github.com/dotnet/sdk/pull/43015
Alternative to https://github.com/dotnet/wpf/pull/10028
WPF uses vcxprojs which don't support downloading PackageReferences via NuGet. There's an experimental feature switch but enabling that didn't work (see https://github.com/dotnet/wpf/pull/10028). Therefore, vcxprojs are dependent on the pre-downloaded "packs" folder content in the SDK layout.
Today, wpf projects target `net9.0` with a 9.0 SDK but when building the repo inside the VMR, a 10.0.100-alpha SDK is used. That SDK only contains 10.0.0-alpha targeting packs, runtime packs and apphosts. But as wpf targets net9.0 it needs the 9.0.0 assets. The solution to that is using the "live" runtime assets to not depend on the SDK.
This repo already uses live assets from runtime but that …
=> Keep apphostpack version in sync with targeting and runtime pack version

src/Microsoft.DotNet.Wpf/src/Common/src/System/AppContextDefaultValues.cs, src/Microsoft.DotNet.Wpf/src/Common/src/System/LocalAppContext.cs, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/BuildTasksAppContextSwitches.cs, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/System/AppContextDefaultValues.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/AppContextDefaultValues.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/FrameworkAppContextSwitches.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/AppContextDefaultValues.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/BaseAppContextSwitches.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/AppContextDefaultValues.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/AccessibilitySwitches.cs
This is a follow-up to #9711, cleaning up the dead code from assemblies that are compiled for .NET Core only.
The PBT one has been kept for obvious reasons.
The effective process is removing the switch statement, values for `NetFX` and copying over contents of `InitializeNetFxSwitchDefaultsForNetCoreRuntime` directly into the partial method.
I have also removed the warning supressions where they were not necessary.
Smaller size of assemblies, 0.0001 ns faster start up time, cleaner codebase for developers.
No.
Local build, app startup.
Low, this is just a cleanup after previous PR.
=> Remove AppContextDefaultValues/AccessibilitySwitches values from NetFX (dead code)

src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/RightsManagementEncryptionTransform.cs
Optimizes some low-hanging fruit in this mostly unused part of WPF to remove some unnecessary allocations.
- `CompareOrdinal` replaced with the most obvious `StartsWith`.
- The Base32 wannabe can be now encoded into a stackallocated buffer if its big enough.
- Parsing authentication type now does it directly off the sliced input string.
- Removed the `LicenseStreamNamePrefixLength`, 4 bytes saved sounds good.
Since I like numbers, here's a benchmark of `MakeUseLicenseStreamName`.
| Method    |Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|---------- |-----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original  |   565.6 ns |    1.71 ns |     1.43 ns | 0.0172 |         260 B |         288 B |
| PR__EDIT2 |  541.0 ns | …
=> Optimize some methods in RightsManagementEncryptionTransform, reduce allocs

src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/PrintSystemPathResolver.cpp
Fixes the above mentioned build error in `PrintSystemPathResolver.cpp`
=> Fix: Missing 'L' encoding-prefix for character literal

eng/Versions.props, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/ArrayTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/BinaryFormat/BinaryFormatWriterTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/WindowsBase.Tests/System/Windows/SplashScreenTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/WindowsBase.Tests/WindowsBase.Tests.csproj
`System.Private.Windows.Core.TestUtilities` is a test utilities package that comes from WinForms that is meant to be shared with WPF to take advantage of test utilities that we have in WinForms such as `TestAccessors`. This change takes the test utilities package in `WindowsBase.Tests` (bumping xunit version is needed) and shows how TestAccessors can be used to validate private fields within a class.
=> Start using System.Private.Windows.Core.TestUtilities

Microsoft.Dotnet.Wpf.sln, src/Microsoft.DotNet.Wpf/src/PresentationFramework/LibraryAssemblyInfo.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj, src/Microsoft.DotNet.Wpf/tests/Directory.Build.props, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/GlobalUsings.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/PresentationFramework.Fluent.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/System/Windows/Controls/ButtonTests.cs
Most of the projects include references to ref and cycle breaker projects. This breaks tests as they will pick the wrong assemblies.
Create a stub PresentationFramework.Fluent.Tests project to validate.
=> Don't enable transitive references in tests

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Provides a workaround for: https://github.com/dotnet/wpf/issues/10054
The changes here add a `DefaultTabControlStyle` and `DefaultTabItemStyle` in Fluent styles.
Provides a way to use `BasedOn` when overriding tab control styles in Fluent theme. This is also a part of our initiative to have consistent theme style, and resource key value.
None
Sample Application Testing
Testing the Gallery Application
Low, simply adding a resource key to the existing style.
=> Fluent: Adding Resource Key to TabItem and TabControl styles

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes # 
https://github.com/microsoft/WPF-Samples/issues/673
#10054 , #10043 
Main PR 
#10094 , #10129 , #10116 , #10132
In this PR, I have backported the fixes from other Fluent style fixing PRs which need to go in .NET 9. It includes the following :
- Fixing HighContrast theme in Fluent
- Matching the list of color resource keys in Light, Dark and HC files for Fluent
- Fixes UI for RadioButton in disabled state
- Adds resource keys for TabControl and TabItem
Developers will be able to use HighContrast mode, use color resource keys without issues and will receive correct UI for RadioButton. For developers who want to customize TabControl and TabItem deafult styles will be able to now do it without redefining the complete style.
Yes, first three of the above are regressions.
Local testing …
=> [.NET 9 ] Fluent Style Fixes : HC.xaml loading, disabled radiobutton UI etc.

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs, src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Window.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #  #10096 
In Windows 10, when using Fluent theme the background of the window appears black. This PR fixes the issue by including a DataTrigger that checks the OS version and in case of Windows 10, it sets the background accordingly as Windows 10 doesn't support the backdrop operations through DWM.
Secondly, when Application is Light / Dark ( not System ) the Window's with ThemeMode set to system didn't react to system theme changes. This was because, when application is in light or dark, the state of fluent theme state for application didn't change and we returned it from the function without checking the window's thememode. We enabled that behavior in this PR.
Developers can use Fluent theme in Windows 10 without using the backdrop switch. Enables the correct behavior for Window …
=> [release/9.0] Fixes window backdrop and background in Windows 10 and window theme interactions with system changes

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
Fixes #  #10043 
Main PR 
While fixing TemplateBinding for different controls, some resource keys in HC.xaml got duplicated, which when loaded causes the above issue.
Developers will be able to use Fluent in HighContrast mode.
Yes, as compared to .NET 9 Preview 4 release.
Ad-hoc testing.
Minimal.
=> Fixing HighContrast theme in Fluent

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
Setting the Application ThemeMode to Light/Dark and changing the system's theme would not reflect on the window when the window is set to System ThemeMode. 
Yes
Local build pass. Tested with Sample applications
=> Fixing window theme changes when system's theme is changed

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
As of now there is a mismatch between the number of keys in Fluent color ResourceDictionary files ( Light.xaml, Dark.xaml and HC.xaml ). If someone uses one of those resources as a StaticResource in their applications, the applications will crash on theme change.
Prevents developers from running into possible crash scenarios.
No
Local testing, Automated Unit tests
Minimal. Resources have been added rather than removed so if anyone is already using the resource, they won't see any crash.
=> Matching the list of color resource keys in Light, Dark and HC files for Fluent

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes https://github.com/microsoft/WPF-Samples/issues/673
Fixes the background color when the radio buttons are disabled
Yes
Local build pass. Tested with Sample applications.
Low
=> Fixing Disabled UI state in radiobutton

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Controls/AnimationFactorToValueConverter.cs, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes https://github.com/microsoft/WPF-Samples/issues/672
While changing the ResourceDictionaries, during the invalidation, Tag property was being set to null ( default value ) which was causing an error with the animation. Replaced it with a dummy border and instead of using Tag, now I use Width property of the border which is a double and it's default value is not null. This avoids the ArgumentNullException when the expander is expanded and the Theme is changed.
Not taking this fix would cause a ArgumentNullException when the Expander is expanded, and the Theme is changed
No
Sample App Testing
Low
=> Modified Expander animation mechanism in Fluent to avoid Argument Null Exception

src/Microsoft.DotNet.Wpf/src/.editorconfig, src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs, src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs, src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/XmlCompatibilityReader.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/GlobalSuppressions.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/AttachablePropertyServices.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/XamlContext.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/XamlParserContext.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/IAttachedPropertyStore.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/Reflector.cs
This work is a part of our initiative to set code-style guidelines, align WPF and WinForms, and ensure PR standards with respect to styles. This in turn will help us in better maintainability and readability of the repo overall. The changes follow up from the PR #10080 and references to the issue #10017.
The current changes addresses the following Errors/Warnings in the src folder of WPF:
- **SA1408:** Conditional expressions should declare precedence
- **SA1404:** Code analysis suppression should have justification
- **SA1131:** Constant values should appear on the right-hand side of comparisons
A good way to go about reviewing this is to go commit by commit which pans over individual errors/warnings, and hence easing out the overall understanding.
_None_
_None_
The …
=> [StyleCleanUp] Addressing SA warnings Part 1

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/WindowsRuntime/Windows/UI/ViewManagement/InputPane.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputElement.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenContexts.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/WispLogic.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndKeyboardInputProvider.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndPanningFeedback.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndPointerInputProvider.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/SecurityMgrSite.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Printing/Win32PrintDialog.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/DocumentViewerHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/CommonDialog.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/HwndHostAutomationPeer.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/WindowAutomationPeer.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/WindowInteropHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/MessageBox.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/PointUtil.cs
Removes CriticalHandle properties, these properties are overloads that are not useful since the deprecation of CAS. It complicates the code with no benefit.
Tiny performance improvement (Probably not measurable) and slightly smaller assemblies.
No.
Local testing.
Low.
=> Remove CriticalHandle properties

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/CultureMapper.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Markup/XmlLanguage.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SafeSecurityHelper.cs
Removes the `SafeSecurityHelper.GetCultureInfoByIetfLanguageTag` method and replaces it directly with `CultureInfo.GetCultureInfoByIetfLanguageTag`.
One of the few leftover remnants from CAS times, there is no reason for this proxy method anymore.
Few bytes less in size of PresentationCore.
No.
Local build.
None.
=> Remove SafeSecurityHelper.GetCultureInfoByIetfLanguageTag proxy for code quality

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FamilyCollection.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSource.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSourceCollection.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphTypeface.cs
Removes `skipDemand` from `FontSource` as it is not used for anything anymore, it was used in `NetFx` for figuring out whether to demand permissions.
Also removes `isWindowsFonts` from `FontSourceCollection`, because this is already a dead code in latest `NetFx` as the internal constructor from `FamilyCollection` that allowed `true` has been removed at the same time it stopped deriving from `IFontCacheElement` and it has been replaced by `FamilyCollection.FromWindowsFonts` which uses DirectWrite factory, so it never reaches `FontSourceCollection` on this code path. It is also way faster if you would run it.
Smaller code size of `PresentationCore`, cleaner code size for developers, faster JITTing, decreased allocs.
No.
Local build, app run, work with custom font sources.
Low, as it is a …
=> Remove dead code in FontSourceCollection/FontSource (+ hollow CAS remnants)

src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs
Code clean
None.
None.
None.
None. I do not change any behavior
=> Reduce magic numbers in FrugalList.cs

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlTextReader.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MeScanner.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlAttribute.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/DynamicMethodRuntime.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/PartialTrustTolerantRuntime.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/CollectionReflector.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/Reflector.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/TypeReflector.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XmlNamespace.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMember.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
Contributes to dotnet/wpf#10018
I replaced comments specifying an argument name with named arguments, which were introduced in C# 7. This improves readability and maintainability.
**Note: The compiled IL is identical.**
None.
No.
Local build + validated IL.
Low to none.
=> [Cleanup] Use named arguments in System.Xaml

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/KeyConverter.cs
Parsing optimization for `Key` and its conversion from/to string. Conversion from is now alloc-free, conversion to is either untouched or free.
- `ConvertFrom` is now allocation free, optimizing performance from x4 for normal keys to x20 for F1-F12 keys.
- The code-size of the method has increased but I think it is an acceptable compromise.
- `ConvertTo` is pretty much unchanged however F10-F12 were added to switch as those are interned.
- Adds/completes code documentation for the whole class.
| Method      | source | Mean [ns]  | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|------------ |------- |-----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original | \x20F5\x20 | 170.052 ns |  1.7088 ns |   1.5984 ns | 0.0048 |         291 B …
=> Optimize conversion of Key enum from/to string, reduce allocations

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/CollectionView.cs
Replaces `ArrayList` used for tracking changes with `List<NotifyCollectionChangedEventArgs>`. Instead of using `SyncRoot` (object) of the `ArrayList` we will just use the new `Lock` for clarity and slightly improved performance.
Also modifies `ProcessChangeLog` / `DeferProcessing` from `ICollection` to `List<NotifyCollectionChangedEventArgs>` for improved performance.
- The `ProcessChangeLog` null-check was there because of the `as` casting pattern, if the `args` inserted into the `_changeLog` would ever be null, it would blow before it was even added in `PostChange` (the only proc adding into `_changeLog`).
- `DeferProcessing` doesn't need the null-check branch because the only time `_changeLog` is written into is always covered using `_changeLogLock`, so it cannot be NULL, and the ref …
=> Replace ArrayList/ICollection used for changelog in CollectionView with generic List

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/CollectionViewGroupInternal.cs
Replaces `Hashtable` that serves as a group name map with `Dictionary<object, WeakReference>`, improving performance and decreasing allocations. Also removes now useless enumerations on removals, making the whole process more efficient.
- No thread-safety concerns here, it is expected for all access to be synchronized by the classes using the view.
- `Dictionary<K, V>`'s enumeration allows for removals, so the complexity goes from O(2n) to O(n).
| Method   | Mean [ns]  | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|--------- |-----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original | 1,180.2 ns |   20.00 ns |    23.81 ns | 0.1068 |       7,128 B |        1792 B |
| PR__EDIT |   592.5 ns |   11.76 ns |    13.54 ns | 0.0334 | …
=> Replace Hashtable with Dictionary<K, V> in CollectionViewGroupInternal

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemContainerGenerator.cs
Replaces `ArrayList` with `List<EmptyGroupItem>` to hold empty group items when needed. Improves code quality by swapping to generic collection and decreases memory footprint.
Sample benchmark showing difference between `ArrayList` and `List<EmptyGroupItem>`.
| Method   | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Gen1   | Allocated [B] |
|--------- |----------:|-----------:|------------:|-------:|--------------:|-------:|--------------:|
| Original | 103.59 ns |   2.013 ns |    3.578 ns | 0.0483 |         740 B | 0.0001 |         808 B |
| PR__EDIT |  95.02 ns |   1.907 ns |    2.480 ns | 0.0483 |         342 B | 0.0001 |         808 B |
```c#
[Benchmark]
public void Original()
{
ArrayList? _alEmptyGroupItems = null;
for …
```
=> Replace ArrayList in ItemContainerGenerator with List<EmptyGroupItem>

src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackUriHelper.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/SparseMemoryStream.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlDigitalSignatureProcessor.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/ComponentModel/PropertyChangedEventManager.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/CompoundFile/DataSpaceManager.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/EncryptedPackage.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/DependencyObject.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/DependencyProperty.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Freezable.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Markup/Primitives/MarkupObject.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Media/Matrix.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/UncommonField.cs
Contributes to dotnet/wpf#10018
I replaced comments specifying an argument name with named arguments, which were introduced in C# 7. This improves readability and maintainability.
My changes are in 2 commits the first commit is automated changes using regexes and the second commit is manual changes where the comment is outdated or formatted differently than the parameter name.
**Note: The compiled IL is identical.**
None.
No.
Local build + validated IL.
Low to none.
=> [Cleanup] Use named arguments in WindowsBase

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/ModifierKeysConverter.cs
Fixes #7502
Parsing optimization for `ModifierKeys` and its conversion from/to string. Conversion **from** is now alloc-free, conversion to is either free or reduced by a big margin (see benchmarks).
- `ConvertFrom` is now fully flying on `ReadOnlySpan<char>` instead of multiple substrings and trims on string instances.
- `ConvertTo` is now within 2 procs, fast-path and slow-path. The only allocated string instance is with multiple modifiers.
- Strings in `ConvertTo` will now be interned with the rest since we use `StringComparison.OrdinalIgnoreCase`.
- `ModifierKeysFlag` static field is now a compile-time constant, saving memory and providing speed-up.
- The JITTed codegen takes up less memory as we removed few things.
- Adds/completes code documentation for the whole class.
| Method   | …
=> Optimize conversion of ModifierKeys enum from/to string, reduce allocations

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Globalization/BamlResourceContent.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Globalization/BamlTreeUpdater.cs
Optimizes parsing BAML string resource content (e.g. localized resources) by replacing the slowest `Regex` use available (`MatchEvaluator` delegate) with a custom unescape function tailored for the specific use. Also further removes array allocs by using `ReadOnlySpan<BamlStringToken>` instead.
- Firstly a short-circuit check is done to find out whether any escape tokens are present (via `SearchValues<string>`)
If not, we return a new string instance / or if the string overload was used, we return the original one.
- In case any escape token was found, we allocate a `StringBuilder` instance and run through the supplied buffer.
- We could use slices like `Slice(1, 4)`; `Slice(1, 3)` etc. and do the compares without `&` and `;` but I've chosen readability.
- Yes, `SearchValues<string>` uses …
=> Optimize unescaping/parsing performance of BamlResourceContent/BamlStringToken

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
The theme generator for `Fluent` themes partially relies on common brushes, colors, and keys written in theme files, i.e. `Light.xaml`, `Dark.xaml` and `HC.xaml`. The current implementation of `HC.xaml` contains a duplication of `SystemColorWindowColor` key.
The resource dictionary loaded at runtime for High Contrast theme is Fluent.HC.xaml, which right now is correct but if/when we generate the same, it will result in duplication of that key and hence runtime crashing of applications on high contrast theme.
Fixes any future regression and crash on high contrast theme (Fluent)
Low, removal of a xaml key.
Does not violate API contract as the key is already present.
=> Fix Potential Crash in Fluent High Contrast

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/DurationConverter.Tests.cs
Adds test coverage for `DurationConverter`. Both the original and my PR #9768 have been tested against this.
Improved test coverage on public surface.
No.
Local build.
None.
=> Add test coverage for public API surface of DurationConverter

src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/FloatUtil.cs
Converts three static variables into compile-time constants as there's no reason they shall be static variables in the first place. This will allow us to save a few precious bytes of memory. `IsOne`/`IsZero` are unused right now but I'll keep them in.
Decreased static allocations by a few bytes and tiny bit of perf!
No.
Local build.
None.
_Besides if someone was using reflection to change them — miloush doesn't like when I say "None", haha._
=> Convert static float variables in FloatUtil into compile-time constants

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
Removes redundant `byte[]` allocation caused by static `Guid` conversion to `byte[]` and initializing from such.
This way it is simply `vmovups` copy -> `lea` to push stack address as expected.
| Method   | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Allocated [B] |
|--------- |----------:|-----------:|------------:|-------:|--------------:|
| Original | 0.8887 ns |  0.0198 ns |   0.0175 ns |      - |             - |
| PR__Edit | 4.6857 ns |  0.1146 ns |   0.0957 ns | 0.0024 |          40 B |
Also removes some obsolete code security notes from the classes that were leftover from previous PRs (second commit).
Improved performance, decreased allocation.
No.
Local build; functionality verified.
None.
=> Remove redundant Guid-init from array/alloc in NotificationWindowHelper

src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework.cs
The reference files in cycle-breaker projects need to be updated whenever any affecting API ( APIs in the project referred in cycle-breakers like PresentationFramework, PresentationUI )  is modified / added. However, the recently modified APIs ( ThemeMode and CommonItemDialog ) have not yet been added. In this PR, I have introduced those changes in the cycle-breakers reference files.
Maintains parity between the reference files. There is no real impact for end users as these changes are required for building projects in WPF.
N/A
N/A
If later, we end up using these types in the projects that refer PresentationFramework , then there is a chance of WPF build failures.
=> Add missing references in cycle-breakers

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Ink/LassoHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Ink/LassoSelectionBehavior.cs
Replaces boxing `ArrayList` with generic `List<Point>` with preallocated size of 4 as that's always gonna be filled in the least, and removes array allocation through usage of `Span<Point>` as a new return type. 
In `LassoHelper` the function to match points finally runs an efficient `foreach` (as it was iterating over an array before).
Note that we could return `ROS<Point>` instead and iterate via value but this solution offers an additional performance without really introducing any real risks.
In total, this will run about 3x faster along with less than 50% of originally introduced allocations.
Improved performance, decreased allocations.
None.
Build and benchmark only but there are no functional changes.
None.
=> Replace boxing ArrayList in LassoSelectionBehavior, remove unnecessary array alloc

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DateTimeValueSerializer.cs
Replaces `StringBuilder` with simple on-stack build as we easily know the maximum length of the format string and don't need to therefore have two heap allocations when we can just have one.
Also replaces the awful virtual call to `GetFormat` for `DateTimeFormatInfo` on `InvariantCulture` and a sad nullability annotation with the very simple, static property of `DateTimeFormatInfo.InvariantInfo`.
| Method   | value               | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|--------- |-------------------- |----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original | 10/10/1999 00:01:07 | 110.30 ns |   1.214 ns |    1.013 ns | 0.0210 |       3,211 B |         352 B |
| PR__EDIT | 10/10/1999 00:01:07 |  70.24 ns |   0.380 …
=> Replace StringBuilder in DateTimeValueSerializer with format constants

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CollectionViewGroup.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ContentControl.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/GroupItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/HeaderedContentControl.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Subset of the PR, #9171 
Following up on the description in #9171, the changes here aim to add missing styles of controls that does not need any differential styles in Fluent design. 
_None_
Low
=> Add Fluent Missing Styles

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/PresentationSource.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Commands/CommandHelpers.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/DataGridDetailsPresenter.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VisualStates.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemParameters.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/VisualStateGroup.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs, src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/Documents/Application/Trace.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Input.Manipulations/System/Windows/Input/Manipulations/Exceptions.cs
Continues the journey that started in #9468 and converts some internal call-chains from `params T[]` to `params ReadOnlySpan<T>` where I felt it is without any side-effects, largely decreasing allocations in other scenarios besides just tracing and improving both performance and allocations since we do not need to create a new heap array of `T[]` everytime.
| Original |  7.547 ns |  0.1129 ns |   0.1056 ns | 0.0029 |         143 B |          48 B |
| PR__EDIT |  1.532 ns |  0.0096 ns |   0.0085 ns |      - |         120 B |             - |
```c#
private static …
```
=> Replace occurrences of params T[] with params ReadOnlySpan<T> where possible

src/Microsoft.DotNet.Wpf/src/System.Windows.Primitives/System.Windows.Primitives.csproj
Adding checksum algorithm to system.windows.primitives.
According to Binskim guidelines
> Compilers can generate and store checksums of source files in order to provide linkage between binaries, their PDBs, and associated source code. This information is typically used to resolve source file when debugging but it can also be used to verify that a specific body of source code is, in fact, the code that was used to produce a specific set of binaries and PDBs. This validation is helpful in verifying supply chain integrity. Due to this security focus, it is important that the hashing algorithm used to produce checksums is secure.
=> Enable Secure Source Code Hashing

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/CachedBitmap.cs
Removes redundant type checks second-time around when constructing `CachedBitmap` (this constructor is used by `BitmapSource.Create()`. There's minimal performance benefit, the main goal here is code simplification, that has been made possible with the introduction of `GetArrayDataReference` few releases ago.
Method has been tested with all array types for correct functionality when constructing in-memory Bitmap.
Smaller code-size of PresentationCore.
None.
Build, constructing Bitmap from memory source.
Low.
=> Simplify constructor in CachedBitmap by removing duplicate type checks

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ContextMenu.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #9989 
Adds ScrollViewer to ContextMenu to support vertical scrolling
NA
None
=> Adding ScrollViewer to ContextMenu

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Input/Command/KeyGestureConverter.Tests.cs
Adds test coverage for `KeyGestureConverter`. Sending these ahead of time for PR related to `KeyGestureConverter`.
No.
Local build.
None.
=> Add test coverage for public API surface of KeyGestureConverter

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Input/Command/MouseGestureConverter.Tests.cs
Adds test coverage for `MouseGestureConverter`. Sending these ahead of time for PR related to `MouseGestureConverter`.
No.
Local build.
None.
=> Add test coverage for public API surface of MouseGestureConverter

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/Animation/RepeatBehavior.Tests.cs
Adds test coverage for `RepeatBehavior`. Both the original and my PR #9776 have been tested against this.
Improved test coverage on public surface.
No.
Local build.
None.
=> Add test coverage for public API surface of RepeatBehavior

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Animation/RepeatBehavior.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/ref/PresentationCore.cs
Since `RepeatBehavior` is immutable by design, we should adjust it to `readonly struct`. This will also prevent defensive copies, even though the struct is small, it will already matter a bit here. It will also improve code quality. **This is not a breaking change**.
- A private constructor for the static `Forever` property creation will be added.
- `new TimeSpan(0)` is exactly what `TimeSpan.Zero` does but it is cleaner imho.
- Some code cleanup included.
Possibly a bit of perf and a clear directive that `RepeatBehavior` and all its methods are not adjusting the state of the `struct`.
No.
Local build, base testing, type creation, etc.
I do not asses any, since the struct is immutable and this is not a breaking change. It is a change to a public type but such changes have been done …
=> Redefine RepeatBehavior as readonly struct to prevent defensive copies

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/SelectionWordBreaker.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextFindEngine.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/SafeNativeMethodsOther.cs, src/Microsoft.DotNet.Wpf/tests/IntegrationTests/Common/DRT/TestServices/MS/Win32/SafeNativeMethodsOther.cs
Removes unnecessary allocations of temporary heap arrays when calling `GetStringTypeEx`, using stack-allocated space instead.
Also removes some unnecessary string copies in `TextFindEngine.Find(...)` method.
| Method   | findPattern          | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|--------- |--------------------- |----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original |  this(...)e it  [92] |  58.53 ns |   1.161 ns |    1.193 ns | 0.0200 |         461 B |         336 B |
| PR__EDIT |  this(...)e it  [92] |  28.89 ns |   0.213 ns |    0.199 ns |      - |         350 B |             - |
```csharp
[Benchmark]
[Arguments(" this is a very long string, and yet its gonna be …
```
=> Decrease allocations in TextFindEngine/SelectionWordBreaker, improve performance

eng/WpfArcadeSdk/tools/FolderPaths.props, src/Microsoft.DotNet.Wpf/tests/UnitTests/Directory.Build.targets
Fixes dotnet/wpf#10250
This fixes the flaky tests which was caused by the native dependencies sometime not being built before the test projects. This PR adds an explicit reference to the projects of the native dependencies to make sure that it's built in the right order and also adds some protection by including the files explictly instead of using file globbing to make the build fail with an error which contain the path of the file missing instead of the tests failing to start, which improves the build logs in case of error.
None, tests only.
No.
Did a bunch of local builds and it fails on 1 out of 5 build before this PR and I did ~10 local builds with this PR and it didn't failed. I also validated the build order in the build log.
Low to none, tests only.
/cc @JeremyKuhne since you …
=> Fix flaky tests

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSource.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Resources/ResourceManagerWrapper.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSourceParameters.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Navigation/BaseUriHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/documents/DocumentsTrace.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006Reader.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006ReaderInternal.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Primitives/MarkupWriter.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/ReflectionUtils.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SafeSecurityHelper.cs, src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/XmlNsInfo.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/SplashScreen.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
Optimizes retrieval of simple name from `Assembly.FullName` and removes all the weird ways used throughout to get it, this optimizes both startup and runtime performance.
- In `Baml2006Reader` and `XamlSchemaContext` the original method did not properly parse assembly names with properly escaped commas, a weird edge-case but still a valid one. This was there due to CAS anyways.
- Since we're in all cases as far as I know working with `RuntimeAssembly`, using `assembly.GetName().Name` is always the slowest, followed by `new AssemblyName(assembly.FullName).Name`.
- The original intention was to merely unify this behaviour, however given how slow it is and since there was already custom parsing done in Xaml/Baml, I've decided to roll our own.
- The two methods were moved from …
=> Optimize retrieval of simple name from Assembly.FullName, fix up faulty methods

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/MouseActionConverter.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Input/MouseActionConverter.Tests.cs
Adds test coverage for `MouseActionConverter`. I've also fixed an unintentional behavioral change I've introduced with #9676, which would mean it wouldn't throw `InvalidEnumArgumentException` due to passing wrong value type to the exception.
- As I've outlined previously, there are basically two (in my opinion) bugs in the class
- `CanConvertTo` throws `InvalidCastException` due to an unboxing cast when you pass an `int`
- The same thing happens in `ConvertTo` when you pass an `int` within range
Improved test coverage on public surface.
Fixing my own oversight at the same time.
Local build.
Low.
=> Add test coverage for public API surface of MouseActionConverter

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/TextDecorationCollectionConverter.Tests.cs
Adds test coverage for `TextDecorationCollectionConverter`. Both the original and my PR #9778 have been tested against this.
- Again, this class is rather inconsistent with others.
- Static `ConvertFromString` will return `null` on `null` but instance method will throw with `NotSupportedException`
- While `ConvertTo` claims it only supports `InstanceDescriptor` as `destinationType`, it calls into base which will gladly accept `string` and based on the value type it will either return `string.Empty` (if value was null), or it returns the type name using `ToString`.
- I did not even include those edge cases because they should be rather fixed imho for more consistent behavior.
Improved test coverage on public surface.
No.
Local build.
Low.
=> Add test coverage for public API surface of TextDecorationCollectionConverter

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/ParserExtension.cs
Fixes dotnet/wpf#2543
Fixes dotnet/wpf#2926
Fixes dotnet/wpf#4457
Fixes dotnet/wpf#4538
Fixes dotnet/wpf#6198
There were many bug reports of different type that were all caused by the same bug. Xaml compilation generating an empty InitializeComponent method when App contains a single item.
Some context:
When generating App.InitializeComponent for a Xaml where there is only the StartupUri property, it will skip loading Baml in App.InitializeComponent and only set the StartupUri property in the generated code for performance reasons. There is currently a bug when detecting if the StartupUri property is the only property that would be loaded from the Baml.
See https://github.com/dotnet/wpf/pull/8853#discussion_r1507014370 for an explanation of the changes in this PR.
Should fix issues linked …
=> Fix Xaml compilation generating an empty InitializeComponent method when App contains a single item

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/FixedTextSelectionProcessor.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/Anchoring/TextSelectionProcessor.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Annotations/Annotation.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeDictionaryExtension.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs
Picks off most places where `string.Split` is used just for parts count or where additional operations are performed on the split strings so it makes sense to work with `ReadOnlySpan<char>`/`SpanSplitEnumerator<char>` instead.
| Method   | updatedFilter        | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|--------- |--------------------- |----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original | Image(...))\|\*.\* [68] |  49.09 ns |   0.676 ns |    0.600 ns | 0.0172 |         672 B |         288 B |
| PR__EDIT | Image(...))\|\*.\* [68] |  17.23 ns |   0.075 ns |    0.066 ns |      - |         412 B |             - |
```csharp
[Benchmark]
[Arguments("Image …
```
=> Use MemoryExtensions.Split over string.Split to decrease allocations/improve perf

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventPrivateKey.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/GlobalEventManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/RoutedEvent.cs
Simplifies the global index generation for each routed event and the key, instead of using an `ArrayList` and the unused `_globalIndexToEventMap` covered in a lock, we shall be sufficient with memory barrier and a global index counter.
Removes `EventFromGlobalIndex` method that is a dead code since the dead calling method was removed in #4636 by @lindexi but I guess he forgot to remove this one as well.
Improved start-up performance/event registration, decreased memory usage without this static list.
No.
Local build, sample app run, event registration.
Low, removes unused code and improves the mechanism.
=> Simplify GlobalEventManager indexing, remove dead code and unnecessarry array

src/Microsoft.DotNet.Wpf/tests/UnitTests/Directory.Build.props, src/Microsoft.DotNet.Wpf/tests/UnitTests/Shared/ModuleInitializer.cs
This is a workaround for dotnet/runtime#111825
Fixes errors in unit tests when trying to load wpfgfx_cor3.dll which depends on D3DCompiler_47_cor3.dll which can't be found at runtime which seems to be caused by a bug in the runtime when using `DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.System32` as the search path. 
This search path is the default search path used by all projects in this repo and it's configured here:
https://github.com/dotnet/wpf/blob/81019fc2492bfc15620ef14053f4f3f22eeeac6c/eng/WpfArcadeSdk/tools/ExtendedAssemblyInfo.props#L16-L20
We can't just set `IncludeDllSafeSearchPathAttribute` to false in the test projects since the attribute is used to configure the search path used by default for each assembly. We would need to set it to false for all …
=> Fix unit tests native dependencies

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapMetadata.cs
Replaces backing `ArrayList` in `BitmapMetadataBlockWriter` and `BitmapMetadataBlockWriterEnumerator`.
Also fixes a bug in `RemoveWriterByIndex` function, which would previously not remove the writer.
Sample benchmark showing difference between `ArrayList` and `List<T>` with reference type can be found f.e. in #9432.
Improved performance, decreased allocations, a bug fix.
No.
Local build, work with `BitmapMetadata`.
Low but note that things might actually work properly and a bit faster now.
=> Fix RemoveWriterByIndex bug, replace ArrayList in BitmapMetadataBlockWriter

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Duration.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DurationConverter.cs
Parsing optimization for `Duration` and its conversion from/to `string`. Conversion from is now alloc-free (besides the non-removable ones), conversion to is massively sped up by modification of `ToString` in `Duration`.
- Besides the obvious improvements, adds/completes code documentation for the whole class.
- The `TimeSpanConverter` from `ComponentModel` does nothing useful but `Parse`/`ToString` on `TimeSpan`/`string` instance; the exceptions are not localized. Using it means we have to use the string instance as ref structs cannot be boxed (`ReadOnlySpan<T>`), and that would result in additional trim for example.
| Method   | source              | Mean [ns]  | Error [ns] | StdDev [ns] | Code Size | Gen0   | Allocated |
|--------- |-------------------- …
=> Optimize parsing and conversion in DurationConverter, reduce allocations

src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.cs.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.de.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.es.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.fr.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.it.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ja.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ko.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.pl.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ru.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.tr.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.zh-Hans.xlf, src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.zh-Hant.xlf
Fixes #10273 
Fixed the translation state for ScrollBar_ContextMenu_Top, ScrollBar_ContextMenu_PageDown and ScrollBar_ContextMenu_PageUp resource
Context menu for users using ScrollBar will be correctly translated for different languages.
N/A
Locally Tested 
Low
=> Fix in .NET 8 for Inconsistent UI Issue due to incorrect localized string resources

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/AccessibilitySwitches.cs
All WPF apps will spend now spend considerable time on startup verifying legacy accessibility switches setting. First it uses reflection to gather `UseNetFx47CompatibleAccessibilityFeatures` / `UseNetFx471CompatibleAccessibilityFeatures` / `UseNetFx472CompatibleAccessibilityFeatures`, then it orders and creates an array to go through its values, which is just a major overkill and this early it results in a big JITTing overhead besides other things.
As I personally don't think those properties are gonna grow in the direction where we would need such an over-engineered solution, I've decided to simplify it. This will improve the start-up time of all WPF apps.
Improved start-up time, decreased start-up allocations.
No.
Local build.
Low, this removes an over-engineered solution for a simple …
=> Improve start-up time by not using LINQ-Reflection combo for AccessibilityFeatures

src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/ClickablePoint.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/ProxySimple.cs
This should be the last boxing `ArrayList` that's still left in `UIAutomationClientSideProviders` when #9388 would be merged.
- Adds `System.Collections` reference to `UIAutomationClientSideProviders` to allow for generic collections in the first place.
- Removes two boxing `ArrayList` instances, both times for `CPRect` structure in `ClickablePoint` and `ProxySimple` class.
- Makes the static fields `readonly` and moves the other static field init into the `static constructor` for readability.
- Adjusts the `CPRect` bool methods as `readonly` since they do not modify struct state.
- Renames the "al*" params as "list*" to reflect reality this ain't an `ArrayList`.
- Adjusts internal comments from "Program" to "Progman".
Improved performance, decreased allocations.
No.
Local build.
Low.
=> Replace boxing ArrayLists in UIAutomationClientSideProviders (ClickablePoint)

src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/ProxyHwnd.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WinEventTracker.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsButton.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsComboBox.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsEditBox.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsFormsLinkLabel.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsHyperlink.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsListBox.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsListView.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsMenu.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsTab.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsTooltip.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsTreeView.cs
This should be one of the last boxing `ArrayList` that are still left.
- Adds `System.Collections` reference to `UIAutomationClientSideProviders` to allow for generic collections in the first place.
- Removes two boxing `ArrayList` instances, for `EvtIdProperty` (main method in `ProxyHwnd.PropertyToWinEvent`) structs and `EventCreateParams` (struct was made internal) — main method in `(WinEventTracker.WinEventProc`).
- Afterwards removes out params for the functions that contain Length of the array as it is not needed (`Length` is contained within `ReadOnlySpan<T>`).
- Modifiers the call chains to work with `ReadOnlySpan<T>` to take advantage of `CollectionsMarshal`.
- Also removes few unnecessary heap array allocations and uses InlineArrays instead.
Improved performance, decreased …
=> Replace boxing ArrayLists in UIAutomationClientSideProviders (hWnd proxies)

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Geometry.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/PropVariant.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/Marshalers.cs
Removes `GCHandle` allocations for short-term pinning operations with `fixed` statements to improve performance of the actual pinning up to 3 times per pinning operation. Any non-pinning and long-term instance pins were not modified.
| Method   | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Allocated [B] |
|--------- |----------:|-----------:|------------:|-------:|--------------:|
| Fixed    |  8.821 ns |  0.1969 ns |   0.4066 ns | 0.0167 |         280 B |
| Handle | 25.544 ns |  0.5316 ns |   0.5221 ns | 0.0167 |         280 B |
```c#
[Benchmark]
public void Fixed() => UnsafePin(new byte[256]);
[Benchmark]
public void Handle() => GCHandleAlloc(new byte[256]);
[MethodImpl(MethodImplOptions.NoInlining)]
private unsafe void GCHandleAlloc(Array sourceBuffer)
{
GCHandle arrayHandle = …
```
=> Replace GCHandle allocs for short-term pinning with fixed statements

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ResourceContainer.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/ReflectionUtils.cs
Optimizes two rather important startup methods in `ResourceContainer` class, the handler for runtime assembly load events - `OnAssemblyLoadEventHandler` and `GetResourceManagerWrapper`. This saves several milliseconds upon startup.
- I retracted from using `StringComparer.OrdinalIgnoreCase` as it would be slower by ~60ns in the final solution.
- For parsing the assembly name from safe input (`RuntimeAssembly`), I've re-used the #9739 and added a new method for `Version`/`PublicKeyToken`
- I've originally used `ArrayPool<char>` for the unlikely event of needing an array (256+ chars) but seems redundant to initialize it this early, and we shall not really need to allocate an array anyways in 99% cases.
- Using `AlternativeLookup`, this now becomes fully allocation-free given that usually …
=> Optimize ResourceContainer/AssemblyLoadEventHandler methods, remove allocs

src/Microsoft.DotNet.Wpf/src/.editorconfig, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/UidManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/RBNode.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/RBTree.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Interop/InternalDispatchObject.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XamlToRtfWriter.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/DependencyPropertyConverter.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/MarkupExtensionParser.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReaderHelper.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/ColorTypeConverter.cs, src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/VisualTreeFlattener.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonKeyTipAndContentSyncHelper.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameParser.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/ProxyManager.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WinFormsSpinner.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsContainer.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsMenu.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsRichEdit.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsSpinner.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsSysHeader.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsUpDown.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AvTrace.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/CompoundFile/ContainerUtilities.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/PackUriHelper.cs
Fixes #10296 
Fixes #10282 
Fixes #10297 
Fixes #10298 
Fixes #10299 
This work is a part of our initiative to set code-style guidelines, align WPF and WinForms, and ensure PR standards with respect to styles. This in turn will help us in better maintainability and readability of the repo overall. The changes follow up from the PR #10080 and references to the issue #10017.
The current changes address the following Errors/Warnings in the src folder of WPF:
- **CA2249:** Consider using 'string.Contains' instead of 'string.IndexOf'
- **CA2251**: Use String.Equals over String.Compare
- **CA1847**: Use string.Contains(char) instead of string.Contains(string) with single characters
- **CA1845**: Use span-based 'string.Concat'
- **CA1846**: Prefer AsSpan over Substring
A good way to go about …
=> [StyleCleanUp] Addressing CA warnings Part 1

eng/Versions.props, src/Microsoft.DotNet.Wpf/src/System.Windows.Primitives/System.Windows.Primitives.csproj, src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
All the projects that reference the S.R.CompilerServices.Unsafe package target a version of .NETCoreApp (net10.0) which already have that assembly available inbox. There's no need for the package references.
=> Remove unnecessary S.R.CompilerServices.Unsafe packageref

eng/WpfArcadeSdk/tools/Packaging.props
Without this fix, the Microsoft.NET.Sdk.WindowsDesktop package is missing the "tools" folder when being built on win-x64.
This happens because the PresentationBuildTasks project targest AnyCPU and so the artifacts aren't present in the ArtifactsPackagingDir with the platform. This is basically a wrong expectation in packaging.props as the Platform isn't aligned between a packable project and its project dependencies.
Fixes https://github.com/dotnet/source-build/issues/4888
Unblocks https://github.com/dotnet/sdk/pull/46550
=> Fix the ArtifactsPackagingDir on win-x64

eng/pipeline.yml
The Build.binlog contains the test binlog for non PR builds. This already got fixed in the -pr.yml file: https://github.com/dotnet/wpf/blob/263c65ed8daee5757fe6e779df4f0c4b76b0fb35/eng/pipeline-pr.yml#L193
=> Fix build binlog overwritten by test step

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapDecoder.cs
Fixes #10390.
`bitmapStream` may be `null` in `SetupDecoderFromUriOrStream`; this fixes a `NullReferenceException` closing it if an exception occurs.
Potential `NullReferenceException` from `BitmapImage` when loading invalid image data.
This fixes a regression introduced in .NET 9.0 in 3854d3238a00ceb81ad4b618686d7d5654582556.
None.
Low. This allows a local variable to be `null` and takes no action if it is.
=> Fix crash if bitmapStream is null

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapDecoder.cs
Backports https://github.com/dotnet/wpf/pull/10428 to `release/net9.0`. See https://github.com/dotnet/wpf/pull/10428#issuecomment-2644481693.
Fixes #10390.
=> Fix crash if bitmapStream is null. Fixes #10390

global.json
Removes .Net Core 2.1.7 which is EOL since 2021. I cannot find a use for it anywhere in this repo and if it does break something we should fix it instead of relying on an EOL runtime.
It's downloaded on each build (Though locally cached) so it should improve the build speed a little bit, especially in CI.
None, build only.
No.
Low, it would only break the WPF build and can always be reverted (Though we really shouldn't keep using .Net Core 2.1.7 since it's EOL).
=> Remove deprecated .Net runtime

src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimatableTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationBaseTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationClockResource.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationResourceTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/AnimationUsingKeyFramesTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/CommandStructure.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/CommandType.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/DiscreteKeyFrameTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/DuceResource.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/EasingKeyFrameTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/Elements.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/FrameworkElementTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/IAnimatableHelper.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/KeyFrameCollectionTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/KeyFrameTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/LinearKeyFrameTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/ManagedEnum.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/ManagedResource.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/ManagedStruct.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/PolySegmentTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/SplineKeyFrameTemplate.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/generators/renderdata.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/CollectionHelper.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/EmptyClassHelper.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/ManagedStyle.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/Style.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/xml/Resource.xml
Contributes to dotnet/wpf#10429
Syncs MilCodeGen to the generated code. This makes it as close as possible to reduce the diff and include changes that were made in the generated code.
None, this does not affect shipping code.
No.
Local build + CI + I manually validated the generated code.
Now to none, this does not affect shipping code.
=> Sync MilCodeGen to generated code

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/Int32RectValueSerializer.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/PointValueSerializer.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/RectValueSerializer.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/SizeValueSerializer.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Converters/Generated/VectorValueSerializer.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Int32Rect.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Int32RectConverter.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Point.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/PointConverter.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Rect.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/RectConverter.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Size.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/SizeConverter.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/Vector.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Generated/VectorConverter.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Media/Converters/Generated/MatrixValueSerializer.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Media/Generated/Matrix.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Media/Generated/MatrixConverter.cs
Contributes to dotnet/wpf#10429
Generates the code in WindowsBase using the changes from dotnet/wpf#10430.
I recommend reviewing only the last commit and with whitespace changes hidden, use [this link](https://github.com/dotnet/wpf/pull/10433/commits/be8df2a030b4570510fbe3113acec4a3967c4204?diff=unified&w=1).
None, shouldn't affect customers.
No.
Local build + CI + I manually validated the generated code.
Low, there shouldn't be any functional changes.
=> Run MilCodeGen for WindowsBase

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Generated/FrameworkContentElement.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Generated/FrameworkElement.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/DiscreteKeyFrames.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/EasingKeyFrames.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/KeyFrames.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/LinearKeyFrames.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/SplineKeyFrames.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessAnimation.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessAnimationBase.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessAnimationUsingKeyFrames.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Media/Animation/Generated/ThicknessKeyFrameCollection.cs
Contributes to dotnet/wpf#10429
Generates the code in PresentationFramework using the changes from dotnet/wpf#10430.
I recommend reviewing only the last commit and with whitespace changes hidden, use [this link](https://github.com/dotnet/wpf/pull/10435/commits/578f907dfb9fe0964bbed2cbb456edff58423d2f?diff=unified&w=1).
None, shouldn't affect customers.
No.
Local build + CI + I manually validated the generated code.
Low, there shouldn't be any functional changes.
=> Run MilCodeGen for PresentationFramework

.editorconfig
Disables code analysis for generated code. Code analysis for generated code does not make sense since generated code will never be perfectly formatted and it prevents doing auto formatting to generated code without modifying the code generator.
We'll probably want to format the generated code someday but it should probably be done only when dotnet/wpf#6135 is merged and we can modify the code generator instead of modifying the generated code manually.
None.
No.
None.
=> Disable code analysis for generated code

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListBoxItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListViewItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10370
This PR makes the margin and padding of ListViewItem and ListBoxItem as Lightweight resources
No
=> Makes Margin and Padding of ListViewItem and ListBoxItem as DynamicResource

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Adds reference to ItemsControl.xaml and UserControl.xaml in Fluent.xaml
No
=> Adds reference to ItemsControl and UserControl xaml files in Fluent.xaml

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Thumb.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Fixes #10467 
A Thumb in WPF is a control that enables drag-and-drop functionality, commonly used in scrollbars, sliders, and resizable elements.
This PR adds styling for Thumb in fluent
Aero:
Fluent:
No
=> Adding style for Thumb in fluent

Documentation/developer-guide.md, eng/wpf-debug.targets
Debugging sample application with local binaries is currently broken due to a recent change removing the x64 folder in packaging. The change here updates the path that the binaries are copied to without the x64 folder.
Seamless debugging experience
Yes
Verified using sample application
Low
=> Change lookup path of binaries: wpf-debug.targets

global.json
Works around an issue where because WPF uses Platform globally as to mean the Target platform, and because this is a default property that arcade uses to install additional runtimes, arcade installs the arm64 runtime on an x64 machine, which breaks when we try to run msbuild in signing. It would also break things if we ever ran testing.
```
<PropertyGroup>
<Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
<Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
<PlatformName Condition="'$(PlatformName)' == ''">$(Platform)</PlatformName>
</PropertyGroup>
```
=> Force an x64 runtime install

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/StatusBarItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml, src/Microsoft.DotNet.Wpf/src/Themes/XAML/StatusBarItem.xaml
Fixes #10500 
A StatusBarItem is a specialized container used within a StatusBar to display status information. It can host text, images, or other controls and supports features like resizing and styling for better UI presentation.
This PR adds styling for this control in fluent and as the style of this control does not have any visible component default state, it has been kept that way, hence no screenshots have been attached.
No
=> Adds style for StatusBarItem in fluent

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ResizeGrip.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Fixes #10510 
ResizeGrip is a WPF control that enables users to resize a Window when placed inside a StatusBar. It provides a visual handle, typically at the bottom-right corner, for resizing operations.
This PR adds styling for this control in fluent
No
=> Adds style for Resizegrip in fluent

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/AppContextDefaultValues.cs
Fixes https://github.com/dotnet/wpf/issues/10491
As in .NET 9, the changes here makes DynamicResource Optimization as opt-in. As observed in some of the SyncFusion based sample applications, the optimized resources, causes crashing apps. The reason we are keeping this as opt-in is to accommodate fixes in the optimized approach. We will look into other options if we are unable to fix it at a later point.
Yes
Sample application testing
Low, changing things back to pre .NET 9 behavior
cc:/ @batzen
=> Make Dynamic Resource Optmization as Opt-Int

Directory.Build.targets, README.md, codecov.yml, eng/CodeCoverage.proj, eng/CodeCoverage.runsettings, eng/Testing.targets, eng/Versions.props, eng/pipeline-pr.yml, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ContentType.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/Directory.Build.props, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System.Xaml.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/WindowsBase.Tests/WindowsBase.Tests.csproj
=> Establish Code Coverage for wpf

src/Microsoft.DotNet.Wpf/tests/UnitTests/WindowsBase.Tests/System/Windows/DependencyPropertyTests.cs
Fixes the test failure seen in main currently. This was caused by the switch from xUnit test runner to VSTest test runner introduced in #10514 which changed the order in which test were ran and exposed an existing bug in the tests.
The problem is because the xUnit test runner ran the test `Register_InvokeStringTypeTypeValidateFail_Throws` before `Register_InvokeStringTypeType_Success` and VSTest test runner runs them in inverse order. This causes problem because both test registers a dependency property for the same type with the same property name, the thing is that `Register_InvokeStringTypeTypeValidateFail_Throws` expects the registration to fail and not register the dependency property in the cache while `Register_InvokeStringTypeType_Success` expects the registration to succeed and …
=> Fix DependencyProperty test

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapSource.cs
Removes redundant type checks second-time around when copying pixels in `CriticalCopyPixels`. There's a small performance improvement, however, the main goal here is decreasing code size, and also code simplification that has been made possible with the introduction of `GetArrayDataReference` few releases ago.
Since `Unsafe.AddByteOffset` won't do an index-out-of-bounds check for us, we do it ourselves to keep the same behaviour as previously, throwing `IndexOutOfRangeException` on when `offset` exceeds the array length.
Smaller code-size of PresentationCore.
No.
Local build.
Low.
=> Simplify CriticalCopyPixels in BitmapSource by removing duplicate type checks

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaSystem.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/FlowDocumentPage.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/PageBreakRecord.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/PtsCache.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/PtsContext.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/PtsPage.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/ShutDownListener.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/AccessibilitySwitches.cs
As [dotnet/runtime - #65184](https://github.com/dotnet/runtime/issues/65184#issue-1132211395) was approved last week and changes were made in the runtime repo to unconstrain the generic overload from class-only behaviour for `Interlocked.Exchange` and `Interlocked.CompareExchange`, we can adjust the code in the WPF repo for improved code quality as well.
Given how few places we rely on `Interlocked` functionality, this should be easy to review.
None, just internal code quality changes that do not measurably affect performance in any direction.
No.
Local build/CI.
None.
=> Replace Interlocked.{Compare}Exchange Int32 overloads with generic <bool> variants

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/ListCollectionView.cs
Fixes #9454
When items are added to a filtering collection, changing a live filtering property too fast might result in the collection view becoming out of sync of the data.
This is because the subscription to changes in the list happens after items are added to a private copy of the list, providing a window between the copy and the subscription in which changes can occur unnoticed. This PR fixes it by moving the subscription before creating the copy.
By not taking this fix, customers cannot rely on data being correctly filtered during live shaping.
No.
Tested with provided repro project at https://github.com/VanderlandeWouterPost/CollectionViewSourceFilterAndSortIssue. Verified the issue occurs before the PR but not after.
Can't think of any significant risk. When the subscription event …
=> Live filtering race condition fix

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Track.cs
Fixes #9904 
Fixes `IndexOutOfRangeException` and infinite loop issues when updating any of `Track`'s children after they've been already set from template or manually.
This issue is present when you attempt to update via any of the public properties (`DecreaseRepeatButton`, `IncreaseRepeatButton`, `Thumb`) after all the public members of Track has already been previously set (and therefore `_visualChildren` is initialized and has stored all three properties).
In standard Aero2 theme, using a `ScrollBar` (as `Track` has no template on its own), the order of the children is:
- _visualChildren[0] = RepeatButton1
- _visualChildren[1] = RepeatButton2
- _visualChildren[2] = Thumb
Setting item at position 2 (which would be `Thumb` property now) will result in an infinite loop.
Setting items at …
=> Fix IndexOutOfRangeException/Infinite loop in UpdateComponent (Track control)

src/Microsoft.DotNet.Wpf/src/PresentationCore/GlobalSuppressions.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/GlobalUsings.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DataFormat.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DataFormats.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj
This uses the shared DataFormats code from System.Private.Windows.Core.
Note that locking is handled by the shared code so there is no need to do so when adding the WPF specific types. The only reason they need added is that casing will stick with whatever the first request is. That is, if you ask for "XAML" that will be the string Windows gives back, not "Xaml".
=> Use shared DataFormats code

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10071
Fixes missing `RecognizesAccessKey` property on some Fluent controls that I found to be lacking based on the original issue.
Users will get less buggy experience migrating to Fluent Theme.
Kinda, from previous themes.
Local build, sample app.
None.
=> Fix missing RecognizesAccessKey property on Fluent controls

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSource.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Shaping/GlyphingCache.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SizeLimitedCache.cs
Fixes #4828 
While checking out `SizeLimitedCache<K, V>` yesterday, I've noticed the double lookups on the dictionary and today I've found there's already a corresponding issue for it, hence we should fix it for optimal performance as this is used with glyphs/fonts.
- Use throw helpers over creating new instance of `ArgumentNullException` directly.
- `Remove` had even three lookups, so now it just has one.
- Fields that could be `readonly` have been adjusted.
- Sealed the class, proper naming conventions.
- `Node` uses auto properties now.
| Original |  988.4 ns |    9.39 ns |     7.84 ns | 0.1183 | …
=> Remove double lookups on SizeLimitedCache<K, V>, improve performance

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolTip.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #9973 
Sets the FontWeight of ToolTip as Normal in Fluent
No
=> Sets the FontWeight of ToolTip as Normal

src/Microsoft.DotNet.Wpf/src/WpfGfx/core/resources/lineargradient.h
Fixes #10502 
As described in the issue description, LinearGradientBrushes ( LGB ) caches it bounds when we use Absolute MappingMode. However, when we apply transformations to the brush, the brush does not work work as expected. This PR removes the caching of the brush, thus resolving the issue.
Developers using the LGB along with MappingMode=Absolute and RelativeTransform will get the correct behavior for the brush.
No
Not yet.
- It will have a performance impact on the application using LGB with Absolute mapping mode.
- Applications using LGB will get a different behavior now.
=> Removes MappingMode from LinearGradientBrush in HasRealizationContextChanged

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Fixes #  https://github.com/microsoft/vscode-dotnettools/issues/1018, https://github.com/dotnet/vscode-csharp/issues/5958
Main PR 
Roslyn's MSBuildWorkspace, Roslyn LSP ProjectSystem, and (possibly) CPS used in C# DevKit do not want to set BuildingInsideVisualStudio because of all the unknown compatibility issues that might create. By adding the 
DesignTimeMarkupCompilation to CoreCompile when a DesignTimeBuild is being performed we will be able to provide our users the ability to open WPF projects and have a good editing experience.
Looks like a previous PR (https://github.com/dotnet/wpf/pull/1895) enabled this for CPS within VisualStudio and this hopes to do the same for project systems outside VS.
https://github.com/microsoft/vscode-dotnettools/issues/1018, …
=> Run DesignTimeMarkupCompilation when DesignTimeBuild is set.

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontSource.cs
Fixes #7289
Fixes memory leak when using fonts from embedded resources that are materialized onto `FontSource` -> `FontFamily`, etc.
The issue is basically in `FontSource.GetUnmanagedStream()`:
- We're passing around pure `UnmanagedMemoryStream` instance, but life without destructor is kind of hard.
- This can be removed once `FontFileStream` from `DirectWriteForwarder` would be migrated to C#.
More context: The fix could be done by disposing the `UnmanagedMemoryStream` instantly and wrapping it in a new instance so it's cleared from the `List<Stream>` of `PackagePart` but I think it's nice to tie the lifetime together.
Customers will finally get their fix after 10 years.
https://stackoverflow.com/questions/31452443/wpf-textblock-memory-leak-when-using-font …
=> Fix FontSource/FontFileStream embedded resource memory leak

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
Fixes 
Avoids a design time build failure observed in IDE logs for dotnet/roslyn.
=> Make sure to ContinueOnError when DesignTimeBuild is true

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10569 
Since #10502 is fixed now, I have raised this PR to fix the elevation brushes for Light and Dark themes. Elevation brushes use RelativeTransform alongwith an Absolute mode LinearGradientBrush. 
Fixes Fluent theme resources 
No
Local testing
Minimal
=> Fixed elevation border brush for Light and Dark theme

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #  #9886 
Button styles were using the common / Fluent brushes directly rather than Button's control brushes like ButtonBorderBrush, ButtonBorderBrushPointerOver, etc.
In this PR, I have fixed the Button styles to use the Button control brushes correctly.
Developers will be able to modify the Button control brushes without affecting other controls.
No
Local testing
No
=> Fixing button border brush and other resource usage

src/Microsoft.DotNet.Wpf/src/.editorconfig, src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/XmlWrappingReader.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtension.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlNodes.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameScanner.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MePullParser.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MeScanner.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/NodeStreamSorter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlAttribute.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlPropertyName.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlScanner.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/RefOnly/LooseTypeExtensions.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Runtime/ClrObjectRuntime.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/BuiltInValueConverter.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlBackgroundReader.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlReader.cs
Fixes #10524 
Fixes spacing around keywords as per `SA1000`, the only violations were in `System.Xaml`.
Cleaner codebase for developers.
No.
Local build.
None.
=> [StyleCleanUp] Fix spacing around keywords (SA1000) 

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/GenericTypeNameScanner.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlTypeName.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlXmlWriter.cs
Optimizes retrievals of subscripts/type names from generic types and also its serialization back to string.
This is meant to be very straightforward (as the main modification is done to `GenericTypeNameScanner.StripSubscript` and other modifications are just to comfort the change), so a lot of strings were kept, that's not an oversight. I believe those changes should be done in small batches.
Improved performance, decreased allocations.
No.
Local build, unit tests.
Low.
=> Optimize parsing and serialization of generic type names in Xaml, decrease allocs

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs
Replaces 4x `ArrayList` collections with `List<T>` for improved performance and increased type safety.
I've also introduced `init` setters for the respective properties so they can be used as part of the `Clone` operation and the underlying fields can be converted to `readonly`. Rest are just NULL check removals coming from the `as` casting pattern or simply redundant as the values in the lists are always from freshly initialized types, no NULLs are inserted.
Sample benchmark showing difference between `ArrayList` and `List<T>` with reference type can be found f.e. in #9432.
Improved performance, cleaner codebase for developers.
No.
Local build.
Low, just type swaps.
=> Replace use of ArrayList with List<T> in BamlMapTable for performance

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/Imaging/BitmapImage.Tests.cs
Adds very basic initialization tests for `BitmapImage`, mostly driven just to provide a test validating fix in #10428.
Also adds reference to `System.IO.Packaging` for `PresentationCore.Tests` since otherwise the package ain't present, causing any `PresentationCore` tests to fail that load types which rely on it as the library cannot be loaded.
None, just a few more tests validating codebase health.
No.
Local build.
None.
=> Add BitmapImage initialization tests validating fix in #10428

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Button.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10413 
Fixes color for AccentButtonBackgroundPressed in HC mode and sets Foreground for MouseOver trigger in AccentButtonStyle.
No
local build pass, tested with sample applications
=> Fixes color for AccentButtonBackgroundPressed in HC mode and sets Foreground for MouseOver trigger in AccentButtonStyle

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10571 
Makes visibility of ScrollViewer as Auto in ComboBox
No
local build pass, tested with sample applications
=> Making visibility of ScrollViewer as Auto in ComboBox

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
This brush should be used as the border in all the text controls when they are focused. However, due to the issue in LinearGradientBrush we were using different workarounds to achieve the same effect in TextBox and related controls wrt to style.
Will allow fixing fluent style for TextBox and other related controls.
NA
None, new brushes added.
=> Added TextControlElevationFocusedBorderBrush to fluent resources

src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AvTrace.cs
Improves performance of the `AntiFormat` function in `AvTrace`, reducing allocations and improving the overall performance up to 2 times in some cases. Also changes `FormatChars` from `char[]` to `ReadOnlySpan<char>`, occurrence I've missed in #9230.
Second commit features added documentation for the function. I've included some basic asserts at the **Testing** section.
| Method     | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Allocated [B] |
|----------- |----------:|-----------:|------------:|-------:|--------------:|
| PR__Edit |  236.1 ns |    4.75 ns |     5.84 ns | 0.0730 |        1224 B |
| Original |  400.7 ns |    8.04 ns |    15.29 ns | 0.1040 |        1744 B |
```c#
AntiFormat2("{aaaa}");
AntiFormat2("{aaaa}}"); …
```
=> Spanify AntiFormat function in AvTrace, decrease allocations, improve perf

src/Microsoft.DotNet.Wpf/src/.editorconfig, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPenimc.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Interop/TipTsfHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusLogic.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusTouchDeviceBase.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResourceKey.cs, src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/TextSearchInternal.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Freezable.cs
Fixes #10300 
Avoid initializing `[ThreadStatic]` variables inline to prevent mistakes as it may lead you into thinking that such value will be initialized for all instances of the variable, not just the first thread.
Cleaner codebase for developers.
No.
Local build.
Low. I've checked that fields that require initialization are properly initialized elsewhere.
=> [StyleCleanUp] ThreadStatic fields should not use inline initialization (CA2019)

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TextCompositionManager.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsCLR.cs
Removes unnecessary `byte[]` , `char[]` and `StringBuilder` alocations during post-input processing when the char is inputted via Alt+Numpad combination. This is not somewhat impactful allocation but it will allow for more optimizations in the future.
Time spent is cut by 2/5 which is more impactful in this case.
| Method   |Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|--------- |-----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original | 48.77 ns |   0.674 ns |    0.630 ns | 0.0086 |         814 B |         144 B |
| PR_EDIT  |  31.83 ns |   0.292 ns |    0.273 ns | 0.0019 |         418 B |          32 B |
Improved performance, decreased allocations.
No.
Local build, text input.
Low.
=> Remove array/object allocs during Alt+Numpad composition, improve performance

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FamilyCollection.cs
I improved performance and allocations by using the new GetAlternateLookup introduced in .Net 9.0. This is a followup to dotnet/wpf#7794 where GetAlternateLookup wasn't available at the time.
Here's the result of my benchmark:
```
|          Method |     Mean |   Error |  StdDev | Ratio | RatioSD |   Gen0 | Allocated | Alloc Ratio |
|---------------- |---------:|--------:|--------:|------:|--------:|-------:|----------:|------------:|
| LookupFamilyOld | 344.6 ns | 4.59 ns | 4.29 ns |  1.00 |    0.00 | 0.0706 |   1.16 KB |        1.00 |
| LookupFamilyNew | 333.0 ns | 3.23 ns | 2.86 ns |  0.97 |    0.02 | 0.0687 |   1.13 KB |        0.97 |
```
Better perf.
No.
I ran FamilyCollection.GetFontFromFamily with different combinations to make sure that the result was the same.
Low.
=> Improve font performance in FamilyCollection.GetFontFromFamily

src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Generated/ToleranceTypeValidation.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/helpers/ManagedStyle.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_command_types.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_commands.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_misc.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_resource_types.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/CsPrimeParser.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/CsPrimeRuntime.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/GlobalUsings.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/MainClass.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/Project.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/TempDirectory.cs, src/Microsoft.DotNet.Wpf/src/WpfGfx/tools/csp/csp.csproj
Fixes #10682
This fixes `using` placements in CSP which I've overlooked when I've removed it in #10374 as we still don't run `MilCodeGen` during build, hence this fixes that + also corrects the header for IDE0073 for generated files from the last commit.
Cleaner codebase for developers, being able to run MilCodeGen.
Kinda, MilCodeGen won't work without suppressing warnings now.
Local build, codegen run.
None.
=> [StyleCleanUp] Fix misplaced using directives in CSP (IDE0065)

eng/WpfArcadeSdk/tools/CodeGen/AvTrace/AvTraceMessages.tt, src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Generated/AvTraceMessages.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Generated/AvTraceMessages.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/TraceData.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AvTrace.cs, src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Generated/AvTraceMessages.cs
Fixes #9467 Reference #9463 
More of a complex fix, modifies the call chain to make use of the latest .NET features.
- ~~I've used `Span<object>` instead of `ReadOnlySpan<object>` as the `parameters` array has always been mutated by the trace class, hence I didn't want to currently change the behaviour.~~
- Builds on the original intention of #6700 
- The fixes should be compatible with my other PR too, #9361 and #9352.
- `ArrayList` replaced with pre-allocated array and used interpolation for building the trace data.
- Modifies the `AvTraceMessages.tt` for completion.
- The overall cost of `AvTrace` / `AvTraceMessages` will be greatly reduced.
Improved performance when tracing is active, decreased array allocations per each executed trace, smaller assemblies due to the function removal. …
=> Modify AvTrace call chain to use params ReadOnlySpan<object> instead of an array

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/Animation/KeySplineConverter.Tests.cs
Adds test coverage for `KeySplineConverter`. Sending these to support the #9364 PR.
No.
Local build.
None.
=> Add test coverage for public API surface of KeySplineConverter

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/Generated/BrushConverter.Tests.cs
Adds test coverage for `BrushConverter`. Sending these to support the #10225 PR.
This doesn't add `ConvertTo`/`ITypeDescriptorContext` tests (as they're not relevant for the PR), should be added later.
No.
Local build.
None.
=> Add test coverage for public API surface of BrushConverter

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/ColorConverter.Tests.cs
Adds test coverage for `ColorConverter`. Sending these to support the #10225 PR.
This doesn't add `ConvertTo`/`ITypeDescriptorContext` tests (as they're not relevant for the PR), should be added later.
No.
Local build.
None.
=> Add test coverage for public API surface of ColorConverter

src/Microsoft.DotNet.Wpf/src/.editorconfig, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsTable/RowSpanVector.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/GuidGenerator.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GridViewAutomationPeer.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/InkCanvas.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Slider.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextSchema.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlTypeMapper.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlMemberInvoker.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/Schema.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/UiaCoreApi.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/CacheRequest.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/MSAANativeProvider.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Internal/AutomationProxies/WindowsRichEdit.cs, src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationTypes/System/Windows/Automation/ControlType.cs
Fixes #10286
This PR mainly resolves `CA1825` but in some cases goes a step further over standard analyzer fix.
- In addition to using singleton over allocating zero-length array everytime, we want to avoid storing those in `readonly` fields (whether they're marked or not), as the pointer to such array is already accessible via `Array.Empty<Type>()`.
- `XamlTypeMapper` was going step further and cloning this zero-length array even. Happy days.
- `RowSpanVector` was performing unnecessary assigment if the branch was not taken.
Increased performance, decreased allocations.
No.
Local build.
Should be low.
=> Avoid zero-length array allocations and storing them in static fields (CA1825)

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapSource.cs, src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/Media/Imaging/WriteableBitmap.Tests.cs
Fixes #9438 
Fixes working with `WriteableBitmap` to (`WritePixels`/`Clone`) operations on large buffers (over `Int32.MaxValue`) as those are supported by `WpfGfx`/`Milcore` as the underlying layer supports creation and working with such buffers.
Previously you were just able to create such WriteableBitmap but unable to `WritePixels` to the bottom-right corner or `Clone` it.
This departs from `BitmapSource` behaviour which uses `WIC` and there's an ongoing disparity between `IWICBitmapSource_CopyPixels_Proxy` and `IWICImagingFactory_CreateBitmapFromMemory_Proxy` where the former works with up to 4GB buffers but creating such bitmap fails with `0x80070057` even though both bufferSize params are documented as `uint`.
Base code that would fail with `OverflowException` before on `WritePixels` …
=> Fix WriteableBitmap's Write/CopyPixels (Clone) to support up to 4GB backbuffers

src/Microsoft.DotNet.Wpf/src/.editorconfig, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/UidManager.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/WinRTSpellerInterop.cs
Fixes #10302
Use `GeneratedRegex` attribute to allow for source-generation of regexes at compile time for improved performance.
We only use regexes in two places which could effectively be removed but for now we should at least take advantage of the highest-performing form of regular expressions on .NET.
In the PBT case, we have to use a pre-processor statement to comfort NetFX scenario, which will later need naming-styles suppression.
Note: `RegexOptions.Compiled` is ignored in source-generated regexes, so I've removed it.
Improved performance, cleaner codebase.
No.
Local build.
While the second occurence was fixed manually because analyzer won't flag it (guess nobody thought someone is declaring regex inline with a const), the change is straightforward.
=> Use source-generated regex instead of runtime compilation (SYSLIB1045)

eng/Versions.props, src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
Fixes https://github.com/dotnet/wpf/issues/10721
System.CodeDom is only used on .NETCoreApp and its live version is available in the SDK directory. Therefore, we shouldn't need to pin it to an older version.
=> Don't redistribute inbox msbuild dependencies

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs
Fixes https://github.com/dotnet/wpf/issues/9467
Reference https://github.com/dotnet/wpf/pull/6700 and https://github.com/dotnet/wpf/pull/9460
See https://github.com/dotnet/wpf/issues/9467
After https://github.com/dotnet/wpf/pull/6700 , to reduce allocations when tracing routed events, we'll use `_traceArguments` field to store the trace arguments which cause https://github.com/dotnet/wpf/issues/9467 issues.
I try clear the reference from `_traceArguments` after call the `TraceRoutedEvent.Trace`.
And this pr is a patch, and I think https://github.com/dotnet/wpf/pull/9460 will be better. Thank you @kasperk81
See https://github.com/dotnet/wpf/issues/9467
The memory will still be freed, albeit at a slower pace. Even if this issue is not addressed, it won't have a significant impact. There are …
=> Try fix EventRoute weak memory leak

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TreeViewItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10209 
In Fluent styles, we use icon fonts to render the arrow / chevron in TreeViewItem instead of Path ( as in Aero2 ). When FlowDirection is set RightToLeft, the arrow defined in Path was reversed, but in case of TextBlock, this does not happen with characters. So, in order to fix this I use a trigger which uses the left chevron for the icon. 
Developers will correct behavior for TreeViewItem when using Fluent theme and RightToLeft FlowDirection.
No
Local app testing.
Minimal
=> Fixes TreeViewItem chevron arrow orientation when FlowDirection is RightToLeft

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
These changes are in accordance to the original API contract of certain `SetData` methods in `DataObject` class. The original behaviour was altered a bit in form of exceptions not being thrown as part of the shared clipboard code for winforms and wpf as in the PR #10544. These changes brings back the expected behaviour that respects WPFs original implementation.
Avoids breaking changes in subsequent preview release of .NET 10.
Yes
Local Build Pass, unit testing and verified the same with sample applications.
Low
=> Fix DataObject SetData methods inaccordance to previous implementation

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Text control common resources and brushes are used by multiple controls like DatePicker, TextBox, RichTextBox, EditableComboBox etc. Therefore adding it before hand to the resources files in Fluent.
Correct Fluent style for controls.
Minimal
Minimal
=> Added text control common resources and brushes

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/GlobalUsings.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/PresentationFramework.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/System/Windows/ResourceDictionaryTests.cs, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/System/Windows/Resources/SampleResourceDictionary.xaml
The following changes adds some unit tests around `ResourceDictionary` and some more `DynamicResource` based tests that ensures obvious functionalities are not breaking. Again, the change here is to validate, to an elementary extent, the changes of the PR #10532 
_None_
Build pass, the unit tests are green here
Low
=> Add Resource Dictionary Tests

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/MenuItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #9980
In the current MenuItem Fluent styles, the Icon column didn't share width among the different MenuItems. Due to this, the Header content presenter gets misaligned.
Improves usability and speeds up visual scanning of the UI
Technically no, but as compared to Aero2 styles this is a regression in Fluent styles.
Local app testing.
Minimal
=> Fixed MenuItem Header alignment wrt to Icons

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/DataObjectTests.cs
The changes here aims at adding tests around `SetData` method of DataObject class. This is to validate that the contracts are not breached and avoid minor bugs after the merger of #10544. The changes also references to a task item mentioned in https://github.com/dotnet/wpf/issues/10736.
The following tests are added in the following changes
**Around [SetData(Object)](https://learn.microsoft.com/en-us/dotnet/api/system.windows.dataobject.setdata?view=windowsdesktop-9.0#system-windows-dataobject-setdata(system-object))**
- Different types returns expected values.
- Same type, returns later value.
**Around [SetData(String, Object)](https://learn.microsoft.com/en-us/dotnet/api/system.windows.dataobject.setdata?view=windowsdesktop-9.0#system-windows-dataobject-setdata(system-string-system-objec …
=> Add DataObject SetData tests

eng/Versions.props, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/PresentationCore.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/PresentationFramework.Fluent.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Tests/PresentationFramework.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Printing.Tests/System.Printing.Tests.csproj, src/Microsoft.DotNet.Wpf/tests/UnitTests/WindowsBase.Tests/WindowsBase.Tests.csproj
Fixes dotnet/wpf#10755
Replace FluentAssertions with AwesomeAssertions. AwesomeAssertions is a fork of FluentAssertions before FluentAssertions 
changed its license (See fluentassertions/fluentassertions#2943).
This change is similar to what has been done in Runtime (dotnet/runtime#113425) and WinForms (dotnet/winforms#13108).
None, tests only.
No.
Ran tests locally.
None, tests only.
=> Replace FluentAssertions with AwesomeAssertions

src/Microsoft.DotNet.Wpf/src/PresentationCore/ref/PresentationCore.cs
Fixes #10738 
The changes here includes updates to the ref file, null annotating new and modified APIs in `DataObject` and `Clipboard` classes.
_None_
=> Null Annotate PresentationCore ref

src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationCore.Tests/System/Windows/DataObjectTests.cs
The changes here aims at adding tests around `ContainsText`, `ContainsAudio`, and `ContainsImage` method of DataObject class. This is to validate that the contracts are not breached and avoid minor bugs after the merger of #10544. The changes also references to a task item mentioned in https://github.com/dotnet/wpf/issues/10736.
Have moved the previous tests a bit to make sure they are in the desired region and hence the removals may look unnecessary, but these tests are still present in the same file.
_None_
Build pass, the tests are all green
Low
=> Add DataObject tests

src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/ManagedWndProcTracker.cs, src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsCLR.cs
The `PostMessage` call while closing the application might throw an invalid window handle exception. Ideally, the `Win32`'s `PostMessage` call is not designed to throw an exception; instead, it is meant to return a boolean indicating success or failure. However, the current call is wrapped to throw a `Win32Exception`. Interestingly, the `SetWindowLong` call just above this call is in a try-catch block that ignores the invalid window handle exception. It makes sense to move the `PostMessage` call inside the try-catch block to avoid the same exception being thrown.
The current `PostMessage` wrapper being used is also modified to get the error code as soon as the failure in `IntPostMessage` is encountered.
This might be a potential fix to the issue #7536 
No
Tested with a …
=> Fix: Plausible Exception while closing an Application

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10772 
Partially fixes #10358 ( have not looked at the selection issue yet )
Main PR 
In this PR I have attempted to restyle TextBox and TextBoxBase styles for Fluent theme in WPF. Here is the list of changes done : 
1. Modified ControlTemplate to closely mirror WinUI, which fixes the positioning of clear button as well.
2. Modified triggers, to hide the clear button when TextWrapping=Wrap or AcceptsReturn=True.
3. Added TextControl specific color and brush resources.
Developers using TextBox in Fluent style will get the correct behaviors.
No
No behavioral breaking change yet.
=> [Fluent] Fixes mulitple issues is TextBox and TextBoxBase styles

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes  #10519 
Fixes multiple issues in DatePicker style including the ones mentioned in the above issue. Few of these include :
1. Fixed calendar button sizing in DatePicker - when using custom height, in default scenario.
2. Modified the template : removed extra accentborder element, used new ControlElevationBorderBrush instead.
3. Fixed the popup background and drop shadow.
4. Matched the tab-stop, alignment, etc behavior with Aero2 theme to minimize breaking changes wrt to Aero2.
Makes it easier for developers to adopt fluent theme.
N/A
Local app testing.
Low - Medium. If developers have adopted Fluent in .NET 9 they would need to make changes in their applications, to incorporate the new behavior. For devs moving from Aero2 to Fluent will see less disruptions in the style.
=> [Fluent] Fixes multiple issues in DatePicker style

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006KeyRecord.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
Second try to improve performance of DynamicResource.
This approach should not cause issues like #10491.
Original issue is still #4468.
Original PR was #5610 with follow up PR #9393 with opt out switch introduced in #9501 and final opt-in switch added in #10516.
Feedback on the approach is very appreciated.
=> Improving DynamicResource performance (second try)

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Thumb.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10497 
Adds a trigger to change the Background color in the Disabled state for Thumb
No visual feedback for disabled state for Thumb
local build pass
Low
=> Adds trigger for disabled state for Thumb

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/AppContextDefaultValues.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs, src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceExpression.cs
The changes here are intended to disregard developers' preferences regarding the `DisableDynamicResourceOptimization` switch. Regardless of the value set for this app context switch, the goal is to execute the code path that includes the recent optimizations introduced in #10532. This is because the optimizations will be part of the preview release, and our aim is to gather as many hits as possible.
cc:/ @batzen 
_None_
By enforcing the execution of the optimized code path, we might encounter unforeseen issues that could have been mitigated using the switch. However, collecting such issues is beneficial to refine the optimizations before the final release, if needed.
=> Ignore Dynamic Resource Opt out Preferences

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/ActiveXHost.cs
Avoids warning suppression for `ApartmentState` property by using the newer method instead. In the retrieval (get) context, checking for STA has no behavioral difference between those two, hence no reason to NOT use it.
Also, this is the only place in WPF where the swap to the method hasn't been done yet.
Cleaner codebase for developers, not using BCL obsoleted methods.
No.
Local build.
Low.
=> Avoid obsoletion warning suppression in ActiveXHost

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Since Preview 4, the creation of TextBox, PasswordBox and RichTextBox was crashing when using `System` theme. This was due to the assignment of it's `BorderThickness` as `StaticResource` and the resource being declared in `Variables.xaml` which is a sibling of `TextBox.xaml` and other files in `Fluent.xaml` and hence resulting in the crash. The changes here aims to resolve this using the `DynamicResource`.
Crash free fluent applications when using `System` theme.
Yes
Local Build Pass,
Verified the working using a sample application
Low
=> Fix crashes in TextBox(es) in Fluent theme

src/Microsoft.DotNet.Wpf/src/.editorconfig, src/Microsoft.DotNet.Wpf/src/PresentationCore/GlobalSuppressions.cs
Fixes #10674 
Fixes the leftover violations via suppressions as there's currently a bug I've described in https://github.com/dotnet/roslyn-analyzers/issues/7617. To be honest, `Duration` could simply implement `IEquatable<T>`/`IComparable<T>`.
Cleaner codebase for developers.
No.
Local build.
None.
=> [StyleCleanUp] Use ArgumentOutOfRangeException throw helper (CA1512)

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/DpiHelper.cs
We can merge the `_transformToDevice` and `_transformToDip` fields to local variable. Why we define the  `_transformToDevice` and `_transformToDip` fields? Because we use the two fields to store the DPI in the previous version, and the code is:
```csharp
private static Matrix _transformToDevice;
private static Matrix _transformToDip;
[SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
static DpiHelper()
{
using (SafeDC desktop = SafeDC.GetDesktop())
{
int deviceCaps1 = NativeMethods.GetDeviceCaps(desktop, DeviceCap.LOGPIXELSX);
int deviceCaps2 = NativeMethods.GetDeviceCaps(desktop, DeviceCap.LOGPIXELSY);
DpiHelper._transformToDip = Matrix.Identity;
DpiHelper._transformToDip.Scale(96.0 / (double)deviceCaps1, 96.0 / (double)deviceCaps2); …
```
=> Remove the unnecessary fields in DpiHelper

NuGet.config, eng/Version.Details.xml, eng/Versions.props
=> Merging internal commits for release/9.0

eng/Tools.props, eng/Version.Details.xml, eng/Versions.props, eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets, global.json
This avoids need for a workaround in VMR builds and reduces friction for stable builds. When building non-win-x64 verticals, we end up having to set the x64 runtime pack and x64 VS redist pack properties (stable and non-stable properties) based on other values in the VMR orchestrator. Instead, use MicrosoftNEtCoreAppRef as the stable version property, and MicrosoftNETCOrePlatforms as the non-stable one.
=> Replace arch-specific package properties with arch neutral ones

src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/ManagedWndProcTracker.cs
Replaces boxing `Hashtable` with generic `Dictionary<HwndSubclass, IntPtr>` and improves overall performance.
- Since all operations are under a lock, there are no thread-safety concerns with replacing `Hashtable`.
- I've also added some more comments for clarity on the class.
- I've felt like the memory fence on `s_exiting` can help because the reads can come from multiple threads.
- Usings for `SecurityHelper` were removed as those are not needed since CAS removal.
Decreased allocations, improved performance.
No.
Local build/sample app run.
Low, the swap is safe.
=> Replace boxing Hashtable in ManagedWndProcTracker with Dictionary<K, V>

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/TextDecorationCollectionConverter.cs
Optimize parsing of `TextDecorations` from string into `TextDecorationCollection`, reduces allocations in all steps and improves performance, also reduces the memory footprint + readibility of the entire class by a large amount.
- Removes static array `TextDecorationNames`, that also removes the strings allocations on its own (not used anywhere else).
- Removes static array `PredefinedTextDecorations`, which was redundant from the start.
- And removes another 120 lines trying to avoid allocations in NetFX by using few newer BCL features.
- The static collections are frozen after creation, so are its items, so we can just grab it via indexer.
|--------- …
=> Optimize parsing/conversion of TextDecorations from string, reduce allocations

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/AssemblyNamespacePair.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs, src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs
Adjusts inefficient `List<AssemblyNamespacePair>` copies in `AddAssemblyNamespacePair` that result in up to double gen0 allocations needed for the job, offering perf benefit and decreased allocations.
- I have changed it to be a `readonly struct`, there's like zero benefit but I think it serves better purpose.
- The `WeakReference` is now generic to prevent unnecessary casting.
- Since `_assemblyNamespaces` is under a write-lock and copies are created each time to allow reading concurrently by multiple readers, we can just swap to an array for overall efficiency since only 1 item is added each time.
| …
=> Optimize assembly/namespace pair creation and updating in XamlSchema

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputProcessorProfiles.cs
Loosely follows #9221, replacing the other part of the `InputLanguageSource.InputLanguageList` with more modern code.
- Instead of marshalling the array members, we just wrap the array in a `ReadOnlySpan<short>`.
- Instead of using `ArrayList`, we preallocate the array as we know the final count.
- The class can be sealed, no reason not to as it has no children.
- I've formatted the file and cleared unused usings for clarity.
| Original |   556.4 ns |    5.70 ns |     5.33 ns | 0.0696 |       1,245 B |        1176 B |
| PR_EDIT  |  443.8 ns |    4.42 ns |     3.69 ns | 0.0563 |         394 B |         944 …
=> Replace ArrayList in InputProcessorProfiles with fixed-size array, reduce allocations

src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Fixes #10846
As explained in the issue above, setting `ThemeMode` to system led to crashes in DatePicker and NavigationWindow control. This was due to the fact that controls' ResourceDictionary was added as individual `MergedDictionaries` and the resolution of `StaticResources` being referenced in these controls was not part of these controls' itself. The current approach combines all the resources of controls, font, staticcolors, variables, and other common resources that were being used by both light and dark mode.
Given the above changes, the primary change of this PR is the update in ThemeGenerator script which includes the generation of newly configured `Fluent.xaml`.
Yes
Local Build pass
A complete testing on the gallery application in light and dark themes (with system theme mode) …
=> Common Fluent.xaml for System ThemeMode

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TabControl.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Fixes #9889 
Fixes the unusally large MinWidth property in TabItem. Due to the large value for the min width, TabControl was less usable. This PR fixes that by removing the MinWidth property and readjusting some other values for TabItem.
Makes TabControl and TabItem more usable
No
Minimal
=> Fixed TabItem MinWidth issue

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
Fixes #10629
Replaces `StackPanel` as `ItemsHost` with `ItemsPresenter` to align the `ComboBox` dropdown menu with rest of the themes and support grouping properly. Noticed this isn't fixed in #10818 either so doing it here.
Without taking this fix, using grouping templates is not feasible.
Not really, this has been the case since grabbing the template from WpfUi.
Local build, testing different grouping scenarios, repro in #10629, confirming it works.
Low.
=> Fix ComboBox popup content to allow grouping in Fluent

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Fixes #10826 
The invalidation style for the Fluent theme was not altered, resulting in the rendering of styles defined by the Aero theme. These changes add an error template for a textbox to align with Fluent design.
Better looking UI
_None_
Validated with a sample application
Low
=> Fix(Fluent): TextBox invalidation style

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Fixes #10470 , #10656 
In this PR I have restyled the ComboBox style and template to make it more similar to WinUI's style, however the styles are slightly different to make it easier in WPF. Here are the list of few major changes in the PR : 
1. Split the control template for ComboBox in two parts : one for normal ComboBox and other for EditableComboBox.
3. Fixed the layout in each of the ComboBox template and matched the height and other parameters to WinUI.
4. Added missing control template triggers to get the correct behavior for different states of controls.
5. Added the correct TextBox style Editable ComboBox and fixed the dropdown button styling.
6. Added the correct resources for ComboBox styles.
- Fixes the chevron icon positioning when ComboBox has custom height. 
- Chevron …
=> Fixed ComboBox style and template

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
Fixes #8678 , #10400 
Since, DataGrid in itself is a very complex control with more than half a dozen subcomponents, hence I have decided to divide the fixing of DataGrid style in parts. In this PR, I have taken a stab at fixing the column header and related components. Next I will try to fix select all and row related components in one go and at last data grid cells and data grid as a whole.
For the complete you can take a look here : [ Restyled DataGrid Control](https://github.com/siagupta0202/wpf/pull/9)
Here are some screenshots of how the column header will look after the changes : 
Customers will get a better looking datagrid, where the interaction with datagrid column headers will have the correct visual feedback.
No
Local app testing.
Minimal
=> Fixed DataGrid Column Header issues

src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/InteropDeviceBitmap.cpp
Fixes #9042
Main PR
WPF applications with D3DImage can crash when a monitor is off or unavailable and IDirect3D9.GetAdapterMonitor returns NULL.
For example on laptops with connected HDMI external display and display setting “Extend”
and control panel “when I close the lid” = “Do nothing”, when closing the lid or on sleep / awake.
WPF applications crash.
This bug exists in existing .NET releases like 4.8.
Take a laptop with connected HDMI external display and set display setting “Extend”
and control panel “when I close the lid” = “Do nothing”, then close the lid and check if a WPF application with D3DImage crashes.
Unclear.
=> Avoid UCEERR_RENDERTHREADFAILURE

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
The "Show Calendar" button for DatePicker control did not have any name set to it, which causes issues for users using Accessibility Features in Windows. 
Customers using Accessibility Features in Windows, like Narrator, etc. will be able to use the control with ease.
No
Local app + Narrator testing
Minimal
=> Fixed AutomationProperties.Name for DatePicker Button

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
This PR reverts a workaround that I had to introduce while fixing the layout of text controls ( DatePicker, TextBox, RichTextBox, PasswordBox, etc ). These all controls use a shared resource TextControlThemeMinHeight, which needed to be changed from 24 to 32. However, in each PR I only fixed a single style, I had to introduce individual resources for these controls at the time.
In this PR, I remove the extra resources and their references are replaced with TextControlThemeMinHeight resource.
Anyone modifying this resource will see the uniform behavior for all text based controls.
N/A
Minimal. Minor issues in content alignment may come up.
=> Removed separate MinHeight resources for text based controls

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ListViewItem.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml, src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml
The TreeView ActiveRectangle is 16. The WinUI Gallery and Windows Settings apps both seem to show ListViews with this size rectangle. The WPF ListView ActiveRectangle height should match up with all of these other ones, currently it looks different from the others.
Inconsistent UI
Nothing really, just changed all places I could see that were defined too tall.
=> ActiveRectangle height in ListView to match TreeView and WinUI

eng/WpfArcadeSdk/Sdk/Sdk.props
The internal service builds of WPF is failing due to c# version 12 being used, and unavailability of certain features like null conditional assignment and others. The change here bumps up the version to make sure non preview release iterations are built successfully.
Low
=> [Release/10.0] Fix internal builds
