dotnet/wpf

src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Xaml/Context/XamlContextStack.cs

The '-1' value of _depth is always overwritten by '0' in constructor.
The default values for _currentFrame and _recycledFrame are null,
so we don't need set them explicitly.

Remove redundant field initialization in XamlContextStack

---

global.json

Adding an Sdk section to global.json. This is needed to ensure that CI servers deterministically use the version of .NET Core 3.0 Sdk specified here to build the projects in the repo.

Adding Sdk section to global.json

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DateTimeValueSerializer.cs

It's a bad practice to compare double values with zero.
A better way to compare TimeSpan with zero is using the Ticks property.

Better TimeSpan comparison with zero

---

README.md

This is the only location that the full name of WPF is written out in the codebase as it currently stands.  The correct name, as it happens, is Windows Presentation Foundation.

Readme WPF name consistency fix

---

src/Microsoft.DotNet.Wpf/src/Directory.Build.Props
src/Microsoft.DotNet.Wpf/src/Localization.targets
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.cs.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.de.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.es.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.fr.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.it.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ja.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ko.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pl.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pt-BR.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ru.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.tr.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hans.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hant.xlf

Generates XLIFF files via a copy of the Arcade localization targets that doesn't require IsShipping to be true.
Fixes #171

Enabling XLIFF generation

---

.gitignore

A `DS_Store` file popped up when I cloned the repo so I'm adding this gitignore to prevent unwanted files sneaking their way in

Add OSX gitignore

---

src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/CriticalExceptions.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SafeSecurityHelper.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/SecurityCriticalDataForSet.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Xaml/Context/XamlContextStack.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Xaml/Context/XamlFrame.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Xaml/Parser/SpecialBracketCharacters.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs
src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs
src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/Replacements/TypeUriConverter.cs
src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/RuntimeIdentifierPropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/TypeConverterHelper.cs
src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/XmlCompatibilityReader.cs
src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/XmlWrappingReader.cs

Certain changes to shared sources proved to be a problem when integrated into our unpublished sources.  This is due to the fact that analyzers do not have a full picture of what is needed based on the fact that the sources are not published.
@AndreyAkinshin I had to revert the changes to shared sources caused by #103.  I should have caught this prior to merging, but I am fixing them up now.  The cleanup done in System.Xaml is perfectly fine as no unpublished mirror exists for those files.  However, the Shared directory still contains files used by PresentationBuildTasks (which multi-targets with 4.7.2) and WindowsBase.  Due to this, we can cause build breaks of various kinds in our unpublished sources.  It's more expedient to revert these for now and wait until all code that requires …

Backing out problematic shared source changes

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/ExceptionStringTable.txt
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/Strings.resx
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.cs.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.de.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.es.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.fr.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.it.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ja.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ko.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pl.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pt-BR.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ru.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.tr.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hans.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hant.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ClrNamespaceUriParser.cs

Unused, so we can remove the parameter and delete the corresponding strings

Remove unused parameter from ClrNamespaceUriParser

---

eng/build.yml

the dotnet-core feed is too contested and causes builds to timeout. thanks @AdamYoblick for this fix!

moving to new feed

---

azure-pipelines.yml
eng/Version.Details.xml
eng/Versions.props
eng/pipeline.yml
global.json
src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj
src/Microsoft.DotNet.Wpf/test/MultiTargeting.props

I've added the darc subscription for the ".NET Core 3 Dev" channel from the CoreFX repo to the WPF (this) repo. This change checks-in the files required by darc to allow Maestro to update these files and get the latest packages that come from the CoreFX build
I've also added other packages that are required for building WPF that come from the prototype branch.
Fixes #248

build against latest core fx packages

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlObjectReader.cs

This addresses #268 by reverting back to the code that was there before the change.

Revert back to not using Linq, which ads unnecessary dll loads

---

eng/pipeline.yml

when I made the change to move to the new jobs.yml arcade templates, I accidently removed the platform specific configurations. this pr adds them back
Fixes #339

adding back platform builds

---

azure-pipelines.yml

Add release/3.0 to triggers #343

Add release/3.0 to list of triggers

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/Strings.resx
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.cs.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.de.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.es.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.fr.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.it.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ja.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ko.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pl.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.pt-BR.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.ru.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.tr.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hans.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/Resources/xlf/Strings.zh-Hant.xlf
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlPullParser.cs

Untranslated strings should not be included in System.Xaml satellite assemblies.  Remove strings from shared Strings.resx, add strings to XamlPullParser, and update XLF files for all languages.

LOC CHECKIN: Strings not intended to be translated should not be included in System.Xaml satellite assemblies

---

eng/Version.Details.xml

Adds a new dependency (not actually used) on Microsoft.NETCore.App and then ties the existing corefx dependencies to that Microsoft.NETCore.App.  This ensures that corefx binaries do not get ahead of a core-setup that has actually ingested those binaries.  This helps our overall coherency push at the end of the release cycle.

Add coherent parent attributes

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializer.cs

Fixes a typo in the class summary documentation and adds punctuation where needed

Fix documentation typo and punctuation

---

eng/WpfArcadeSdk/tools/Packaging.targets
eng/WpfArcadeSdk/tools/Pbt.props
eng/WpfArcadeSdk/tools/Pbt.targets

Adding fallbacks for building WPF projects that use PresentationBuildTasks.dll and Microsoft.WinFX.targets for markup compilation
When PresentationBuildTasks (PBT) moves to [dotnet/wpf](https://github.com/dotnet/wpf) from [dotnet-wpf-int](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int), internal builds will need to consume PBT via a transport package instead of using the local source copy of `Microsoft.WinFX.targets` and local build output of PresentationBuildTasks.dll. 
Since we already produce and MSBuild Sdk containing these files - `Microsoft.NET.Sdk.WindowsDesktop` (which will also move alongwith PBT to dotnet/wpf - they go together) - we will simply leverage this Sdk package as our _transport package_  for internal builds. 
===
This fix also contains an unrealted fixup to …

Fallbacks for building internal WPF projects that use PresentationBuildTasks.dll and Microsoft.WinFX.targets for markup compilation

---

eng/WpfArcadeSdk/tools/Pbt.targets

Required for the internal change that reduces PresentationBuildTasks reflection-only probing targets during build time to the reference list. Duplicate NetCoreReferences are benign.

Default NetCore references for internal markup compilation should include System and TypeConverter

---

Microsoft.Dotnet.Wpf.sln
eng/WpfArcadeSdk/tools/Packaging.targets
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/dotnetcli.host.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/App.xaml
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/App.xaml.cs
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/Company.WpfApplication1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/MainWindow.xaml
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/MainWindow.xaml.cs

This is the Project Template for WPF used by `dotnet new wpf` and _Create New Project_ -> _WPF App (.NET Core)_ in Visual Studio. 
Moving it from our internal repo build and ship from GitHub. We will make modifications to this in a future PR (likely to get this to match the template for .NET Framework).  
/cc @chabiss, @grubioe, @zsd4yr, @ericstj

Project template for WPF

---

eng/Version.Details.xml
eng/Versions.props

CoherentParentDependency attributes should only be applied to child dependencies of a repo.  This was blocking updates

Fix coherency attributes

---

eng/WpfArcadeSdk/Sdk/Sdk.props
eng/WpfArcadeSdk/Sdk/Sdk.targets
eng/WpfArcadeSdk/tools/ShippingProjects.props
eng/WpfArcadeSdk/tools/Signing.props
eng/WpfArcadeSdk/tools/Signing.targets
src/Microsoft.DotNet.Wpf/src/Directory.Build.Props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/Directory.Build.Props
src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj

This is the public half of a two part change. The original fix (adding StrongNameKeyId=Ecma to WPF assembly projects) was insufficient. After help from @nguerrera and more investigation of which PKTs were contained in which NETFX assemblies, @vatsan-madhavan provided a much more comprehensive fix that also fixed other regressions introduced during Arcade onboarding. @vatsan-madhavan's complete fix is included here. 
- WPF assemblies are incompatible with each other in 3.0.0-alpha-27128-4 #208 (fixes issue #208)
- Could not find assembly 'System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' #508 (fixes issue #508)
This internal half of this change will be committed after the darc update containing this change reaches dotnet-wpf-int.  Thanks.

Public key tokens of .NET core WPF assemblies and .NET Framework WPF assemblies need to match

---

eng/Version.Details.xml
eng/Versions.props

* separate out version.props into different property groups by source to ease merging
* alphabetize version.props inside each property group
* alphabetize versions.details.xml by dependency name
* remove source ids
* make all xunit dependencies the same number
@vatsan-madhavan

Some changes to Versions.props and Versions.Details.xml to make them easier to work in 

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props

VB projects, by convention, use Application.xaml for the name of their ApplicationDefinition file. Without this change, we run into the problem described at https://github.com/dotnet/wpf/issues/500. Fixes #550.

Recognize Application.xaml as well as App.xaml

---

eng/WpfArcadeSdk/tools/ShippingProjects.props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.cs.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.de.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.es.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.fr.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.it.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ja.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ko.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.pl.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.pt-BR.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ru.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.tr.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.zh-Hans.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.zh-Hant.xlf

* Add initial xlf files for PresentationBuildTasks
* Bring PresentationBuildTasks translations over from NETFX
* Modify PresentationBuildTasks csproj to enable satellite assembly generation
* Don't exclude PresentationBuildTasks from xlf localization in ShippingProjects.props

LOC CHECKIN | Add PresentationBuildTasks xlf localization

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs

NETFX Regression: No longer can set name property to MarkupExtension in certain places #378.
Move KnownAssemblyInfoRecord initialization out of BamlMapTable's static constructor to its constructor. (Fixes #378)

BamlMapTable should always reinitialize KnownAssemblyInfoRecord

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs

System.Reflection.Assembly.ReflectionOnlyLoad is not supported on .NET core and has been replaced with MetadataLoadContext.  MetadataLoadContext is cleared between markup compile passes, invalidating all System.Relection.Assembly instances loaded by MetadataLoadContext.  
Various markup compilation errors were occuring because of failed property lookups due to comparisons against an invalid System.Reflection.Assembly instance (PresentationFramework) in BamlMapTable.KnownAssemblyInfoRecord.  PresentationFramework is now loaded each time BamlMapTable is created by XamlTypeMapper, per markup compile pass.
This change includes the recommendation from @weltkante's review to update BamlAssemblyInfoRecord on BamlMapTable to be an instance field.

BamlMapTable's KnownAssemblyInfoRecord should be an instance field

---

eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
eng/WpfArcadeSdk/tools/SdkReferences.targets
global.json
src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj

- Update related targets, esp. SdkReferences.targets and related mechanisms used to filter `NetCoreReference`
- Update RuntimeFrameworkReference targets to exclude test projects because they currently depend on WindowsDesktop SDK.

Update targets to adapt to ref-pack based references

---

eng/Version.Details.xml
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets

This is part-2 of setting `RuntimeFrameworkVersion` intentionally. 
For now, tests are opted-out of `RuntimeFrameworkVersion` and `TargetingPackVersion`. Some tests continue to use `Sdk=Microsoft.NET.Sdk.WindowsDesktop `- we need to move them to use `Sdk=Microsoft.NET.Sdk` instead, and opt-them also into using `RuntimeFrameworkVersion`. We will do this after https://github.com/dotnet/arcade/pull/2343 is merged and becomes available generally. 
We are not updating global.json tools.dotnet and sdk.version yet - we'll keep slightly older versions there as well until we make relevant changes to tests.

Set TargetingPackVersion intentionally

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

GenerateTemporaryTargetAssembly creates intermediate files that should be deleted along with the temporary project when compilation is complete.  (Fixes #510)

Remove temporary files created by GenerateTemporaryTargetAssembly compilation

---

eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
eng/WpfArcadeSdk/tools/SdkReferences.targets
eng/WpfArcadeSdk/tools/Wpf.Cpp.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
global.json
src/Microsoft.DotNet.Wpf/test/DRT/DrtXaml/DrtXaml/XamlTestFrameWork/TestFinder.cs

- Fixes build break by changing when `LimitNetCoreAppReferences` runs
- Removes dependence on private C++/CLI tooling in favor of tools that are now present in Dev16.1 P2 builds (that are already on our build servers)
- Add a workaround in tests for a type missing from System.Runtime

Fix build failures (issue #638) and remove private C++ toolset workaround

---

eng/WpfArcadeSdk/tools/SystemResources.props

Due to a change in Arcade in GenerateResxSource.targets, we need to set GenerateResxSource to true so that codegen runs on our EmbeddedResources.  This is blocking some DARC PRs with the latest Arcade changes.
fixes #662

Fix ResX Code Generation

---

eng/WpfArcadeSdk/Sdk/Sdk.props

We were using DebugType=Full for all build configurations.  This can place undo burden on the JIT for Release builds.  In Release, we still want to emit a PDB, but we want as much optimization as possible so we should use pdbonly.
fixes #693

Fix DebugType in Release builds

---

eng/WpfArcadeSdk/tools/Packaging.targets

WPF's internal transport packages currently place RID specific binaries under lib\<RID> folder. 
This change moves them under runtimes\<RID>native\ folder, per spec at [Supporting Multiple .NET Versions](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks). 
When referencing one of these packages from a test, we noticed that the native assemblies were not getting included in `deps.json`, which lead to the identification of this problem. Placing the binaries under the correct location remedies the `deps.json` creation errors.

Fix packaging to place RID specific binaries under runtimes\<rid>\native

---

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Factory.cpp
src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Factory.h

Removing use of GUID struct in initialization of the DWrite factory.  This is a workaround for a JIT bug that marshals incorrect GUID data, causing the cast to fail with E_NOINTERFACE.
fixes #725

Change DWriteForwarder to use __uuidof

---

eng/Version.Details.xml
eng/Versions.props

- Move `Microsoft.Private.Winforms` from `Product` to `Toolset` Dependency
- Add `CoherentParentDependency=Microsoft.NETCore.App` 
- Note: Not adding a `CoherentParentDependency=Microsoft.NETCore.App` for `Microsoft.DotNet.Wpf.DncEng` - this is a cycle from dotnet-wpf-int => dotnet/wpf used for testing purposes only.

Add missing CoherentParentDependency=Microsoft.NETCore.App for Microsoft.Private.Winforms

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

Fixes #773 
As a result of https://github.com/dotnet/corefx/issues/37943, we have a pinned version of System.Memory in PresentationBuildTasks.csproj.
Turns out that System.Memory v4.5.2 has a dependency on S.Runtime.CompilerServices.Unsafe v4.5.2/AssemblyVersion=4.0.4.1. Pinning this also to PresentationBuildTasks.csproj.

Adding a pinned version of S.Runtime.CompilerServices.Unsafe to PresentationBuildTasks.csproj

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs

In the case where Clipboard objects are COM objects, this protects us from a System.InvalidOperationException from the marshaler when calling IDataObject.GetData(Type) due to Type not being marked with the COMVisibleAttribute.
This was already present in WPF on .NET Core 3 before and was accidentally dropped during a .NET Framework sync.
Fixes #735

Wrap COM objects coming out of Clipboard.GetDataObjectInternal.

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.de.xlf

A previous loc check-in translated locked strings, only in DE.   I'm reviewing other loc updates to verify this didn't happen elsewhere.

Revert PresentationFramework to .NET Framework translations for DE

---

src/Microsoft.DotNet.Wpf/src/Common/src/System/AppContextDefaultValues.cs
src/Microsoft.DotNet.Wpf/src/Common/src/System/LocalAppContext.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/BuildTasksAppContextSwitches.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/System/AppContextDefaultValues.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/Directory.Build.Props
src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/AppContextDefaultValues.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/CoreCompatibilityPreferences.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/AppContextDefaultValues.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/Directory.Build.Props
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/AppContextDefaultValues.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/AccessibilitySwitches.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/BaseCompatibilityPreferences.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj

This PR brings up a functioning infrastructure for `AppContext` and `*CompatibilityPreferences` infrastructure. 
- `AppContext` based quirks would be set in `runtimeconfig.template.json`
- I haven't tested to verify whether these support registry. 
- `*CompatibilityPreferences` would continue being set in `App.config`
The new defaults for various quirks are so: 
```JSON
{
"configProperties": {
/*
// BuildTasksAppContextSwitches
"Switch.System.Windows.Markup.DoNotUseSha256ForMarkupCompilerChecksumAlgorithm": false,
// CoreAppContextSwitches
"Switch.System.Windows.DoNotScaleForDpiChanges": false,
"Switch.System.Windows.Media.ImageSourceConverter.OverrideExceptionWithNullReferenceException": false,
"Switch.System.Windows.DoNotUsePresentationDpiCapabilityTier2OrGreater": false, …
```

AppContext and *CompatibilityPreferences infrastructure

---

eng/Version.Details.xml
eng/Versions.props
global.json
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

https://github.com/dotnet/wpf/issues/763
corefx has fixed the underlying bug - removing pinned version of System.Memory. We need to cherry pick this into release/3.0 as well.

Remove pinned version of System.Memory

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GroupItemAutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemsControlAutomationPeer.cs

VS 2017 and 2019 crash when
a. Automation is enabled (e.g. Narrator or Inspect are running)
b. User clicks on the Text Editor\C#\Code Style\Naming page in Tools\Options
(also other similar pages)
This is a regression in 4.8.  The bad pages contain a DataGrid whose cells contain a ComboBox, and whose virtualizing mode is Recycling
Fixes #860

Crash in DataGridItemAutomationPeer

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props

Fixes #866 
Related: [WindowsDesktop reference assembly split](https://github.com/dotnet/cli/issues/10536)
| UseWPF  | UseWindowsForms  | FrameworkReference |
| --- | --- | --- |
| False | False  | *Error* (Will be addressed in #867)  |
| True  | False   | `Microsoft.WindowsDesktop.App.WPF` |
| False | True   | `Microsoft.WindowsDesktop.App.WindowsForms`   |
| True | True    | `Microsoft.WindowsDesktop.App` |

Support `Microsoft.NetCore.App.Wpf` and `Microsoft.NetCore.App.WinForms` profiles in `Microsoft.NET.Sdk.WidnowsDesktop` 

---

src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemCore/PresentationFramework-SystemCore.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemData/PresentationFramework-SystemData.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemDrawing/PresentationFramework-SystemDrawing.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXml/PresentationFramework-SystemXml.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXmlLinq/PresentationFramework-SystemXmlLinq.csproj

Don't generate ref assemblies for WPF extension assemblies

---

src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXmlLinq/SystemXmlLinqExtension.cs

Remove workaround for https://github.com/dotnet/corefx/issues/32641.
Fixes #743

Remove null reference workaround for PresentationFramework-SystemXmlLinq

---

eng/helixpublish.proj
eng/pipeline.yml

fixing helix queues. we can't have a queue that ends with ".Open" for internal builds.
Fixes #889

fix helix target queues

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props

Fixes #255
Traditionally, Visual Studio has supplied these references for .NET Framework based WPF Projects: 
- .NET 3.x:   PresentationCore, PresentationFramework, WindowsBase 
- .NET 4.x:   PresentationCore, PresentationFramework, WindowsBase, System.Xaml 
`Microsoft.NET.WindowsDesktop.SDK` will supply the following references to .NET Framework based 
WPF Projects: 
- .NET 3.x:
- PresentationCore, PresentationFramework, WindowsBase 
- .NET 4.0:   
- PresentationCore, PresentationFramework, WindowsBase, System.Xaml, 
- UIAutomationClient, UIAutomationClientSideProviders, UIAutomationProvider, UIAutomationTypes
- .NET 4.5+:  
- PresentationCore, PresentationFramework, WindowsBase, System.Xaml, 
- UIAutomationClient, UIAutomationClientSideProviders, UIAutomationProvider, UIAutomationTypes …

Ensure that implicit references for .NET Framework projects are appropriate when targeting net3x and net40

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/ComponentModel/PropertyChangedEventManager.cs

port 2 changes from .NET 4.8: crash in PropertyChangeEventManager and GDI handle leak

---

src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AssemblyHelper.cs

`MS.Internal.SystemCoreHelper.IsIDynamicMetaObjectProvider` was returning false for `System.Dynamic.ExpandoObject` causing the PropertyPath resolution to fail. 
On .NET Core, System.Core is now a facade assembly that will never be loaded by the CLR.  **All System.Core types are now forwarded to other assemblies.**  This change updates the required assemblies to those containing the forwarded types (System.Runtime, loaded by default, and System.Linq.Expressions).  AssemblyHelper.cs will now check for System.Linq.Expressions instead of System.Core before loading the extension assembly. 
Fixes #695.  A larger architectural fix for the extension assemblies may happen after RTM.

Bindings to System.Dynamic types fail to resolve

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json

Having mismatched identities means that shim templates cannot be re-used across languages in VS

Ensure the identity name is the same for C# and VB templates

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PropertyPathWorker.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AssemblyHelper.cs

AssemblyHelper keeps track of uncommon assemblies and loads the appropriate extension assembly (e.g. PresentationFramework-SystemData), only when it determines that the assembly has already been loaded by the application (to prevent said assembly from being loaded by WPF all the time). The types used by the extension assemblies have moved to different assemblies, so we need to update the list of uncommon assemblies.
fixes #756

Fixing the list of uncommon assemblies used by AssemblyHelper

---

azure-pipelines.yml
eng/pipeline.yml

Changing `_TestHelixAgentPool` from 19H1 to RS5 seems to bring down execution time in Helix to approx 15 mins. 
https://dev.azure.com/dnceng/public/_build/results?buildId=226613&view=logs 
Looks like the 19H1 pool may have been the reason our builds have been suffering from chronic timeouts, much like the ServerRS5 pool prior to that. 
Fixes #952

Change _TestHelixAgentPool from 19H1 to RS5

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json

This reverts Revert "Ensure the identity name is the same for C# and VB templates(#946)"; commit cf0bed3f96531e505ee0edc2fad6774deb2804bc
Fixes #987
This could regress [AB#902637](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/902637), FYI @jmarolf 
/cc @peterhuene, @livarcocc

Revert "Ensure the identity name is the same for C# and VB templates(#946)" 

---

Documentation/developer-guide.md
eng/copy-wpf.ps1

I'm trying to make our developer-guide and scripts more helpful for people new to the project. In doing so, I realized the `-local` to copy-wpf.ps1 isn't really helpful since the version of the `Microsoft.WindowsDesktop.App` runtime there is fairly old, and coincides with the version of the sdk defined in our global.json. In general, I feel like it's a better practice to use the dotnet-install script to create a dotnet install at a known location, then modify that install as you see fit. The local `.dotnet` folder should really only be used for automated testing and building our product, not modified for manual testing purposes. Since we don't build our tests against the `Microsoft.WindowsDesktop.App` runtime, copying our assemblies anywhere in that location doesn't even make sense …

making copy-wpf more useful

---

eng/WpfArcadeSdk/tools/ApiCompat.targets

Fixes #1023 
Makes the globbing in ResolveRefApiCompatItems more specific so that it always picks exactly one reference assembly.

Fix globbing in ResolveRefApiCompatItems

---

Documentation/developer-guide.md

PropertyGroup tag wasn't closing and FrameworkReference must be inside an ItemGroup

Dev guide fix

---

global.json
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

Fixes the following:
- Fixes #685: Remove **/*.xaml from None
- Fixes #327: Cannot multi-target netcoreap < 3.0 and use WindowsDesktop SDK unconditionally.
- Fixes #746: [Epic] Support WPF and WinForms specific FrameworkReferences a Profiles
- Fixes #867: Show error when neither UseWpf nor UseWindowsForms is set to true
Also cleans up the way in which we import Microsoft.WinFX.targets - UseLegacyPresentationBuildTasks has been broken for some time now and unusable.

Add warnings to Microsoft.NET.Sdk.WindowsDesktop to improve UseWpf/UseWinforms and multi-targeting experience

---

eng/WpfArcadeSdk/tools/Pbt.props
eng/WpfArcadeSdk/tools/Pbt.targets

Define `_WindowsDesktopSdkTargetFrameworkVersionFloor` before `Microsoft.NET.Sdk.WindowsDesktop.targets` is imported
This is needed since we changed the way props are defined in #1027

Define _WindowsDesktopSdkTargetFrameworkVersionFloor before  Microsoft.NET.Sdk.WindowsDesktop.targets is imported

---

azure-pipelines.yml
eng/pipeline.yml

Update how timeout is defined in yml files.
We just noticed that our 120 min timeout is not working correctly, causing backlogs in build and preventing work from progressing. Trying to define this a different way.

Update how timeout is defined in yml files.

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.targets

Updating generated CppCliHelper project to reference and use RID-specific WPF GitHub package.
This is the WpfArcadeSdk piece of the change.  The latest commit in https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/1772?_a=overview contains the internal piece of the fix.

System.Printing does not consume lib assemblies from WPF GitHub package

---

src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/DrtBaseInput.cs

Fixes #920 
(Most of the port already went into wpf-test.  One file appears in both repos, hence needs this PR.)

Port test changes from .NET 4.8

---

azure-pipelines.yml
eng/pipeline.yml

YAML improvements - various. 
Fixes #1121 
Intended to prevent build backlogs due to slow and overlapping builds that were observed to bottleneck PR'son 6/24. 
- Introduces a new AzDo build _public_ pipeline - `dotnet-wpf-citests`
- This is a test-signed pipeline
- CI builds are disabled on this pipeline. Only PR builds are allowed [This is an AzDo pipeline setting]
- ![image](https://user-images.githubusercontent.com/20246435/60376226-490ffb00-99c2-11e9-82c5-60d40cde73fc.png)
- Will create and test _Release_ builds only on _Helix_
- Helix test-runs can be disabled by disabling the pipeline on AzDo
- ![image](https://user-images.githubusercontent.com/20246435/60376206-1d8d1080-99c2-11e9-8731-cfd28ca3344c.png)
- Main AzDo pipeline `dotnet-wpf CI` will no longer run any tests (in _Helix_ or …

yml improvements and helix decoupling to separate pipeline

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridClipboardHelper.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/RtfToXamlLexer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/RtfToXamlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XamlToRtfWriter.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Text/InternalEncoding.cs

Fixes issue #664, #579 
The cause of the crash was that we were missing an encoding (Windows-1252) that is not available by default in core. In order to obtain it, we need to register an encoding provider. I added an internal encoding class to make sure we have this encoding provider registered.
I wrapped the uses of the static Encoding class that pass in parameters such as code page id or some `Encoding` parameters (as opposed to the places where we are just accessing properties)

Fix crash when copying from RichTextBox

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj
src/Microsoft.DotNet.Wpf/src/System.Xaml/ref/System.Xaml-ref.csproj

Related to issue #1183 
`XamlAccessLevel` was moved to System.Windows.Extensions.dll as part of the following PR: https://github.com/dotnet/corefx/pull/38908
Updating System.Xaml.csproj to have this package reference so that when dependencies are updated, the type can be found in its new location

Add PackageReference to account for XamlAccessLevel move

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedPage.cs

Issue #1141 
This test was failing because we were trying to read the scheme of a relative URI (which was throwing an exception). Removed this statement as the check should have been removed as part of the changes that were made here: https://github.com/dotnet/wpf/pull/969/files#diff-d6cd62f214719773a7a26ab93a0235b8
Ran a full DRT test pass on this change for verification.

Fix for Relative Uri's in Flowdocument being broken

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

I'm looking to make the same change in https://github.com/dotnet/sdk/pull/3399 and am blocked by the fact that `Microsoft.NET.Sdk.WindowsDesktop.targets` still uses the property defined there.
This property is defaulted to `false` by MSBuild in https://github.com/microsoft/msbuild/blob/0cd0e92a7243088977d31b56626b56d6116de016/src/Tasks/Microsoft.Common.CurrentVersion.targets#L608
In a design time build it will have a value of `ContinueOnError`.
This is the same behaviour as for `CheckForDuplicateItemsContinueOnError`, just without the redundant duplicate property.
//cc: @nguerrera @davkean

Reuse MSBuild's ContinueOnError property

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets

Fixes #299 
WinFX.targets has a condition for preventing `SplashScreen` build-action from running on .NET Framework 3.0 - which is specified overly broadly.
Rewriting this condition to be more specific fixes the problem and brings the `SplashScreen` build action back to .NET Core 3.0.

Enable SplashScreen build-action for .NET Core 3.0

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/Strings.resx
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.cs.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.de.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.es.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.fr.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.it.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ja.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ko.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.pl.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.pt-BR.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.ru.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.tr.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.zh-Hans.xlf
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.zh-Hant.xlf

**Problem description:**
When you use an Open File Dialog and provide an invalid file OR if you use a Save File Dialog and try to overwrite an existing file the messagebox renders the \r\n as text instead of  a line break.
See issue #977 for a full description. 
Confirmed these updates fix File Dialog messages in English and German.  (Fixes #977.)

Update localized strings that render \r\n as text

---

eng/WpfArcadeSdk/Sdk/Sdk.props

See https://github.com/dotnet/roslyn/issues/37281 for context 
After upgrading to Dev16.2.0 Preview 4 builds, local builds would start failing with CS8614 at [dotnet/wpf:SortDescriptionCollection.cs#L138](https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/ComponentModel/SortDescriptionCollection.cs#L138)
. In order to continue building successfully (until the roslyn/corefx issue is resolved), we need to supply `/p:AdditionalNoWarn:8614` 
Fixes #1289

`AdditionalNoWarn` support for diagnostic builds/debugging/dev-builds

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props

Default to 'true' for unset `EnableDefaultPageItems` and `EnableDefaultApplicationDefinition` in `Microsoft.NET.Sdk.WindowsDesktop.props` to allow MSBuild's `CheckForDuplicateItems` to provide a descriptive duplicate `Page` error.  The check was previously no-op'd in the target due to unset properties.  
Builds with duplicate `Page` items now fail with this error: 
C:\Program Files\dotnet\sdk\3.0.100-preview8-013270\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.NET.Sdk.WindowsDesktop.targets(21,5): error NETSDK1022: Duplicate 'Page' items were included. The .NET SDK includes 'Page' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultPageItems' property to 'false' if you want to explicitly include them …

Default to 'true' for unset properties owned by WPF

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json

fixes [AB#832526](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/832526)

open xaml file first in editor

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/IO/Packaging/PackWebResponse.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/PackageFilter.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/WpfPayload.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XamlToRtfWriter.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/IO/Packaging/PackagePartExtensions.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/IO/Packaging/PackagingUtilities.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Certificate.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlDigitalSignatureProcessor.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/XmlSignatureManifest.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj

Convert non-seekable PackagePart streams to seekable

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/dotnetcli.host.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/Class1.cs
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/Company.ClassLibrary1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/dotnetcli.host.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/Class1.vb
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/Company.ClassLibrary1.vbproj

add wpf class library template

---

src/Microsoft.DotNet.Wpf/src/Common/Graphics/wgx_core_types.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs

Issue #848 
In CoreCLR, the GetHashCode logic for the MILColorF struct (struct with float values) changed and only uses the first field for hash computation (see [this](https://github.com/dotnet/corefx/issues/35613) for more details). Added custom GetHashCode logic to the MILColorF struct in order to have the GetHashCode computation use all four float values for hash computation (as per recommendation from [here](https://github.com/dotnet/corefx/issues/35613#issuecomment-467726210)).
Opened a [complementary PR in the internal repo](https://dnceng.visualstudio.com/internal/_git/dotnet-wpf-int/pullrequest/2196?_a=overview) to update the MILColorF struct definitions there as well.
- Verified that the failing 2D color test is now passing.
- Ran a full DRT test pass and verified that DRTs are …

Updated GetHashCode for MILColorF structs

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/AppContextDefaultValues.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/dataobject.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Ink/XamlClipboardData.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorCopyPaste.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/WpfPayload.cs

Remove support for `UseLegacyDangerousClipboardDeserializationMode` and permanently disallow deserialization of dangerous types.
- Removes support for AppContext flag `UseLegacyDangerousClipboardDeserializationMode`
- Permanently limits clipboard-deserialziation to primitive non-text types only.
Fixes #1132
PS: Creating a WIP PR since this hasn't gone through enough testing yet.

Remove support for `UseLegacyDangerousClipboardDeserializationMode`

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ComboBoxAutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GroupItemAutomationPeer.cs

Fixes #791, #1015 
This pull request contains two changes.
1. Setting ScrollPattern on ComboBox to only be enabled when its dropdown is opened.
2. Ensuring that expander is added to GroupItemDataAutomationPeer if it is the only child. This ensures that the expander is accessible to screen readers.

Fixing MAS Compliance Issues

---

eng/Versions.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.PrivateTools.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.PrivateTools.targets
eng/WpfArcadeSdk/tools/Wpf.Cpp.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
global.json

Partially addresses https://github.com/dotnet/wpf/issues/634 
The new toolset contains several fixes to the backend and the frontend. 
After this fix, this is what we see: 
```
grep -i -E "(\[System\.Runtime\]System\.Runtime\.CompilerServices\.SuppressMergeCheckAttribute)|(\[System\.Runtime\]System\.Runtime\.CompilerServices\.DecoratedNameAttribute)|(\[mscorlib\]System\.Runtime\.CompilerServices\.AssemblyAttributesGoHere)|(\[System\.Runtime\]System\.Runtime\.InteropServices\.Marshal)|(\[System\.Runtime\]System\.Runtime\.CompilerServices\.DecoratedNameAttribute)" DirectWriteForwarder.il   
.custom instance void [System.Runtime]System.Runtime.CompilerServices.SuppressMergeCheckAttribute::.ctor() = ( 01 00 00 00 ) 
.custom instance void …
```

New C++ toolset with fixes for https://github.com/dotnet/wpf/issues/634

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/ILLinkTrim.xml
src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
src/Microsoft.DotNet.Wpf/src/ReachFramework/ILLinkTrim.xml
src/Microsoft.DotNet.Wpf/src/ReachFramework/ReachFramework.csproj

Fixes #1385 
When producing ReadyToRun images, the ILLinker is configured to skip C++/CLI images. See mono/linker#651 and mono/linker#658.
In turn, this results in a failure of dependencies of such assemblies (like System.Diagnostics.Debug.dll, which is required by DirectWriteForwarder.dll) from being identified and included in the ReadyToRun images.
These linker hints tell ILLinker to include certain dependencies, which we know to be required by DirectWriteForwarder and System.Printing respectively.

Linker hints for C++/CLI dependencies 

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.targets

Fixes #1491 
Embeds a new RC file containing a string table for any native DLL or EXE project. This string table will contain **two** pieces of information:
- Commit SHA
- Repo name that built this assembly.

Embed Commit SHA as a string resource in native DLLs

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PropertyPathWorker.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs

Issue number: #1379 
Two-way binding to properties with non-public setters was being allowed because we took on behavior that was caused by a bug in .NET Framework 4.5. Back then, a compatibility flag was introduced due to this 4.5 bug. We no longer want to support this scenario because we want correct behavior in .NET Core and we want the behavior to be on parity with net472/8. So there is no longer need for the compat flag.
Ran a full DRT pass against this change and it was successful.

Removed HandleTwoWayBindingToPropertyWithNonPublicSetter compat flag

---

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/TrueTypeSubsetter/truetype.cpp

When a call to CreateDeltaTTF returns ERR_WOULD_GROW, ComputeSubset should not throw FileFormatException.  Instead, it should copy the original font into the result buffer and return that.
This is so a subsetting attempt that would increase the font size can succeed by using the original font, since that is sufficient to display the file and is more compact than the subsetting algorithm can achieve.
Addresses #1511

XPS: Use original font when subsetting would grow the font

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/DpiUtil/DpiUtil+DpiAwarenessScope.cs

Addresses #1198. 
--
When a caller passes in `dpiAwarenessContextValue==Invalid`, `new DpiAwarenessContextHandle(dpiAwarenssContextValue)` throws `KeyNotFoundException`.
This happens because we do not have a pre-created pseudo-_HANDLE_  corresponding to `Invalid` in our internal map of pseudo-handles in `DpiAwarenessContextHandle.WellKnownContextValues`. Such a pseudo-handle cannot be created either.
When `dpiAwarenessContextValue=Invalid` is passed, the correct behavior is to treat it as a no-op and simply `return`. The corresponding `Dispose()` will also run benignly and the caller will get the correct behavior - which is that no changes will be made to the thread-state.

Fix for #1198 - fixes potential crashes in high-DPI applications

---

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/TrueTypeSubsetter/TtfDelta/ttfdelta.cpp

Addresses #1554 
During execution of CreateTTFDeltaEx, the call-chain may re-allocate and move *ppuchDestBuffer.  If this happens and an error condition occurs, we will return the buffer that realloc de-allocated.  Callers may then double-free *ppuchDestBuffer.
To fix this, set *ppuchDestBuffer to NULL after it is stored in OutputBufferInfo.puchBuffer.  After this change, the non-error return will set *ppuchDestBuffer to OutputBufferInfo.puchBuffer as always, but the error case will de-allocate OutputBufferInfo.puchBuffer (as was intended) and return NULL in *ppuchDestBuffer.  Callers then cannot double-free the buffer.

Fix double free in calls to CreateTTFDelta(Ex).

---

eng/WpfArcadeSdk/tools/ApiCompat.props
eng/WpfArcadeSdk/tools/ShippingProjects.props

Helps with addressing #1423 - adding back PresentationUI ref-assembly.
Adding PUI to RefAssembly list in props.

Adding PresentationUI to RefAssembly list in build-props.

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Selector.cs

Addresses #1541 
Selector should not change its selection properties, when reacting to being disconnected.

WPF controls in a RowVirtualized DataGrid control lose their value after scrolling

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props

- Addresses #1567
- Completes work started in https://github.com/dotnet/sdk/issues/3438
- Removes unsupported TFM's from SupportedTargetFramework.

 Remove unsupported TFM's from SupportedTargetFramework.

---

src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/TestServices.csproj

There was a conflict with https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/commit/3837b2d11c6d9bf2fc7af85e6d06cd31b0a332aa/?refName=refs%2Fheads%2Fmaster
And since GitHub got the update to the `Microsoft.DotNet.Wpf.DncEng` package that contained the `PresentationUI` ref assembly in it, we now get an error. TestServices doesn't need to reference the `DncEng` package, now that all managed assemblies are in dotnet/wpf

remove dnceng ref from TestServices

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/MatrixCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/OrthographicCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/PerspectiveCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/Key.cs

Fixes policheck bugs assigned to us via the SDL build step. There were a lot more issues identified, but only these 5 issues were actually relevant and worth fixing. The other issues aren't actually offensive or used in the incorrect context.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969303/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969349/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969362/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969298/
Potentially offensive terms
No
None. Only affects comments
Fixes https://github.com/dotnet/wpf/issues/1696

Fix issues flagged by Policheck

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

We've observed some tooling related issues filed in the repo that take some additional time to get routed to the right Visual Studio teams. By suggesting developers to file issues on VS directly (for tools related issues), hopefully we can expedite triage and ultimately fixes.

Updating issue and feature request templates

---

eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets

Fixes #1711 
- PresentationCore was losing its auto-generated manifest during the ILDASM/ILASM round-tripping. This is fixed easily by including the `.res` file in ILASM task. 
- For C++ binaries, a new version resource is added and included in builds. 
This change needs to be merged into dotnet/wpf, and then flowed into dotnet-wpf-int, in order to fix WpfGfx, PenImc, and PresentationNative. (See [dotnet-wpf-int PR](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/2801?_a=overview))
/cc @rladuca , @fabiant3 , @ryalanms , @leculver

Adds missing Version resource to C++ binaries, and fixes PresentationCore.dll's missing Version resource

---

eng/WpfArcadeSdk/tools/Pbt.targets
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

Addresses https://github.com/dotnet/wpf/issues/1651 - Invalid comparison in MSBuild's ignore-conditions mode in outer build of multitargeted project
This change ensures that the WindowsDesktop SDK never deals with undefined numeric values related to TFM.
This solution leverages the fact that `Items` are evaluated after `Properties` by MSBuild. See [Comparing properties and items](https://docs.microsoft.com/en-us/visualstudio/msbuild/comparing-properties-and-items?view=vs-2019)
`_TargetFrameworkVersionValue` - a new Property which is defined for exclusive use within the WindowsDesktop SDK, and which is intended to act as a proxy for `_TargetFrameworkVersionWithoutV` - is defined in `Microsoft.NET.Sdk.WindowsDesktop.targets` _after_ `TargetFrameworkVersionWithoutV` is guaranteed to be …

Fixes problems in WindowsDesktop SDK due to _TargetFrameworkVersionWithoutV being undefined sometimes

---

eng/Versions.props
global.json

Addresses #634 
These updated C++ tools address the last of dangling type-refs in DirectWriteForwarder and System.Printing.

Update private C++ tools version to 0.0.0.8

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj

Fixes #1734 
I'm attaching NuPkg's that is representative of what will be produced henceforth in release/3.0 branch for WPF project templates. 
After installing this project template, this is what I see: 
```
λ dotnet new --install Microsoft.DotNet.Wpf.ProjectTemplates::3.0.0-dev --nuget-source %cd%
Restore completed in 191.09 ms for C:\Users\srivatsm\.templateengine\dotnetcli\v5.0.100-alpha1-013704\scratch\restore.csproj.
Templates                                         Short Name               Language          Tags
---------------------------------------------------------------------------------------------------------------------------------- Console Application                               console                  [C#], F#, VB      Common/Console
Class library …
```

Exclude VB Templates from packaging

---

eng/Versions.props
global.json

Addresses #634
These updated C++ tools address the last of dangling type-refs in DirectWriteForwarder and System.Printing.

Update private C++ tools version to 0.0.0.8 (release/3.0)

---

eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets

Addresses #1549 
In the `ReconstituteDll` target, we call ILAsm to merge a module constructor into the assembly we previously disassembled.  We need to enable JIT optimizations here so that we get an appropriate `DebuggableAttribute` on the assembly and don't cause perf problems.
@vatsan-madhavan who helped debug and find this fix.

Fix DebuggableAttribute in InjectModuleInitializer post-build targets

---

eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
global.json

Updates Intellisense XML data from a latest build from https://ops.microsoft.com/#/sites/Docs/docsets/dotnet-api-docs?tabName=builds. 
Intellisense data for `WindowsBase.dll` was not being generated correctly until recently. `WindowsBase.dll` in `Microsoft.NetCore.App` was _hiding_ `WindowsBase.dll` in `Microsoft.WindowsDesktop.App`. 
This problem was recently fixed in `dotnet/dotnet-api-docs`, and this PR incorporates updated intellisense XML's generated from a recent build from `dotnet/dotnet-api-docs` repo. 
Intellisense XML's for API's exposed through WindowsBase.dll will now be available through the SDK.
No
Very low.
Medium - doesn't affect WPF directly, but affects the overall IDE experience.
None.
Related: https://github.com/dotnet/dotnet-api-docs/issues/2602
Fixes: …

Update Intellisense XML data 

---

eng/Versions.props

- Rebrand release/3.0 to rc2
- There is a twin of this PR for dotnet-wpf-int at https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/2930?_a=overview
Part of #1777

Rebrand release/3.0 to rc2

---

eng/Version.Details.xml
eng/Versions.props
eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
eng/WpfArcadeSdk/tools/Pbt.targets
eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
global.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/MatrixCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/OrthographicCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/PerspectiveCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/Key.cs

- Merge release/3.0 into release/3.0-preview9
- There is a twin of this PR for dotnet-wpf-int at https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/2929?_a=overview
Note: Do not squash when completing this PR 
Part of #1777

Merge release/3.0 into release/3.0-preview9

---

eng/Version.Details.xml
eng/Versions.props
eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
global.json

Merging missing commits from release/3.0 -> release/3.1
dotnet-wpf-int PR: https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/2935?_a=overview
Merging changes from release/3.0 that were not ported onto release/3.1 branch. 
Regressions will be introduced in 3.1 preview if the branches are not kept in sync
Low
High
None

Merging missing commits from release/3.0 -> release/3.1

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

Addresses #1758 
Fixing removal of None from Page under certain conditions (EnableDefaultApplicationDefinition or EnableDefaultPageItems is false).
Further adding a fix to ensure this doesn't result in ApplicationDefinition being included in Page as well when EnableDefaultApplicationDefinition is false.
@nguerrera Can you take a look at this as well?  Thanks!

Fixing removal of None from Page under certain conditions

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

Addresses #1758 
* Fixing removal of None from Page under certain conditions (EnableDefaultApplicationDefinition or EnableDefaultPageItems is false).
Further adding a fix to ensure this doesn't result in ApplicationDefinition being included in Page as well when EnableDefaultApplicationDefinition is false.
* Fixing removal of ApplicationDefinition from Page to be unconditional.
* Removing extraneous ApplicationDefinition
* Clarifying comments

Fixing removal of None from Page under certain conditions (#1790)

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets

Fixes https://github.com/dotnet/project-system/issues/2488
In SDK-style projects the project system will combine design time builds together to improve performance, but depending on timing, this can cause issues. If something like the designer asks for output groups, then the build for that could be combined with the build that produces the intellisense file, but getting output groups sets BuildingProject to true.
This change works around the issue by allowing the intellisense file to generate even if `BuildingProject` is true, as long we're still doing a design time build.

Ensure that markup compilation is run for all design time builds

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemParameters.cs

Ask Mode Template:  
Description 
TextBox insertion caret fails to render when on a lower DPI monitor than primary when per-monitor awareness is enabled. 
Customer Impact 
VS features that rely on Text Caret position (search controls, commit messages, Editor, etc) are unable to easily tell where their focus is when using these features if PMA support is enabled and the text box is rendered off the primary display. 
Regression 
No.   (Port of .NET 4.8 servicing fix)
Risk 
Low 
Fixes #1774 
WPF TextBox insertion caret does not render when moved to lower DPI monitor in a PMAv2 process.

WPF TextBox insertion caret does not render when moved to lower DPI monitor in a PMAv2 process.

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.sln

This was done to align with the solution files in the `PresentationBuildTasks` and `WindowsBase` directories.

Move System.Xaml.sln into System.Xaml directory

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/README.md
src/Microsoft.DotNet.Wpf/src/WindowsBase/README.md

There is no longer any need to warn users about modifying the code in these directories, as it has long since been open-sourced. I have kept the warning file in the Shared directory for now, as code in the remaining native projects may well reference that code.

Remove outdated README files

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemParameters.cs

Description
TextBox insertion caret fails to render when on a lower DPI monitor than primary when per-monitor awareness is enabled.
Customer Impact
VS features that rely on Text Caret position (search controls, commit messages, Editor, etc) are unable to easily tell where their focus is when using these features if PMA support is enabled and the text box is rendered off the primary display.
Regression
No. (Port of .NET 4.8 servicing fix)
Risk
Low
Fixes #1774
WPF TextBox insertion caret does not render when moved to lower DPI monitor in a PMAv2 process.

WPF TextBox insertion caret does not render when moved to lower DPI monitor in a PMAv2 process

---

eng/Versions.props
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj

In preparation for 3.0.1, 
•	Versions go to the next patch release to 3.0.1
•	Prerelease label goes to servicing
Fixes https://github.com/dotnet/wpf/issues/1952

Update branding for 3.0.1 servicing and turn off stable builds

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

Actually, the correct word is `ReferencePath`.
```xml
<ReferencePath Include="xxx" />
```

Fix a incorrect spelled word.

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj

Fixes #1957 
Mark the following packages with `<IsShipping>false</IsShipping>`
- Microsoft.NET.Sdk.WindowsDesktop
- Microsoft.DotNet.Wpf.ProjectTemplates
These are transport packages and ship exclusively via the SDK. Importantly, these should not be marked for publishing to NuGet.

Mark ProjectTemplates and Microsoft.NET.Sdk.WindowsDesktop as NonShipping

---

eng/copy-wpf.ps1

More command-line messages are shown into the prompt window when the WPF file copy procedure is used. It has been modified the source directory of the binary files from 3.0 to 5.0.
Fixes #1883

Fix for issue 1883

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/AssemblyInfo.cs
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/AssemblyInfo.vb

Fixes #1699, #1966 
Adding `generic.xaml` to a .NET Core application doesn't work out of the box because the default application template doesn't include `ThemeInfoAttribute` the way it used to in .NET Framework.
This can create subtle problems like https://github.com/dotnet/wpf/issues/1966
This change adds back `ThemeInfoAttribute` that was inadvertently left out of the .NET Core application templates.
`generic.xaml` is used to supply default styles, often for custom controls etc. For it to function so, the application must have the `ThemeInfoAttribute` set. This was always the case in .NET Framework given the fact that WPF's application template set this attribute by default. 
In .NET core, we inadvertently dropped this attribute from the application project-templates (they are still …

Add `ThemeInfoAttribute` to application project templates

---

eng/WpfArcadeSdk/tools/Pbt.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

The PresentationBuildTasks.dll built out of the .NET Core codebase is not being used for msbuild based builds (i.e., when `$(MSBuildRuntimeType)==Full`) of WPF projects that use WindowsDesktop SDK. Instead, the PresentationBuildTasks.dll from GAC, i.e., the DLL that shipped with .NET Framework, is being used for builds instead.
This is because the *first* occurance of an `UsingTask` element that applies to a `TaskName` will always be used - it can not be overridden by subsequent `UsingTask` entries (this is unlike `Property` and `Item` behavior). See note in https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/usingtask-element-msbuild.md immediate after the **Syntax** section (Note: The msbuild team added this note after identifying this behavior as part of …

Use correct PresentationBuildTasks.dll for VS and MSBuild builds

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero/themes/Aero.NormalColor.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Aero2/Themes/Aero2.NormalColor.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.AeroLite/Themes/AeroLite.NormalColor.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Classic/Themes/Classic.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.HomeStead.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.Metallic.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Luna/Themes/Luna.NormalColor.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Royale/Themes/Royale.NormalColor.xaml
src/Microsoft.DotNet.Wpf/src/Themes/XAML/Button.xaml

In non-high contrast themes, when you check a ToggleButton and navigate to another control, we display the checked status by highlighting the button with a lighter shade of the selection color.
We don't follow this behavior in high contrast themes. The text is slightly-depressed upon checking but that is not visually apparent and would definitely not be to a visually impaired person.
In the image above, the 'S', 'C' and 'I' buttons are checked. However, it's barely noticeable that 'S' and 'C' are checked. The checked status of the 'I' button is also not noticeable when it receives focus.
The fix here is to check for a toggle button to be checked when in a high-contrast theme, we then add a border around the button. When a checked button also has keyboard focus, we add a border in the …

Adding border to ToggleButton when checked in high-contrast themes

---

src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsDocument.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsManager.cs

Related to #1985
3.1 PR: https://github.com/dotnet/wpf/pull/2081
In .NET Core 3.0 System.IO.Compression's ZipArchive does not support multiple ZipArchiveEntries to be open concurrently when using FileAccess.Write. This is a requirement of the XPS serialization stack in WPF. As such, we need to create XPS documents as FileAccess.ReadWrite in order to allow this behavior.
NOTE: These sort of changes have been used as a workaround in different, but related cases pre-GA of .NET Core 3 and have worked well.  Codifying them in the product itself helps move developers forward and gives some time to consider a re-design of the XPS serialization stack.
XPS creation when a customer chooses FileAccess.Write will get an exception from:
https://github.com/dotnet/corefx/blob/861259bf87d8e4ee2c4f8dab31b7 …

Change XPS document creation to use FileAccess.ReadWrite instead of FileAccess.Write.

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/MenuItemAutomationPeer.cs

Screen readers were reading incorrect values of the number of menu items and their position since we were counting separators as MenuItems in the automation tree. 
I filtered for separators in the current MenuItems to fix the SizeofSet count.
I filtered for separators again for PositionInSet but added a short-circuit to break when you're at the element whose position you're trying to find. This short-circuit was added to not remove separators below the relevant MenuItem from the PositionInSet count.
Fixes #1467

Removing separators from SizeOfSet and PositionInSet counts

---

eng/WpfArcadeSdk/tools/Pbt.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

Port of https://github.com/dotnet/wpf/pull/1999
Fixes #1998 
The PresentationBuildTasks.dll built out of the .NET Core codebase is not being used for msbuild based builds (i.e., when `$(MSBuildRuntimeType)==Full`) of WPF projects that use WindowsDesktop SDK. Instead, the PresentationBuildTasks.dll from GAC, i.e., the DLL that shipped with .NET Framework, is being used for builds instead.
This is because the *first* occurance of an `UsingTask` element that applies to a `TaskName` will always be used - it can not be overridden by subsequent `UsingTask` entries (this is unlike `Property` and `Item` behavior). See note in https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/usingtask-element-msbuild.md immediate after the **Syntax** section (Note: The msbuild team added …

[release/3.1] Use correct PresentationBuildTasks.dll for VS and MSBuild builds

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs

Addresses #2088 
As part of a previous fix (that shipped originally as part of .NET 4.8 in), a change was made to `Popup` that involved the destruction and recreation of the underlying `HWND`. This was done to ensure that the `HWND` was always created with the correct monitor (~=DPI) affinity.
In order to acheive this, `DestroyWindow()` and `BuildWindow()` - private methods in `Popup` - were used.
We are finding that `DestroyWindow()` has side-effects that can lead to incorrect behavior. The incorrect beahvior works as follows:
- The call into `Popup.CreateWindow` is usually a consequence `Popup.IsOpenChanged` (`false -> true`)
- Within `Popup.CreateWindow`, `DestroyWindow()` is called (when high-dpi mode is detected).
- `DestroyWindow()` destroys the underlying `HWND`, releases the …

Context Menus are sometimes not shown in High-DPI applications

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs

Addresses #2089 
When an `HwndHost `receives `SourceChanged `event, it goes through `BuildOrReparentWindow`. When the hosted window is invisible, it is usually reparented under a temporary windows maintained by WPF in the `SystemResources `class, until later on the window can be rebuilt and parented back to a valid parent.
There is a latent bug in this logic where in `NULL ` `HWND's `are attempted to be parented to `SystemResources `managed temporary windows. This bug goes back quite a while (.NET 4.5 likely). WPF seems to ignore the return value from `kernel32!SetParent` and not deal with this failure. This has not been a crashing failure until now.
Starting .NET 4.8, there have been some changes to this codepath that has resulted in the current bug becoming a crash. In addition to …

Prevent NULL HWND's from being parented under SystemResources listener windows

---

eng/Version.Details.xml
eng/Versions.props
eng/WpfArcadeSdk/tools/Pbt.props
global.json

Fixes #2114 
There is a matching PR for [dotnet-wpf-int#3879](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/3879?_a=overview) that is needed along-with this change. 
This PR updates C++ tools used by WPF to VS 16.3 Preview 4 bits. 
From https://github.com/dotnet/wpf/pull/2105, we now know that C++ toolset containing libs that were built targeting 3.0 could not be used to build against 3.1 libs. 
https://github.com/dotnet/wpf/pull/2105#issuecomment-545746253
> This was fixed in 16.4P3. It's caused by a mismatch between targeting 3.1 and using libs built against 3.0. Updating the tools should fix it and you should no longer need the private tools. 
>
```
##[error]msvcurt_netcore.lib(msilexit.obj)(0,0): error LNK2022: metadata operation failed (80131195) : Custom …
```

Update C++ Tools to VS16.3 Preview 4 

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs

Addresses #2088 
.NET 5 PR: #2097 
As part of a previous fix (that shipped originally as part of .NET 4.8 in), a change was made to `Popup` that involved the destruction and recreation of the underlying `HWND`. This was done to ensure that the `HWND` was always created with the correct monitor (~=DPI) affinity.
This previous fix depended upon a private helper-method (`Popup.DestroyWindow`) that had side-effects that were not accounted for in the original fix. One of the side effects is that the `ContextMenu` is not sown consistently. 
The solution modifies (refactors) the private method to extract the useful portion and uses it to improve the previous fix. 
This is a forward-port from from .NET 4.8. This was reported by a customer, and has also been discovered by Visual Studio internally. …

[release/3.1] Context Menus are sometimes not shown in High-DPI applications

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/HitTestWithGeometryDrawingContextWalker.cs

On behalf of @Simon-IT :
This is related to my issue 642. In the hit testing by geometry algotithm, the order in which the transformations are crosses is wrong. In the issue 642 there is a project to test in very simple manner the problem.
3.1 port related to https://github.com/dotnet/wpf/pull/1761

[Release/3.1] Hit testing by geometry fails if more than one matrix trasformation is applied to a geometry.

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs

Addresses #2089 
.NET 5 PR: #2100 
When `HwndHost` hosted `HWND`'s need to be "parked" while the `HwndHost` is not being actively shown, WPF will reparent such `HWND`'s under temporary message-only windows maintained inside the `SystemResources` class. 
There is a bug that causes null `HWND`'s to be parented under such message-only windows. When this happens in High-DPI applications that use mixed-mode DPI capabilities introduced by WPF in .NET 4.8 (parent and child windows with different `DPI_AWARENESS_CONTEXT `values),  a crash ensues. 
This is a fix for a crash affecting several applications including Visual Studio, and Azure Information Protection Add-in for Office 
This was fixed recently in .NET 4.8, and is being forwarded ported to .NET Core for consistency. 
Not a regression in …

[release/3.1] Prevent NULL HWND's from being parented under SystemResources listener windows 

---

eng/WpfArcadeSdk/Sdk/Sdk.props
global.json

We've been seeing build failures due to a recent update from Arcade (https://github.com/dotnet/arcade/issues/4235) because we are not using a high enough version of .NET in our builds.
Therefore, bumping the version to ensure the publishing step is not using incorrect versions of NuGet.

Increase .NET version to ensure we are using higher versions of NuGet

---

eng/Version.Details.xml
eng/Versions.props
src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/System/Windows/Integration/ElementHost.cs

Fixes #2169 
This is a fixup to WPF to adapt to legacy api removal in WinForms (see https://github.com/dotnet/winforms/pull/2157). 
Low - minor changes to ElementHost. 
Doesn't seem like very much of an impact from WPF directly. Indirect impact from WinForms changes are off-topic here. 
None - this builds. 
Related: We need this to get https://github.com/dotnet/wpf/pull/2161 going. 
/cc @RussKie

Fixup to WPF to adapt to removal of legacy API's from WinForms

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.targets

Since 16.0, MSBuild automatically prepends the most recently modified import to this property, so there's no need to ensure all imports do this themselves. In fact, doing so actively harms performance as this property's value becomes very large and processing it is expensive.
I assume this SDK does not need to support VS versions earlier than 16.0.

Remove modification of MSBuildAllProjects property

---

eng/pipeline.yml

Fixes #2201 
Ensures PR builds can run from internal code-mirror.

Fixup pipelines for internal PR's to work

---

eng/WpfArcadeSdk/tools/SdkReferences.targets

Porting changes over from Release/3.1 into the DARC flow for Release/3.0.
Cherry-picked commits:
https://github.com/dotnet/wpf/commit/e1d79c0e7c593ccbf9c700d830fbb5d9f2fcc43b
MarkupCompilationPass1 getting too large a list of references which was causing a conflict between WindowsBase (the facade in NetCoreApp) and WindowsBase (the product assembly).
https://github.com/dotnet/wpf/commit/7f91d7c79eaddf12b5528a39e0f08e6f22967ad4
NuGet changes here are creating errors in our packaging.

Include "ResolveTargetingPackAssets" in AfterTargets; Remove unused Targets

---

NuGet.config

The dotnet-tools feed is being moved to dotnet-eng so that dotnet-tools can be used for actual tools.
https://github.com/dotnet/arcade/issues/4197
Also remove some feeds that I don't think are necessary any longer.

Add dotnet-eng and remove some other feeds

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs

Fixes #2239 
`s/_hwnd.Handle/Handle` in a few places, notably in in a check in `BuildOrReparentWindow`
--
The key change is in `BuildOrReparentWindow `where an additional check for  `IsWindow()` is desirable; without this check, non-`NULL` yet invalid `HWND`'s are able to make their way into the "reparent under a `SystemResources` managed message-only `HWND`" logic, which in turn tries to query other characteristics of the (invalid) `HWND`. 
One of these steps eventually fails, and WPF decides that the failure is sufficiently bad and crashes (this happens in `MS.Internal.DpiUtil.HwndDpiInfo.NearestMonitorInfoFromWindow(IntPtr hwnd)`).
Also changing `_hwnd.Handle` to `Handle` in a few other places where additional check for `HWND` validity seems valuable.
/cc @teh173 …

Improve `HWND` validity testing in `HwndHost` 

---

eng/WpfArcadeSdk/tools/Packaging.targets
eng/WpfArcadeSdk/tools/SdkReferences.targets
eng/WpfArcadeSdk/tools/ShippingProjects.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
eng/WpfArcadeSdk/tools/WpfProjectReference.targets

Today, the assemblies built out of [dotnet/wpf](https://github.com/dotnet/wpf) are packaged into a transport NuGet package (`Microsoft.DotNet.Wpf.GitHub`). This package is consumed by an internal repo that builds native DLL's, and produces another transport package `Microsoft.DotNet.Wpf.DncEng`. 
Both of these transport packages are in eventually consumed by [dotnet/windowsdesktop](https://github.com/dotnet/windowsdesktop) (alongwith a transport package from WinForms) to build the WindowsDesktop shared runtime. 
These updates to build targets will enable us to build a single transport package - `Microsoft.DotNet.Wpf.GitHub` - to flow into `dotnet/windowsdesktop`. This repo will use `Microsoft.DotNet.Wpf.DncEng` as an input (which contains native DLL's) and will produce a single transport …

Build orchestration updates

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/IncrementalCompileAnalyzer.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/shared.cs

Ensure that we don't include XAML files that no longer exist on disk as part of the LocalMarkupPages when we load from the compiler cache.
This allows SDK style projects to react to files deleted from the glob between two incremental builds.
Fixes #2287

Handle incremental build when XAML files are removed from the Page glob

---

eng/WpfArcadeSdk/tools/Pbt.props

Import Microsoft.WinFx.props only when it is present

Import Microsoft.WinFx.props only when it is present

---

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Common.h

Copy (from .NET 4.6.1 SDK) the one HR definition used by DirectWriteForwarder.
Fixes #2297

Remove dependency on CorError.h

---

Documentation/developer-guide.md

Document dependency on .NET SDK.  
The build of PresentationCore uses IL tools.  ILdasm.exe is obtained from a .NET SDK, either 4.6.1 or 4.6.2 (but not higher).
This is a mitigation for #2298.

Add .NET SDK to developer guide

---

Documentation/developer-guide.md
eng/Versions.props
eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets
eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs
global.json

Fixes #2298
Use a set of matched, private IL tools in order to inject a module constructor into `PresentationCore`.  These are copied binaries from a .NET Framework 4.7.2 installation and SDK.
Also fixing some issues with utilizing `ILAsm` outside of the installed Framework directory and some bugs that went unnoticed in our injection targets.

Remove dependency on .NET SDK installs for IL Tools

---

eng/WpfArcadeSdk/tools/ShippingProjects.props

Fixes #2363 
Ensure the WindowsDesktopSdk RepoLocation overrides all others.  This is key to packaging PresentationBuildTasks and associated files.

Ensure the WindowsDesktopSdk RepoLocation overrides all others.

---

src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationFramework/PresentationFramework.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/StickyNote/StickyNoteContentControl.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextRange.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsDocument.cs

This PR addresses issues #2424, #2425

Microsoft Security Advisory CVE-2020-0606 : .NET Core Remote Code Execution Vulnerability (5.0 PR)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Ask Mode Template:  
Description 
Certain scrolling operations cause TreeView to hang.  There are two causes:
1. Floating-point catastrophic cancellation while detecting an element’s position within the viewport
2. Inappropriate “offset replacement” when filling the “before” cache.   (Internal concepts, I’d need a whiteboard to explain fully.)
Customer Impact 
Hang. 
Regression 
No.   (Port of servicing fix for .NET 4.7 - 4.8)
Risk 
Low 
Fixes #1962
WPF TreeView, virtualization, scroll, freeze

TreeView scroll hang

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DefinitionBase.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Grid.cs

Ask Mode Template:  
Description 
After every layout pass, a SharedSizeGroup re-evaluates its  shared size and updates the state of its constituent ColumnDefinitions.  The  goal is to mark the "long-pole" definitions (the largest ones in the group), and  to identify Grids that need to be remeasured.  The logic for this is flawed in  several ways;  both goals can fail in either direction (false positive or false  negative).   These flaws usually result in redundant layout work - the Grids get  measured twice, with the mistakes in the second pass cancelling those in in the  first - but correct layout results.  But in some cases they lead to an infinite  cycle of re-layout;  the app hangs.   In the customer's scenario this happens  when  
a. the Grids are within the scope of a ScrollViewer …

SharedSizeGroup loop

---

src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonHelper.cs
src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonMenuButton.cs

Ask Mode Template:  
Description 
An app that programmatically disables a RibbonMenuButton and replaces its  menu items with new ones can cause a focus war leading to infinite recursion and  StackOverflow.  This can happen if the user presses the toggle button (which  opens the menu dropdown) and drags the mouse over the dropdown, and the  programmatic disable/replace occurs before the user releases the mouse  button.
Customer Impact 
Crash. 
Regression 
No.   (Port of servicing fix for .NET 4.7 - 4.8)
Risk 
Low 
Fixes #2220
StackOverflow due to focus war in RibbonMenuButton

Ribbon focus war

---

eng/Versions.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.props
global.json

Fixes #2259, #2296
Matching internal PR at https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/4692?_a=overview
- The C++ Tools prior VS 2019 16.4 has a bug in detecting AVX-512 support (512-bit extensions to 256-bit Advanced Vector Extensions SIMD instructions for x86 ISA). It reports support to be present incorrectly on some Xeon processors when the support is not available. 
- It results in a `STATUS_ILLEGAL_INSTRUCTION` crash when running x86 WPF apps on certain Xeon processors. 
- The fix is to simply recompile WPF using a newer 16.4 compiler tools. 
- Switch to use production C++ tools that are ambient to the build machine, instead of privatized C++ tools 
- Dev/local builds would rely on tools from Dev16.4+ 
- Update tools.dotnet in global.json to 3.1.100
This …

Fix STATUS_ILLEGAL_INSTRUCTION crash in win-x86 on some Xeon CPU's

---

eng/Versions.props

This matches what's in release/3.0: https://github.com/dotnet/wpf/blob/release/3.0/eng/Versions.props#L6
@vatsan-madhavan @mmitche PTAL

Update branding from '4.8.1-rtm' to '4.8.1-servicing'

---

eng/Versions.props
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj

Centralize VersionPrefix information in Version.props
Verified using local build using shipping-versions that this works as intended. 
```
build -pack /p:DotNetUseShippingVersions=true
C:\src\repos\wpf (refactor-versionprefix-rel30 -> origin)
λ dir /s artifacts\packages\Debug\NonShipping\ /b
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Arcade.Wpf.Sdk.4.8.0-dev.20065.1.nupkg
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Wpf.GitHub.4.8.0-dev.20065.1.nupkg
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Wpf.ProjectTemplates.3.0.3-dev.20065.1.nupkg
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\Microsoft.NET.Sdk.WindowsDesktop.3.0.3-dev.20065.1.nupkg
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\runtime.wi …
```

[release/3.0] Centralize VersionPrefix information in Version.props

---

eng/Versions.props
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj

Centralize VersionPrefix information in Version.props
Verified using local build using shipping-versions that this works as intended.
```
build -ci -pack /p:DotNetUseShippingVersions=true
> dir /s artifacts\packages\Debug\NonShipping\ /b 
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Arcade.Wpf.Sdk.4.8.1-ci.20065.1.nupkg
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Wpf.GitHub.4.8.1-ci.20065.1.nupkg
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\Microsoft.DotNet.Wpf.ProjectTemplates.3.1.2-ci.20065.1.nupkg
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\Microsoft.NET.Sdk.WindowsDesktop.3.1.2-ci.20065.1.nupkg
C:\src\repos\wpf\artifacts\packages\Debug\NonShipping\runtime.win-x86.Microsoft.DotNet.Wpf.GitHub.4.8.1-ci.20065.1.nupkg …
```

[release/3.1] Centralize VersionPrefix information in Version.props

---

src/Microsoft.DotNet.Wpf/src/PresentationUI/PresentationUI.csproj
src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/WindowsFormsIntegration.csproj
src/Microsoft.DotNet.Wpf/src/WindowsFormsIntegration/ref/WindowsFormsIntegration-ref.csproj

Add S.W.Forms.Primitives references to accommodate type-moves comign from dotnet/winforms
dotnet/winforms has moved some types from S.W.Forms.dll to S.W.Forms.Primitives.dll. Adding references to it to accomodate the type move. 
WinForms still needs to fix a bug on its end (namely, the transport package Microsoft.Winforms.Private has lib\S.W.Forms.Primitives.dll, but ref\S.W.Forms.Primitives.dll is absent) to complete the solution. 
These are needed to unblock https://github.com/dotnet/wpf/pull/2432
/cc @RussKie

Add S.W.Forms.Primitives references to accommodate type-moves coming from dotnet/winforms

---

eng/WpfArcadeSdk/tools/InlineTasks.targets
eng/WpfArcadeSdk/tools/Wpf.Cpp.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
eng/WpfArcadeSdk/tools/WpfProjectReference.targets

A few additional build orchestration fixups needed for an upcoming repo-refactoring. 
**ps:** do not squash this PR - create a merge commit instead;

Build orchestration fixups

---

eng/WpfArcadeSdk/tools/FolderPaths.props
eng/WpfArcadeSdk/tools/Publishing.props

Make ArtifactsTmpDir platform-specific - this should help ensure Asset-manifests are not clobbered.

Make ArtifactsTmpDir platform-specific

---

eng/Publishing.props
eng/WpfArcadeSdk/tools/FolderPaths.props

`Publish.pro`j comes from within the Arcade.SDK, which is outside the cone of the repo - this normally doesn't import WPF's build props, the Repo's D.B.props etc. 
It makes one exception - it will import `eng\Publishing.prop`s. 
We add `eng\Publishing.props` and use that to hook up our own `publishing.props/publishing.targets`, where we will in-turn override` $(AssetManifestFilePath)` to be distinct for` {$Platform} x {$Configuration}`. This will in turn ensure that all transport-packages produced by CI builds are published without loss. The current default-scheme in Arcade is lossy (it only uses` $(Platform)` in `$(AssetManifestFilePath)`, which means that `$(Configuration)` sensitive packages clobber one another).

Publishing fixup for .Debug builds

---

eng/Publishing.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets

Move DebugInformationFormat setting to Wpf.Cpp.targets; Remove version from sdk import (it's implicit)

Move DebugInformationFormat setting to Wpf.Cpp.target

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets

Revert "Set debug and optimization settings in targets so that it supersedes settings set by props files"
This reverts commit c22c04640b325af24b392a13fb8bf3b7f91baf73.

Set debug optimization flags early in build

---

eng/WpfArcadeSdk/tools/FolderPaths.targets
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets

Ensure C/C++ .lib builds in dotnet-wpf-int will set DebugInformationFormat=oldStyle. 
https://github.com/dotnet/arcade/issues/4763

Ensure C/C++ .lib builds in dotnet-wpf-int will set DebugInformationFormat=oldStyle

---

eng/Version.Details.xml

- Update dependency Uri's to https://github.com/dotnet/runtime 
- Update CoherentParentDependency for packages coming from dotnet/runtime to Microsoft.Private.Winforms

Fixup dependencies 

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props

Fixes #2415 
.NET Core 3.1 SDK installed in paths containing special characters like `'(` fails to build WPF projects. This affects the default WOW64 installation - i.e., x86 MSI installation on x64 system, that typically installs under `%SystemDrive%\Program Files (x86)\dotnet`
The builds fail with the following error: 
```
c:\Program Files (x86)\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(225,9): 
error MSB4062: The "Microsoft.Build.Tasks.Windows.MarkupCompilePass1" task could not be loaded from
the assembly c:\Program Files %28x86%29\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.WindowsDesktop\tools\netcoreapp2.1\PresentationBuildTasks.dll. 
Could not load file or assembly 'c:\Program Files …
```

[release/3.1] Unescape PresentationBuildTasks.dll paths containing special characters

---

eng/WpfArcadeSdk/tools/FolderPaths.targets
packaging/Microsoft.DotNet.Arcade.Wpf.Sdk/Microsoft.DotNet.Arcade.Wpf.Sdk.ArchNeutral.csproj

Include additional headers in the transported Microsoft.DotNet.Arcade.Wpf.Sdk used by internal dotnet-wpf-int repo.

Include additional headers in the transported Microsoft.DotNet.Arcade.Wpf.Sdk used by internal dotnet-wpf-int repo

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/CommonDialog.cs

Fixes #2663 
Temporary workaround for https://github.com/dotnet/runtime/issues/32929; do not merge into master.
Treat `Environment.UserInteractive` as `true`
/cc @rladuca, @danmosemsft, @ericstj, @richaverma1

Fixup Environment.UserInteractive uses to workaround https://github.com/dotnet/runtime/issues/32929

---

global.json

Adds `sdk.version` entry to `global.json` which tells msbuild SDK resolver which SDK version to look for when looking for `Microsoft.NET.Sdk`
Detailed explanation at https://github.com/dotnet/wpf/issues/2714#issuecomment-595419219
Fixes #2714

Add sdk.version entry to global.json

---

src/Microsoft.DotNet.Wpf/src/WpfGfx/core/resources/glyphrunslave.cpp

Fix CGlyphRunResource::GetDWriteRenderingMode to choose correct DWriteRenderingMode under ClearType

---

eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets

https://github.com/dotnet/wpf/commit/60422e32024e035a42ae036f876669abcded3cda regressed `RuntimeFrameworkVersion` references. Update to use `MicrosoftNETCoreAppInternalVersion `for `RuntimeFrameworkVersion`

Fix RuntimeFrameworkVersion logic

---

CODEOWNERS

Add @dotnet/wpf-developers to CODEOWNERS to get automatic inclusion into all PR's
The msftbot system in use today for PR assignments doesn't work with GitHub teams, and requires individual GitHub ID's to be used. CODEOWNERS is more flexible and can automatically include a team in CR's. I believe i can also work side-by-side with msftbot. 
[dotnet/winforms](https://github.com/dotnet/winforms) uses a similar scheme today and this is borrowed from there.

Add @dotnet/wpf-developers to CODEOWNERS 

---

eng/pipeline.yml

There is no need to build debug in official builds as it's covered in CI as well as PRs

Do not build debug in official builds

---

.github/ISSUE_TEMPLATE/config.yml

This .yml adds quick links to other repos below the existing issue template buttons in your new issue flow.
For an example of what this looks like, see https://github.com/danmosemsft/runtime/issues/new/choose (the white buttons below your existing green buttons)
We are adding this in dotnet/runtime (https://github.com/dotnet/runtime/pull/36431). Reasoning: it's sometimes confusing which is the correct repo to open an issue in. The goal here is to make it easier to open an issue in the correct repo first time so we need to move fewer issues and they more quickly get attention from the right people.

Add links in "new issue" flow to other related repos

---

src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/interfaces/matrix_t.hpp

The builds will start failing soon when building using Dev16.7 previews (I'm on Version 16.7.0 Preview 3.0 [30126.5.master]) with the following errors: 
```
\wpf\src\Microsoft.DotNet.Wpf\src\WpfGfx\common\DirectXLayer\xmath\matrix_xm.hpp(135,1): error C2027: use of undefined type 'std::tuple<dxlayer::vector3_t<dxlayer::dxapi::xmath>,dxlayer::quaternion_t<dxlayer::dxapi::xmath>,dxlayer::vector3_t<dxlayer::dxapi::xmath>>' [\wpf\src\Microsoft.DotNet.Wpf\src\WpfGfx\core\control\util\util.vcxproj]
\wpf\src\Microsoft.DotNet.Wpf\src\WpfGfx\common\DirectXLayer\xmath\matrix_xm.hpp(134,17): error C2027: use of undefined type 'std::tuple<dxlayer::vector3_t<dxlayer::dxapi::xmath>,dxlayer::quaternion_t<dxlayer::dxapi::xmath>,dxlayer::vector3_t<dxlayer::dxapi::xmath>>' …
```

#include <tuple> to matrix_t.hpp

---

eng/Versions.props

Update branding for 3.1.6
Includes the merge from internal/release/3.1 (847da8feefa286affd3f458fc3fdcedcd0d93869) which resulted in no changes after resolving merge conflicts.  No MSRCs were taken for this release, so that is expected.

Update branding for 3.1.6

---

src/Microsoft.DotNet.Wpf/src/PenImc/dll/SxSCOMRegistration.cpp
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPenimc.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Wisp/PenThreadWorker.cs

Related #2393 (so we keep the bug open)

Fix PenIMC Activation Context Handling

---

global.json

This update (darc-master-89e15d90-235e-4313-959a-f0283bd51d70) caused APICompat to start failing. APICompat expects PresentationUI.dll to exist in wpf.tools\native\bin\net-framework-48-ref-assemblies\0.0.0.1.
The is due to the initial version of the _BlockWinMDsOnUnsupportedTFMs target: 
`.dotnet\sdk\5.0.100-preview.6.20310.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets`
<Target Name="_BlockWinMDsOnUnsupportedTFMs"
BeforeTargets="CoreCompile"
DependsOnTargets="ResolveReferences"
The version of the SDK must include the fix for _BlockWinMDsOnUnsupportedTFMs (Preview6.20310.4 does not include the fix).  Update global.json SDK and tools version to include fix for _BlockWinMDsOnSupportedTFMs.

Update global.json SDK and tools version to include fix for _BlockWinMDsOnSupportedTFMs causing build failures

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

Fixes dotnet/sdk#11233
cc @wli3

Setting default TargetPlatformVersion

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.props

So SDK side of the change will not be blocked by WPF side of change
More info in https://github.com/dotnet/sdk/issues/12108

Add the property for MicrosoftWindowsDesktopSdkImported

---

azure-pipelines.yml

Reduces build time. SDL is now right nightly + on each build candidate. No need to keep running on a per-build basis.

Disable per-build validation

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

Please review by commit. These are 3 additional changes related to WindowsDesktop SDK.
8ecabfc is to solve https://github.com/dotnet/sdk/issues/12403 (currently has a workaround in SDK)
7baee74 is solve a simple mistake
f309b4b is moved due to dotnet/sdk@d21aaa5
Tested against _WPF-Samples\Graphics\Point_. And all SDK unit tests
SDK side change https://github.com/dotnet/sdk/pull/12459

Remove workarounds

---

eng/common/sdl/packages.config
eng/common/templates/job/execute-sdl.yml

Update the guardian package version to unblock SDL Validation - this is a subset of the failing arcade update at https://github.com/dotnet/wpf/pull/3272

Update guardian package

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006Reader.cs

- In dotnet/runtime#13339 I found that due to our changes to use icu by default there was a significant regression in Baml parsing time in .NET 5.0
- There is a plan to address most, if not all of that regression, but it won't be as good as simply using the char based IndexOf

Use faster char based overload of String.IndexOf

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/Company.WpfApplication3x1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/Company.WpfApplication1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/Company.WpfApplication3x1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/Company.ClassLibrary3x1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/Company.ClassLibrary3x1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/Company.WpfCustomControlLibrary3x.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/Company.WpfCustomControlLibrary.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/Company.WpfCustomControlLibrary3x.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/Company.WpfControlLibrary3x.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/Company.WpfControlLibrary3x.vbproj

Port https://github.com/dotnet/wpf/pull/3302

Update to net5.0 template with backcompact

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

This PR contains a scoped version of the changes described in #3245 
For now, we'll keep the globbing in WPF targets, and add the appropriate Item metadata and project property, so that vs tooling can distinguish WPF from WinUI in .NET core projects.
/cc @dsplaisted @ryalanms @chabiss

adding XamlRuntime msbuild property/metadata

---

eng/Version.Details.xml
eng/Versions.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets

In RTM and post-RTM, the ref pack will rev less frequently, and so the ref pack version should be used for the targeting pack version.
In addition, the RuntimeFrameworkVersion should be set to a property that will track the stable version of the runtime, rather than the internal version.

Fix RuntimeFrameworkReferences for RTM builds

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Diagnostics/XamlSourceInfoHelper.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/CLRBindingWorker.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/DefaultValueConverter.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/EnumerableCollectionView.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/ObjectRef.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PropertyPathWorker.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/XmlBindingWorker.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Helper.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/TraceData.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataErrorValidationRule.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGrid.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpression.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpressionBase.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingGroup.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/CollectionView.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/MultiBindingExpression.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/ObjectDataProvider.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/PriorityBindingExpression.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/XmlDataProvider.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Diagnostics/BindingDiagnostics.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Diagnostics/BindingFailedEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Diagnostics/ResourceDictionaryDiagnostics.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AvTrace.cs

Visual Studio 16.8 will include a new set of XAML Binding Failures diagnostic improvements. The challenge with a binding failure is locating the source of the binding in XAML. We determined that to locate a binding failure in XAML, the source location must be provided by the platform. This will allow the user to quickly navigate to the binding failure.
The design is that WPF will trigger a new event any time debug traces are written for a binding failure. Debug traces alone aren’t enough to find the source of the failure. The new event will contain more information about the binding failure, such as the BindingExpression object, which helps locate the binding in the XAML source.
**Risk**
The risk for the runtime is very low because this feature doesn’t get activated for any application …

Add BindingFailed event for diagnostics of binding failures

---

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/CPP/DWriteWrapper/Common.h
src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonHelper.cs

This change removes or replaces the word 'whitelist' from code comments in two files.

Remove or replace Policheck violations in code comments

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/PathInternal.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

**Original PR:** 
https://github.com/dotnet/wpf/pull/3120
**Customer Impact:**
Setting custom output paths in a WPF project breaks markup compilation, a necessary requirement for many customers.  We continue to get new issues related to this problem.
**Risk:** 
This only affects markup compilation in WPF projects that use custom paths.  There are no changes to the WPF runtime.   
**Testing:**
Unit testing of the path calculation, .NET Core and .NET Framework markup compilation targeting .NET Core and .NET Framework, and all of the current issues root-caused to this problem that contain repro projects.
**Regression:**
No.

Ask-Mode: [release/5.0-rc2] Custom intermediate output paths shouldn't break markup compilation

---

README.md

The link points to old repo (dotnet/coreclr) which migrated to dotnet/runtime. The old one is used only for servicing .NET Core 2.1 and 3.1.

Update dotnet/CoreCLR repo link to dotnet/Runtime

---

eng/WpfArcadeSdk/tools/FolderPaths.targets

The value was specified with a lower case 's', but the directory in Git is spelt with a capital 'S'. This discrepancy causes failures on source server lookups. For example, stepping into `MS.Utility.FrugalList` tries to load (using .NET 5.0 RC1):
https://raw.githubusercontent.com/dotnet/wpf/be89bbfaded6ad3f0f4143bf1a8dd075a5789715/src/Microsoft.DotNet.Wpf/src/shared/MS/Utility/FrugalList.cs
but the server returns a 404 response. The source is actually at:
https://raw.githubusercontent.com/dotnet/wpf/be89bbfaded6ad3f0f4143bf1a8dd075a5789715/src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs

Fix the casing of 'Shared' in WpfSharedDir

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/HierarchicalVirtualizationConstraints.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses #2490 
This is a port of a servicing fix in .NET 4.7/4.8.
**Issue:** Scrolling a TreeView hangs.
The customer's data is highly non-uniform, in the sense that a given node's children govern subtrees whose sizes are quite different.  This means the estimates VSP computes can differ wildly from the truth, and are subject to frequent (and sometimes violent) revision as more of the tree de-virtualizes.  This is not necessarily bad, but it stresses the algorithms in ways that uniform trees don't.  This stress uncovers two problems:
1.  VSP stores "effective offsets", intended to support correct layout after bottom-up size changes (e.g. a deep node gets larger because of new content), which shouldn't move the visible items.  When VSP revises its estimates, it also …

Vsp freeze

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/DataGridColumnHeadersPresenterAutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GroupItemAutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemsControlAutomationPeer.cs

Addresses #3116 
**Issue:** Crash involving automation of ItemsControls
This bug arises because some AutomationPeers can add 'null' to their list of children, which leads to NRE in the common method EnsureChildren.  The peer in the repro is a DataGridColumnHeadersPresenterAutomationPeer, but I've identified two other peers with the same flaw.
The flawed peers add null only when 'null' appears as a child in the corresponding visual tree.  This normally doesn't happen, but it can if the visual tree is in a torn state at the time GetChildrenCore is called, specifically if the first few entries of the corresponding visual collection have been set to null but the collection itself has not yet been cleared.  This situation …

Avoid null item AutomationPeers

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextBlock.cs

Addresses #3099 
**Issue:** Text that is narrower after shaping (e.g. applying ligatures and kerning) can reflow, yielding different line breaks than the original measure.  Some words can disappear, and programmatic access can crash hard (FailFast).
The root cause turns out to be a faulty assumption in TextBlock's logic to choose a width to send to FormatLine in post-measure situations like render and hit-test.  The intent is that FormatLine makes the same line-breaking decisions it did during measure.  The faulty assumption is "Reflowing will not happen when Width is between _previousDesiredSize.Width and ReferenceWidth".  [Comment quoted from TextBlock.CalcWrappingWidth.  "Reflowing" means "different line-breaking …

Avoid reflow of shaped text

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/HostVisual.cs
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/exports.cs

Addresses #3100
**Issue:** HostVisual can disconnect from its rendering channel on the wrong thread.  This can result in corruption that can crash the render thread, usually in some unrelated activity many minutes (or hours) later.
HostVisual sometimes adds commands to the graphics channel on the wrong thread.  And sometimes this leaves the channel in a corrupt state, where the primary handle table releases a slot but the secondary handle table doesn't release the corresponding slot.  This is a time-bomb - the next time the primary table allocates the slot, the secondary table allocation will fail, which will crash the app at the next SyncFlush.  (It could take minutes or hours for this to happen.)
The fix is for HostVisual …

HostVisual threading

---

src/Microsoft.DotNet.Wpf/src/WpfGfx/core/resources/glyphrunslave.cpp

Addresses #2025 
**Issue:** Text rendered with TextRenderingMode.ClearType send the wrong parameter to DWrite, resulting in poor rendering.
The meat of the fix already appears in .NET 5, see #2668.  This PR removes a useless assert, bringing the code into alignment with .NET 4.7/4.8.

ClearType anti-aliasing

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs

Addresses #3114 
This is a port of a servicing fix in .NET 4.8
**Issue:**  Expensive diagnostic code is running on the normal code-path.
A recent servicing fix added code to capture a stack trace whenever a certain anomalous condition occurs.  However it always creates the stack trace, and merely discards it in the normal case.
Fixed by moving the creation of the stack trace into the anomalous branch.

Move StackTrace to error branch

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedSOMPageConstructor.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs

Addresses #3115 
**Issue:** For certain XPS documents, DocumentViewer cannot select text correctly.
There are actually two bugs, both affecting the construction of the FixedPage's "Semantic Object Model".
1.	Each text run is tested to see if it can be combined into the current text block.  The test is intended to recognize when the text and the block are separated by a line drawn somewhere on the page.  The bug arises when the text and the block overlap in both the x- and y-directions, and there is a vertical line that touches the overlap.  The test erroneously thinks the line separates the text from the block, and doesn't combine them.
2.	The lines come from a recursive tree walk of the XPS elements.  The tree walk …

FixedPage SOM bugs

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGrid.cs

Addresses #3113 
This is a port of a servicing fix in .NET 4.5-4.8
**Issue:**  DataGrid's Copy command crashes the app if the clipboard is locked. 
DataGrid's Copy command throws an exception if the clipboard is locked (after the usual round of retries).  There is usually no app code on the stack, so this exception crashes the app.  Other controls that implement Copy (TextBox et al.) simply fail silently - no exception, but nothing gets put on the clipboard.  This is also the way other apps behave (Notepad, Word, browsers, etc.).  This change gives DataGrid that same behavior.

DataGrid.Copy: fail silently if clipboard is locked

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs

Addresses #3563 
**Issue:** Crash when multi-threaded app loads app resources
There is a race condition when two threads try to add parts to one of the app's predefined packages (ResourceContainer or SiteOfOriginContainer), one from Application.GetResourceOrContentPart or Application.GetResourceStream, and the other from PackWebResponse+CachedResponse.GetResponseStream.  These two codepaths use different lock objects to synchronize access to the package, so they can interleave.  An unfavorable interleaving during the time they are actually adding to the package's underlying SortedList can corrupt the list (it's not thread-safe), leaving it with entries in the wrong order and/or spurious 'null' entries.  This breaks the …

App resource threading issue

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/EllipseGeometry.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapSourceSafeMILHandle.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/LineGeometry.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/RectangleGeometry.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/GeneralTransform3DTo2D.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/IO/Packaging/indexingfiltermarshaler.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Printing/printdlgexmarshaler.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/PtsHost/CellParaClient.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/Marshalers.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/DateTimeAutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Calendar.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/CalendarBlackoutDatesCollection.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/CalendarItem.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SelectedDatesCollection.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpression.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkElement.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/VisualStateManager.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/HwndSubclass.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/Security/RightsManagement/IssuanceLicense.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/SplashScreen.cs

Replace null comparisons on non-nullable types that now cause compilation errors, due to the .NET SDK update.  This is preventing WPF from updating from the RC1 version of the .NET SDK to RC2.  
These redundant null checks against IntPtr and DateTime are now errors.  This primarily replaces null comparisons on IntPtr and DateTime, but there are a few others.  Where possible, checks were replaced with an alternative (e.g., IntPtr.Zero).  
/cc @SamBent @dotnet/wpf-developers

Replace null comparisons on non-nullable types that now cause compilation errors, due to the .NET SDK update.

---

Documentation/getting-started.md

When we remove a specific version, we will use the latest version by default

Remove special vs version on the link

---

eng/Version.Details.xml
eng/Versions.props
global.json

The Microsoft.NETCore.App.Internal package is being removed in https://github.com/dotnet/runtime/pull/38457/. The usage in WPF can be replaced with the .NET Core Shared Framework VS insertion package, which is a supported package to reference a runtime version.

Remove usage of Microsoft.NETCore.App.Internal package.

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props

Current wording could create a false assumption that `UseWinForms` is a supported property name, while it really isn't.

Fix a wrong property name in a comment

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Generated/AvTraceMessages.cs

Fixes #2956
When targeting .NET Framework, not finding a `ResourceDictionary` key named `someKey` causes
> System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='someKey'
to be written to `PresentationTraceSources.ResourceDictionarySource`, but when targeting .NET Core, that message is only
> System.Windows.ResourceDictionary Warning: 9 : Resource not found
This branch contributes a fix.  I want to explain both why it is a fix and why (I think) it is the correct fix.
The change adds `"ResourceKey"` to a string array.  That array is later passed into 
https://github.com/dotnet/wpf/blob/b15227213778b882c11f788bb8679fd52bf88ddb/src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/AvTrace.cs#L256-L261
as the `labels` argument.  With the code currently in `master`, the …

added label "ResourceKey" to trace details when resource is not found

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT/GuidGenerator.cs

We're trying to minimize usage of the `*CryptoServiceProvider` and `*Managed` types through our code bases so that we can eventually write analyzers to recommend moving off of them. See https://github.com/dotnet/runtime/issues/40169 for some related discussion w.r.t. `RNGCryptoServiceProvider`.
This PR changes the call site to use the static one-shot helper method so that you don't need to instantiate a hasher object. The `HashData` static method uses the best available implementation for the current OS.

Call SHA1.HashData static helper instead of instantiating SHA1CSP

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializer.cs

The Empty property are only used in TypeReferences

Reduce memory usage by Array.Empty

---

README.md

The WPF framework requires the most recent version of Visual Studio public preview to build against the .NET 6.0 SDK.  Update the readme to link to the the preview version of VS.

Update Visual Studio link in readme to VS Preview

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json

Fixes Issue #3964 and targets .NET 6.0

Adjust project templates to support .NET 6.0 (and default to it)

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/ContourSegment.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/EllipticalNodeOperations.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/Quad.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeFIndices.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeNode.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeNodeData.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Ink/StrokeNodeOperations.cs

See: https://github.com/dotnet/wpf/issues/812
Benchmark:
|          Method |           context |     Mean |     Error |    StdDev | Ratio | RatioSD |
|---------------- |------------------ |---------:|----------:|----------:|------:|--------:|
|    CalcGeometry |    WpfInk.Context | 1.595 ms | 0.0031 ms | 0.0029 ms |     ? |       ? |
|                 |                   |          |           |           |       |         |
| CalcGeometryOld | WpfInkOld.Context | 1.628 ms | 0.0069 ms | 0.0064 ms |  1.00 |    0.00 |
Benchmark code:  https://github.com/lindexi/lindexi_gd/tree/376e4404/WpfInk
Update https://github.com/dotnet/wpf/pull/2839/

Using readonly struct in WPF Ink module

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MarshalLocal.cs

See https://github.com/dotnet/coreclr/pull/19507
https://github.com/dotnet/runtime/issues/26497

Use the new Marshal.IsTypeVisibleFromCom Api

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.targets
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

Don't import .NET Framework's WinFX targets, When the SDK's implementation is being used and vice versa
**Reference**: microsoft/msbuild#4948

Don't double import WinFX targets

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/D3DImage.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/AppDomainShutdownMonitor.cs

Benchmark:
|             Method |              argList |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------- |--------------------- |---------:|---------:|---------:|------:|--------:|
| 'AddAndRemove Old' | Syste(...)ence] [55] | 679.7 us | 10.42 us |  8.70 us |  1.00 |    0.00 |
|                    |                      |          |          |          |       |         |
| 'AddAndRemove New' |  Syst(...)er]] [113] | 667.7 us | 11.07 us | 10.35 us |     ? |       ? |
|                Method |              argList |     Mean |     Error |    StdDev | Ratio | RatioSD |
|---------------------- |--------------------- |---------:|----------:|----------:|------:|--------:|
| 'AddBeforeRemove Old' | Syste(...)ence] [55] | 1.414 ms | 0.0174 ms | 0.0154 ms |  1.00 |    0.00 …

Replace the Dictionary with HashSet in AppDomainShutdownMonitor

---

eng/Version.Details.xml
eng/Versions.props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/PathInternal.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerWrapper.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskHelper.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass2.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

*This feature requires applications to **opt-in** by explicitly setting a property in their project file.  Otherwise, the existing path handling code is executed.*
> * Relative path fixes from previous commit: https://github.com/dotnet/wpf/pull/3120
This PR brings the changes from master to release/5.0: 
A single property turns on the feature `(IncludePackageReferencesDuringMarkupCompilation = true)` and enables the new behavior.  By default, the unmodified markup compiler code is called, the *old* path.

[release/5.0] Improve handling of custom paths in markup compiler

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs

We define the selfStyle variable, but we do not use it. I remove the codes to improve performance

Remove unused local variable 'selfStyle' and related conditionals in System.Windows.StyleHelper.GetThemeStyle

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerWrapper.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskHelper.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass2.cs

*This feature requires applications to **opt-in** by explicitly setting a property in their project file.  Otherwise, the existing path handling code is executed.*
> * Relative path fixes from previous commit: https://github.com/dotnet/wpf/pull/3120
This PR brings the changes from master to release/5.0: 
A single property turns on the feature `(IncludePackageReferencesDuringMarkupCompilation = true)` and enables the new behavior.  By default, the unmodified markup compiler code is called, the *old* path.

Port release/5.0 5.0.3 servicing fix to master: markup compiler updates

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

.NET 6.0 Preview 1 has snapped.  Make source generator and package reference support opt-out (on by default) for Preview 2.

Make source generator and package reference support opt-out (on by default)

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerState.cs

This PR fixes incremental builds for WPF projects if `dotnet.exe` is used for building.
The `GetHashCode()` method of strings can produce different hash values between subsequent program runs in .NET Core and cannot be used to persist the `MarkupCompile.cache` file.
A copy of the `GetNonRandomizedHashCode()` method from `String.Comparison.cs` is used instead.
The bug was found as part of #3876.

Fix incremental build for WPF projects with dotnet.exe

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerState.cs

This moves @MichaeIDietrich's original PR from master. 
*WPF rebuilds its intermediate assembly containing local types when no inputs have changed.*
As part of the WPF's incremental build logic, WPF applies a hash to the list of reference filenames during compilation.  The hash value is written to a cache file and compared against the hash value of the new list of reference filenames next compile.  This comparison always fails due to the hash value for the same list of strings differing between runs and causes WPF to always build its intermediate project, even when inputs have not changed.  .NET's GetHashCode is not stable between separate application runs as it was in .NET Framework.
One large internal Microsoft customer and one large external customer have both asked for this to be …

[release/5.0] Fix incremental build issue in WPF's markup compiler 

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerState.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

This moves @MichaeIDietrich's original PR from master. 
*WPF rebuilds its intermediate assembly containing local types when no inputs have changed.*
As part of the WPF's incremental build logic, WPF applies a hash to the list of reference filenames during compilation.  The hash value is written to a cache file and compared against the hash value of the new list of reference filenames next compile.  This comparison always fails due to the hash value for the same list of strings differing between runs and causes WPF to always build its intermediate project, even when inputs have not changed.  .NET's GetHashCode is not stable between separate application runs as it was in .NET Framework.
One large internal Microsoft customer and one large external customer have both asked for this to be …

[release/3.1] Fix major incremental build issue in WPF's markup compiler 

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DateTimeValueSerializer.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/MeScanner.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Parser/XamlName.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ClrNamespaceUriParser.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlMarkupExtensionWriter.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlType.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlTypeName.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlXmlWriter.cs

Replace all method call that uses a single char string while there is another method that accepts a char.
Should yield tiny performance benefit on hot paths.

Use char overload in System.Xaml

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/ParserExtension.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/CompilerWrapper.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass1.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/MarkupCompilePass2.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/KeyGesture.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/CursorConverter.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/WindowsRuntime/Generated/WinRT.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/RtfToXamlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XamlToRtfWriter.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Input/Command/CommandConverter.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Primitives/MarkupWriter.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/ClrNamespaceUriParser.cs

Follow up to https://github.com/dotnet/wpf/pull/3278

Use char.{Last}IndexOf

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/KnownStrings.cs

Merging the community test pass PRs independently caused two methods with the same signature to be added.  This removes one of them.

Remove method with the same signature created in two different CTP PRs 

---

eng/Version.Details.xml
eng/Versions.props

Reverts dotnet/wpf#4165.  This should not have been a squash commit.

Revert "Merge internal/release/3.1 and update branding in release/3.1 to 3.1.13"

---

src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs

Use reflection-only context for InternalsVisibleToAttribute type comparison.
Fixes Issue #2492: Compilation error MC3064 when importing internal user control from signed class library.  The wrong load context was used for a type comparison that always failed.  
Internal types contained in assemblies with InternalsVisibleTo attributes that are referenced in markup cause a markup compiler error:  *error MC3064: Only public or internal classes can be used within markup. 'InternalClass' type is not public or internal.*
This is a regression from .NET Framework.  
Repro'd the issue and tested the fix against .NET Core targeting .NET Framework 4.72/4.8 + .NET Core 3.1/6.0 and .NET Framework targeting .NET Framework 4.72/4.8 + .NET Core 3.1/6.0.  Referencing internal types in markup that are …

Use reflection-only context for InternalsVisibleToAttribute type comparison

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

Fixes Issue #4203.
A case-sensitive string comparison was failing: "true" != "True".  This has been removed and now any embedinteroptypes value, including explicit 'false', will be added as item metadata.  
Note that this appears to have been in WPF since 2005.  (The bigger related issue is that only select item metadata is being passed through to the temporary project, which is not fixed here.)
This project will not get embedinteroptypes metadata passed to the temporary project due to the uncapitalized 'T' in 'True'. 
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<OutputType>WinExe</OutputType>
<TargetFramework>net5.0-windows</TargetFramework>
<UseWPF>true</UseWPF>
<UseWindowsForms>true</UseWindowsForms>
</PropertyGroup>  
<ItemGroup>
<COMReference …
```

WPF fails to pass on embedinteroptypes metadata to items in its temp project

---

azure-pipelines.yml

Please see https://github.com/dotnet/wpf/issues/4120.  This change updates the triggers to include the 'main' branch.

Change WPF's default branch to 'main':  Update pipeline triggers to include 'main'

---

azure-pipelines.yml

Temporarily disable PR builds in main to prevent PR builds for all open PRs from running after default branch change.

Temporarily disable PR builds in main to prevent PR builds for all open PRs from running

---

azure-pipelines.yml

The triggers had to be disabled prior to renaming the branch to prevent 60+ PR builds from kicking off.  This change re-enables the build triggers.

Enable build triggers after default branch rename from master to main

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/FontCache/FontResourceCache.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Resources/ContentFileHelper.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/Primitives/RibbonMenuItemsPanel.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/ObjectWriterContext.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Context/XamlParserContext.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/MS/Impl/XmlNsInfo.cs

I replaced some Dictionaries and Hashtables that only use the key as a way to filter out duplicates. I replaced them with HashSet to improve performance.
I used the following code to benchmark it :
https://gist.github.com/ThomasGoulet73/99559a6cd49a04dc70a413e9668eee22
Here are the results (First row is 10 items, second is 1000 and third is 100000) :
Dictionary vs HashSet:
|     Method |           enumerable |           Mean |         Error |        StdDev |    Ratio | RatioSD |    Gen 0 |    Gen 1 |    Gen 2 |   Allocated |
|----------- |--------------------- |---------------:|--------------:|--------------:|---------:|--------:|---------:|---------:|---------:|------------:|
| Dictionary | Syste(...)ring] [48] |       742.2 ns |      14.71 ns |      13.76 ns |     1.00 |    0.00 | …

Replaced some Dictionaries and Hashtables with Hashsets

---

src/Microsoft.DotNet.Wpf/src/ReachFramework/SR.cs

System.Windows.Documents.Serialization.SerializerProvider creation always fails while creating System.Uri. 
```cs
SerializerProvider sp = new SerializerProvider();
```   
> at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at System.Windows.Xps.Serialization.XpsSerializerFactory.get_ManufacturerWebsite()
at System.Windows.Documents.Serialization.SerializerDescriptor.CreateFromFactoryInstance(ISerializerFactory factoryInstance)
at System.Windows.Documents.Serialization.SerializerProvider..ctor()
at TestSerializerProvider.MainWindow..ctor() in D:\PluginSerializer\TestSerializerProvider\MainWindow.xaml.cs:line 30
The issue is that resource lookups for the ReachFramework were not actually resolving the string, and instead were …

Fix ReachFramework's resource string resolution

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/MimeObjectFactory.cs

Fixes Issue  #4492
The default MS.Internal.AppModel.MimeObjectFactory._objectConverters capacity should be 9

Fix the MimeObjectFactory field capacity

---

NuGet.config

This should allow the feed check to verify no upstreams across all input feeds.

Remove windowsdesktop blob feed

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.props
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/Serialization/SerializerDescriptor.cs
src/Microsoft.DotNet.Wpf/src/PresentationUI/PresentationUI.csproj

These changes are necessary to take the most dependency updates required for the Preview 5 branch snap.
* Add temporary workaround for SDK props import bug affecting C++/CLI projects (ILLinkTasksAssembly is empty)
* https://github.com/dotnet/sdk/issues/16725
* Suppress obsolete API warning:  This `SerializerDescriptor` will be added to the release notes as 'not supported'.
* Add `System.Runtime.Loader` now required by `PresentationUI`

Fix and workaround various issues with dependency updates and Preview 3 SDK

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/dotnetcli.host.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/Company.WpfApplication1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/dotnetcli.host.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/Company.ClassLibrary1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/dotnetcli.host.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/Company.WpfCustomControlLibrary.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/dotnetcli.host.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/Company.WpfControlLibrary.csproj

resolves https://github.com/dotnet/templates/issues/485

enable nullable for new projects

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/Sdk/Sdk.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props

Partially Fixes #4515
Partially Fixes dotnet/sdk#18062
Disable .NET Framework's WinFX targets import only when the Windows Desktop SDK is used directly instead!
Example:
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop" />
```
Here, we're simply moving the logic to the `Sdk.props`. This still does not fix the root of the problem
where the SDK provided WinFX targets should work properly when targeting .NET Framework only projects.
As per the issues mentioned above, the .NET Framework projects that depends on older inbox WinFX targets no longer used those targets and so, the build fails.
Yes, it was a regression of a Desktop SDK's PBT bug that revealed itself through #2976.
Works when tested locally.
Low, since the .NET 6 is still in preview.
It only fixes when the SDK used is .NET SDK …

Disable NETFX WinFX targets only when the SDK is used directly

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPenimc.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs

DeactivateActCtx do not have HRESULT as returning type, so PreserveSig == false is no op.
SHCreateItemFromParsingName will always throw in case of error,
and error handling in
https://github.com/dotnet/wpf/blob/d26eaaca20aa2f5de768e4053593f50a30776380/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ShellProvider.cs#L901-L909
would never works.
Discovered as part of attempt to compile WPF in Native AOT in https://github.com/dotnet/runtimelab/issues/1183
Also apologize for style correction, seems to be editorconfig picked up.

Fix incorrect marshalling spec

---

eng/pipeline.yml

Currently OneLocBuild does not automatically make PRs back to GitHub. This will make it automatically make PRs back to GitHub. Documentation [here](https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md).
Customers will be able to use WPF in languages other than English.
No.
N/A
PRs may be noisy. If this occurs, please file an issue with the localization team.

Turn on loc PRs

---

eng/Version.Details.xml
eng/Versions.props
global.json
src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
src/Microsoft.DotNet.Wpf/src/PresentationCore/ref/PresentationCore-ref.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework-ref.csproj
src/Microsoft.DotNet.Wpf/src/PresentationUI/PresentationUI.csproj
src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj
src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
src/Microsoft.DotNet.Wpf/src/WindowsBase/ref/WindowsBase-ref.csproj
src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/TestServices.csproj

Remove references now included in the Microsoft.NETCore.App.Ref targeting pack + update SDK
https://github.com/dotnet/runtime/pull/54147 exposed reference assemblies in the NetCore.App targeting pack.  Remove versioning and references to these assemblies from WPF. 
(This unblocks the most recent WinForms + runtime updates: https://github.com/dotnet/wpf/pull/4697.)

Remove references now included in the Microsoft.NETCore.App.Ref targeting pack + update SDK

---

eng/Version.Details.xml
eng/Versions.props
src/Microsoft.DotNet.Wpf/src/PresentationCore/PresentationCore.csproj
src/Microsoft.DotNet.Wpf/src/PresentationCore/ref/PresentationCore-ref.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/ref/PresentationFramework-ref.csproj
src/Microsoft.DotNet.Wpf/src/PresentationUI/PresentationUI.csproj
src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj
src/Microsoft.DotNet.Wpf/src/WindowsBase/WindowsBase.csproj
src/Microsoft.DotNet.Wpf/src/WindowsBase/ref/WindowsBase-ref.csproj
src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/TestServices.csproj

* Remove references now included in the runtime + update SDK
* Revert SDK version to Preview 4
Fixes Issue 
Master PR

[release/6.0-preview6] port: Remove references now included in the Microsoft.NETCore.App.Ref targeting pack + update SDK (#4706)

---

global.json

Update the SDK version that WPF builds against to .NET 6.0 Preview 6 from Preview 4.  
(We were waiting for the build pool machines to be updated with VS 16.11.)

Update the SDK version that WPF builds against to .NET 6.0 Preview 6 from Preview 4

---

eng/WpfArcadeSdk/tools/ExtendedAssemblyInfo.targets
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets

In my experience, MSBuild marked WpfGfx.dll and all of its dependencies for rebuild every time because various `<WriteLinesToFile>` calls lacked `WriteOnlyWhenDifferent=true`. This made my inner-loop significantly slower.
None; this is a build-time fix only.

Fix issue causing constant rebuilds

---

src/Directory.Build.Props

This file does nothing (MSBuild will evaluate the same way without it), and its existence prevents GitHub from collapsing the src/Microsoft.DotNet.Wpf subdirectory into one link.
Developers will be able to enter the src/Microsoft.DotNet.Wpf subdirectory from the repo homepage with one click, rather than having to click into the src subdirectory and then into Microsoft.DotNet.Wpf. I find this latter behavior very annoying whenever I browse the WPF repo on GitHub.

Remove unneeded Directory.Build.props file

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

WPF applications will not build with the most recent SDK.

Disable implicit namespace imports

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

WinForms project also import Microsoft.WinFX.targets, and WinForms now relies on implicit imports.  Scope disabling implicit imports to WPF.  This broke WinForms VB projects.
> But it wasn't @JunTaoLuo's change(s). It's actually caused by DisableImplicitNamespaceImports here: dotnet/wpf@ff1be8e#diff-681ca681001fbc20488df7fdbb46a8c40ac2df9dc2210df5ad869aee6a56df16R23
This disables these VB imports:
https://github.com/dotnet/sdk/blob/55195f3c4ba3f582aa91ec824bd24a7ba3e73528/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L118-L129
/cc @dotnet/wpf-developers

Only enable `DisableImplicitNamespaceImports` when `UseWPF` is set

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

Cherry-pick "Only enable `DisableImplicitNamespaceImports` when `UseWPF` is set #4868" from main. 
> WinForms project also import Microsoft.WinFX.targets, and WinForms now relies on implicit imports. Scope disabling implicit imports to WPF. This broke WinForms VB projects.
> But it wasn't @JunTaoLuo's change(s). It's actually caused by DisableImplicitNamespaceImports here: ff1be8e#diff-681ca681001fbc20488df7fdbb46a8c40ac2df9dc2210df5ad869aee6a56df16R23
This disables these VB imports:
https://github.com/dotnet/sdk/blob/55195f3c4ba3f582aa91ec824bd24a7ba3e73528/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L118-L129
/cc @dotnet/wpf-developers
Required to unblock: https://github.com/dotnet/installer/pull/11143.

Cherry-pick 'Only enable `DisableImplicitNamespaceImports` when `UseWPF` is set #4868' from main

---

Directory.Build.targets

Reverts dotnet/wpf#4849
This should no longer needed now that WPF is consuming an RC SDK.  Don't merge this until we manually validate the C++/CLI binaries don't have references to the JSON source generator (since that would only fail after ingestion upstack).

Revert "Remove analyzers from framework references"

---

eng/WindowsFormsImports.targets
packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.ArchNeutral.csproj
packaging/Microsoft.NET.Sdk.WindowsDesktop/Microsoft.NET.Sdk.WindowsDesktop.WinForms.Packaging.targets
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets

* Establish a mechanism to import Windows Forms related functionality into Windows Desktop SDK via the Windows Forms transport package.
* Add a basic validation of the content of the shipping package in .\eng\WindowsFormsImports.targets.
Enables https://github.com/dotnet/winforms/pull/5183
- Manually locally modifying the installed SDK
- Building winforms -> wpf -> windowsdesktop

Import Windows Forms related props and targets into Windows Desktop

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ContentFilePart.cs

Fixes Issue #4781
We do not escape the path string in GetEntryAssemblyLocation method. And it will break when the application in the special path, such as the path contains a `#`. See https://github.com/dotnet/wpf/issues/4781
All the GetContentStream
No.
Just CI

Fix GetEntryAssemblyLocation Uri

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Primitives/WriterDelegate.cs

Every call to Dispose is allocating one or two delegates.  They're not unique to this instance; we can let the compiler cache them for us.
Less allocation, less GC impact.
No
Just CI
Minimal.  It's just changing one form of delegate creation to another.

Stop allocating new delegates in WriterDelegate.Dispose

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/ActiveXHelper.cs

This was discovered when trying to run WPF under NativeAOT https://github.com/dotnet/runtimelab/issues/1109
ResetLogPixelsY and ResetLogPixelsX just seems to be not used too.

Remove not used code

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextAdaptor.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/UiaCoreApi.cs

Fixing two problems with the recent work to support new UIA events (#4850):
1. New events were not delivered to client-side code.  More precisely, UIA delivers the events to our internal client-side listener, but it lacked the plumbing needed to forward the event to user client-side listeners (decoding the event type, converting event args from native to managed, etc.).
2. The TextRange argument to the ActiveTextPositionChanged event was set to a raw ITextRangeProvider, instead of a wrapper.  
1. Managed clients don't receive the new events.
2. An ActiveTextPositionChanged listener that calls one of the ITextRangeProvider methods crashes the target app.  
Problems only affect usage of the new events.
Ad-hoc.  New test cases are being added.
These fixes are required.

Client-side support for new UIA events

---

eng/WpfArcadeSdk/Sdk/Sdk.props

Update LangVersion to C# 9. WPF seems to be the only repo that still use C# 8.
Here's a list of popular dotnet repos and their version:
aspnetcore: [9.0](https://github.com/dotnet/aspnetcore/blob/main/eng/targets/CSharp.Common.props#L4)
efcore: [9.0](https://github.com/dotnet/efcore/blob/main/Directory.Build.props#L24)
runtime: [preview](https://github.com/dotnet/runtime/blob/main/Directory.Build.props#L282)
winforms: [preview](https://github.com/dotnet/winforms/blob/main/Directory.Build.props#L16)
This change allows us to use newer feature (E.g. Static anonymous functions: https://github.com/dotnet/wpf/pull/4717#discussion_r656966634)
None
No
I tested by doing a build locally.
There shouldn't be any risk, C# 9 is already the default version for .Net 6.

Update LangVersion to C# 9

---

src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalMap.cs

This is boxing the integer keys.
Less allocation, less GC, less pause time.
No
Just CI
Minimal.  Just switches a Hashtable to a Dictionary.  The one thing to typically watch out for in such a change is the thread-safety guarantee differences between the two, but that's not relevant here based on the usage.

Avoid int boxing in HashObjectMap

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsCache.cs

Fixes Issue #3876
Main PR 
Building a WPF .NET Core project with dotnet.exe is not deterministic, but building it with msbuild.exe is deterministic as expected.
This PR is based on [this](https://github.com/MichaeIDietrich/wpf/commit/cff984aaf851ba126a822190bf815d0bf5c4d40e) fix from @MichaeIDietrich.
This issue may break incremental builds.
No regression.
The fix was testing building some projects using the `dotnet build` command, and comparing the generated files using a diff program. Without the fix, the files are almost always different.

Fixing deterministic build bug with dotnet.exe

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.WPF.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.WPF.targets
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

Remove `System.IO` and `System.Net.Http` from the list of generated global usings and enable implicit global namespaces.
These are the global usings that will be included in the generated file when compiling a WPF application: 
```cs
// <autogenerated />
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;
global using global::System.Threading;
global using global::System.Threading.Tasks;
```

Update implicit global namespace support for WPF

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ContentFilePart.cs

The failure looks like an unintended consequence of #4799. The path incorrectly contains the filename of the application assembly.  Reverting the change for now, since we are so close to snapping the release candidate for .NET 6.0.  
Fixes issue https://github.com/dotnet/wpf/issues/4987.

System.Windows.Markup.XamlParseException when reading resource file 

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XmlnsCache.cs

Fixes Issue #3876
Main PR 
Building a WPF .NET Core project with dotnet.exe is not deterministic, but building it with msbuild.exe is deterministic as expected:  .NET Core does not create identical .BAML files.
During compilation, WPF creates an optimized binary version of .XAML files, called .BAML.  The .BAML files between two different builds sometimes have references in the references section written in a different order.  .BAML created from the same .XAML file should always be the same.  
This PR is based on [this](https://github.com/MichaeIDietrich/wpf/commit/cff984aaf851ba126a822190bf815d0bf5c4d40e) fix from @MichaeIDietrich.
Builds may not be deterministic.
No regression.
The fix was testing building some projects using the `dotnet build` command, and comparing the generated files …

[release/5.0] Fixing deterministic build bug in WPF's BAML files

---

src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/ReflectionHelper.cs

Backport fix from 6.0 to 5.0:  Compilation error MC3064 when importing internal user control from signed class library.
> Use reflection-only context for InternalsVisibleToAttribute type comparison.
> Fixes Issue #2492: Compilation error MC3064 when importing internal user control from signed class library.  The wrong load context was used for a type comparison that always failed.  
Internal types contained in assemblies with InternalsVisibleTo attributes that are referenced in markup cause a markup compiler error:  *error MC3064: Only public or internal classes can be used within markup. 'InternalClass' type is not public or internal.*
This is a regression from .NET Framework.  
Very low.  This code is only exercised when WPF applications are compiled.  This is a single-line change that …

[release/5.0] Use reflection-only context for InternalsVisibleToAttribute type comparison

---

eng/WpfArcadeSdk/tools/InjectModuleInitializer.targets

The release/3.1 build breaks on machines that don't have an .NET Framework SDK for version 4.6.2 or lower.
This fixes the break by asking MSBuild to look for ILDasm.exe in all versions it knows about.

[release/3.1] ILDasm build break

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/TextBlock.cs

Addresses #3099 
**Issue:** Text that is narrower after shaping (e.g. applying ligatures and kerning) can reflow, yielding different line breaks than the original measure.  Some words can disappear, and programmatic access can crash hard (FailFast).
The root cause turns out to be a faulty assumption in TextBlock's logic to choose a width to send to FormatLine in post-measure situations like render and hit-test.  The intent is that FormatLine makes the same line-breaking decisions it did during measure.  The faulty assumption is "Reflowing will not happen when Width is between _previousDesiredSize.Width and ReferenceWidth".  [Comment quoted from TextBlock.CalcWrappingWidth.  "Reflowing" means "different line-breaking …

[release/3.1] Do not reflow lines after measure

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/HostVisual.cs

Addresses #3100
Issue: HostVisual can disconnect from its rendering channel on the wrong thread. This can result in corruption that can crash the render thread, usually in some unrelated activity many minutes (or hours) later.
Discussion:
HostVisual sometimes adds commands to the graphics channel on the wrong thread. And sometimes this leaves the channel in a corrupt state, where the primary handle table releases a slot but the secondary handle table doesn't release the corresponding slot. This is a time-bomb - the next time the primary table allocates the slot, the secondary table allocation will fail, which will crash the app at the next SyncFlush. (It could take minutes or hours for this to happen.)
The fix is for HostVisual to marshal …

[release/3.1] Port HostVisual fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/HierarchicalVirtualizationConstraints.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses #2490
This is a port of a servicing fix in .NET 4.7/4.8.
Issue: Scrolling a TreeView hangs.
Discussion:
The customer's data is highly non-uniform, in the sense that a given node's children govern subtrees whose sizes are quite different. This means the estimates VSP computes can differ wildly from the truth, and are subject to frequent (and sometimes violent) revision as more of the tree de-virtualizes. This is not necessarily bad, but it stresses the algorithms in ways that uniform trees don't. This stress uncovers two problems:
1. VSP stores "effective offsets", intended to support correct layout after bottom-up size changes (e.g. a deep node gets larger because of new content), which shouldn't move the visible items. When VSP revises its estimates, it also changes its …

[release/3.1] Port VSP Freeze fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Addresses #3112
Issue: Closing a ToolTip raises events to user code that can request the ToolTip to close. The re-entrancy can lead to a NullReferenceException.
Discussion:
PopupControlService.RaiseToolTipClosingEvent should check _currentToolTip for null after doing anything that can call out to user code, to guard against re-entrant calls.

[release/3.1] Port ToolTip reentrancy fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGrid.cs

Addresses #3113
This is a port of a servicing fix in .NET 4.5-4.8
Issue: DataGrid's Copy command crashes the app if the clipboard is locked.
Discussion:
DataGrid's Copy command throws an exception if the clipboard is locked (after the usual round of retries). There is usually no app code on the stack, so this exception crashes the app. Other controls that implement Copy (TextBox et al.) simply fail silently - no exception, but nothing gets put on the clipboard. This is also the way other apps behave (Notepad, Word, browsers, etc.). This change gives DataGrid that same behavior.

[release/3.1] DataGrid.Copy: fail silently if clipboard is locked

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/HwndHost.cs

Addresses #3114
This is a port of a servicing fix in .NET 4.8
Issue: Expensive diagnostic code is running on the normal code-path.
Discussion:
A recent servicing fix added code to capture a stack trace whenever a certain anomalous condition occurs. However it always creates the stack trace, and merely discards it in the normal case.
Fixed by moving the creation of the stack trace into the anomalous branch.

[release/3.1] Port HwndHost stack trace fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedSOMPageConstructor.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs

Addresses #3115
Issue: For certain XPS documents, DocumentViewer cannot select text correctly.
Discussion:
There are actually two bugs, both affecting the construction of the FixedPage's "Semantic Object Model".
1. Each text run is tested to see if it can be combined into the current text block. The test is intended to recognize when the text and the block are separated by a line drawn somewhere on the page. The bug arises when the text and the block overlap in both the x- and y-directions, and there is a vertical line that touches the overlap. The test erroneously thinks the line separates the text from the block, and doesn't combine them.
2. The lines come from a recursive tree walk of the XPS elements. The tree walk combines transforms …

[release/3.1] Port FixedPage SOM fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/DataGridColumnHeadersPresenterAutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/GroupItemAutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemsControlAutomationPeer.cs

Addresses #3116
Issue: Crash involving automation of ItemsControls
Discussion:
This bug arises because some AutomationPeers can add 'null' to their list of children, which leads to NRE in the common method EnsureChildren. The peer in the repro is a DataGridColumnHeadersPresenterAutomationPeer, but I've identified two other peers with the same flaw.
The flawed peers add null only when 'null' appears as a child in the corresponding visual tree. This normally doesn't happen, but it can if the visual tree is in a torn state at the time GetChildrenCore is called, specifically if the first few entries of the corresponding visual collection have been set to null but the collection itself has not yet been cleared. This situation doesn't usually …

[release/3.1] Port nulll ItemAutomationPeer fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs

Addresses #3563
Issue: Crash when multi-threaded app loads app resources
Discussion:
There is a race condition when two threads try to add parts to one of the app's predefined packages (ResourceContainer or SiteOfOriginContainer), one from Application.GetResourceOrContentPart or Application.GetResourceStream, and the other from PackWebResponse+CachedResponse.GetResponseStream. These two codepaths use different lock objects to synchronize access to the package, so they can interleave. An unfavorable interleaving during the time they are actually adding to the package's underlying SortedList can corrupt the list (it's not thread-safe), leaving it with entries in the wrong order and/or spurious 'null' entries. This breaks the binary search …

[release/3.1] Port predefined package fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs

Addresses Issue #4984.  This is a port of a servicing fix in .NET 4.7-4.8.
The Text Services Framework (Cicero) uses a locking protocol for communication between an IME and WPF.  When an IME wants to change the text:
•	Cicero asks for a write lock (ITextStoreACP.RequestLock)
•	WPF (specifically TextStore) grants the lock and calls back into Cicero  (ITextStoreACPSink.OnLockGranted)
•	Cicero calls other ITextStoreACP methods to make the desired changes.  No one else is allowed to change the text during this time, until OnLockGranted returns.
•	WPF notifies other parties about the changes, as follows (HandleCompositionEvents):
+ Undo the IME changes
+ Replay the IME changes one-by-one, this time raising public events (except to Cicero itself)
+ If the event listeners changed the text, …

[release/3.1] Port IME reentrancy fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemAutomationPeer.cs

Addresses Issue #4992
The root cause is calling peer.InvalidatePeer(), which schedules an asynchronous call to peer.UpdatePeer(), then removing the peer from the automation tree before the async call happens.  UpdatePeer calls several methods that look for context in the automation tree and throw ElementNotAvailableException if the context can't be found.
This is similar to a bug fixed 3 years ago.  The differences are
1. old bug: peer represents a FrameworkElement
this bug:  peer represents a data item
2. old bug: peer invalidated because fe.IsEnabled changed
this bug:  peer invalidated because GridViewColumnCollection changed
There are two factors in the customer's app that contribute to the crash, both having to do with the grouped …

[release/3.1] Port UpdatePeer fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/HierarchicalVirtualizationConstraints.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses Issue #4978. This is a port of a servicing fix in .NET 4.7-4.8.
Description
The hang is due to floating-point drift. After any scroll, VSP runs logic to verify that it scrolled to the right place (it can be wrong due to new information discovered while de-virtualizing). There's a special case when the scroll reaches the end of the data, comparing the actual offset to the maximum (extent - viewport height). This uses the strict test DoubleUtil.AreClose(actual, maximum), which tolerates floating-point drift of 10^-16 pixel. But the difference in the repro is 10^-14 pixel, so the test fails.
Prior to the 2020-08 update, this would have merely triggered a Debug.Assert, invisible to customers. With the update, it now requests a re-measure, fixing a bug that arose when the numbers …

[release/3.1] Port VSP floating-point hang from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/WebBrowserEvent.cs

Addresses Issue #4990
When WebBrowser navigates to about:blank, it cancels outstanding navigations.  However it may still receive completion events for those navigations, due to race conditions between the browser process and the WPF app.  When this happens, ignore the completion event (instead of failing an assert and crashing).
Intermittent crashes.
No.
Standard regressions testing.
Low.  Port of .NETFx servicing fix released earlier this year.

[release/3.1] Web browser completion events 3.1

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses issue #4991
ScrollIntoView relies on a helper method VirtualizingStackPanel.MakeVisiblePhysicalHelper, whose job is 
1. compute a candidate scroll offset that would bring the desired child (DataGridRow) into view within the VSP's viewport
2. compute the visible rectangle of the child relative to the viewport [that's a direct quote of a comment in the code]
The code for job (2) is totally wrong;  it describes the rectangle occupied by the child before scrolling to the new offset (and doesn't even get that right in all cases), rather than the rectangle the child will occupy after scrolling.
The rectangle is only used in the nested-scrolling situation;  it's how an inner scroller tells an outer scroller where it should scroll to.  This situation has never worked, but apparently no …

[release/3.1] Port nested ScrollIntoView fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses Issue #4978. This is a port of a servicing fix in .NET 4.7-4.8.
Description
The hang is due to floating-point drift. After any scroll, VSP runs logic to verify that it scrolled to the right place (it can be wrong due to new information discovered while de-virtualizing). There's a special case when the scroll reaches the end of the data, comparing the actual offset to the maximum (extent - viewport height). This uses the strict test DoubleUtil.AreClose(actual, maximum), which tolerates floating-point drift of 10^-16 pixel. But the difference in the repro is 10^-14 pixel, so the test fails.
Prior to the 2020-08 update, this would have merely triggered a Debug.Assert, invisible to customers. With the update, it now requests a re-measure, fixing a bug that arose when the numbers …

[release/5.0] Port fix for VSP floating-point hang from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs

Addresses Issue #4984.  This is a port of a servicing fix in .NET 4.7-4.8.
The Text Services Framework (Cicero) uses a locking protocol for communication between an IME and WPF.  When an IME wants to change the text:
•	Cicero asks for a write lock (ITextStoreACP.RequestLock)
•	WPF (specifically TextStore) grants the lock and calls back into Cicero  (ITextStoreACPSink.OnLockGranted)
•	Cicero calls other ITextStoreACP methods to make the desired changes.  No one else is allowed to change the text during this time, until OnLockGranted returns.
•	WPF notifies other parties about the changes, as follows (HandleCompositionEvents):
+ Undo the IME changes
+ Replay the IME changes one-by-one, this time raising public events (except to Cicero itself)
+ If the event listeners changed the text, …

[release/5.0] Port IME reentrancy fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/WebBrowserEvent.cs

Addresses Issue #4990
When WebBrowser navigates to about:blank, it cancels outstanding navigations.  However it may still receive completion events for those navigations, due to race conditions between the browser process and the WPF app.  When this happens, ignore the completion event (instead of failing an assert and crashing).
Intermittent crashes.
No.
Standard regressions testing.
Low.  Port of .NETFx servicing fix released earlier this year.

[release/5.0] Web browser completion events 5.0

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses issue #4991
ScrollIntoView relies on a helper method VirtualizingStackPanel.MakeVisiblePhysicalHelper, whose job is 
1. compute a candidate scroll offset that would bring the desired child (DataGridRow) into view within the VSP's viewport
2. compute the visible rectangle of the child relative to the viewport [that's a direct quote of a comment in the code]
The code for job (2) is totally wrong;  it describes the rectangle occupied by the child before scrolling to the new offset (and doesn't even get that right in all cases), rather than the rectangle the child will occupy after scrolling.
The rectangle is only used in the nested-scrolling situation;  it's how an inner scroller tells an outer scroller where it should scroll to.  This situation has never worked, but apparently no …

[release/5.0] Port nested ScrollIntoView fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemAutomationPeer.cs

Addresses Issue #4992
The root cause is calling peer.InvalidatePeer(), which schedules an asynchronous call to peer.UpdatePeer(), then removing the peer from the automation tree before the async call happens.  UpdatePeer calls several methods that look for context in the automation tree and throw ElementNotAvailableException if the context can't be found.
This is similar to a bug fixed 3 years ago.  The differences are
1. old bug: peer represents a FrameworkElement
this bug:  peer represents a data item
2. old bug: peer invalidated because fe.IsEnabled changed
this bug:  peer invalidated because GridViewColumnCollection changed
There are two factors in the customer's app that contribute to the crash, both having to do with the grouped …

[release/5.0] Port UpdatePeer fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/DispatcherTimer.cs

Every time DispatcherTimer.Restart is called (which may happen on every tick), it's allocating a new delegate to point to the instance's FireTick method.  We can instead make it a non-capturing delegate, such that the compiler caches it on first use and never has to allocate it again, passing in `this` via the object state.
Less garbage allocated for the GC to clean up.
No
Only what's done by CI.
Minimal.  The change just modifies how `this` is passed to the callback.

Avoid new delegate allocation on each DispatcherTimer tick

---

src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/Trace.cs

There are a multitude of call sites to EventTrace.EasyTraceEvent that pass value type arguments as the param1/param2/param3 arguments, e.g.
https://github.com/dotnet/wpf/blob/5695fbe1b5767bc318f6630d2245b5376be8d779/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs#L669
https://github.com/dotnet/wpf/blob/5695fbe1b5767bc318f6630d2245b5376be8d779/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs#L829
These, however, are defined to take `object`, which means the arguments are boxed.  And that boxing happens before we even check whether the provider is enabled, as the call sites aren't guarded by checks for IsEnabled.  That ends up meaning we potentially do lots of boxing only to immediately find that the data isn't required as …

Avoid unnecessary boxing in calls to EasyTraceEvent

---

src/Microsoft.DotNet.Wpf/src/Shared/MS/Utility/FrugalList.cs

All comparisons are being performed with object.Equals(object).  If T is a value type, every comparison ends up boxing the argument.
Less boxing means less garbage generated and less time spent on collections.
No
Just CI
Minimal. `EqualityComparer<T>.Default.Equals` will use `object.Equals` if the type doesn't provide an `IEquatable<T>` implementation.

Avoid boxing in FrugalList

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Automation/EventMap.cs

It's currently using a Hashtable with Int32 keys, which means every operation on the Hashtable boxes the int.  Switching to a Dictionary removes those costs.  It also lets use use TryGetValue to perform a single lookup to get a value rather than first calling ContainsKey and then using the indexer, and avoiding multiple virtual calls (most APIs on Hashtable are virtual) when we're only using the base class.
Less unnecessary boxing means less pauses due to GC.
No
Just CI
Minimal.  In general we prefer Dictionary over Hashtable, and the only places we're generally keeping Hashtable is when we benefit from its thread-safety guarantees, but all accesses here are protected by a lock.
You can see some of the associated costs with a microbenchmark like this:
|         Method | Count | …

Use Dictionary instead of Hashtable in EventMap

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/Automation/ElementProxy.cs

We can just pass `this` as the argument and let the compiler cache the delegate for the non-capturing lambda, rather than allocating a new delegate for the instance method on each access.
Less allocation, less GC, less GC pause time / overhead.
No
Just CI
Minimal.  It's just changing how the delegates are created.

Avoid unnecessary DispatcherOperationCallback allocations in ElementProxy properties

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndStylusInputProvider.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/ActiveXSite.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/webbrowsersite.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/ImmComposition.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/PointUtil.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsCLR.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsSetLastError.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/SafeNativeMethodsCLR.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsCLR.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsTextServices.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/HwndProxyElementProvider.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Win32/UnsafeNativeMethods.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/MS/Win32/UnsafeNativeMethods.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/SplashScreen.cs
src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/DrtBase.cs
src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/MS/Internal/PointUtil.cs
src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/MS/Win32/NativeMethodsCLR.cs
src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/MS/Win32/SafeNativeMethodsCLR.cs
src/Microsoft.DotNet.Wpf/test/Common/DRT/TestServices/MS/Win32/UnsafeNativeMethodsCLR.cs

There are a bunch of copies around the tree of POINT interop types: some are structs (as they should be), some are classes.  The latter are resulting in tons of allocations.  This standardizes on using structs for all of them.
In a simple WPF app just moving my mouse around for a few seconds, these are the resulting top allocations:
With this PR, the highlighted line goes away.
Less allocation, less GC, less pause time.
No
CI, plus validation that the allocations went away in the example scenarios I was looking at.
There is some risk here.  The change itself is sound. However, the interop definitions throughout the repo are in a bit of disarray, with many different copies of the same interop types and functions, all defined subtly differently.  I believe I caught all of the relevant paths …

Avoid POINT allocations

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs

Calls to MouseDevice.PreNotifyInput are allocating two arrays unnecessarily.
Less allocation means less GC means less pauses.
No
Just CI
Minimal.  The arrays were simply iterated through and were used for convenience; we can trivially do so with a span instead.

Stop allocating two RawMouseActions[] arrays in PreNotifyInput

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TouchDevice.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/HostVisual.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Frame.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/NGCSerializationManagerAsync.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/XpsOMSerializationManagerAsync.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/manager/XpsSerializationManagerAsync.cs
src/Microsoft.DotNet.Wpf/src/System.Windows.Controls.Ribbon/Microsoft/Windows/Controls/Ribbon/RibbonGalleryItem.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/SplashScreen.cs

A bunch of DispatcherOperationCallback delegates that with trivial changes the compiler can easily cache, e.g.
Less memory allocation.
No
Just CI
Minimal.  It's just removing some unecessary allocations.

Remove more unnecessary DispatcherOperationCallbacks instances

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses Issue #4978.  This is a port of a servicing fix in .NET 4.7-4.8.
The hang is due to floating-point drift.  After any scroll, VSP runs logic to verify that it scrolled to the right place (it can be wrong due to new information discovered while de-virtualizing).  There's a special case when the scroll reaches the end of the data, comparing the actual offset to the maximum (extent - viewport height).  This uses the strict test DoubleUtil.AreClose(actual, maximum), which tolerates floating-point drift of 10^-16 pixel.  But the difference in the repro is 10^-14 pixel, so the test fails.
Prior to the 2020-08 update, this would have merely triggered a Debug.Assert, invisible to customers.  With the update, it now requests a re-measure, fixing a bug that arose when the numbers were …

Port fix for VSP floating-point hang from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkCompatibilityPreferences.cs

Addresses Issue #4984.  This is a port of a servicing fix in .NET 4.7-4.8.
The Text Services Framework (Cicero) uses a locking protocol for communication between an IME and WPF.  When an IME wants to change the text:
•	Cicero asks for a write lock (ITextStoreACP.RequestLock)
•	WPF (specifically TextStore) grants the lock and calls back into Cicero  (ITextStoreACPSink.OnLockGranted)
•	Cicero calls other ITextStoreACP methods to make the desired changes.  No one else is allowed to change the text during this time, until OnLockGranted returns.
•	WPF notifies other parties about the changes, as follows (HandleCompositionEvents):
+ Undo the IME changes
+ Replay the IME changes one-by-one, this time raising public events (except to Cicero itself)
+ If the event listeners changed the text, …

Port IME reentrancy fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/WebBrowserEvent.cs

Addresses Issue #4990
When WebBrowser navigates to about:blank, it cancels outstanding navigations.  However it may still receive completion events for those navigations, due to race conditions between the browser process and the WPF app.  When this happens, ignore the completion event (instead of failing an assert and crashing).
Intermittent crashes.
No.
Standard regressions testing.
Low.  Port of .NETFx servicing fix released earlier this year.

Port WebBrowser completion events fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ScrollViewer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses issue #4991
ScrollIntoView relies on a helper method VirtualizingStackPanel.MakeVisiblePhysicalHelper, whose job is 
1. compute a candidate scroll offset that would bring the desired child (DataGridRow) into view within the VSP's viewport
2. compute the visible rectangle of the child relative to the viewport [that's a direct quote of a comment in the code]
The code for job (2) is totally wrong;  it describes the rectangle occupied by the child before scrolling to the new offset (and doesn't even get that right in all cases), rather than the rectangle the child will occupy after scrolling.
The rectangle is only used in the nested-scrolling situation;  it's how an inner scroller tells an outer scroller where it should scroll to.  This situation has never worked, but apparently no …

Port nested ScrollIntoView fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ItemAutomationPeer.cs

Addresses Issue #4992
The root cause is calling peer.InvalidatePeer(), which schedules an asynchronous call to peer.UpdatePeer(), then removing the peer from the automation tree before the async call happens.  UpdatePeer calls several methods that look for context in the automation tree and throw ElementNotAvailableException if the context can't be found.
This is similar to a bug fixed 3 years ago.  The differences are
1. old bug: peer represents a FrameworkElement
this bug:  peer represents a data item
2. old bug: peer invalidated because fe.IsEnabled changed
this bug:  peer invalidated because GridViewColumnCollection changed
There are two factors in the customer's app that contribute to the crash, both having to do with the grouped …

Port UpdatePeer fix from 4.8

---

global.json
src/Microsoft.DotNet.Wpf/src/PresentationCore/ModuleInitializer.cs

WPF relies on a module initializer to load DirectWriteForwarder before PresentationCore is used.   WPF previously used ILasm/ILdasm to create the module initializer but now uses the language feature.  In new versions of the SDK, the analyzer gives a warning that must be suppressed: https://github.com/dotnet/runtime/issues/43328.

Update the SDK version and disable module initializer warning

---

eng/Versions.props

release/6.0 will be branched to release/6.0-rc2 when rc2 snaps.  Any final fixes to rc1 should go in release/6.0-rc1.

Update release/6.0 branding to rc2

---

NuGet.config

Add feeds for .NET 7: 
`<add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />`
`<add key="dotnet7-transport" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7-transport/nuget/v3/index.json" />`

Add net7 and net7 transport nuget feeds to nuget.config

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs

Fixes Issue #4631
The automation ClickablePoint property shouldn't be an onscreen point, when the IsOffscreen property is true.
This is a port of @SamBent's Accessibility fix from main.  
Accessibility Insights for Windows flags this as an accessibility error.
The test cases that claimed to check this didn't work, for 3 independent reasons.  I've repaired them in a companion PR in the test repo.  That PR is _much_ more interesting than this one.
Low.   Changing this case to conform to the expected behavior, per UIA docs.  The new return value is the same as we return in other "no clickable point" scenarios.

[release/6.0-rc1] Accessibility:  Fix ClickablePoint property when IsOffscreen is true

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs

Fixes Issue #4631
The automation ClickablePoint property shouldn't be an onscreen point, when the IsOffscreen property is true.
Accessibility Insights for Windows flags this as an accessibility error.
The test cases that claimed to check this didn't work, for 3 independent reasons.  I've repaired them in a companion PR in the test repo.  That PR is _much_ more interesting than this one.
Low.   Changing this case to conform to the expected behavior, per UIA docs.  The new return value is the same as we return in other "no clickable point" scenarios.

Fix ClickablePoint property when IsOffscreen is true.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
Documentation/api-compat.md
Documentation/c++-private-tools.md
Documentation/developer-guide.md
Documentation/gen-api.md
Documentation/getting-started.md
Documentation/testing-in-helix.md
README.md

Small documentation cleanup to remove links to master branch in Github repos. Most repos renamed master -> main and Github does the redirection automatically but we should use the right branch name.
Also removes the message "Branch master was renamed to main." when navigating to a link.
None, developer doc only.
No.
Manually tested every modified link.
None, developer doc only.

Remove master branch links from documentations

---

eng/Version.Details.xml
eng/Versions.props

Just a small cleanup because ILAsm and ILDasm looks unused after the move to C# 9 module initializer.
None, only used at build time.
No.
Local build & CI.
None, only used at build time.

Remove ILAsm/ILDasm

---

eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
global.json

Consume the WPF Intellisense files with .NET 6.0 API updates:
`dotnet-api-docs_net6.0-0.0.0.4-win32-x86` 
`dotnet-api-docs_net6.0-0.0.0.4-win64-x64`
/cc @MattGal @carlossanlop

Consume the updated WPF Intellisense files for 6.0 RC2

---

Documentation/developer-guide.md
eng/wpf-debug.targets

The copy operation using PowerShell script was a quick setup for developer to debug WPF project locally.
**Developer Guide:** Added section _Debugging locally build WPF assemblies with WPF Application_. The section explains, what changes are required in CSPROJ, which is configured to consume the WPF project. The steps are simplified by adding a wpf-debug.targets file.
**Targets file:** This is just to simplify the setting up of the project consuming WPF. Instead of using installed assemblies, the project will use assemblies built using this project.
This presents ease of setup for the developers. 
Tested using guidelines added in Developer Guide.

Debugging locally built WPF assemblies with WPF Application

---

azure-pipelines.yml
eng/pipeline.yml

Tracking  Issue: https://github.com/dotnet/core-eng/issues/14276
~Main PR~ N/A
We need to move over to 1ES servicing pools for servicing branches. This accomplishes this in release/6.0.
N/A
None.
N/A
If tests fail in this PR, it's due to interactive mode not being turned on. That's being tracked here: https://github.com/dotnet/core-eng/issues/14358.

Switch to 1ES servicing pools on release/6.0

---

azure-pipelines.yml
eng/pipeline.yml

Same as https://github.com/dotnet/wpf/pull/5372 but for `release/5.0`.

Switch to 1ES servicing pools on release/5.0

---

azure-pipelines.yml
eng/pipeline.yml

Same as https://github.com/dotnet/wpf/pull/5372 but for `release/6.0-rc2`.

Switch to 1ES servicing pools on release/6.0-rc2

---

azure-pipelines.yml
eng/pipeline.yml

Same as https://github.com/dotnet/wpf/pull/5372 but for `release/3.1`.

Switch to 1ES servicing pools on release/3.1

---

azure-pipelines.yml
eng/pipeline.yml

Switch to 1ES R&D pools on main per https://github.com/dotnet/core-eng/issues/14276.

Switch to 1ES R&D pools on main

---

Directory.Build.props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

[release/6.0] Overbuild caused by PackageReference support (Remove WPF Arcade workaround)
WPF PackageReference support conflicted with an existing Arcade workaround.  The WPF workaround (for the Arcade workaround) changed a global property that caused project references to be rebuilt in WPF's temporary project.  
This removes the global property.
The issue is described here: 
https://github.com/dotnet/wpf/issues/5448
https://github.com/dotnet/wpf/issues/4119
Project references will be built a second time by the internal WPF project.  
This is a regression from 5.0.
Low.  
Tested the updated WindowsDesktop SDK containing the change against AppCompat applications and WPF samples.

[release/6.0] Overbuild caused by PackageReference support (Remove WPF Arcade workaround)

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

Fixes #5239
WPF projects that use a versioned custom SDK fail to build:  `<Project Sdk="My.Custom.Sdk/1.2.3" />`.  Parse and add an explicit Version attribute when creating the temporary WPF .csproj.  
Any customer that requires a WPF project with a versioned custom SDK with SourceGenerator/PackageReference support will be blocked until this is fixed.  
Yes, partially.  Using a custom SDK with a version works in 5.0 and 6.0 with PackageReference support turned off.  
Added/ran new unit tests and confirmed custom SDKs work with fix.  Verified WPF Samples build against markup compiler containing change.  Performed additional manual validation.    
Low.  The Sdk attribute parsing uses the same public method from Microsoft.Build.Framework used by msbuild.

WPF projects that use a versioned custom SDK fail to build

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

This was approved for 6.0 GA over email.  @ThomasGoulet73'a PR for main is here:  https://github.com/dotnet/wpf/pull/5426.  
Fixes #5239
WPF projects that use a versioned custom SDK fail to build:  `<Project Sdk="My.Custom.Sdk/1.2.3" />`.  Parse and add an explicit Version attribute when creating the temporary WPF .csproj.  
Any customer that requires a WPF project with a versioned custom SDK with SourceGenerator/PackageReference support will be blocked until this is fixed.  
Yes, partially.  Using a custom SDK with a version works in 5.0 and 6.0 with PackageReference support turned off.  
Added/ran new unit tests and confirmed custom SDKs work with fix.  Verified WPF Samples build against markup compiler containing change.  Performed additional manual validation.    
Low.  The Sdk …

[release/6.0] WPF projects that use a versioned custom SDK fail to build

---

src/Microsoft.DotNet.Wpf/src/Common/src/Interop/Windows/Interop.Libraries.cs

Fixes Issue #505
WPF makes calls into this private DLL:
https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/Common/src/Interop/Windows/Interop.Libraries.cs#L35
https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/Common/src/Interop/Windows/zlib/zlib.cs#L43
https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/CompoundFileDeflateTransform.cs
clrcompression.dll has been renamed to System.IO.Compression.Native. After renaming clrcompression.dll, **createStream** [API](https://docs.microsoft.com/en-us/dotnet/api/system.io.packaging.storageinfo.createstream?view=net-5.0) is not working due …

Updating Compression Native dll Name (dotnet#505)

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/RectangleGeometry.cs

Corrected case of variable name from upper case to lower case in the internal GetPathGeometryData method of the System.Windows.Media.RectangleGeometry class.
The value of "Rect" dependency property had been assigned to local variable "rect", but had been misspelled in three places making unnecessary lookup.
Fixes Issue #5471
Main PR 
This is fixing a misspelled variable name that was "hidden" due to that only the case of first letter of the variable maned differed from the property.
It should have a minimal positive impact to performance.
Because three unnecessary dependency property get/lookups are eliminated without any additional footprint to memory. 
Low risk.
Fixing the variable name has no change to behavior of method.

Fix #5471 Corrected case of variable name 

---

.github/PULL_REQUEST_TEMPLATE.md

Fix issue number to allow GitHub to link a PR with an issue. This also allows GitHub to automatically close the linked issue when the pull request is merged.
GitHub does not recognize "Fixes Issue #..."
GitHub recognizes "Fixes #..."
I also moved "PULL_REQUEST_TEMPLATE" to ".github/PULL_REQUEST_TEMPLATE.md", the same path as the template in the Windows Forms repo.
None.
No.
I don't really know how to test it without merging this PR.
None.

Fix issue number in pull request template

---

eng/WpfArcadeSdk/tools/WPF_Generated_Files.txt
eng/WpfArcadeSdk/tools/pre-commit.githook

Fixes Issue 
Main PR 
Improvements to the hook that deters users from changing generated files:
1. The hook calls a file-comparison tool that expects its inputs to be sorted, but doesn't sort the inputs ("comm: file 1 is not in sorted order").  Fixed that by (a) sorting the dynamic list of staged files, and (b) pre-sorting the fixed list of generated files.
2. Revised the error output to give a better suggestion about what to do next.
To get the full benefit of this change, copy `eng\WpfArcadeSdk\tools\pre-commit.githook` to `.git\hooks\pre-commit`, overwriting the existing file (both paths are relative to your repo's root).  There's probably some way to cause this to happen automatically, but I couldn't find it.
No change to product code.  Developer experience is improved.
No.
It works …

Improve pre-commit githook

---

src/Microsoft.DotNet.Wpf/redist/VCRuntime/VCRuntime.vcxproj

Fixes Issue 
https://github.com/dotnet/wpf/pull/5804#discussion_r767093676
Fallback not required. Remove it.
Main PR 
https://github.com/dotnet/wpf/pull/5804
Fallback to VC141 not required. Remove it.
None
None
Build CI
None

Remove fallback to 141, not required.

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/WriteableBitmap.cs

Fixes Issue #5855 
Updated the explanation for sourceBufferStride in WriteableBitmap.
Makes it easier for developers to understand the parameter.
No
No
None. Documentation Change

Updated sourceBufferStride's documentation

---

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/UncommonField.cs

Fixes Issue [4114](https://github.com/dotnet/wpf/issues/4114)
Master PR 
#4114 
Using the EqualityComparer<T>.Default instead the ReferenceEquals method to avoid the boxing for value types.
No risks

avoid boxing

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DpiChangedEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputProcessorProfiles.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndSource.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/ImageSourceConverter.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapSource.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Printing/printdlgexmarshaler.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/Microsoft/Win32/FileDialog.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/ImmComposition.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/MessageWindow.cs
src/Microsoft.DotNet.Wpf/src/PresentationUI/MS/Internal/documents/PeoplePickerWrapper.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/NativeMethodsCLR.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsCLR.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/UiaCoreApi.cs

Use generic Marshal.PtrToStructure instead of the non-generic. The generic one is slightly faster than the non-generic. Also, I removed the customs UnsafeNativeMethods.PtrToStructure which justs forwards to Marshal.PtrToStructure because it causes linker warnings because Marshal.PtrToStructure is annotated while UnsafeNativeMethods.PtrToStructure isn't.
Contributes to #3811
None, same behavior as the non-generic.
No
I manually tested a few of the generic and non-generic and they gave the same result.
None, same behavior as the non-generic.

Use generic Marshal.PtrToStructure

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/StylusPointCollection.cs

Benchmark:
|      Method | start | length |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Allocated |
|------------ |------ |------- |----------:|----------:|----------:|-------:|-------:|----------:|
|   CopyByFor |     0 |     10 | 10.940 ns | 0.0908 ns | 0.0850 ns | 0.0102 |      - |      64 B |
| CopyByArray |     0 |     10 |  9.861 ns | 0.0784 ns | 0.0655 ns | 0.0102 |      - |      64 B |
|   CopyByFor |     0 |     20 | 18.666 ns | 0.2216 ns | 0.2073 ns | 0.0166 |      - |     104 B |
| CopyByArray |     0 |     20 | 13.494 ns | 0.1908 ns | 0.1785 ns | 0.0166 |      - |     104 B |
|   CopyByFor |     0 |    100 | 88.846 ns | 0.5168 ns | 0.4834 ns | 0.0675 |      - |     424 B |
| CopyByArray |     0 |    100 | 32.594 ns | 0.4785 ns | 0.4476 ns | 0.0675 | 0.0001 |     424 …

Using `Array.Copy` to make array copy faster in StylusPointCollection

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/RenderData.cs

Using ArrayPool in RenderData. The max length is 72, see MILCMD_DRAW_ROUNDED_RECTANGLE_ANIMATE
https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Generated/RenderData.cs#L149-L184
None. But it will affect the rendering of all DrawingVisual and UIElement 
dotnet 7
Just CI and my [demo](https://github.com/lindexi/lindexi_gd/commit/d40a0dd82fb7d6bf8fa24b4b4206b968ec44a07d)
Low

Using ArrayPool in RenderData

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/glyphs.cs

Fixes Issue [#5330 ](https://github.com/dotnet/wpf/issues/5330)
The method calls _measurementGlyphRun.ComputeInkBoundingBox(), does some additional calculations, throws the result away and returns the original finalSize
wpf/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/glyphs.cs
protected override Size ArrangeOverride(Size finalSize)
Code cleanup
No
Developer Regression Suite
No Risk

Glyphs.cs code cleanup

---

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/main.cpp
src/Microsoft.DotNet.Wpf/src/PresentationCore/ModuleInitializer.cs

Contributes #5305
Migrate DPI awareness initialization to managed.
I removed the OS check used to only do the initialization on Windows Vista or later since every version of Windows supported by .Net 6 are more recent than Windows Vista, which renders the check unnecessary.
None.
No.
I tested a WPF application with this PR with high DPI and the DPI awareness was initialized properly.
Seems pretty low.

Migrate DPI awareness initialization to managed

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/CommandBinding.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/CommandBindingCollection.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/CommandManager.cs

Might fix Issue #4869
The main focus was on the FindCommandBinding method in CommandManager.cs. Here I decided to use a ValueTuple instead of a Tuple as well as to do the check using a switch-is block, as this is most likely easier to optimize through the JIT.
Furthermore, I made other code improvements in related methods, like reducing code-nesting and using new C# features.
I don't think these make a big difference to the generated JIT asm, but still hope to have made the code a bit more readable.
/cc @IAmTheCShark

FindCommandBinding improvements

---

eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
eng/WpfArcadeSdk/tools/SdkReferences.targets
eng/WpfArcadeSdk/tools/WpfProjectReference.targets

Future-proofs target framework version increments by using builtin MSBuild functions to compare target framework versions.
Reduces the number of place to update when incrementing the target framework version.
This PR could be merged before #5901 to reduce diff or after to reduce diff of future target framework version increments.
The changes in this PR requires MSBuild 16.5 since `VersionGreaterThanOrEquals` was added in this version.
Build only.
No.
None.
/cc @singhashish-wpf @RussKie

Use builtin MSBuild functions to compare versions

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

Fixes 
[**https://github.com/dotnet/sdk/pull/23293**
](https://github.com/dotnet/sdk/pull/23293)
Main PR 
[**https://github.com/dotnet/sdk/pull/23293**
](https://github.com/dotnet/sdk/pull/23293)
Tests in dotnet SDK failing.
None
CI Build and Run SDK Tests
None

Remove .net6.0; not required

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

Fixes # 
https://github.com/dotnet/sdk/pull/23293
Main PR 
https://github.com/dotnet/sdk/pull/23293
Mismatch of the TargetFramework used to create the package and to locate the task DLL.
PBT csproj has net7.0 while winfx targets had net6.0
None
None
Build CI and SDK Tests
None

Mismatch of PBT version between WinFX Targets and PBT csproj

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json

Fixes #5949
Main PR 
None
Template changes for 7.0 TFM. 
Won't see .Net 7 templates.
None
Build and CI
None

Update .NET 7 templates

---

README.md

That repo is obscure and not visible in regular docs. Bring visibility to it,

Add link to WPF tests repo

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs

Addresses #5835
There are two reasons the context menu does not display.  The first reason is that its owner gets removed from the tree after the right-button-up gesture but before the PopupControlService initiates the display logic.  The logic notices that the owner is not being displayed, and therefore doesn't display the context menu.  This is by design - you shouldn't display a context menu for an element that isn't itself visible.
The second reason is that the (shared) context menu is in a bad state, where it's marked IsOpen=true, but isn't actually being displayed.  The display logic doesn't do anything, since it thinks the menu is already open.  This is a bug, left over from the first case, which doesn't reset IsOpen to false when …

Port "remove ContextMenu owner" fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/HwndProxyElementProvider.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Win32/UnsafeNativeMethods.cs

Addresses #5443 
This bug is about "anomalous" windows, where the UIA_WindowVisibilityOverridden property is set to 1 (ForceVisible), but window's rect is empty.  The .NET automation code doesn't recognize this property, and thus treats the window as "not visible" because it's empty.  This means an automation search won't find any windows below the anomalous window.
Fixed by recognizing the property, and overriding the hwnd's visibility to automation accordingly.  
Automation searches cannot find descendants of anomalous windows (e.g. the Windows 11 Start button).
No.

Port UIA_WindowVisibilityOverridden fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsOther.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs

Addresses #5442
As part of a mitigation for an OS problem (delivering WM_CHAR messages after the related WM_KEYDOWN message has been marked "handled"), WPF reorders the thread's message queue by removing a certain private message, then re-inserting it at the end of the queue.  This happens early while acting on a WM_KEYDOWN, but has the (undocumented) side-effect of overwriting the "extra info" associated with the WM_KEYDOWN.  
This is fixed by preserving the "extra info" across the call that removes the private message.
Extra info attached to a WM_KEYDOWN is lost.
No.

Port extra-info fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Fixes #5730
Closing a tooltip's Popup directly (as opposed to closing the ToolTip and letting WPF close the Popup in response) causes WPF to clear some private state on the ToolTip while leaving its IsOpen=true.  When the ToolTip is eventually closed, WPF uses that state and crashes because it's null.
Fixed by preserving the private state until the ToolTip itself is closed, and adding logic to ensure that the state is cleared even if the Popup was already closed before the ToolTip closed.
Yes.
Low.  The fix itself is safe.  The customer reports did not include repros, so there's a small risk that there are crashing scenarios that this fix doesn't address.

Crash after closing a tooltip's Popup directly

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses #2854
The crash arises when adding an item to the items-source collection underlying the ItemsControl, when the VSP is in an odd state: viewport.Y > extent.Height and <another relationship between viewport, extent, and last-computed "extended viewport", whose exact details I haven't yet determined>.  The logic that determines whether such an addition requires a re-measurement predicts the height of the new extended viewport;  in the odd state this sets the height to (extent.Height - viewport.Y), a negative number that's not allowed.
The first condition cannot happen during Measure, or immediately after;   Measure starts by initializing viewport.Y to a value <= extent.Height.  But it can occur after collection changes, as these …

Port negative-height VSP fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses #4834
This hang arises when UseLayoutRounding is set, and the container's top margin is not a multiple of the rounding quantum.  VSP uses two offsets from the viewport to the container, one that includes the margin and one that doesn't.  It was computing the second and subtracting the margin to obtain the first, but that can give the wrong answer in the situation above.  This can lead to infinite re-measures in anchored scrolls.
Fixed by computing the first offset directly from layout information.  The two offsets will differ by an amount that is close to the margin size, and rounded to a quantum, but there's no way to know which of the nearby candidates is the right one.
Hang while scrolling an ItemsControl.
no
Ad-hoc around …

Port HighDPI/margin fix from 4.8

---

eng/WpfArcadeSdk/tools/Packaging.targets
src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/DirectWriteForwarder.vcxproj
src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj

Fixes # [PR Failing Test](https://github.com/dotnet/installer/pull/13073)
Main PR 
https://github.com/dotnet/installer/pull/13073
PresentationNative and some more native dls weren't getting created in the native folder, instead were going inside the lib folder.
Some dlls won't be created in their respective locations.
This was a regression of the PR https://github.com/dotnet/wpf/pull/5901
Local build, CI
None

Fix dlls not generated in native directory

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs

Addresses #5440
During a manipulation (e.g. swipe), WPF's Pointer stack discards all promoted mouse events.   In the given scenario, this includes the Activation event.  But this means the MouseDevice never gets the Activation event, and thus stays inactive (unresponsive) even after the manipulation ends, until it gets another Activation event, i.e. until the user activates another window then returns to the WPF app.
Fixed by detecting a "promoted" Activation event and explicitly pushing a non-promoted Activation event in its place.
Touch is broken
No

Port touch activation fix from 4.8

---

azure-pipelines.yml
eng/Versions.props

Updates the pre-release label to 2 and adds triggers for the 7.0 branches.

Update pre-release label and add triggers

---

README.md

Update stale information. Make sure that current development targets .NET 7, because otherwise README get's impression of being state. Redirect to contribution guide instead of mentioning that VS version is required. No need for preview right now, I suspect later in .NET 7 cycle that can be requirement again. Overall I think that's not for main page.

Update versions of .NET and links

---

src/Microsoft.DotNet.Wpf/src/Common/Graphics/exports.cs
src/Microsoft.DotNet.Wpf/src/Common/Graphics/wgx_core_types.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaSystem.cs
src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/xml/Resource.xml
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/api/api_utils.cpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwdisplayrt.cpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwdisplayrt.h
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/sw/swhwndrt.h
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/sw/swlib/swhwndrt.cpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/uce/hwndtarget.cpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_misc.h
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/exports.cs
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/processed/wgx_core_types.h
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/wgx_core_types_compat.cs

Addresses #5441
The problem is due to a limitation of D3D - the content it presents via dirty-rectangles can be out of sync with the rest of the content, if the timing of the presents and fills is unfortunate.  WPF cannot fix this, but we can mitigate it by giving the app a way to disable the dirty-rectangle optimization.  This impacts the graphics performance;  by opting-in the app accepts the tradeoff of performance vs. fidelity.
The mitigation takes the form of two AppContext switches:
* Switch.System.Windows.Media.MediaContext.DisableDirtyRectangles
* Switch.System.Windows.Media.MediaContext.EnableDynamicDirtyRectangles
These can be set using one of the techniques listed [here](https://docs.microsoft.com/en-us/dotnet/api/system.appcont …

Port dirty-rectangle opt-out from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Fixes #5703
Moving the mouse from a control A that is showing a tooltip, to another control B that has a tooltip, should show B's tooltip immediately (ignoring its InitialShowDelay). This works correctly if A's tooltip is closed before checking whether B has a tooltip, which was always the case prior to .NET 6.0. The new tooltip behavior in 6.0 can keep A's tooltip open longer, and now needs to check whether a tooltip is already open when it decides that B wants to open its tooltip.
There's an ambiguous case when moving the mouse toward A's tooltip and passing over B.  If the user intends to move to A's tooltip (e.g. to read the tooltip with Magnifier), the tooltip should stay open;  but if the user intends to move to B, the tooltip should close and be immediately replaced by B's tooltip. …

show immediately when replacing current tooltip

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Fixes https://github.com/dotnet/wpf/pull/6063#issuecomment-1030253981
Main PR 
#5931 #5932 
Merge conflict in PopupControlService resulted in bad merge due to changes in same files being pushed one before another.
This additive PR fixes the bad merge problem by including both the resultant eventual changes.
No
Build and code verification
Low

Fix merge errors for #5931 and #5932

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseDevice.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerLogic.cs

Addresses #5440
During a manipulation (e.g. swipe), WPF's Pointer stack discards all promoted mouse events. In the given scenario, this includes the Activation event. But this means the MouseDevice never gets the Activation event, and thus stays inactive (unresponsive) even after the manipulation ends, until it gets another Activation event, i.e. until the user activates another window then returns to the WPF app.
Fixed by detecting a "promoted" Activation event and explicitly pushing a non-promoted Activation event in its place.
Touch is broken
No

forward activation message during manipulation (#5836)

---

src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsOther.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Threading/Dispatcher.cs

Addresses #5442
As part of a mitigation for an OS problem (delivering WM_CHAR messages after the related WM_KEYDOWN message has been marked "handled"), WPF reorders the thread's message queue by removing a certain private message, then re-inserting it at the end of the queue. This happens early while acting on a WM_KEYDOWN, but has the (undocumented) side-effect of overwriting the "extra info" associated with the WM_KEYDOWN.
This is fixed by preserving the "extra info" across the call that removes the private message.
Extra info attached to a WM_KEYDOWN is lost.
No.

preserve extra info across PeekMessage (#5838)

---

src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Internal/Automation/HwndProxyElementProvider.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/MS/Win32/UnsafeNativeMethods.cs

Addresses #5443
This bug is about "anomalous" windows, where the UIA_WindowVisibilityOverridden property is set to 1 (ForceVisible), but window's rect is empty. The .NET automation code doesn't recognize this property, and thus treats the window as "not visible" because it's empty. This means an automation search won't find any windows below the anomalous window.
Fixed by recognizing the property, and overriding the hwnd's visibility to automation accordingly.
Automation searches cannot find descendants of anomalous windows (e.g. the Windows 11 Start button).
No.

honor UIA_WindowVisibilityOverridden property (#5839)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpressionBase.cs

Addresses #5444
A binding on TextBox.Text defers two kinds of work when an IME composition is in progress on the TextBox:
When the text changes (and UpdateTrigger=PropertyChanged), write a new value into the source property.
After writing a value into the source property, read the property's new value (which might be different), apply the customary conversions, and write the result into the TextBox.
The bug occurs when the IME starts a new composition before the previous composition's type 2 work happens. This yields a situation where two tasks are deferred: the older composition's type 2 task and the newer composition's type 1 task. The type 2 task happens first, overwriting the text change that the type 1 task is supposed to handle. …

fix IME vs. property-changed Binding battle (#5840)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ItemsControl.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses #4834
This hang arises when UseLayoutRounding is set, and the container's top margin is not a multiple of the rounding quantum. VSP uses two offsets from the viewport to the container, one that includes the margin and one that doesn't. It was computing the second and subtracting the margin to obtain the first, but that can give the wrong answer in the situation above. This can lead to infinite re-measures in anchored scrolls.
Fixed by computing the first offset directly from layout information. The two offsets will differ by an amount that is close to the margin size, and rounded to a quantum, but there's no way to know which of the nearby candidates is the right one.
Hang while scrolling an ItemsControl.
no
Ad-hoc around …

fix hang when margin is not a multiple of DPI rounding quantum (#5841)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs

Addresses #5835
There are two reasons the context menu does not display. The first reason is that its owner gets removed from the tree after the right-button-up gesture but before the PopupControlService initiates the display logic. The logic notices that the owner is not being displayed, and therefore doesn't display the context menu. This is by design - you shouldn't display a context menu for an element that isn't itself visible.
The second reason is that the (shared) context menu is in a bad state, where it's marked IsOpen=true, but isn't actually being displayed. The display logic doesn't do anything, since it thinks the menu is already open. This is a bug, left over from the first case, which doesn't reset IsOpen to false when it …

reset ContextMenu whose popup cannot be opened (#5843)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses #2854
The crash arises when adding an item to the items-source collection underlying the ItemsControl, when the VSP is in an odd state: viewport.Y > extent.Height and <another relationship between viewport, extent, and last-computed "extended viewport", whose exact details I haven't yet determined>. The logic that determines whether such an addition requires a re-measurement predicts the height of the new extended viewport; in the odd state this sets the height to (extent.Height - viewport.Y), a negative number that's not allowed.
The first condition cannot happen during Measure, or immediately after; Measure starts by initializing viewport.Y to a value <= extent.Height. But it can occur after collection changes, as these can …

rect with negative height is not allowed (#5842)

---

src/Microsoft.DotNet.Wpf/src/Common/Graphics/exports.cs
src/Microsoft.DotNet.Wpf/src/Common/Graphics/wgx_core_types.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/CoreAppContextSwitches.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndTarget.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaContext.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/MediaSystem.cs
src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/xml/Resource.xml
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/api/api_utils.cpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwdisplayrt.cpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/hwdisplayrt.h
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/sw/swhwndrt.h
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/sw/swlib/swhwndrt.cpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/uce/hwndtarget.cpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/Generated/wgx_misc.h
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/exports.cs
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/processed/wgx_core_types.h
src/Microsoft.DotNet.Wpf/src/WpfGfx/include/wgx_core_types_compat.cs

Addresses #5441
The problem is due to a limitation of D3D - the content it presents via dirty-rectangles can be out of sync with the rest of the content, if the timing of the presents and fills is unfortunate.  WPF cannot fix this, but we can mitigate it by giving the app a way to disable the dirty-rectangle optimization.  This impacts the graphics performance;  by opting-in the app accepts the tradeoff of performance vs. fidelity.
The mitigation takes the form of two AppContext switches:
* Switch.System.Windows.Media.MediaContext.DisableDirtyRectangles
* Switch.System.Windows.Media.MediaContext.EnableDynamicDirtyRectangles
These can be set using one of the techniques listed [here](https://docs.microsoft.com/en-us/dotnet/api/system.appcont …

Port dirty-rectangle opt-out from 4.8 (#5837)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Fixes #5716
The new 6.0 tooltip behavior computes a "safe area" in which the user can move the mouse without dismissing the tooltip.  It's computed with coordinates relative to the owner's PresentationSource (hwnd), but the mouse movements were tracked relative to the input provider's PresentationSource.  These are often the same, but not when the tooltip's owner comes from a Popup (or similar context that captures mouse input away from the normal input provider).  This dismisses the tooltip immediately - the logic thinks the mouse has left the safe area.
Fixed by converting the mouse position to the correct coordinate system - relative to the tooltip owner's PresentationSource.
Yes.
Low.  Applies the correct coordinate transformation before checking the mouse …

ToolTips in popups (or any context where capture is active) (#5931)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Fixes #5703
Moving the mouse from a control A that is showing a tooltip, to another control B that has a tooltip, should show B's tooltip immediately (ignoring its InitialShowDelay). This works correctly if A's tooltip is closed before checking whether B has a tooltip, which was always the case prior to .NET 6.0. The new tooltip behavior in 6.0 can keep A's tooltip open longer, and now needs to check whether a tooltip is already open when it decides that B wants to open its tooltip.
There's an ambiguous case when moving the mouse toward A's tooltip and passing over B.  If the user intends to move to A's tooltip (e.g. to read the tooltip with Magnifier), the tooltip should stay open;  but if the user intends to move to B, the tooltip should close and be immediately replaced by B's tooltip. …

show immediately when replacing current tooltip (#6058)

---

eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
global.json
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

Contains #5453 and #5329
Fixes #5448
Fixes #4119
I recently noticed that a couple of changes were made in `release/6.0` and were never pulled back into `main` so I took the liberty of opening a PR targeting `main` with those changes.
I did this by rebasing and squashing `release/6.0` onto `main` and then I removed changes that were specific to `release/6.0`.
None.
No.
Local build + this code is already in `release/6.0`.
None.

Pull release/6.0 into main

---

eng/Versions.props
packaging/Microsoft.DotNet.Wpf.GitHub/Check-AssemblyVersions.ps1
packaging/Microsoft.DotNet.Wpf.GitHub/Directory.Build.targets

Relates to https://github.com/dotnet/core/issues/7172#issuecomment-1034105137 and https://github.com/dotnet/core/issues/7176

Pin assembly versions to prevent revving those in servicing releases

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardDevice.cs

The XML element is not closed. I found this while reading the code, so I fixed it.
None.
None.
Low. I just changed the comment.

Fix the comment in DefaultRestoreFocusMode property

---

eng/Version.Details.xml
eng/Versions.props
eng/WpfArcadeSdk/tools/GenApi.props

https://github.com/dotnet/arcade/commit/e44123d2796c8333cf90f90b51dfd9d04d224bea switched GenAPI to run in-proc as an msbuild task. Because of that, the usage is slightly different when additional parameters are passed in to GenAPI.

Update GenAPI additional parameter usage

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridColumn.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/GridViewColumnHeader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ListBox.cs

Fixes #  #5880 
Main PR  #6054 
Issue related to WPF DataGrid column width can now be changed using the keyboard shortcut "ALT + left arrow key" and "ALT + right arrow key".
Yes.
Integration tests are in progress.
Low. Add ability to adjust column width using keyboard for WPF DataGrid.

WPF DataGrid/GridView  column width can be changed using the keyboard shortcut ALT+left or right arrow key

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

Fixes #5921
Fixes a build error when using multiple SDKs in the SDK attribute when `IncludePackageReferencesDuringMarkupCompilation` is set to true. Loops through every SDKs in the SDK attribute and adds them to the generated project separately.
I used this code from the MSBuild repo to split the SDKs: https://github.com/dotnet/msbuild/blob/main/src/Build/Construction/ProjectRootElement.cs#L1907.
Developers cannot build projects with multiple SDKs.
This is an accidental regression introduced in the .Net 6 SDK when `IncludePackageReferencesDuringMarkupCompilation` was changed to true by default. The same bug is happening in the .Net 5 SDK when overriding `IncludePackageReferencesDuringMarkupCompilation` to true.
Tested build of a project with multiple SDKs.
Low.
Note to reviewer: I …

Fix build failing when using multiple SDK

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props

Fixes #5461
Removes unused item metadata that are automatically added to the project after copy/pasting a xaml file in Visual Studio.
None.
No.
Tested locally by modifying my installed SDK to apply the changes in this PR. It fixed the addition of `<XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>` on copy/paste.
This PR will add `<Generator>MSBuild:Compile</Generator>` and `<XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>` to any `Page` or `ApplicationDefinition` item even if globbing is disabled or if they are added manually.

Remove unused item metadata after copy/paste in Visual Studio

---

src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/ColorTypeConverter.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/FontTypeConverter.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/Serialization/ImageSourceTypeConverter.cs

We can reduce the allocation of a static array. And it can run faster than traversing the array.
Just CI.
Low.

Remove the unnecessary Array code in FontTypeConverter.cs

---

src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsCLR.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClient/System/Windows/Automation/Condition.cs

Use generic Marshal.StructureToPtr instead of the non-generic. I removed the customs UnsafeNativeMethods.StructureToPtr which justs forwards to Marshal.StructureToPtr because it causes linker warnings because Marshal.StructureToPtr is annotated while UnsafeNativeMethods.StructureToPtr isn't.
Almost every call to Marshal.StructureToPtr were already using the generic overload without the need to change the code.
Contributes to #3811
None, same behavior as the non-generic.
No
I manually tested a few of the generic and non-generic and they gave the same result.
None, same behavior as the non-generic.

Use generic Marshal.StructureToPtr

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Fixes #6220
In high DPI environment, most tooltips opened by the mouse close immediately.
This is because the SafeArea uses unscaled coordinates, while the current mouse point uses scaled coordinates.  In high DPI, these are different, leading to false negatives from the containment test "is the mouse within the SafeArea".
Fixed by using unscaled coordinates for the mouse point.  (And incidentally improving the perf by avoiding a lot of unnecessary transformations into, and out of, scaled coordinates.)
Make ToolTips great again (in high DPI).
Regression in PR #5931.
Tested by hand, but thoroughly, in .NET 4.8.1.  The automated tests don't cover high DPI, unless you explicitly run them on a machine whose primary monitor is high DPI.
This is a straightforward port of the .NET Fx fix, but …

ToolTip closes immediately in high DPI

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Fixes #6220
In high DPI environment, most tooltips opened by the mouse close immediately.
This is because the SafeArea uses unscaled coordinates, while the current mouse point uses scaled coordinates.  In high DPI, these are different, leading to false negatives from the containment test "is the mouse within the SafeArea".
Fixed by using unscaled coordinates for the mouse point.  (And incidentally improving the perf by avoiding a lot of unnecessary transformations into, and out of, scaled coordinates.)
Make ToolTips great again (in high DPI).
Regression in PR #5931.
Tested by hand, but thoroughly, in .NET 4.8.1.  The automated tests don't cover high DPI, unless you explicitly run them on a machine whose primary monitor is high DPI.
This is a straightforward port of the .NET Fx fix but …

use unscaled mouse coordinates for convex hull test (#6332)

---

eng/common/templates/job/source-index-stage1.yml
eng/pipeline.yml

Fixes https://github.com/dotnet/wpf/discussions/6410
Wpf isn't showing up on source.dot.net due to a dependency on preview features. This enables the source index "stage1" processing to solve this issue without forcing the preview features on the entire index build.
The changes to eng/common are contained in the next arcade update, but I am including them here so this change works.
source.dot.net won't have wpf sources on it.
no
https://dev.azure.com/dnceng/internal/_build/results?buildId=1727210&view=results
Minimal, this job is separate from the parts of the build that build the project.

Enable stage1 source index

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlDirective.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlLanguage.cs

We can just index into the ReadOnlyCollection rather than iterating it via IEnumerator.  We can also avoid unnecessary collection allocations when all of our internal usage that already has an immutable ReadOnlyCollection goes through the internal constructor.
These XamlDirective instances are frequently stored in Dictionary's, resulting in every GetHashCode call by the dictionary allocating an enumerator.
No
CI
Minimal.

Avoid unnecessary enumerator allocations in XamlDirective.GetHashCode

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/StaticExtension.cs

ProvideValue is frequently creating a string that only ends up being used to populate an exception.  We can just delay creating the string until the exception is thrown so that we don't create it in success cases.
Unnecessary allocations meant only for an exceptional path showing up in success paths.
No
CI
Minimal

Avoid exceptional string allocation in StaticExtension.ProvideValue

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Schema/XamlNamespace.cs

XamlNamespace.GetXamlType is always concatenating a string together, but that string is only used on a fallback path.  So only create it on the fallback path.
Unnecessary string allocation.
No
CI
Minimal

Don't allocate fallback name in XamlNamespace.GetXamlType unless it's needed

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/InfosetObjects/XamlObjectWriter.cs

Logic_ConvertPositionalParamsToArgs is using foreach with an `IList<>` it gets back from `GetPositionalParameters`.  Doing so will end up boxing the enumerator, typically of a `List<T>`, when we can instead just use a for loop with the `IList<>`, avoiding the boxing and reducing interface calls.
Unnecessary allocation and interface dispatch.
No
CI
Minimal

Avoid boxing list enumerator in XamlObjectWriter.Logic_ConvertPositionalParamsToArgs

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/TextStore.cs

GetTextShapeableSymbols returns an `IList<T>`, but it's getting treated as an `ICollection<T>` and thus enumerated.  We can index into it instead to avoid some interface dispatch and boxing the enumerator of what's typically a `List<T>` or a `T[]`.
Unnecessary allocation/overhead.
No
CI
Minimal

Avoid boxing list/array enumerator in CreateTextLSRuns

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/XamlSchemaContext.cs

UpdateNamespaceByUriList has an `IList<T>` but is enumerating it with foreach, resulting in boxing the underlying list or array's enumerator.
Unnecessary allocation.
No
CI
Minimal

Avoid enumerator boxing in XamlSchemaContext.UpdateNamespaceByUriList

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DpiScale.cs

This uses DpiScale.Equals(DpiScale), but there's no such strongly-typed overload, so it falls back to using ValueType.Equals(object), which not only boxes the DpiScale but also both doubles that end up being compared.  This just adds an internal Equals method to DpiScale to bind to that Equals instead; ideally in the future DpiScale would implement `IEquatable<T>` and this `Equals` would be made public.
Unnecessary allocation / overhead
No
CI
Minimal

Stop boxing in Visual.SetDpiScaleVisualFlags

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/ImageSource.cs

Should we remove the calculate when dpif equals 96.0F?
return (double)(pixels * (96.0F / dpif));
When dpif == 96.0F
(double)(pixels * (96.0F / dpif)) 
= (double)(pixels * (96.0F / 96.0F)) 
= (double)(pixels * 1) 
= (double)(pixels) 
None.
Just CI
Low.

Remove the unnecessary calculate code in ImageSource.cs

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UnsafeNativeMethodsMilCoreApi.cs

This is done to please AOT compilers.
Removed not used MilGlyphCache_SetCreateGlyphBitmapsCallback
Technically NativeAOT would handle that after https://github.com/dotnet/runtime/pull/63219/ but want to cleanup just in case
overall I think using untyped delegates in C# is wrong
Fixes https://github.com/dotnet/runtimelab/issues/1107

Explicit delegate types

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/ModuleInitializer.cs

Currently DPI awareness will be enabled *only if* a `DisableDpiAwarenessAttribute` attribute is applied to the entry assembly. Which does not make a lot of sense. This also does not match the behavior of .NET 6.
This PR changes the logic to always enable DPI awareness *unless* a `DisableDpiAwarenessAttribute` attribute is applied to the entry assembly.
WPF applications are not DPI aware. This can be seen by:
```
dotnet new wpf
dotnet run
```
And then checking the DPI Awareness column in Task Manager. On .NET 6 the DPI awareness is "System". In .NET 7 preview 1, it is "Unaware".
This regression was introduced by #5765, which migrated the DPI awareness enablement code from C++ to C#.
```
dotnet new wpf
```
Then replace the contents of `MainWindow.xml.cs` with:
```csharp
using …
```

Fix setting DPI awareness

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ProgressBar.cs

Fixes dotnet/wpf#6264
Disable Indeterminate animation when hiding ProgressBar. Fixes a performance regression introduced in Aero2 theme (Windows 8 or newer)
Better performance when hiding an indeterminate progress bar with the theme Aero2.
Performance regression introduced in Aero2 theme (Windows 8 or newer).
Tested with the sample in #6264 and a combination of Visibility and Indeterminate to validate that this PR does not break existing behavior.
Low.

Disable Indeterminate animation when hiding ProgressBar

---

src/Microsoft.DotNet.Wpf/src/WpfGfx/core/api/exports.cpp

Fixes #6344 
`System.Windows.Media.StreamAsIStream.Write(byte[] buffer, uint cb, out uint cbWritten)` throws `NullReferenceException` when trying to set `cbWritten` because the `out int cbWritten` parameter has been passed in as null.
According to the documentation, caller can pass `NULL` as `pcbWritten` to [IStream::Write](https://docs.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-isequentialstream-write) when they are not interested in the number of bytes written.
The `CManagedStreamWrapper` does not expect that and [simply passes](https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/WpfGfx/core/api/exports.cpp#L775-L782) the pointer to the managed assembly, however, CLR is not happy with writing to null out parameters.
The PR …

Account for optional out parameters in IStream

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphsSerializer.cs

Fixes #  #6525 
Main PR  #6295
When we serialize a GlyphRun to an XPS file, the advance widths for each glyph are rounded to an integer separately, thus producing a significant difference between the rendered output in the file and on the screen. This PR fixes the rounding, by taking into account the cumulative rounding error from the previous glyphs while rounding the current glyph.
Affects the visual fidelity of WPF Applications.
No
Ad-Hoc testing. Tried with different sample apps.
Less

[Port .NET 6 ] Fixes rounding error while glyphrun serialization

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/GlyphsSerializer.cs

Fixes #  #6525 
Main PR 
When we serialize a GlyphRun to an XPS file, the advance widths for each glyph are rounded to an integer separately, thus producing a significant difference between the rendered output in the file and on the screen. This PR fixes the rounding, by taking into account the cumulative rounding error from the previous glyphs while rounding the current glyph.
Affects the visual fidelity of WPF Applications.
No
Ad-Hoc testing. Tried with different sample apps.
Less

Fixes rounding error while glyphrun serialization

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006Reader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006ReaderInternal.cs

When getting the assembly name, we can slice out the piece that's needed rather than allocating a substring.
Unnecessary string allocations.
No
CI
Minimal

Remove substring allocation from Baml2006Reader.Logic_GetFullXmlns

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Globalization/LocalizationComments.cs

When we already have a StringBuilder, just clear it rather than allocating a replacement.  Also don't ToString() only to then create a new string without the first character; use StringBuilder's ToString that takes an offset and length.
Unnecessary allocation.
No
CI
Minimal

Stop allocating unnecessary StringBuilders in ParsePropertyComments

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Globalization/LocalizationComments.cs

Clear the StringBuilder rather than throwing it away and creating a new one.
No
CI
Minimal

Avoid unnecessary StringBuilder reallocation in LookupAndSetLocalizabilityAttribute

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/FullTextLine.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/TextRunCacheImp.cs

We know exactly how big the resulting list needs to be.  As is done in other variants of this method, just allocate the array to be used as an IList.  Also in one place where we do continue using a `List<T>`, strongly-type the local as such to avoid unnecessarily going through the interface.
No
CI
Minimal.  Other implementations already return arrays, so callers can't be expecting it'll always be a `List<>`.

Avoid unnecessary `List<>` wrapper in GetTextRunSpans

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpressionBase.cs

The temporary list is just being used locally.  There's no reason to allocate and go through an extra level of indirection.
No
CI
Minimal

Avoid unnecessary `Collection<T>` wrapper in CombineSources

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/EventRoute.cs

When peeking to see if the BranchNodeStack is empty, it may force it into existence.
No
CI
Minimal

Avoid allocating `Stack<BranchNode>` just to peek at it

---

src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/UncommonField.cs

In some scenarios, these UncommonField<bool>s end up being set very frequently, and each time the value being passed in gets boxed.  We can avoid that by caching and reusing a box for each of the only two possible values (though it looks like the default value is almost always false and so it mainly only boxes true).
No
CI
Minimal.

Reuse bool box objects in UncommonField<bool>.SetValue

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

Fixes dotnet/wpf#6522
Fixes https://github.com/dotnet/roslyn/issues/60257
Fixes the build when using source generators.
Without this PR, customers cannot build a WPF application with source generators.
No. To my knowledge, it never worked.
Tested by building a blank WPF application that uses the Regex source generator. This PR fixed the build.
Low.
/cc @RussKie (It looks like your hunch about the `Analyzers` property was right)

Fix build when using source generators

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

Fixes dotnet/wpf#6522
Fixes https://github.com/dotnet/roslyn/issues/60257
Fixes the build when using source generators.
Without this PR, customers cannot build a WPF application with source generators.
No. To my knowledge, it never worked.
Tested by building a blank WPF application that uses the Regex source generator. This PR fixed the build.
Low.
/cc @RussKie (It looks like your hunch about the `Analyzers` property was right)

Fix build when using source generators (#6534)

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/DirectWriteForwarder.vcxproj
src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj

Fixes #  #6647 
Main PR 
Fixed the DuplicatePackageReference build issue in C++/CLI projects.
This PR along with PR #6648 , fixes the build issues is VS 2022 preview.
None
No
CI + Local Testing
Low.

Fixing the C++/CLI projects failing due to NU1504

---

eng/wpf-debug.targets

Fixes 2 bug in wpf-debug.targets.
Fixes a bug introduced in #6334: `WPFArtifactsPath` should use `WpfArtifactsPackagesCommonPath` instead of `WpfPackagesCommonPath` which doesn't exist.
Fixes a bug in Release: `WPFArtifactsPath` should only contain suffix `.$(WpfConfig)` in Debug. In release, there are no suffix to `Microsoft.DotNet.Wpf.GitHub`
None.
No.
I built WPF for Debug x86, Debug x64, Release x86 and Release x64. Then I used wpf-debug.targets in a project and made sure that the correct binaries were copied to the output path for the correct combination of Configuration and TargetPlatform.
None.

Fix wpf-debug.targets

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/MenuItemAutomationPeer.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs

Fixes #5237
Provided a fix for the problem when windows Narrator was not announcing anything when IsChecked is changed (e.g. the item is clicked on or the user types "Enter" while focusing it).
Yes
NA
Low

Fix for Bug 1493635: MenuItems with IsCheckable and StaysOpenOnClick set to true do not announce to Narrator when IsChecked is changed

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/MenuItemAutomationPeer.cs

Fixes #5237
Main PR 
Added NoInLining attribute
NA
Low

Fix for Bug 1493635: MenuItems with IsCheckable and StaysOpenOnClick set to true do not announce to Narrator when IsChecked is changed 

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Pointer/PointerTabletDevice.cs

No one use the `mouseDragDefault` local variable, but we should initialize it by call the `UnsafeNativeMethods.GetSystemMetrics` code.
None.
None.
Juse CI.
Low.

Remove the unused local variable in PointerTabletDevice.cs

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkElementFactory.cs

In some places the PropertyValues indexer was called multiple times. This change just stores the value into a local once then use the local variable instead.
No noticeable difference.
No.

Avoid excessive calls to the PropertyValues index getter.

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ShellProvider.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs

Fixes #2377
In some cases, not closer specified in the documentation, [ITaskbarList::HrInit](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-hrinit) can fail. When that happens, WPF applications setting `Window.TaskbarItemInfo` crash without possibility of gracefully handling the error.
This PR fixes the issue by checking for the result of HrInit, and not proceeding with taskbar customization if it fails, as per the documentation. "Not proceeding" simply means returning from the `ApplyTaskbarItemInfo` method the same way it is done in the method in other cases (e.g. API not supported by OS).
Application crashes when it sets `TaskbarItemInfo` and the API fails. Reports in #2377 indicate this happens in cases when no user is logged in, a custom …

Ignore NotImplementedException from ITaskbarList

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.cs.xlf

Fixes #6603
Wrong translation for the `TextBox`' context menu for Cut in cs-CZ.
Not taking this fix will keep showing the wrong command name to customers (meaning Delete instead of Cut) running with cs-CZ resources. `ApplicationCommands.Cut.Text` has the correct translation.
No.
Not tested.
Low, translation changed. Verified that the second letter is the accelerator in Notepad.

Translation fix for TextBox_ContextMenu_Cut [cs-CZ]

---

eng/WpfArcadeSdk/tools/SystemResources.props
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/System/Windows/Automation/Provider/AutomationInteropProvider.cs
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/UIAutomationProvider.csproj
src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationProvider/ref/UIAutomationProvider-ref.csproj

Contributes to dotnet/wpf#1
Replace the use of resource constants with properties in UIAutomationProvider. This follows the standard of other .Net projects, like [dotnet/runtime](https://github.com/dotnet/runtime).
None.
No.
None.

Replace resource constants with properties in UIAutomationProvider

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/MediaTrace.cs

Remove sorcery for getting consistent names in the traces
