dotnet/wpf

README.md

Fixes a missing space in the "How to Engage, Contribute, and Provide Feedback" section.

Fixes missing space

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XmlLangPropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XmlnsCompatibleWithAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XmlnsDefinitionAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XmlnsPrefixAttribute.cs

Cleaning up the coding style of some XAML attributes like XmlnsDefinitionAttribute.

Use Auto-Properties and nameof

---

roadmap.md

Adding components that have not yet been published in their priority order.

Updating roadmap

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ConstructorArgumentAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ContentPropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ContentWrapperAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DependsOnAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DictionaryKeyPropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/MarkupExtensionReturnTypeAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/NameScopePropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/NullExtension.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/PropertyDefinition.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/RootNamespaceAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetValueEventArgs.cs

Cleaning up attributes and extensions to use auto properties

Use AutoProperties for different Attributes and Extensions

---

eng/common/templates/phases/base.yml

removing specific version of microbuild so we don't timeout

---

eng/Version.Details.xml
global.json

@AdamYoblick made some comments on PR #264 that didn't make it until after the merge

fixing up some changes that didn't make it in the last pr

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj

Setting PrivateAssets=All in PackageReference

---

eng/Versions.props
src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj

Updating branding to Preview4

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj

Go back to producing packages sans preview label

---

azure-pipelines.yml
eng/Version.Details.xml
eng/Versions.props
eng/common/templates/phases/publish-build-assets.yml
eng/pipeline.yml
global.json
src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj

Update branding for release/3.0 branch to preview3

branding update for release/3.0 branch

---

azure-pipelines.yml

fix publishing

---

README.md

VS2019 is in RC now, no need for downloading preview version.

Update VS2019 link in README.md

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.props
global.json

Updating C++ tools used in internal builds. This is the final update until these tools are integrated into Dev16.1 Preview 2 bits directly.

Update to C++ tools used in internal builds

---

eng/Versions.props

Change label for master to preview 5

Change label for master to preview 5

---

eng/Version.Details.xml
eng/Versions.props
eng/WpfArcadeSdk/Sdk/Sdk.props
eng/WpfArcadeSdk/Sdk/Sdk.targets
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

Adds support for using RuntimeFrameworkVersion in our builds

Use RuntimeFrameworkVersion in builds

---

azure-pipelines.yml
eng/pipeline.yml

Relates to: https://github.com/dotnet/arcade/issues/2443
Goal: mitigate `lock on the feed problem` and add further validations. [More details here.](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing_HowToUse.md)
Test build was here: https://dnceng.visualstudio.com/internal/_build/results?buildId=149683
Test release: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=4444

Onboard on async publishing #1126

---

eng/WpfArcadeSdk/tools/Packaging.targets

Ensure that newer files are always updated under artifacts\packaging

---

eng/WpfArcadeSdk/tools/ExtendedAssemblyInfo.targets

This PR addresses #587 
/cc @fadimounir

Add AssemblyMetadata[Language] attribute

---

eng/Versions.props

moving master to preview6 since we've snapped the preview branch for preview 5 (see #617)

updating to preview 6 branding

---

packaging/Microsoft.DotNet.Arcade.Wpf.Sdk/Microsoft.DotNet.Arcade.Wpf.Sdk.ArchNeutral.csproj

adding the AvTrace directory, i didn't realize when i switched the directory structure around that these files were no longer being packaged in

fix package location

---

eng/WpfArcadeSdk/tools/ShippingProjects.targets

Do not publish PDB's for packaging or redist projects

Do not publish PDB's for packaging or redist projects

---

eng/WpfArcadeSdk/tools/ShippingProjects.props
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemCore/DynamicAccessorImpl.cs
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemCore/PresentationFramework-SystemCore.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemCore/SystemCoreExtension.cs
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemData/PresentationFramework-SystemData.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemData/SystemDataExtension.cs
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemDrawing/PresentationFramework-SystemDrawing.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemDrawing/SystemDrawingExtension.cs
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXml/PresentationFramework-SystemXml.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXml/SystemXmlExtension.cs
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXml/XmlNodeComparer.cs
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXmlLinq/PresentationFramework-SystemXmlLinq.csproj
src/Microsoft.DotNet.Wpf/src/Extensions/PresentationFramework-SystemXmlLinq/SystemXmlLinqExtension.cs

Open source PresentationFramework extension assemblies: 
PresentationFramework-SystemCore.dll
PresentationFramework-SystemData.dll
PresentationFramework-SystemDrawing.dll
PresentationFramework-SystemXml.dll
PresentationFramework-SystemXmlLinq.dll

Open source PresentationFramework extension assemblies

---

Documentation/acceptance_criteria.md
Documentation/contributing.md
Documentation/developer-guide.md

(Pushing reviewed PR acceptance criteria from internal mirror...)

Add pull request acceptance criteria 

---

eng/Version.Details.xml
eng/Versions.props
eng/common/PublishToPackageFeed.proj
global.json
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

Workaround for https://github.com/dotnet/corefx/issues/37943

Fix PBT build - workaround for corefx/37943

---

.editorconfig
Microsoft.Dotnet.Wpf.sln

Adds extensions to the WPF solution file, and includes a minor update to .editorconfig for .sln line endings.

Add PresentationFramework extensions to WPF solution

---

eng/Versions.props

Change branding to preview 7

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System.Xaml.csproj

Add back ValueSerializerAttribute TypeForward to System.Xaml

---

azure-pipelines.yml

Update to pool-provider sourced machines

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.targets
global.json

Frontend in our package version 0.0.0.4 was last known to be a good version. 
Adds workaround for #988

Add back support for private C++ frontend 

---

eng/Versions.props

Rebrand master to Preview 8
#1100

Rebrand master to Preview 8

---

eng/configure-toolset.ps1

See https://github.com/dotnet/arcade/pull/3315

Suppress warnings generated by native-tools installation.

---

eng/Versions.props

Rebrand master to Preview9

---

azure-pipelines.yml
eng/pipeline.yml

Addresses https://github.com/dotnet/wpf/issues/1564 for [dotnet/wpf](https://github.com/dotnet/wpf). 
We have a couple of successful builds from this branch: 
- https://dev.azure.com/dnceng/internal/_build/results?buildId=299330
- https://dev.azure.com/dnceng/internal/_build/results?buildId=298971

Adopt YAML stages based publishing and validation in dotnet/wpf

---

eng/Versions.props
eng/WpfArcadeSdk/tools/Wpf.Cpp.PrivateTools.targets
global.json

Addresses #1604 
From @vatsan-madhavan 's update branch.

Update private C++ toolset to 0.0.0.7

---

azure-pipelines.yml

Addresses #1585
This was validated via a one-off pipeline build on this branch.  The SDL step executed successfully.

Re-enable SDL validation build step.

---

azure-pipelines.yml
eng/Version.Details.xml
eng/Versions.props

Update branding for release/3.0 branch

Update branding for release/3.0 branch

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/MatrixCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/OrthographicCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media3D/PerspectiveCamera.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedTextBuilder.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Input/Key.cs

Fixes the following AzDO issues related to SDL violations
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969303/
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969349/
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969362/
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969298/

making small fixes for sdl violations

---

azure-pipelines.yml
eng/Versions.props

Update Versions.props for release/3.1

Update Versions.props for release/3.1

---

src/Microsoft.DotNet.Wpf/src/DirectWriteForwarder/DirectWriteForwarder.vcxproj
src/Microsoft.DotNet.Wpf/src/Shared/cpp/Utils.cxx

This PR is the first in a series of PRs that I am going to create that clean up (according to my, admittedly subjective, opinions) the code in this repo. There will be one PR created per project/group of closely related projects (e.g. Extensions, Themes). I will endeavor to cause zero functional changes and zero API surface changes in these PRs. I am perfectly OK with these being delayed until after 3.0 release, or if any of my cleanup ideas is contrary to what the core WPF maintainers desire. This is just really, really hairy code, and I thought giving it a shave would be an interesting use of my time.
In this PR, I only went over a very few files, as the others were not listed in the Solution Explorer, and due to the complex build process, IntelliSense was not working in the C++ files. …

Cleanup DirectWriteForwarder

---

azure-pipelines.yml

Addresses #2201 
Adds internal/3.* to PR trigger list

add internal/release/3.* to PR trigger list

---

azure-pipelines.yml

We don't need an actual re-branding change. 
Adding internal/release/3.* to PR trigger list. 
Addresses #2201 
/cc @mmitche

Add internal/release/3.* to PR trigger

---

azure-pipelines.yml

Add internal/release/* to trigger

Add internal/release/* to trigger

---

Documentation/developer-guide.md
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/RichTextBox.cs

Two small changes in the documentation of a control and of a guideline.

Typos and formatting

---

Documentation/getting-started.md

Doc was still referring to 3.0 preview 1.

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/StickyNote/StickyNoteContentControl.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextRange.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/Packaging/XpsDocument.cs
src/Microsoft.DotNet.Wpf/src/ReachFramework/ReachFramework.csproj
src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Markup/XamlReaderProxy.cs

This PR addresses issues #2424, #2425

Fixing Microsoft Security Advisory CVE-2020-0605 : .NET Core Remote Code Execution Vulnerability 

---

eng/Versions.props

Branding updates

---

eng/pipeline.yml

Enable publishing in Debug builds

Enable publishing in Debug builds

---

eng/pipeline.yml

Set _SignType=real for Debug builds

Set _SignType=real for Debug builds

---

eng/WpfArcadeSdk/Sdk/Sdk.props
eng/WpfArcadeSdk/tools/Publishing.props
eng/WpfArcadeSdk/tools/Publishing.targets

...so that 4 distinct copies are generated instead of just 2.

Add $(Configuration) to AssetManifest file name 

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.props
src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/XMath/matrix_xm.hpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/XMath/quaternion_xm.hpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/XMath/vector3_xm.hpp
src/Microsoft.DotNet.Wpf/src/WpfGfx/common/DirectXLayer/XMath/vector4_xm.hpp

Update win10 sdk used by WPF builds to 18362

---

azure-pipelines.yml

Update CI and PR branches 
/cc @mmitche

[release/5.0-preview1] Update CI and PR branches

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/CompilationUnit.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPointer.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/CommandDevice.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/FocusChangedEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/InputReport.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/KeyboardInputProviderAcquireFocusEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseButtonEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/MouseWheelEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/QueryCursorEventArgs.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawAppCommandInputReport.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawKeyboardInputReport.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawMouseInputReport.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawTextInputReport.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/RawUIStateInputReport.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Stylus/Common/RawStylusInputReport.cs
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/TouchPoint.cs

Fixed some typos : 
- occured --> occurred
- analagous --> analogous

Contributing: fixed some typos

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
eng/WpfArcadeSdk/tools/CreateTestPayload.targets
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.props
eng/WpfArcadeSdk/tools/RuntimeFrameworkReference.targets
eng/helixpublish.proj
global.json

I don't have permission to push to dotnet/wpf for some reason 😢 
@mmitche @rladuca PTAL & merge into https://github.com/dotnet/wpf/pull/2670 (then merge that into release/3.1 😆)

Fixup microsoft.netcore.app dependencies

---

Documentation/developer-guide.md
Documentation/wpf.vsconfig
README.md
roadmap.md

- A few updates to roadmap to fixup open-sourcing status
- Partial updates to contrib guidelines 
- Addition of wpf.vsconfig to specify individual workloads.

Update roadmap and contrib guidelines

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.cs.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.de.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.es.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.fr.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.it.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ja.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ko.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.pl.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.pt-BR.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.ru.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.tr.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.zh-Hans.xlf
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Resources/xlf/Strings.zh-Hant.xlf

LOC CHECKIN | dotnet/wpf | 20200403

---

eng/common/templates/post-build/post-build.yml

manual arcade update

---

NuGet.config
eng/pipeline.yml
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XpsS0ValidatingLoader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReader.cs

This PR addresses issues #3018.

Fixing Microsoft Security Advisory CVE-2020-0605 : .NET Core Remote Code Execution Vulnerability- Variant (.Net Core 3.1)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/XpsS0ValidatingLoader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReader.cs

This PR addresses issues #3018.

Fixing Microsoft Security Advisory CVE-2020-0605 : .NET Core Remote Code Execution Vulnerability- Variant (.Net 5.0)

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/Company.WpfApplication1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/Company.WpfApplication1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/Company.ClassLibrary1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/Company.ClassLibrary1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/Company.WpfCustomControlLibrary.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/Company.WpfCustomControlLibrary.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/Company.WpfControlLibrary.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/Company.WpfControlLibrary.vbproj

SDK related issue https://github.com/dotnet/sdk/issues/11706

Update .NET 5 templates with net5.0 tfm

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/Microsoft.DotNet.Wpf.ProjectTemplates.ArchNeutral.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/Company.WpfApplication1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/Company.WpfApplication1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/Company.ClassLibrary1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/Company.ClassLibrary1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/Company.WpfCustomControlLibrary.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/Company.WpfCustomControlLibrary.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/Company.WpfControlLibrary.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/Company.WpfControlLibrary.vbproj

Cherry pick of https://github.com/dotnet/wpf/commit/091244f0adccbb1cb85942e4dc3e56559a162318.
cc @grinrag @mmitche

Update .NET 5 templates with net5.0 tfm (#3042)

---

packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
packaging/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.props
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFx.targets

Remake of https://github.com/dotnet/wpf/pull/2869 due to CI issues

Shuffle property location

---

roadmap.md

DEP has taken up ownership of WPF. This the new roadmap the team is committing to.

Updated Roadmap

---

roadmap.md

Fix the roadmap document format

---

eng/sdl-tsa-vars.config

Enables post-build and nightly SDL verification, rather than within the build

Add SDL vars config file

---

eng/Version.Details.xml
eng/Versions.props

Update branding to 3.1.7.  Includes the merge from internal/release/3.1.

Update branding to 3.1.7

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/MultiBinding.cs

Index must be less than the size of _bindingCollection
Fix #3220

Fix range of for statement

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/Company.WpfApplication3x1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/Company.WpfApplication1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/Company.WpfApplication3x1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/Company.ClassLibrary3x1.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/Company.ClassLibrary3x1.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/Company.WpfCustomControlLibrary3x.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/Company.WpfCustomControlLibrary.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/Company.WpfCustomControlLibrary3x.vbproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/Company.WpfControlLibrary3x.csproj
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/Company.WpfControlLibrary3x.vbproj

Works for
```
dotnet new wpf -n wpf1 -f netcoreapp3.1
dotnet new wpf -n wpf2
dotnet new wpf -n wpf3 -f netcoreapp3.1 --target-framework-override net461
dotnet new wpf -n wpf3 -f net5.0 --target-framework-override net6.0
dotnet new wpf -n wpf4 -f net5.0 --target-framework-override net6.0
```

Update to net5.0 template with backcompact

---

eng/Versions.props

Update release/3.1 branding to 3.1.9

Update release/3.1 branding to 3.1.9

---

azure-pipelines.yml
eng/Publishing.props

Test build https://dev.azure.com/dnceng/internal/_build/results?buildId=825314&view=results

[release/5.0-rc2] Onboard to v3 publishing

---

eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
global.json

Creating this PR instead of https://github.com/dotnet/wpf/pull/3580 so this can go directly into the 5.0-rc2 branch.

update intellisense artifacts

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Addresses #3112 
**Issue:**  Closing a ToolTip raises events to user code that can request the ToolTip to close.  The re-entrancy can lead to a NullReferenceException.
PopupControlService.RaiseToolTipClosingEvent should check _currentToolTip for null after doing anything that can call out to user code, to guard against re-entrant calls.

Reentrancy when closing ToolTip

---

eng/Versions.props
eng/pipeline.yml

Update release/3.1 branding to 3.1.10

Update release/3.1 branding to 3.1.10

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/PopupControlService.cs

Fix Policheck bug in release/5.0.  Approved by Tactics.

1228498 [ wpf ][ PoliCheck ] - Defect : Term "nuked"

---

eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
global.json

Winforms sister PR is at https://github.com/dotnet/winforms/pull/4094

Update intellisense version

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json

Fix typo in the template name

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/GenerateTemporaryTargetAssembly.cs

Move remaining release/5.0 change to master: [release/5.0] Support source generators in WPF projects (#3846) [5.0.2 servicing].

Move remaining release/5.0 change to master: [release/5.0] Support source generators in WPF projects (#3846) [5.0.2 servicing]

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
eng/common/post-build/publish-using-darc.ps1
eng/pipeline.yml

FYI, the internal feeds in nuget.config are intentional and benign.  Thanks.

Merge internal/release/5.0 to release/5.0 and update branding

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.targets

Co-authored-by: Alexandre Zollinger Chohfi <...>
Co-authored-by: Marcpems <...>
Co-authored-by: Juan Sebastian Hoyos Ayala <...>
Co-authored-by: Ryland <41491307+ryalanms@users.noreply.github.com>

WPF ARM64: Update Wpf.Cpp.Targets TFM.  win10- should be win-.

---

eng/Versions.props

Update branding to preview2 after release/6.0-preview1 branch

Update branding to preview2 after release/6.0-preview1 branch

---

PULL_REQUEST_TEMPLATE

The WPF repo doesn't have a PR template configured.  Add initial pull request template to WPF repo.

Add initial pull request template to WPF repo

---

PULL_REQUEST_TEMPLATE

Add default label to PR template:  #4134.

Add 'Untriaged' label to WPF GitHub PR template

---

Documentation/developer-guide.md

Minor update to developer guide that updates the path to net6.0.

Updated developer guide TFM to 6.0

---

eng/Versions.props

release/net6.0-Preview2 has branched.  Update branding of master to Preview 3.

Update .NET 6.0 branding to Preview 3

---

eng/Versions.props

Update release/3.1 branding to 3.1.14

Update release/3.1 branding to 3.1.14

---

eng/Versions.props

Update release/5.0 branding to 5.0.5

Update release/5.0 branding to 5.0.5

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/DragDrop.cs

Fix the comment typo in DragDrop.cs

Fix comment typo in DragDrop.cs

---

eng/Versions.props

(The internal merge will occur on 4/13.)

Update release/5.0 branding to 5.0.6

---

eng/Versions.props

(The internal merge will occur on 4/13. )

Update release/3.1 branding to 3.1.15

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props

Merge internal/release/5.0 into release/5.0.

Merge internal/release/5.0 into release/5.0

---

README.md

1. Add .NET foundation to badge collection.

chore (Badge) : Add .NET foundation badge

---

eng/Versions.props

Update release/5.0 branding to 5.0.9.

Update release/5.0 branding to 5.0.9

---

eng/Versions.props

Update release/3.1 branding to 3.1.18.

Update release/3.1 branding to 3.1.18

---

src/Microsoft.DotNet.Wpf/specs/AutomationUpdate.md

Spec for refresh of automation wrapper APIs.

Spec for automation update

---

src/Microsoft.DotNet.Wpf/src/WpfGfx/core/common/utils.cpp

Just noticed this nit when looking though the code base.
Fixes Issue 
none
Main PR 
Fixes typo in comment
none
none
none
possible that i introduce a typo when fixing a typo

Fix typo in comment

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs

Addresses Issue #4980.  This is a port from a servicing fix in .NET 4.7-4.8.
When the mouse moves between windows, WPF tries to avoid "flickering" the thread's input stream (deactivating, then immediately re-activating).  The original logic decides that Deactivate is unnecessary when moving from window A to B if
- A and B both belong to the same Dispatcher, and
- The move ends in B’s client area
This doesn't work when B supplies its own chrome, and the move ends in the "effective" non-client area.  The subsequent mouse events should go to DWM, not to either A or B.  Leaving the thread's input stream active causes each event to be delivered both to DWM and to whichever of A or B is topmost at the mouse position.
Fixed by changing the second clause to be
- The move ends in B’s “effective” …

[release/3.1] Port WindowChrome fix from 4.8

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/InterOp/HwndMouseInputProvider.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs

Addresses Issue #4980. This is a port from a servicing fix in .NET 4.7-4.8.
Description
When the mouse moves between windows, WPF tries to avoid "flickering" the thread's input stream (deactivating, then immediately re-activating). The original logic decides that Deactivate is unnecessary when moving from window A to B if
- A and B both belong to the same Dispatcher, and
- The move ends in B’s client area
This doesn't work when B supplies its own chrome, and the move ends in the "effective" non-client area. The subsequent mouse events should go to DWM, not to either A or B. Leaving the thread's input stream active causes each event to be delivered both to DWM and to whichever of A or B is topmost at the mouse position.
Fixed by changing the second clause to be
- The move ends in B’s …

[release/5.0] Port WindowChrome fix from 4.8

---

Documentation/developer-guide.md

Update the document.
We updated the output path, that we should also update the document.
NO.
Just CI

Update the testing api changes in developer-guide.md

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/Resources/xlf/Strings.zh-Hans.xlf

Fixes Issue https://github.com/dotnet/wpf/issues/4367
For scrollbar I fixed several translate and not translated localization strings.
No

Fix scrollbar zh-Hans localization

---

Directory.Build.targets

Respond to PR feedback in https://github.com/dotnet/wpf/pull/5208#discussion_r698783329. That PR was merged before I could make the requested change.

Respond to PR feedback

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

- Fixup new-lines
- Remove trailing white-space
- Respect EditorConfig preferences

Clean-up `Microsoft.WinFX.targets` file

---

eng/common/build.sh
eng/common/tools.ps1
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Automation/Peers/AutomationPeer.cs

Not all changes from release/6.0-rc1 were included in release/6.0.  Merge release/6.0-rc1 in to release/6.0.

Merge RC1 branch (release/6.0-rc1) into 6.0 branch (release/6.0) prior to RC2 snap

---

eng/Versions.props

Update to 6.0.1 branding servicing

---

src/Microsoft.DotNet.Wpf/src/Common/src/System/LocalAppContext.cs

The AppContext.TryGetSwitch was a public method after .NET Framework 4.6 and we can call it without reflection.
https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.trygetswitch?view=net-5.0
No need to call slow reflection when launching the app 
.NET 7
Just CI.
Low. I do not change the behavior.

Calling AppContext.TryGetSwitch without Reflection in LocalAppContext.cs

---

eng/pipeline.yml

Fixes Issue 
Internal
Main PR 
None
Internal pools were being used temporarily. Change to public pools.
None
None
CI Build
None

Change pools from internal to public

---

src/Microsoft.DotNet.Wpf/src/System.Windows.Presentation/System/Windows/Threading/TaskExtensions.cs

Use pattern matching in TaskExtensions.cs. It will be clearer.
Just CI.
Low.

Use pattern matching in TaskExtensions

---

eng/Versions.props

Update branding to 7.0 Preview 1

branding for 7.0 preview 1

---

Documentation/getting-started.md

That gives very stale look on the WPF. Designer is working too.

Replace mention of .NET Core 3 to .NET 6

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizingStackPanel.cs

Addresses #2854
The crash arises when adding an item to the items-source collection underlying the ItemsControl, when the VSP is in an odd state: viewport.Y > extent.Height and <another relationship between viewport, extent, and last-computed "extended viewport", whose exact details I haven't yet determined>. The logic that determines whether such an addition requires a re-measurement predicts the height of the new extended viewport; in the odd state this sets the height to (extent.Height - viewport.Y), a negative number that's not allowed.
The first condition cannot happen during Measure, or immediately after; Measure starts by initializing viewport.Y to a value <= extent.Height. But it can occur after collection changes, as these can …

rect with negative height is not allowed (#5842)

---

eng/Version.Details.xml
eng/Versions.props

Revert "[release/6.0] Update dependencies from dnceng/internal/dotnet-wpf-int"

---

eng/WpfArcadeSdk/tools/ExtendedAssemblyInfo.targets

This updates MSBuild to cross-platform tools. In my case that allow me to smoke test changes on Linux
where I occasionally type code.

Update MSBuild tasks

---

.github/fabricbot.json

Adding and updating msbot configuration file, as per recommendation by fabricbot team
Fixes #5849
1. Moving to use of Code-as-configuration for better version control of the configuration. 
2. Updating default reviewer to @singhashish-wpf  @dipeshmsft  and @SamBent 
None
None
NA 
None

Adding msbot configuration file, as per recommendation by fabricbot team

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPenimc.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/webbrowsersite.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/AccessorTable.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PropertyPathWorker.cs

Removes words that are policheck violations : "crazy", etc.

Remove or replace policheck violations from the code

---

eng/Versions.props

Update branding to Preview 3

---

.github/fabricbot.json

Adding rules to fabric bot for servicing consider and community contributions label.

Add rules to fabricbot

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Annotations/ObservableDictionary.cs

fix typo "forthe"

---

eng/Versions.props

Update branding iteration to 4

Update branding iteration to 4

---

eng/Versions.props

Update branding to 5.0.17

---

eng/Versions.props

Update branding to 3.1.25

---

eng/Versions.props

Update branding to 6.0.5

---

eng/Versions.props

Update branding to 5

---

azure-pipelines1.yml

Set up new wpf pipeline

---

eng/Versions.props

Update branding to 6.0.6

---

eng/Versions.props

Update branding to 3.1.26

---

azure-pipelines1.yml

Temporarily disable drttesting pipeline for PRs.

temporarily disable pieline for PRs

---

azure-pipelines1.yml

Update azure-pipelines1.yml for experimentation

Update azure-pipelines1.yml for experimentation

---

eng/Version.Details.xml
eng/Versions.props

Merging internal commits for release/3.1

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props

Merging internal commits for release/5.0

---

eng/Versions.props

Update branding to PreRelease 6

Update branding to prerelease 6

---

src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ComponentResourceKey.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/VirtualizationCacheLengthConverter.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/CornerRadiusConverter.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedPage.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/RtfToXamlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlMapTable.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlReader.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/CompoundFileStreamReference.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/RightsManagementEncryptionTransform.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/IO/Packaging/Compoundfile/versionPair.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Security/RightsManagement/User.cs

There are a bunch of StringBuilders being created that aren't necessary.  This removes some of them.
Unnecessary overheads.
No
CI
Minimal (basically just if there were typos)

Remove some unnecessary StringBuilders

---

eng/Versions.props

Update branding to 6.0.7

---

eng/Versions.props

Update branding to 3.1.27

---

eng/Versions.props

bump up intellisense version

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props

Merging internal commits for release/6.0

---

src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj

Temporary workaround to fix build error due to pool update

Fix build error temporarily to unblock

---

eng/Versions.props

Update branding to PreRelease 7

Update Branding to prerelease 7

---

src/Microsoft.DotNet.Wpf/src/System.Printing/System.Printing.vcxproj

Fix build error temporarily to unblock

Fix build error temporarily to unblock (#6718) 

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextStore.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/UnsafeNativeMethodsTextServices.cs

Set proper parameter
Most likely nobody affected otherwise that should be crashing.

Fix QueryInsertEmbedded parameter type

---

eng/Versions.props

Update branding to 6.0.8

---

eng/Versions.props

Update branding to 3.1.28

---

Documentation/report-on-adding-new-property.md

Just fix the report-on-adding-new-property.md document format.
None.
None.
None.
None.

Fix document format

---

eng/WpfArcadeSdk/tools/Wpf.Cpp.props

Just add the comment.
None.
None.
None.
None.

Add comment to Wpf.Cpp.props code

---

eng/Versions.props

update branding to rc1

---

src/Microsoft.DotNet.Wpf/src/Common/src/Interop/Windows/zlib/zlib.cs
src/Microsoft.DotNet.Wpf/src/Common/src/System/IO/Compression/DeflateZLib/ZLibNative.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/FixedDSBuilder.cs
src/Microsoft.DotNet.Wpf/src/WindowsBase/MS/Internal/IO/Packaging/Compoundfile/CompoundFileDeflateTransform.cs

Fix Zlib and ds lowercase issues
https://github.com/dotnet/wpf/pull/6753/checks?check_run_id=7263833319

Fix Zlib and ds lowercase issues

---

azure-pipelines.yml
azure-pipelines1.yml
eng/pipeline.yml

Should work around https://github.com/dotnet/arcade/issues/10106

Workaround missing lib with non-preview images

---

eng/pipeline.yml

Fixes #6769 
Update WPF pipeline to Run DRTs

Update pipeline to run DRTs on PRs

---

eng/Versions.props

Update branding to 6.0.9

---

eng/Versions.props

Update branding to 3.1.29

---

azure-pipelines.yml
eng/pipeline.yml

- Remove unused secrets
- PublishUsingPipelines is always true
- Fix the internal runtime download location

Some pipeline cleanup

---

eng/Versions.props

Update branding to rc2

---

eng/Versions.props

Branding main to .NET8 alpha 1

Branding main to .NET8 alpha 1

---

azure-pipelines1.yml
eng/pipeline.yml

Use svc pool for release/7.0

---

eng/Versions.props
global.json

Relates to https://github.com/dotnet/windowsdesktop/pull/3114
Relates to https://github.com/dotnet/winforms/pull/7664

Update VS redist package version

---

eng/Version.Details.xml

Update VS redist for coherency

---

eng/pipeline.yml

This change is required for builds to continue working in the new org, dev.azure.com/dnceng-public.

Update public pool names

---

eng/Versions.props

Update branding to 3.1.30

---

eng/Versions.props

Update branding to 6.0.10

---

azure-pipelines1.yml
eng/common/templates/job/execute-sdl.yml
eng/common/templates/job/onelocbuild.yml
eng/common/templates/job/source-build.yml
eng/common/templates/job/source-index-stage1.yml
eng/common/templates/jobs/jobs.yml
eng/common/templates/post-build/post-build.yml
eng/pipeline.yml

update pools for build failures.

change pool names

---

eng/Versions.props

update branding to rtm

---

eng/Versions.props

update intellisense versions

---

eng/pipeline.yml

Change NetCore-Svc-Internal to NetCore1ESPool-Svc-Internal

Change NetCore-Svc-Internal to NetCore1ESPool-Svc-Internal

---

eng/pipeline.yml

Update pool name

---

eng/pipeline.yml

Run DRTs only on public pipeline

Run DRTs only on public pipeline

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json

Main PR
None
Template changes for 8.0 TFM.
Won't see .Net 8 templates.
None
Build and CI
None

Update .NET8 templates

---

eng/Versions.props

Update branding to 3.1.31

---

eng/Versions.props

Update branding to 6.0.11

---

eng/pipeline.yml

Build error: Container couldn't be found.

Fix pipeline errors

---

Documentation/developer-guide.md

Adding Commonly Encountered Error section to developers-guide
None
NA
NA
NA

fix(doc/developer-guide): adding Commonly Encountered Errors section

---

eng/Versions.props

Intellisense update for .NET 7.0 RC2

Intellisense Update for .NET 7.0 RC2

---

Directory.Build.props
eng/WpfArcadeSdk/tools/SdkReferences.targets
global.json
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj

Update TFM from .net7.0 to .net8.0

Update TFM from .net7.0 to .net8.0

---

azure-pipelines.yml
eng/pipeline.yml

Fixes # https://github.com/dotnet/arcade/issues/9592
Main PR https://github.com/dotnet/wpf/pull/7009
Switches to new images on release/6.0
Builds will break in release/6.0
No
N/A
None

[release/6.0] Switch to new images

---

eng/Versions.props

Update branding to 7.0.1

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

Update PresentationBuildTasktfm version to .Net8

Update PresentationBuildTasktfm version to .Net8

---

eng/Versions.props

Update branding to 6.0.12

---

eng/Versions.props

Update branding to 3.1.32

---

eng/Version.Details.xml

Update Winforms version release/7.0

Update Winforms version release/7.0

---

eng/Versions.props

Change PreReleaseVersionLabel to servicing

---

azure-pipelines.yml
eng/pipeline.yml

Pool image changes release/3.1

Pool image changes release/3.1

---

eng/Versions.props

Update branding to 6.0.13

---

eng/Versions.props

Update branding to 7.0.2

---

eng/pipeline.yml

Enable Codeql

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs

Fix typo in MenuItem comment
None.
None.
None.
None.

Fix typo in MenuItem comment

---

Documentation/developer-guide.md

Rectifying Commonly Encountered Error section in developers-guide
None
NA
NA
NA

Rectifying Commonly Encountered Error section in developers-guide

---

eng/Versions.props

Update branding to 7.0.3

---

eng/Versions.props

Update branding to 6.0.14

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReaderHelper.cs

Fixing CA2200: Rethrow to preserve stack details

Fixing CA2200: Rethrow to preserve stack details

---

azure-pipelines1.yml
eng/wpfautomatedtests.yml

Remove unwanted steps in wpf automated tests pipeline.

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs

Merging internal commits for release/7.0

---

azure-pipelines.yml

Adding release/8.0 to azure-pipeline.yml

Adding release/8.0 to azure-pipeline.yml

---

azure-pipelines.yml

Enable in-build signing based on branch

---

azure-pipelines.yml

[release/8.0-preview1] Enable in-build signing based on branch

---

.github/ISSUE_TEMPLATE/01_bug_report.yml

Creating new bug report template

New bug report template

---

eng/Versions.props

Update branding to 7.0.4

---

eng/Versions.props

Update branding to 6.0.15

---

eng/common/dotnet-test-install.ps1
eng/wpfautomatedtests.yml

CTP automation, dotnet test install  and bin replacement

CTP automation, dotnet test install and bin replacement

---

azure-pipelines1.yml
eng/wpfautomatedtests.yml

WPF Test Automation

---

azure-pipelines1.yml
eng/common/dotnet-test-install.ps1
eng/wpfautomatedtests.yml

Add dotnet updated install script for automation testing

Add dotnet updated install script

---

eng/pipeline.yml

Fix build errors due to specific build

Fix build errors due to specific build

---

roadmap.md

WPF roadmap 2023

---

eng/Versions.props

Update branding to 8.0-preview3

Update branding to 8.0-preview3

---

eng/Versions.props

Update branding to 6.0.16

---

eng/Versions.props

Update branding to 7.0.5

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/WebBrowserSite.cs
src/Microsoft.DotNet.Wpf/src/WpfGfx/core/hw/waffling-and-packing.txt

Remove policheck violations from the code

Remove policheck violations from the code

---

azure-pipelines1.yml

Update build image to unblock https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int/pullrequest/26733

Update build image in the release branch 7.0

---

eng/pipeline.yml

Publish test artifacts and show test results

Publish test artifacts and show test results

---

azure-pipelines1.yml
dotnet-test-install.ps1
eng/wpfautomatedtests.yml

Update dotnet install script location for tests

---

eng/Versions.props

Branding to preview 4

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs

Fixes Build Error
Main PR 
https://github.com/dotnet/wpf/pull/7556
Fixing Build Error: 
error MC1000: Unknown build error, 'Object reference not set to an instance of an object.' 
Build error https://github.com/dotnet/sdk/pull/31323
Yes
https://github.com/dotnet/wpf/pull/7556
Local Testing, Build Sample app.
Low. Adding a null check

Adding null check for checksumalgorithm

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs

Fixes Build Error https://github.com/dotnet/sdk/pull/31323
Main PR 
https://github.com/dotnet/wpf/pull/7556
Fixing Build Error: 
error MC1000: Unknown build error, 'Object reference not set to an instance of an object.' 
Build error https://github.com/dotnet/sdk/pull/31323
Yes
https://github.com/dotnet/wpf/pull/7556
Local Testing, Build Sample app.
Low. Adding a null check

Adding null check for ChecksumAlgorithm (#7666)

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGridCell.cs

Fixing switch for data grid sort using keyboard shortcut
NA
NA
NA
NA

Fixing switch for data grid sort using keyboard shortcut

---

Documentation/developer-guide.md

Adding documentation for "How to debug Presentation Build Task?".
NA
NO
NA
NA

Adding documentation for debugging PBT

---

eng/Versions.props

Update branding to 6.0.17

---

eng/Versions.props

Update branding to 7.0.6

---

eng/Versions.props

Update branding to 8-preview5

---

.github/workflows/backportPRs.yml

Github action to backport PRs to branch

Github action to backport PRs to branch

---

src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ContentWrapperAttribute.cs

Fixes https://github.com/dotnet/wpf/issues/212

 Fix NullReferenceException in `new ContentWrapperAttribute(null).GetHashCode`

---

eng/Versions.props

Update branding to 7.0.7

---

eng/Versions.props

Update branding to 6.0.18

---

Documentation/developer-guide.md
README.md

Updating README.md and docs

---

eng/pipeline.yml

Updated pipeline to install .NET 8 Preview 3 after build

---

eng/Versions.props

Update branding of 8.0 from preview5 to preview6

Update branding of 8.0 from preview5 to preview6

---

roadmap.md

Removing words like: Differently abled and Accessibility complient

Removing Policheck violation from roadmap.md

---

eng/Versions.props

Update branding to 7.0.8

---

eng/Versions.props

Update branding to 6.0.19

---

eng/pipeline.yml

.NET CLI version had to be updated every time the version changed. Picking the latest preview now for testing.

Fixing errors due to dotnet versions during test.

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/AppModelKnownContentFactory.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/MimeObjectFactory.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/ParserContext.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/RestrictiveXamlXmlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/WpfXamlLoader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/XamlReader.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Navigation/NavigationService.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs

WPF MSRC Fix port for CVE-2023-24895

---

eng/Versions.props

Update branding to 6.0.20

---

eng/Versions.props

Update branding to 7.0.9

---

eng/Versions.props

Update branding of Release8.0 from preview6 to 7

Update branding from preview6 to 7

---

eng/Versions.props

Update branding to 7.0.10

---

eng/Versions.props

Update branding to 6.0.21

---

eng/pipeline.yml
eng/scripts/CIBuild.cmd
eng/scripts/CIUnitTest.cmd

Move custom CI scripts to a different directory

---

README.md

Improved the README's legibility by fixing grammatical errors and using more intuitive wording.
Furthermore, information was added about both VS Designer and VS Blend being usable for GUI creation using WPF.
Potentially improved attractivity of WPF to newcomers

Improve README wording, add information about VS Blend

---

eng/Versions.props

Update branding to 7.0.11

---

eng/Versions.props

Update branding to 6.0.22

---

eng/Versions.props

Updated main to 9.0-alpha1

---

eng/Versions.props

Update branding to 7.0.12

---

eng/Versions.props

Update branding to 6.0.23

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json

Updating WPF Project templates to version 9.0

Update templates to 9.0

---

eng/Version.Details.xml
eng/Versions.props
global.json

Merging internal commits for release/8.0

---

eng/Versions.props

Updated the Intellisense's version for Visual Studio in WPF.
Checked the build pass locally.
Low

Updating Intellisense Version

---

eng/Versions.props

Update Release/8.0-rc2 to Release/8.0-rtm

Update Release/8.0-rc2 to Release/8.0-rtm 

---

eng/Versions.props

Update branding to 6.0.24

---

eng/Versions.props

Update branding to 7.0.13

---

eng/Versions.props
eng/WpfArcadeSdk/tools/ReferenceAssembly.targets
eng/WpfArcadeSdk/tools/Wpf.Cpp.props
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Color.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/DataGrid.cs

[manual] Merge release/7.0-staging into release/7.0

---

eng/Versions.props

Update branding to 7.0.14

---

eng/Versions.props

Update branding to 6.0.25

---

eng/pipeline.yml

Tests were failing.
Fix the .net version installations and changed the quality parameter to daily

update the dotnet installation versions, quality

---

eng/pipeline.yml

Update .net installation quality parameter

Update .net installation quality parameter

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

Fix build/test failures in sdk repo for wpf.
https://github.com/dotnet/sdk/pull/36125#issuecomment-1771031866

Fix wpf sdk test failures

---

eng/Versions.props

Update branding to 8.0.1

---

eng/Versions.props

Update branding to 7.0.15

---

eng/Versions.props

Update branding to 6.0.26

---

eng/Versions.props

Change to servicing branding

---

azure-pipelines.yml

Add PR trigger for win11 theming branch

Add PR trigger for win11 theming branch

---

azure-pipelines.yml

Fix CI - * not working for feature branch

Fix CI - * not working for feature branch

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/PresentationFramework.csproj
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/SymbolIconExtension.cs
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Button.xaml

Fix Button Appearance and Calendar Button not showing

Fix Button Appearance and Calendar Button not showing

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Calendar.xaml

Adding win11 styles to Calendar
NA
Build Pass.
NA

Adding win11 styles to Calendar

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/Label.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ProgressBar.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/StatusBar.xaml

Adding Win11 Styles to the following controls:
1) Label
2) ProgressBar
3) StatusBar
Build Pass.

Adding win11 styles to progressbar, label and statusbar

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ContextMenu.xaml

Adding Win11 Styles to Context menu
NA
Build Pass.
NA

Adding Win11 Styles to Context menu

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/TextBlock.xaml

Adding Win11 Styles to the TextBlock Control
Verified that the visual appearance changes in a sample application

Applying win11 theme to textblock

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ScrollBar.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ScrollViewer.xaml

Adding Win11 Styles to the following controls: 
1. ScrollBar
2. ScrollViewer
NA
Build Pass.
NA

Adding win11 styles to ScrollBar and ScrollViewer

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ListView.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Styles/ListViewItem.xaml

Adding Win11 Styles to ListView and ListViewItem 
NA
Build Pass.
NA

Adding Win11 Styles to ListView and ListViewItem 

---

eng/Versions.props

Update branding to 8.0.2

---

eng/Versions.props

Update branding to 7.0.16

---

eng/Versions.props

Update branding to 6.0.27

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Win11/Resources/PresentationFramework.Win11.xaml

Import xaml styles in the integrated styles page

Import xaml styles in the integrated styles page

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Appearance/ApplicationThemeManager.cs

Update ApplicationThemeManager.cs to use correct namespace

Update ApplicationThemeManager.cs to use correct namespace

---

eng/Versions.props

Updating branding to release/9.0-preview1

Updating branding to release/9.0-preview1

---

eng/Versions.props

Updating branding to release/9.0-preview2

Updating branding to release/9.0-preview2

---

src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/TypeConverterHelper.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DateTimeValueSerializer.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ValueSerializer.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Xaml/Replacements/DateTimeConverter2.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/ms/Internal/Markup/StringValueSerializer.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/ms/Internal/Markup/TypeConverterValueSerializer.cs
src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/DateTimeValueSerializerTests.cs
src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/StringValueSerializerTests.cs
src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/ValueSerializerTests.cs

Contributes to #7563
Enable nullable reference type annotations for `ValueSerializer`, the types it uses and its overrides inside System.Xaml
CI
Low

[NRT] Annotate ValueSerializer and related files for NRT

---

eng/Versions.props

Update branding to 6.0.28

---

eng/Versions.props

Update branding to 7.0.17

---

eng/Versions.props

Update branding to 8.0.3

---

eng/Versions.props

Updating branding to release/9.0-preview3

Updating branding to release/9.0-preview3

---

eng/Versions.props

Update branding to 8.0.4

---

eng/Versions.props

Update branding to 7.0.18

---

eng/Versions.props

Update branding to 6.0.29

---

azure-pipelines-pr.yml

Adding azure-pipelines-pr.yml for running public pipelines. 
This change for adding 1ESPT to internal pipelines.

Adding public pipeline azure-pipelines-pr.yml

---

azure-pipelines-pr.yml
eng/pipeline-pr.yml

Duplicate All Build YAML Files

Duplicate All Build YAML Files 

---

azure-pipelines-pr.yml

Adding azure-pipelines-pr.yml file.
(Now public build pipeline name is azure-pipelines-pr)

[release/6.0] Adding auzure-pipelines-pr.yml 

---

azure-pipelines-pr.yml

Adding azure-pipelines-pr.yml file.
(Now public build pipeline name is azure-pipelines-pr)

[release/7.0] Adding azure-pipelines-pr.yml

---

eng/Versions.props

Update branding to 6.0.30

---

eng/Versions.props

Update branding to 7.0.19

---

eng/Versions.props

Update branding to 8.0.5

---

eng/Versions.props

Update branding to 8.0.6

---

eng/Versions.props

Update branding to 6.0.31

---

eng/Versions.props

Update branding to 7.0.20

---

eng/Versions.props

Update branding to 8.0.7

---

eng/Versions.props

Update branding to 6.0.32

---

azure-pipelines.yml

Remove -pt from pool image since they have been removed by dnceng
Test: https://dev.azure.com/dnceng/internal/_build/results?buildId=2452938&view=results#SourceCard

Remove -pt from pool image

---

azure-pipelines.yml

remove -pt from pipeline images

---

src/Microsoft.DotNet.Wpf/src/UIAutomation/UIAutomationClientSideProviders/UIAutomationClientSideProviders.csproj

Continuation of https://github.com/dotnet/wpf/commit/f704647788c026d99652b5b3716fab92486841d9

Add missing System.Memory references (part 4)

---

eng/Versions.props

Updating branding to release/9.0-preview5

Updating branding to release/9.0-preview5

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Accent.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC1.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC2.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCBlack.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HCWhite.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml

This reverts commit 58b94704f70bf2776f88097df8ad64a71e41c5fb.

Revert "Making resources in parity with WinUI"

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml

Addressed name for previous and next button in calendar control
A11y issue
None
Local build passed. Checked sample app.
None

Addressed name for previous and next button in calendar control

---

eng/Versions.props

Updating branding to release/9.0-preview6

Updating branding to release/9.0-preview6

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml

Normalized mscorlib namespace in fluent xaml files

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/BamlReader.cs
src/Microsoft.DotNet.Wpf/src/Shared/MS/Win32/SafeNativeMethodsCLR.cs

Use generic version of Enum.IsDefined to improve performance and reduce allocations.
The non-generic version of Enum.IsDefined also supports using the name of the enum value which the generic does not support so the generic version skips this unused code for better performance.
The generic version was introduced in .Net 5: https://learn.microsoft.com/en-us/dotnet/api/system.enum.isdefined?view=net-8.0#system-enum-isdefined-1(-0)
Benchmark results:
|     Method |                value |      Mean |     Error |    StdDev | Ratio |  Gen 0 | Allocated |
|----------- |--------------------- |----------:|----------:|----------:|------:|-------:|----------:|
| NonGeneric |           2147483647 | 11.088 ns | 0.1035 ns | 0.0968 ns |  1.00 | 0.0014 |      24 B |
|    Generic |           2147483647 | …

Use generic version of Enum.IsDefined

---

src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/RuntimeIdentifierPropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/AcceptedMarkupExtensionExpressionTypeAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ConstructorArgumentAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/ContentWrapperAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DependsOnAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/DictionaryKeyPropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/NameScopePropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/RootNamespaceAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/UidPropertyAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetMarkupExtensionAttribute.cs
src/Microsoft.DotNet.Wpf/src/System.Xaml/System/Windows/Markup/XamlSetTypeConverterAttribute.cs

Addresses #8905.
I haven't had time to review #8675 yet

Fix some attributes NRT annotations

---

eng/Version.Details.xml
eng/Versions.props
eng/common/post-build/publish-using-darc.ps1
eng/common/templates-official/job/publish-build-assets.yml
eng/common/templates-official/job/source-build.yml
eng/common/templates-official/job/source-index-stage1.yml
eng/common/templates-official/jobs/source-build.yml
eng/common/templates-official/post-build/post-build.yml
eng/common/templates-official/steps/enable-internal-runtimes.yml
eng/common/templates-official/steps/get-delegation-sas.yml
eng/common/templates-official/steps/get-federated-access-token.yml
eng/common/templates/job/publish-build-assets.yml
eng/common/templates/job/source-build.yml
eng/common/templates/job/source-index-stage1.yml
eng/common/templates/jobs/source-build.yml
eng/common/templates/post-build/post-build.yml
eng/common/templates/post-build/setup-maestro-vars.yml
eng/common/templates/steps/enable-internal-runtimes.yml
eng/common/templates/steps/get-delegation-sas.yml
eng/common/templates/steps/get-federated-access-token.yml
eng/pipeline-pr.yml
eng/pipeline.yml
global.json

[release/8.0] Switch to dSAS for internal runtimes

---

eng/wpfautomatedtests.yml

Switch to dSAS for internal runtimes for wpfautomatedtests

---

eng/Versions.props

Update branding to 6.0.33

---

eng/Versions.props
eng/pipeline-pr.yml

Update branding to 8.0.8

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml

Tab navigation not working for header, next and previous buttons in calendar
Motor impaired users will not be able to navigate to the controls in calendar.
None
NA

Added tab navigation control in calendar

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml

Keyboard focus is not navigating to date picker control.
Motor impaired users will not be able to navigate to the date picker control.
None
Local build pass, tested in sample app.
NA

Fixed keyboard focus for DatePicker control

---

eng/Versions.props

Update branding to 9.0.0-rc1

---

eng/Versions.props

Revert Xunit version

---

eng/Versions.props

[Release/9.0-preview7] Revert Xunit version

---

src/Microsoft.DotNet.Wpf/src/Themes/Generator/ThemeGenerator.Fluent.ps1

Updated the Fluent Theme Generator script to fix the issue of not retrieving the file's path. 
NA
Tested in my Local System 
NA

Updated Fluent Theme Generator script 

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Tab navigation stuck in a loop for calendar
Users will not be able to navigate out of the calendar
None
NA

Fixed tab navigation control in calendar

---

eng/Version.Details.xml
eng/Versions.props

Added System.Formatters.Nrbf to Version.Details.xml

---

eng/Versions.props

Update branding to 6.0.34

---

eng/Versions.props

Update branding to 8.0.9

---

eng/Versions.props

Updating branding to release/9.0-rc2

Updating branding to release/9.0-rc2

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FluentThemeState.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs

Resolves the remaining comments on PR #9436 
Local testing
Minimal

Resolving PR #9436 ( Implementing ThemeMode properties ) comments

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RadioButton.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Adding animations for Radio button
None
NA

Adding animations for Radio button

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixed DatePicker AccentBorder style issue

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Bringing RichTextBox style on parity with WinUI
None
NA

Making RichTextBox style on parity with WinUI

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Adding Shadow to Menuflyout in ComboBox
None
NA

Adding Shadow to Menuflyout in ComboBox

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Application.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourcesChangeInfo.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ThemeManager.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs

Fixing ThemeMode.System syncing issues

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Made alignment center for Calendar
NA
Local build passed, tested sample app.
NA

Made alignment center for Calendar

---

eng/Versions.props

[Branding] Update main to 10.0.0-alpha1

---

eng/Versions.props

[Branding] Update branding to 9.0.0-rc2

---

eng/pipeline-pr.yml

Disable Test on PR for Release/9.0

Disable Test on PR for Release/9.0

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ContextMenu.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixes #9626 
Change key of ContextMenu from DefaultContextMenu to DefaultContextMenuStyle
NA

Change key of ContextMenu from DefaultContextMenu to DefaultContextMenuStyle

---

eng/Versions.props

Update branding to 6.0.35

---

eng/Versions.props

Update branding to 8.0.10

---

eng/Versions.props

Update the Microsoft Intellisense Nuget package version.
Developers will get the latest intellisense package.
N/A
Local build
N/A

Update Intellisense Package Version

---

eng/Versions.props

Updating version to .NET 9 RTM

Update branding to .NET 9 RTM

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixed padding in TextBox

---

github-merge-flow.jsonc.txt

add configuration for flow

---

.github/workflows/main.yml
github-merge-flow.jsonc.txt

Sync changes between branches.

Interbranch workflow

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

This PR fixes the following issues in Fluent styles :
- Fixes ListViewItem keys duplication
- Fixes bindings in CheckBox
- Fixes inconsistent border brushes for TextBox, ComboBox and other controls
- Fixes Height and Width being ignored when HorizontalAlignment and VerticalAlignment are set on DatePicker, Calendar and TextBox controls
PS : Bugs were found as a result of local testing with applications. 
Developers who will want to use the new Fluent styles will be able to use the controls correctly, and they will need less customization in their already existing apps to use the new theme. Brings more parity with WinUI styles and decreases few inconsistencies in the styles.
Technically no, but any developer who will try to port their application to use the new styles will face these issue …

Fixing Fluent style for CheckBox, Calendar and text input controls

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Calendar.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ComboBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixes Height & Width not being respected when setting Alignment properties on some controls

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixing template bindings in CheckBox and making the style similar to WinUI

---

eng/Versions.props

Update branding to 6.0.36

---

eng/Versions.props

Update branding to 8.0.11

---

eng/Versions.props

Updates Intellisense package version to 9.0.0-preview-20241010.1
Developers will get the most recent document / intellisense files when using WPF in .NET 9
No
Local build
No

Updated Intellisense package version to 9.0.0-preview-20241010.1

---

eng/Versions.props

Update branding to 8.0.12

---

eng/Versions.props

Update branding to 9.0.1

---

.github/policies/resourceManagement.yml

**Change Description** Modifying default reviewers

Modifying default reviewers 

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Nrbf/SerializationRecordExtensions.cs

Merging internal commits for release/9.0

---

.editorconfig
src/Microsoft.DotNet.Wpf/cycle-breakers/.editorconfig
src/Microsoft.DotNet.Wpf/src/.editorconfig
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/Tasks/TaskFileService.cs
src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft/Build/Tasks/Windows/ResourcesGenerator.cs
src/Microsoft.DotNet.Wpf/src/Shared/System/Windows/Markup/TypeConverterHelper.cs
src/Microsoft.DotNet.Wpf/tests/UnitTests/PresentationFramework.Fluent.Tests/System/Windows/Controls/ButtonTests.cs
src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/StaticExtensionTests.cs
src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Xaml.Tests/System/Windows/Markup/TypeExtensionTests.cs

Remove TODO from root .editorconfig and add temporary/permanent overrides. Fix the few instances in tests and a few random files in the other sources related to these analyzers.

Enable TODO analyzers

---

Documentation/docs/using-fluent.md

Fixed typo

---

Microsoft.Dotnet.Wpf.sln
src/Microsoft.DotNet.Wpf/src/System.Printing/CPP/src/PrintSystemAssemblyInfo.cpp
src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Printing.Tests/GlobalUsings.cs
src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Printing.Tests/System.Printing.Tests.csproj
src/Microsoft.DotNet.Wpf/tests/UnitTests/System.Printing.Tests/System/Printing/IndexedProperties/PrintStringPropertyTests.cs

Add test project for System.Printing along with a few starter tests.

Start System.Printing test project

---

src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/Microsoft.WinFX.targets

Fix build/test failures in sdk repo for wpf. https://github.com/dotnet/sdk/pull/45376#issuecomment-2541268312

Updating PresentationBuildTasksTfm to Net 10

---

eng/WpfArcadeSdk/tools/SdkReferences.targets

Unblocks https://github.com/dotnet/sdk/pull/45563

Fix winforms private package TFM when building inside VMR

---

eng/Versions.props

Update branding to 9.0.2

---

eng/Versions.props

Update branding to 8.0.13

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixes #10223
Fixes content alignment of TextBox
NA
None

Fixes content alignment in TextBox

---

Documentation/contributing.md

- techn**olo**gy
- comman**d l**ine
Fixes # 
Main PR 
see:
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/c/command-line

fix: contributing.md spelling

---

Documentation/acceptance_criteria.md

- When **a** solution has been...
Fixes # 
Main PR 
Simplify the sentence by removing a useless word

fix: acceptance_criteria.md remove useless article

---

Documentation/api-compat.md

- referen**ce** assemblies
- availab**le**
- generate **an** MSBuild error
- inten**tion**al
Fixes # 
Main PR 
see:
https://www.merriam-webster.com/dictionary/availabe
https://www.merriam-webster.com/dictionary/intential
https://www.merriam-webster.com/dictionary/e.g.#examples
https://www.merriam-webster.com/dictionary/an#usage-discussion-1

fix: api-compat.md spelling punctuation

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Data/PathParser.cs

Replaces boxing `ArrayList` with `List<SourceValueInfo>`, greatly improving performance and decreasing allocations on this kind of hot path. Also removes static field of composing `Array.Empty<SourceValueInfo>()` as it has no impact on storing it.
I've also removed the `bool isIndexer` as it just complicates the `switch` statement, added explicit accessibility modifiers, and sealed the class as it has no derivates.
| Method   | error | Mean [ns] | Error [ns] | StdDev [ns] | Gen0   | Code Size [B] | Allocated [B] |
|--------- |------ |----------:|-----------:|------------:|-------:|--------------:|--------------:|
| Original | True  | 139.60 ns |   2.808 ns |    3.748 ns | 0.0491 |       2,314 B |         824 B |
| PR__EDIT | True  |  42.81 ns |   0.846 ns |    0.831 ns | 0.0206 | …

Replace boxing ArrayList in PathParser, improve performance, decrease allocs

---

packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfClassLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfCustomControlLibrary-VisualBasic/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-CSharp/.template.config/template.json
packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfUserControlLibrary-VisualBasic/.template.config/template.json

Update WPF Project templates to version 10.0.

Update templates to 10.0

---

eng/Versions.props

Update branding to release/10.0-preview2.

Update branding to release/10.0-preview2

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Expander.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixes #10295 
Updating KeyTime to 0.2 seconds for expander in down expanded direction
Yes

Updating KeyTime of Expander

---

Documentation/developer-guide.md

- occu**rr**ing
- a**pp**ropriate value
- binaries are buil**t**
Fixes # 
Main PR 
see:
https://www.merriam-webster.com/dictionary/apropriate
and:
https://www.merriam-webster.com/dictionary/occuring

fix: stelling and grammar in developer-guide.md

---

packaging/Directory.Build.props

Fixes https://github.com/dotnet/source-build/issues/4885
This repo doesn't have auto-merge enabled. Please merge on my behalf.

Create arch neutral packages when building inside the VMR

---

eng/Versions.props

Update branding to 9.0.3

---

eng/Versions.props

Update branding to 8.0.14

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Label.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixes #10360 
Adds default style key for label
No
None

Adding Default Style key for Label

---

Documentation/gen-api.md

Fixes # 
Main PR 
- requ**ir**ed
see:
https://www.merriam-webster.com/dictionary/required

fix: spelling of required in gen-api.md

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/CheckBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DataGrid.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolBar.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixes  #8799 
Replaces the use of Hand cursor with Arrow cursors as per the Windows 11 guidelines.
Developers and customers will get the native behavior of Windows 11 with WPF applications.
No
Local Testing
No

Fixed cursor type in CheckBox, ToolBar and DataGrid

---

eng/Versions.props

Update branding to release/10.0-preview3 

Update branding to release/10.0-preview3 

---

.editorconfig
src/Microsoft.DotNet.Wpf/src/.editorconfig

Enable SA1000: Spacing around keywords

---

eng/Versions.props

Update branding to 8.0.15

---

eng/Versions.props

Update branding to 9.0.4

---

eng/Versions.props

Update branding to release/10.0-preview4

Update branding to release/10.0-preview4

---

eng/Versions.props

Update branding to 8.0.16

---

eng/Versions.props

Update branding to 9.0.5

---

src/Microsoft.DotNet.Wpf/specs/tooltip.md

fix: Fix typo mistake committed
No risk

fix: Fix typo mistake committed

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Added missing TextControl brushes that are used in all the text based controls : TextBox, PasswordBox, DatePicker, etc.
Correct resources for Fluent styles. Reduces the amount of changes in other style fixing PRs for text controls.
No
Minimal
=

Added missing TextControl brushes

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/Menu.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixes #10493 
Adds ItemsPresenter in Menu
Low

Adds ItemsPresenter in Menu

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Fixes #10770 
Fixes the layout and resource usage for PasswordBox style in Fluent. This PR covers the following issues with the style.
Coherent behavior of Fluent PasswordBox style.
No
Minimal

Fixes the layout and resource usage for PasswordBox

---

eng/Versions.props

Branding for Preview 5

---

src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/AppContextDefaultValues.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/Baml2006KeyRecord.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceDictionary.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/ResourceReferenceExpression.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs
src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/SystemResources.cs
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Variables.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/DatePicker.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

This changes here includes following 5 PRs
- #10768 
- #10756 
- #10688 
- #10532 and 
- #10794

Sync release/preview4 with latest changes

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/PasswordBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/RichTextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/TextBox.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml

Sets SelectionBrush for TextBox and other controls
local build pass, tested with sample applications
Low

Sets SelectionBrush for TextBox and other controls

---

eng/Versions.props

Update branding to 9.0.6

---

eng/Versions.props

Update branding to 8.0.17

---

eng/pipeline.yml

Do not check out: self with clean, avoids deleting installed Microbuild plugins

---

eng/Versions.props

Update branding to release/10.0-preview6

Update Branding to Preview 6

---

src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Resources/Theme/Light.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Styles/ToolTip.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Dark.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.HC.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.Light.xaml
src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.Fluent/Themes/Fluent.xaml

Fixes #9672 
Fixes issues in ToolTip style : including resource naming, some values and layout
Correct style for ToolTip
N/A
Local 
Minimal.
\

Fixed ToolTip Fluent Style and Resources

---

eng/Version.Details.xml
eng/Versions.props

Remove unused arch-specific properties

---

eng/Versions.props

Update branding to 9.0.7

---

eng/Versions.props

Update Versions.props to Preview 7

---

eng/Versions.props

Update branding to 8.0.19

---

eng/Versions.props

Update branding to 9.0.9

---

eng/Versions.props

Update branding to 9.0.10

---

eng/WpfArcadeSdk/Sdk/Sdk.props

The following changes bumps up the C# language version to 14, in order to align with latest changes.
Low

Bump up lang version to 14

---

eng/Versions.props

Update branding to 9.0.11

---

eng/Versions.props

Update branding to 8.0.22
